### ISSUE TITLE
Session save and load don't work / exist

### ISSUE THREAD

**Issue by taylor00541** [androguard/androguard#1000]
The functions in the [docs](https://androguard.readthedocs.io/en/latest/intro/sessions.html) don't exist

(from the docs)
```python
from androguard import misc
from androguard import session

# OK - works
sess = misc.get_default_session()

# does not exist
session.Save(sess, "androguard_session.ag")

# does not exist
sess = session.Load("androguard_session.ag")
````

There is a function `Session.save` in `session.py` but it just ignores the filename parameter. There is no relevant `load` function for sessions.

**Comment by erev0s** [comment]
Sessions are outdated and no longer work as expected based on the documentation
