### ISSUE TITLE
Error trying to install 

### ISSUE THREAD

**Issue by datshicray** [androguard/androguard#1001]
I expected to install androguard with the command:
`$ pip install androguard`

I first tried in termux on  Oxygen OS (android 13) OnePlus 8T (kb2007). I then tried on Ubuntu 23.10 x64-arm (proot in termux on top of the android OS. Both attempts have given me the same error:

`ERROR: Could not build wheels for frida, which is required to install pyproject.toml-based projects`

### System Information

- Androguard Version: master
- Python Version: 3.4/3.5/...
- Android 13 & Ubuntu 23.10

**Comment by ehrenb** [comment]
Are you able to `pip install frida` successfully? This is probably an issue with some underlying dependency attempting to be compiled on ARM.

**Comment by erev0s** [comment]
@datshicray please check https://github.com/frida/frida/discussions/2411
