### ISSUE TITLE
A malform AndroidManifest file

### ISSUE THREAD

**Issue by HongThatCong** [androguard/androguard#1006]
### Describe what actually happened
Androguard parse failed with this malform AndroidManifest.xml file.
ApkInspector parse OK

### System Information
[Malform_AndroidManifest.zip.txt](https://github.com/androguard/androguard/files/14450272/Malform_AndroidManifest.zip.txt)

- Androguard Version: master
- Python Version: 3.9.7
- Operating System: Windows 10

**Comment by erev0s** [comment]
@HongThatCong thank you for reporting this. Would it be possible to share this apk as well please? You can use a service like https://tria.ge/

**Comment by HongThatCong** [comment]
Of course, here is the link:
https://tria.ge/240311-b3mlraha95/behavioral1

Brgds

**Comment by erev0s** [comment]
Using the apk, I provided a more suitable fix.
Please try it out by installing the version with the latest commits:
~~~~
pip install git+https://github.com/androguard/androguard
~~~~
