### ISSUE TITLE
Could not install androguard in Python 3.12.2 using poetry due to no matching version pyqt5-qt5

### ISSUE THREAD

**Issue by JackLiar** [androguard/androguard#1018]
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do

install androguard using poetry like this:

```shell
poetry add androguard
```

### Describe what you expected

androguard to be installed

### Describe what actually happened

get this log message:

```shell
$ poetry add androguard
Using version ^4.1.1 for androguard

Updating dependencies
Resolving dependencies... (5.5s)

Package operations: 15 installs, 0 updates, 0 removals

  - Installing pyqt5-qt5 (5.15.13): Failed

  RuntimeError

  Unable to find installation candidates for pyqt5-qt5 (5.15.13)

  at venv/lib/python3.12/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install pyqt5-qt5.
```

### System Information

- Androguard Version: 4.1.1
- Python Version: 3.12.2 & 3.10.13
- Operating System: Ubuntu 22.04.4 LTS

### Further Log Files and Output

no more

---

I do see the github action, and I did a test on 3.10.13, but I could not reproduce the peocedure. Could you guys create a new environment and make a test?

**Comment by ehrenb** [comment]
Could be related to https://github.com/androguard/androguard/pull/985#issuecomment-1874822028

**Comment by JackLiar** [comment]
Oh thx dude! May I ask would there be a hot fix release like 4.1.2? That would be a great help to all the users :)

**Comment by ehrenb** [comment]
> Oh thx dude! May I ask would there be a hot fix release like 4.1.2? That would be a great help to all the users :)

@erev0s

**Comment by erev0s** [comment]
Will release another patch version in the coming days

**Comment by JackLiar** [comment]
It seems like even lock down to pyqt5-qt5 5.15.2, it still fails on apple silicon environment. Linux x86_64 is ok though

**Comment by ehrenb** [comment]
Ok, this should be resolvable by installing the "right" version based on a platform condition.  For example, when `sys_platform == 'darwin' and (`platform_machine == 'arm64`  or `platform_machine == x86_64`), we should be safe to install the latest version of pyqt5-qt5, otherwise we need to use the older version.  I don't have an ARM MacOS machine to test this on.

* https://python-poetry.org/docs/dependency-specification/#using-environment-markers
* https://peps.python.org/pep-0508/#environment-markers

**Comment by ehrenb** [comment]
> It seems like even lock down to pyqt5-qt5 5.15.2, it still fails on apple silicon environment. Linux x86_64 is ok though

Could you try cloning running `poetry install` on this forked branch https://github.com/ehrenb/androguard/tree/pyqt5-qt5-fix and share the output?

**Comment by JackLiar** [comment]
It's good :)

whole procedure:

```shell
$ pyenv shell 3.12.0
$ virtualenv venv
$ source venv/bin/activate
$ pip install poetry
$ poetry install
Updating dependencies
Resolving dependencies... (1.6s)

Package operations: 44 installs, 0 updates, 0 removals

  - Installing markupsafe (2.1.5)
  - Installing six (1.16.0)
  - Installing asttokens (2.4.1)
  - Installing executing (2.0.1)
  - Installing mako (1.3.2)
  - Installing numpy (1.26.4)
  - Installing parso (0.8.3)
  - Installing pure-eval (0.2.2)
  - Installing sqlalchemy (1.4.52)
  - Installing traitlets (5.14.2)
  - Installing typing-extensions (4.10.0)
  - Installing wcwidth (0.2.13)
  - Installing alembic (1.13.1)
  - Installing banal (1.0.6)
  - Installing contourpy (1.2.1)
  - Installing cycler (0.12.1)
  - Installing decorator (5.1.1)
  - Installing fonttools (4.50.0)
  - Installing jedi (0.19.1)
  - Installing kiwisolver (1.4.5)
  - Installing matplotlib-inline (0.1.6)
  - Installing pillow (10.3.0)
  - Installing prompt-toolkit (3.0.43)
  - Installing pygments (2.17.2)
  - Installing pyparsing (3.1.2)
  - Installing pyqt5-qt5 (5.15.13)
  - Installing pyqt5-sip (12.13.0)
  - Installing python-dateutil (2.9.0.post0)
  - Installing stack-data (0.6.3)
  - Installing apkinspector (1.2.2)
  - Installing asn1crypto (1.5.1)
  - Installing click (8.1.7)
  - Installing colorama (0.4.6)
  - Installing dataset (1.6.2)
  - Installing frida (16.2.1)
  - Installing ipython (8.18.1)
  - Installing loguru (0.7.2)
  - Installing lxml (5.2.1)
  - Installing matplotlib (3.8.4)
  - Installing mutf8 (1.0.6)
  - Installing networkx (3.2.1)
  - Installing pydot (2.0.0)
  - Installing pyqt5 (5.15.10)
  - Installing pyyaml (6.0.1)

Writing lock file

Installing the current project: androguard (4.1.1)
```
