### ISSUE TITLE
androaxml error "not well-formed (invalid token)"

### ISSUE THREAD

**Issue by xkrt** [androguard/androguard#104]
Imported from: https://code.google.com/p/androguard/issues/detail?id=163

**What steps will reproduce the problem?**
1. .\androaxml.py -i eu.chainfire.firepaper.fivehundredpx.xml -o out.xml

**What is the expected output? What do you see instead?**
expected: unpacked xml file.
but was: xml.parsers.expat.ExpatError: not well-formed (invalid token): line 5, column 0

**What version of the product are you using? On what operating system?**
Androaxml version 1.9 with python 2.7.7 on windows 7

**Please provide any additional information below.**
aapt tool from android-4.4W perfectly dumps xml tree.
aapt version: Android Asset Packaging Tool, v0.2
run: >aapt.exe dump xmltree eu.chainfire.fire
paper.fivehundredpx.apk AndroidManifest.xml

Packed AndroidManifest.xml and whole apk:
https://github.com/xkrt/misc/blob/master/issue_attaches/eu.chainfire.firepaper.fivehundredpx.xml
https://github.com/xkrt/misc/blob/master/issue_attaches/eu.chainfire.firepaper.fivehundredpx.apk

**Comment by adesnos** [comment]
Seems to work on the latest commit.

**Comment by leonid-s-usov** [comment]
This was an issue of invalid StringBlock decoding, fixed by ab2fbac1b11002581a454048417a3930c7d88b32
