### ISSUE TITLE
Protection level for custom permissions

### ISSUE THREAD

**Issue by Ch0pin** [androguard/androguard#1046]
When an app sets a custom permission, Androguard returns the protection level as 'normal' even if it is set as 'signature' by the app. It would be nice to have the actual protection level for custom permissions.

**Comment by erev0s** [comment]
Hi @Ch0pin thank you for pointing it out. 
It has been merged to masterhttps://github.com/androguard/androguard/commit/2e3eaca88de92eb05459eb717f0bf1bfc33a10d0

**Comment by Ch0pin** [comment]
Awesome, thanks @erev0s
