### ISSUE TITLE
How to omit the log when using AnalyzeAPK?

### ISSUE THREAD

**Issue by Ma-Zijing** [androguard/androguard#1052]
Hi guys, I use AnalyzeAPK in the pycharm:
`a, d, dx = AnalyzeAPK("./test_data/xxxx.apk")`,

but everytime the code is executed, there are many information about DEBUG and INFO printed on the python console, and these information will make the pycharm do not work, like this:

> 2024-05-22 08:45:35.232 | DEBUG    | androguard.misc:AnalyzeAPK:41 - AnalyzeAPK
2024-05-22 08:45:35.232 | DEBUG    | androguard.misc:AnalyzeAPK:56 - Analysing without session
2024-05-22 08:45:35.267 | INFO     | androguard.core.apk:_apk_analysis:312 - Starting analysis on AndroidManifest.xml
2024-05-22 08:45:35.267 | DEBUG    | androguard.core.axml:__init__:940 - AXMLPrinter

So I wonder whether there are methods to omit these information or just do not let the information print on the console? Thank you.

**Comment by erev0s** [comment]
You can use for example set it to see only errors:
~~~~
from androguard.util import set_log
set_log("ERROR")
~~~~
The possible values are TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL

**Comment by Ma-Zijing** [comment]
It works! Thank you so much :)
