### ISSUE TITLE
ValueError: End of central directory record (EOCD) signature not found

### ISSUE THREAD

**Issue by Ma-Zijing** [androguard/androguard#1062]
Hi guys. I try to analyze an APK file: 
`a, d, dx = AnalyzeAPK(apk_path)`
however, it raises an error:
> Traceback (most recent call last):
>   File "/home/iot/Documents/Zijing/Ollama/main.py", line 18, in <module>
>     StaticAnalysis.test_apk(args.apk_path)
>   File "/home/iot/Documents/Zijing/Ollama/Android/StaticAnalysis.py", line 201, in test_apk
>     a, d, dx = AnalyzeAPK(apk_path)
>   File "/home/iot/.local/lib/python3.10/site-packages/androguard/misc.py", line 57, in AnalyzeAPK
>     a = apk.APK(_file, raw=raw)
>   File "/home/iot/.local/lib/python3.10/site-packages/androguard/core/apk/__init__.py", line 273, in __init__
>     self.zip = ZipEntry.parse(filename, False)
>   File "/home/iot/.local/lib/python3.10/site-packages/apkInspector/headers.py", line 410, in parse
>     eocd = EndOfCentralDirectoryRecord.parse(apk_file)
>   File "/home/iot/.local/lib/python3.10/site-packages/apkInspector/headers.py", line 59, in parse
>     raise ValueError("End of central directory record (EOCD) signature not found")
> ValueError: End of central directory record (EOCD) signature not found

Does it mean the apk file cannot be analyzed? Thank you.

**Comment by obfusk** [comment]
I can't rule out the APK doesn't have an EOCD header, but this looks like a bug in `apkInspector` `EndOfCentralDirectoryRecord.parse()`:

```py
        chunk_size = 1024
        offset = 0
        signature_offset = -1
        file_size = apk_file.seek(0, 2)
        while offset < file_size:
            position = file_size - offset - chunk_size
            if position < 0:
                position = 0
            apk_file.seek(position)
            chunk = apk_file.read(chunk_size)
            if not chunk:
                break
            signature_offset = chunk.rfind(b'\x50\x4b\x05\x06')  # end of Central Directory File Header signature
            if signature_offset != -1:
                eo_central_directory_offset = position + signature_offset
                break  # Found End of central directory record (EOCD) signature
            offset += chunk_size
        if signature_offset == -1:
            raise ValueError("End of central directory record (EOCD) signature not found")
```

If the EOCD header signature happens to be positioned so that it overlaps two chunks (e.g. 1026 bytes before EOF) it will not be found. You could either just `offset += chunk_size - 4` or append the first 4 bytes of the previous chunk (if any) after reading a new one to catch those cases.

Of course most APKs would not have a comment field in the EOCD, let alone one that's more than 1kb.

**Comment by erev0s** [comment]
hey @Ma-Zijing  and @obfusk great work in pinpointing this edge case, thank you. I have already pushed a patched version to fix this issue and I included a test case as well.

**Comment by Ma-Zijing** [comment]
@erev0s @obfusk I guess it's because when I download the apk file, sth goes wrong and the apk file is broken :(
Anyway, thank you for your help :)

**Comment by erev0s** [comment]
@Ma-Zijing maybe you can share the link to the apk to check it out and make sure?

**Comment by Ma-Zijing** [comment]
@erev0s Of course. I upload the apk file below:
[0D77604D2B4424A716C8802125C4FE062E784709810A6A555CC4C081AE9780FE.zip](https://github.com/user-attachments/files/15614641/0D77604D2B4424A716C8802125C4FE062E784709810A6A555CC4C081AE9780FE.zip)

**Comment by obfusk** [comment]
> because it is not an apk

I thought that might be it (stuff like that has happened to me as well) but thanks to that I did spot an unhandled edge case :)
