### ISSUE TITLE
'_io.BufferedReader' object has no attribute 'size'

### ISSUE THREAD

**Issue by claugner** [androguard/androguard#1067]
### Describe what you wanted to do
Parse apk with tampered axml.

### Describe what you expected
`self.buff.size()` in https://github.com/androguard/androguard/blob/ba16da0c0403bbbd339c5cbb444979a822c32437/androguard/core/axml/__init__.py#L448 and https://github.com/androguard/androguard/blob/ba16da0c0403bbbd339c5cbb444979a822c32437/androguard/core/axml/__init__.py#L1410 should be `self.buff_size`.

### Describe what actually happened
```log
File "python3.10/site-packages/androguard/core/axml/__init__.py", line 448, in __init__
"Was something appended to the file? Trying to parse it anyways.".format(self.filesize, self.buff.size()))
AttributeError: '_io.BufferedReader' object has no attribute 'size'
```

**Comment by erev0s** [comment]
Nice! thank you @claugner
