### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by GSKhond** [androguard/androguard#1069]
### Describe what you wanted to do

- AnalyzeAPK for md5- 49ef7f31342241bd4d14ac3576819114

### Describe what actually happened
	AnalyzeAPK is failed.
	In apk(49ef7f31342241bd4d14ac3576819114) there is 6 dex files in it, some dex files are 1kb size with no string data. so it's thowing error.

### System Information

- Androguard Version: 4.1.2
- Python Version: 3.10.2
- Operating System: Windows, kali

### Further Log Files and Output

-	AnalyzeAPK("49ef7f31342241bd4d14ac3576819114")
  File "\Python\Python310\lib\site-packages\androguard\misc.py", line 70, in AnalyzeAPK
    dx.add(df)
  File "\Python\Python310\lib\site-packages\androguard\core\analysis\analysis.py", line 1496, in add
    for string_value in vm.get_strings():
  File "\Python\Python310\lib\site-packages\androguard\core\dex\__init__.py", line 8265, in get_strings
    return [i.get() for i in self.strings]
TypeError: 'NoneType' object is not iterable

**Comment by erev0s** [comment]
@GSKhond if you could provide the apk, i could possibly take a look

**Comment by GSKhond** [comment]
[Sample.zip](https://github.com/user-attachments/files/16637215/Sample.zip)
@erev0s  password: infected

**Comment by erev0s** [comment]
@GSKhond  please check the latest master version. It should fix the issue.

**Comment by GSKhond** [comment]
Thanks :)
