### ISSUE TITLE
NEED HELP! How do i import DalvikVMFormat and GVMAnalysis for androguard 4.1.2？

### ISSUE THREAD

**Issue by Jockey-hub** [androguard/androguard#1072]
Androguard version：4.1.2
python version：3.9
problems：
from androguard.core.bytecodes import DalvikVMFormat
from androguard.core.analysis.ganalysis import GVMAnalysis  is wrong.
How？thanks！

**Comment by erev0s** [comment]
hi @Jockey-hub we are in the process of migrating the documentation and fixing outdated content.
You can take a quick look [here](https://ehrenb.github.io/androguard/reference/androguard/core/index.html) (not merged yet : wip) to see that the classes you are trying to use simply do not exist anymore. 

Feel free to share what you are trying to do and someone may be able to point you to the right direction.

**Comment by Jockey-hub** [comment]
tks! I would like to know that i create a call graph.A node in the gtaph is a API or a function? After all a function may contain two or more APIs.

**Comment by AbhiTheModder** [comment]
For `DalvikVMFormat` i used this example of their test script [here](https://github.com/androguard/androguard/blob/master/tests/test_dexcodeparsing.py#L20). You'll need to use `parse_dex.py` contents inside your project for this since it's inside the `test/` folder we can't import it.
