### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by ohyeah521** [androguard/androguard#1073]
### System Information

- Androguard Version: master
- Python Version: 3.11
- Operating System：Windows

### Further Log Files and Output
```
from androguard.core import (
    androconf,
    apk,
)
a = apk.APK(app_path)
        ^^^^^^^^^^^^^^^^^
  File "D:\venv\Lib\site-packages\androguard\core\apk\__init__.py", line 340, in __init__
    self._apk_analysis()
  File "D:\venv\Lib\site-packages\androguard\core\apk\__init__.py", line 364, in _apk_analysis
    ap = AXMLPrinter(manifest_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\venv\Lib\site-packages\androguard\core\axml\__init__.py", line 980, in __init__
    uri, name = self._fix_name(uri, self.axml.name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\venv\Lib\site-packages\androguard\core\axml\__init__.py", line 1111, in _fix_name
    if not name[0].isalpha() and name[0] != "_":
           ~~~~^^^
IndexError: string index out of range
```

**Comment by erev0s** [comment]
hi @ohyeah521  could you please share a test apk for this

**Comment by ohyeah521** [comment]
@erev0s 
[test.zip](https://github.com/user-attachments/files/16955932/test.zip)

**Comment by erev0s** [comment]
@ohyeah521 feel free to test the version available at `master` and let me know.

**Comment by ohyeah521** [comment]
@erev0s Okay, let me test it

**Comment by ohyeah521** [comment]
@erev0s      
```
a = apk.APK(app_path)
        ^^^^^^^^^^^^^^^^^
  File "D:\venv\Lib\site-packages\androguard\core\apk\__init__.py", line 340, in __init__
    self._apk_analysis()
  File "D:\venv\Lib\site-packages\androguard\core\apk\__init__.py", line 364, in _apk_analysis
    ap = AXMLPrinter(manifest_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\venv\Lib\site-packages\androguard\core\axml\__init__.py", line 980, in __init__
    uri, name = self._fix_name(uri, self.axml.name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\venv\Lib\site-packages\androguard\core\axml\__init__.py", line 1111, in _fix_name
    if not name[0].isalpha() and name[0] != "_":
           ~~~~^^^
IndexError: string index out of range
```

[ sample](https://www.dropbox.com/scl/fi/ww9y6ye6smjxqvrbmqkqu/sample.apk?rlkey=q2tr1krpb4sjbrg66n8ord2ne&st=z22rbe5t&dl=0)

**Comment by erev0s** [comment]
@ohyeah521 are you sure you have the correct version. I just tried and it works fine for me.

**Comment by ohyeah521** [comment]
pip install git+https://github.com/androguard/androguard
Collecting git+https://github.com/androguard/androguard
  Cloning https://github.com/androguard/androguard to c:\users\monkey\appdata\local\temp\pip-req-build-3ro2y4g9
  Running command git clone --filter=blob:none --quiet https://github.com/androguard/androguard 'C:\Users\zxxxx\AppData\Local\Temp\pip-req-build-3ro2y4g9'
  Resolved https://github.com/androguard/androguard to commit da5c1dd8ef8d41cdf9160d0bc6db5965ab457d30
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

**Comment by ohyeah521** [comment]
After I uninstalled and reinstalled it worked fine

```
pip uninstall androguard
pip install git+https://github.com/androguard/androguard
```
