### ISSUE TITLE
Substitute all occurrences of get_permissions and get_detail_permissions in AndroGuard

### ISSUE THREAD

**Issue by zyrikby** [androguard/androguard#108]
After merging PR #103 need to substitute all occurrences of get_permissions and get_detail_permissions methods in apk.py with the correct counterparts.

**Comment by adesnos** [comment]
Do you want to do it ?

**Comment by subho007** [comment]
@zyrikby any updates on this ?

**Comment by zyrikby** [comment]
It seemed to me that Anthony during his last big cleaning removed old references. In PR #138, I removed the implementations of these old methods and my eclipse did not find any references to these methods.

**Comment by subho007** [comment]
there seems to be some mismatch.

The API_PERMISSION_MATCHING are in the following Folder: https://github.com/androguard/androguard/tree/master/androguard/core/api_specific_resources/api_permission_mappings

This is not invoked anywhere, and the old way of extracting used permissions are now removed along with `PathVars` and `TaintedVariables` which now makes it difficult for me to track down permissions which are used in the application.

CC'ing @dhilipsiva who is helping me to refactor this

**Comment by zyrikby** [comment]
As I said, @adesnos completely rewrote VMAnalysis class. Now there is no references to this functionality anymore. I suppose that Anthony plans to add this functionality to newVMAnalysis later (see androguard/core/analysis/analysis.py).

However, I agree that the project needs a more clear plan how to be developed. Any thoughts @adesnos ?

**Comment by subho007** [comment]
@zyrikby I agree, let me look at it and suggest a new PR :)

**Comment by subho007** [comment]
@adesnos it seems a lot of changes needs to be done, without proper plan, I seem to hit a wall. Can you suggest/add API permission mappings ?

**Comment by subho007** [comment]
@adesnos can we have a separate issue for upgrades. Stuffs which are missing now:
1. Permission Maps
2. Tainted_Packages
3. Tainted_Variables
4. Complete port of newVMAnalysis to uVMAnalysis

**Comment by dhilipsiva** [comment]
@subho007 If possible can you close this? Not relevant anymore.
