### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_end' when calling `get_source`

### ISSUE THREAD

**Issue by aitviid** [androguard/androguard#1081]
### Describe what you wanted to do

Print source code of this APK: https://updates.signal.org/android/Signal-Android-website-prod-universal-release-7.17.5.apk

### Describe what you expected

The snippet below should print the source code of the selected method without issues:

```python
from loguru import logger
from core.apk import APK
from core.dex import DEX
from decompiler.decompiler import DecompilerDAD
from core.analysis.analysis import Analysis

logger.disable("")

apk = APK("Signal-Android-website-prod-universal-release-7.17.5.apk")

analysis = Analysis()
for dex_bytes in apk.get_all_dex():
    df = DEX(dex_bytes, using_api=apk.get_target_sdk_version())
    analysis.add(df)
    df.set_decompiler(DecompilerDAD(df, analysis))

analysed_methods = (
    ("Lorg/thoughtcrime/securesms/database/MessageTable;", "collapseJoinRequestEventsIfPossible"),
)

for method in analysis.get_methods():
    encoded_method = method.get_method()

    if (encoded_method.class_name, encoded_method.name) not in analysed_methods:
        continue
    print(f"{encoded_method.class_name}.{encoded_method.name}")
    print(encoded_method.get_source())
```

### Describe what actually happened

The code crashed with `AttributeError: 'NoneType' object has no attribute 'get_end'` because the 
`end` attribute was set to the default `None`:

```
Traceback (most recent call last):
  File "scratch_1.py", line 37, in <module>
    encoded_method.get_source()
  File "androguard/androguard/core/dex/__init__.py", line 3236, in get_source
    return self.CM.decompiler_ob.get_source_method(self)
  File "androguard/androguard/decompiler/decompiler.py", line 57, in get_source_method
    z.process()
  File "androguard/androguard/decompiler/decompile.py", line 187, in process
    identify_structures(graph, graph.immediate_dominators())
  File "androguard/androguard/decompiler/control_flow.py", line 405, in identify_structures
    loop_struct(Gi, Li)
  File "androguard/androguard/decompiler/control_flow.py", line 189, in loop_struct
    lnodes = mark_loop(first_graph, head, node, head.interval)
  File "androguard/androguard/decompiler/control_flow.py", line 123, in mark_loop
    latch = end.get_end()
  File "androguard/androguard/decompiler/node.py", line 152, in get_end
    return self.end.get_end()
AttributeError: 'NoneType' object has no attribute 'get_end'
```

### System Information

- Androguard Version: master
- Python Version: 3.10.12 and 3.11.2
- Operating System: Both Linux x86_64 and arm64.

### Further Log Files and Output

After some debugging I found that the `decompiler.node.Interval.compute_end` method never 
manages to find a suitable value for `self.end`.

My knowledge on the code is very limited, but after playing around with it for a while I figured the method
might need some fallback value.

I looked at the `self.contents` set and noticed that the `head` node is always present. After that 
I iterated over the entire file and noted down how many times `self.end` gets set to `self.head` 
by the original code.

Out of 314216 times `compute_end` left the `for` loop, `self.end` was equal to `self.head` 11056 times.

I applied this change to `decompiler.node.Interval.compute_end`:

![Screenshot from 2024-09-30 20-13-42](https://github.com/user-attachments/assets/9d1f68a1-c564-427d-948e-4d0944ddc533)

and the code stopped crashing.

I also considered introducing an early `return` statement after the `self.end` assignment in the `for` loop, but I couldn't tell for sure if the author didn't intend to go over the entire set.

I pushed my changes to #1082. I'd appreciate a review.

**Comment by erev0s** [comment]
great work @aitviid . Thank you
