### ISSUE TITLE
How to find out in which method a string is used?

### ISSUE THREAD

**Issue by zyrikby** [androguard/androguard#113]
I would like to find out how to detect a method in an application where a particular string is used? E.g., it is common to specify content provider by a string. So I would like to know in which method the string is used.

**Comment by leonid-s-usov** [comment]
just iterate over tainted strings; when you find the matching string value get the method reference from the TaintedVariable 

`
for tv, candidate in self.vmx.get_tainted_variables().get_strings():
    # if match(candidate):
        # tv.show_paths()
`

**Comment by adesnos** [comment]
With the new analysis you can do:
In [7]: print dx.get_strings_analysis()["YOUR_STRING"]
