### ISSUE TITLE
AnalyzeAPK Fails with "AttributeError: 'dict' object has no attribute 'AOSP_PERMISSIONS'"

### ISSUE THREAD

**Issue by ptroxell** [androguard/androguard#114]
Trying to analyze an app as follows:

> androlyze.py -s
Androlyze version 3.0
In [1]: a,d,dx = AnalyzeAPK("../com.whatsapp.apk")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Library/Python/2.7/site-packages/androguard-3.0-py2.7.egg/EGG-INFO/scripts/androlyze.py in <module>()
----> 1 a,d,dx = AnalyzeAPK("../com.whatsapp.apk")

/Library/Python/2.7/site-packages/androguard-3.0-py2.7.egg/androguard/misc.pyc in AnalyzeAPK(filename, raw, decompiler)
     55     androconf.debug("APK ...")
     56     a = APK(filename, raw)
---> 57     d, dx = AnalyzeDex(a.get_dex(), raw=True, decompiler=decompiler)
     58     return a, d, dx
     59 

/Library/Python/2.7/site-packages/androguard-3.0-py2.7.egg/androguard/misc.pyc in AnalyzeDex(filename, raw, decompiler)
     84 
     85     androconf.debug("GVMAnalysis ...")
---> 86     gx = GVMAnalysis(dx, None)
     87 
     88     d.set_vmanalysis(dx)

/Library/Python/2.7/site-packages/androguard-3.0-py2.7.egg/androguard/core/analysis/ganalysis.pyc in __init__(self, vmx, apk)
   3206         #                                            j.get_class_name(), j.get_name(), j.get_descriptor())
   3207 
-> 3208         list_permissions = self.vmx.get_permissions([])
   3209         for x in list_permissions:
   3210             for j in list_permissions[x]:

/Library/Python/2.7/site-packages/androguard-3.0-py2.7.egg/androguard/core/analysis/analysis.pyc in get_permissions(self, permissions_needed)
   1967         permissions = {}
   1968 
-> 1969         permissions.update( self.get_tainted_packages().get_permissions( permissions_needed ) )
   1970         permissions.update( self.get_tainted_variables().get_permissions( permissions_needed ) )
   1971 

/Library/Python/2.7/site-packages/androguard-3.0-py2.7.egg/androguard/core/analysis/analysis.pyc in get_permissions(self, permissions_needed)
   1174         pn = set(permissions_needed)
   1175         if permissions_needed == []:
-> 1176             pn = set(self.AOSP_PERMISSIONS_MODULE.AOSP_PERMISSIONS.keys())
   1177 
   1178         classes = self.__vm.get_classes_names()

AttributeError: 'dict' object has no attribute 'AOSP_PERMISSIONS'

In [2]: 

Tried other APKs with same result. Thoughts?

**Comment by ririhedou** [comment]
I believe this is a bug cuz I met the same problem several times,
Traceback (most recent call last):
  File "androguard_ANALYSIS.py", line 89, in <module>
    display_PERMISSION( vm, x, classes )
  File "androguard_ANALYSIS.py", line 69, in display_PERMISSION
    perms_access = x.get_tainted_packages().get_permissions( [] )
  File "build/bdist.linux-x86_64/egg/androguard/core/analysis/analysis.py", line 1179, in get_permissions
AttributeError: 'dict' object has no attribute 'AOSP_PERMISSIONS

I meet the same problem , I believe the issue locates in the code here:
self.AOSP_PERMISSIONS_MODULE = load_api_specific_resource_module("aosp_permissions", self.__vm.get_api_version())
        self.API_PERMISSION_MAPPINGS_MODULE = load_api_specific_resource_module("api_permission_mappings", self.__vm.get_api_version())

In the function <get_permissions(self, permissions_needed):>  located tin the class class TaintedPackages(object):
we should modify 
if permissions_needed == []:
            pn = set(self.AOSP_PERMISSIONS_MODULE.AOSP_PERMISSIONS.keys())
to 
if permissions_needed == []:
            pn = set(self.AOSP_PERMISSIONS_MODULE["AOSP_PERMISSIONS"].keys())
#the wrong usage of dic in python
the same as others similar bugs.
Best,

**Comment by ririhedou** [comment]
Hi,
 I have updated two files, the code looks running successfully.
 
![1](https://cloud.githubusercontent.com/assets/6613414/8659785/0675ace2-297b-11e5-9ccd-bde5700d635a.png)

Here are the functions in the two modified files.
the function: get_permissions in Class TaintedPackages(object) and Class TaintedVariables(object):
in core/analysis.py
```python
#TODO update this part 
    def get_permissions(self, permissions_needed):
        """
            @param permissions_needed : a list of restricted permissions to get ([] returns all permissions)

            @rtype : a dictionnary of permissions' paths
        """
        permissions = {}

        pn = set(permissions_needed)
        if permissions_needed == []:
            pn = set(self.AOSP_PERMISSIONS_MODULE['AOSP_PERMISSIONS'].keys())

        for f, _ in self.get_fields():
            data = "%s-%s-%s" % (f.var[0], f.var[2], f.var[1])
            if data in self.API_PERMISSION_MAPPINGS_MODULE['AOSP_PERMISSIONS_BY_FIELDS'].keys():
                perm_intersection = pn.intersection(self.API_PERMISSION_MAPPINGS_MODULE['AOSP_PERMISSIONS_BY_FIELDS'][data])
                for p in perm_intersection:
                    try:
                        permissions[p].extend(self.toPathVariable(f))
                    except KeyError:
                        permissions[p] = []
                        permissions[p].extend(self.toPathVariable(f))

        return permissions
```
the function load_api_specific_resource_module(resource_name, api) in androcoonf.py

```python
from androguard.core.api_specific_resources.api_permission_mappings.api_permission_mappings import AOSP_PERMISSIONS_MAPPINGS
#TODO update this part 
def load_api_specific_resource_module(resource_name, api):
    if not api:
        api = CONF["DEFAULT_API"]
    if resource_name == "aosp_permissions":
       value = AOSP_PERMISSIONS.get(api)
       if value:
          return value
       return AOSP_PERMISSIONS.get('9')
    elif resource_name == "api_permission_mappings":
       value = AOSP_PERMISSIONS_MAPPINGS.get(api)
       if value:
          return value
       return AOSP_PERMISSIONS_MAPPINGS.get('9')
    else:
       raise Exception('No such keyword')
```

**Comment by harryhappy** [comment]
@ririhedou 
the function: get_permissions in Class TaintedPackages(object) and Class TaintedVariables(object):
in core/analysis.py
the function load_api_specific_resource_module(resource_name, api) in androcoonf.py

another error 
androguard\core\analysis\analysis.py", line 1179, in get_permissions
    for f, _ in self.get_fields():
AttributeError: 'TaintedPackages' object has no attribute 'get_fields'
