### ISSUE TITLE
What has replaced AndroguardS?

### ISSUE THREAD

**Issue by rotlogix** [androguard/androguard#126]
I was using this class for a lot of functionality in my own tool and I noticed after pulling today, that the androgen file is no longer available.

**Comment by adesnos** [comment]
Uhm sorry, please sync to an older version if you want, I'm trying to clean up a lot of thing.

Otherwise you can do:
    s = session.Session()
    with open("examples/android/TestsAndroguard/bin/classes.dex", "r") as fd:
        s.add("examples/android/TestsAndroguard/bin/classes.dex", fd.read())

**Comment by adesnos** [comment]
(the new way is better, the idea is to support for example multidex apk, or dropped dex/odex etc for the same APK).

**Comment by adesnos** [comment]
and I will fix all files that used androgen with the new way.

**Comment by rotlogix** [comment]
does APK().get_dex() still return the .dex?

**Comment by adesnos** [comment]
yes sure but now it is a generator to support multidex. So you use .next()

**Comment by leonid-s-usov** [comment]
Actually, it would probably be a better idea to add another function as a generator, and leave this backward compatible. Maybe even add a conveniency `get_dex2`

Sent from mobile device, typos and false corrections are possible

Regards,
Leonid S. Usov

14 вер. 2015 о 08:14 Anthony Desnos <notifications@github.com> написав(ла):

**Comment by adesnos** [comment]
yeah ok I changed that :)

get_dex -> simply for the classes.dex
get_all_dex -> multidex support

**Comment by adesnos** [comment]
Please use the release: https://github.com/androguard/androguard/releases
