### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by leonid-s-usov** [androguard/androguard#128]
Hi,

I suggest that we create a clean release branch and start merging master there once it is stabilized. Over the couple of last days master was quite unstable, and that is the only branch people are checking out. Also, we need to bump up the version. WDYT?

**Comment by subho007** [comment]
I think it is a good Idea. I follow git-flow way of working, we can have a `develop` branch which has the latest tested/un-tested code and a `master` branch which has only the latest stable codes.

We should also use tags and releases for it. What do you think @adesnos

**Comment by adesnos** [comment]
Let's add a release or a zip and keep the master for development :)

**Comment by leonid-s-usov** [comment]
master for development is OK with me, though not orthodox. Please introduce the release branch, and make sure that on master the version is with .dev suffix, whereas on release it will be pure version

**Comment by adesnos** [comment]
yep ok
