### ISSUE TITLE
requirements/dependencies

### ISSUE THREAD

**Issue by dweinstein** [androguard/androguard#133]
would be nice to have a more complete description of requirements for using all the aspects of androguard. I have a dockerfile that I maintain for most of the features that I use https://github.com/dweinstein/dockerfile-androguard/blob/master/Dockerfile if it's helpful at all. probably it needs to be updated a bit as well.

for the normal androguard install `yara`, `openssl`, `requests`, `ipython`, `ptrace` shouldn't be needed (I use them for some of my own stuff) but I do think there's `pygments`, `pyfuzzy`, `chilkat`, `pydot`, [`magic`](https://github.com/androguard/androguard/blob/2c96c6a65bc4b5a99c81a87d66f7aa82f2300982/androguard/core/bytecodes/apk.py#L397), [`numpy`](https://github.com/androguard/androguard/blob/45b30eb0b17121e2399dde407249e527eb2dcf5b/elsim/elsim/elsim.py#L74), [`sklearn`](https://github.com/androguard/androguard/blob/45b30eb0b17121e2399dde407249e527eb2dcf5b/elsim/elsim/elsim.py#L75) that could be made a little easier in the `requirements.txt`
# OS X:
- `sparsehash` (for elsim) - `brew install google-sparsehash`
- `muParser` (for elsim) - `brew install muparser`
- `snappy` (for esim/libsimilarity) - `brew install snappy`
- `lzma` `bz`, ... (for elsim/libsimilarity -- but actually included in the repo) - `brew install xz`

**Comment by dweinstein** [comment]
FWIW I try to maintain the official mitmproxy Dockerfile https://github.com/mitmproxy/docker-base/blob/master/Dockerfile if someone wants me to help with the official androguard dockerfile as well...

**Comment by subho007** [comment]
@dweinstein I am willing to help you, what do you need to maintain the androguard docker? The proper build instructions ?

**Comment by dweinstein** [comment]
I have build instructions in my personal dockerfile that I shared above, but could use help reviewing for accuracy and coverage of all the different use cases to make a proper official one. ISTM that there's a dev build and a normal build (i.e., maybe everyone doesn't need the libsimilarity functions for example). 

I'll open up a PR with a starting place to discuss more with you @subho007

**Comment by subho007** [comment]
Agreed. Willing to help :+1:

**Comment by reox** [comment]
I documented the dependencies in #208 

@dweinstein If you could document how to install androguard on OS X, I would add that to the documentation too. Or would you just suggest to use a docker/vagrant/other VM solution as described in  #156?

**Comment by reox** [comment]
We should give an overview about the (optional) dependencies for androguard and seperately for elsim. Maybe it is also a good idea to specify minimum versions as seen in #177 and also dependencies for different OS types, like in #156 .

A good starting point is the debian package: https://packages.debian.org/androguard
as well as #208 which states also some dependencies.
The dependencies should be in the setup.py file as well, for users who just want to install it using pip.

Should the requirements file lists all dependencies too?

**Comment by reox** [comment]
I think the requirements are now good.
If you like to write setup instructions for other OS, feel free and create a PR!
