### ISSUE TITLE
ganalysis and uVMAnalysis

### ISSUE THREAD

**Issue by bwright611** [androguard/androguard#136]
I'm using this for a school project and it seems like I can't import ganalysis nor uVMAnalysis anymore. Can someone let me know how to utilize those?

six@ubuntu:~/androguard$ ./demos/dalvikvm_format_8.py
Traceback (most recent call last):
  File "./demos/dalvikvm_format_8.py", line 10, in <module>
    from androguard.core.analysis import analysis, ganalysis
ImportError: cannot import name ganalysis

**Comment by subho007** [comment]
@bwright611 did you install androguard properly? run the following before you execute the demos:

`[sudo] python setup.py install`

**Comment by bwright611** [comment]
@subho007 Yes, I did. I still get an error about ganalysis and uVMAnalysis. I looked into the androguard/core/analysis directory and I didn't see those classes available anymore. Basically I'm trying to get Mallodroid to run, but it depends on those resources.

**Comment by xeroxnir** [comment]
I'm having the same problem. GVMAnalysis and uVMAnalysis missing in master. Also VMAnalysis replaced newVMAnalysis doesn't have tainted_packages field.

**Comment by bwright611** [comment]
@xeroxnir Did you ever find a solution?

**Comment by adesnos** [comment]
Please use https://github.com/androguard/androguard/releases and not the current git. We are working on refactoring.

**Comment by bwright611** [comment]
Thanks for the response. I was trying to get 1.9 working with Mallodroid but I can't seem to get it working correctly. Everyone has told me 1.9 is the version to use.

**Comment by bowers24** [comment]
Has the github version been refactored? I am experiencing the same issue with that version.

**Comment by reox** [comment]
@bowers24 yep, there was a big refactoring. These things are either gone or renamed.

you can either use an old release (should work fine) or try the latest master and rework your code.
