### ISSUE TITLE
Supporting Python 3 ?

### ISSUE THREAD

**Issue by subho007** [androguard/androguard#137]
@adesnos any thoughts about supporting Androguard for Python 3 ? I am willing to take the challenge to port it to Python 3

**Comment by ybdesire** [comment]
+1

**Comment by bincker** [comment]
+1  support!

**Comment by eighthave** [comment]
@subho007 how about starting your work in a fork?

**Comment by subho007** [comment]
@eighthave we already have a python3 support for androguard :)

Check out: https://github.com/appknox/androguard

**Comment by ybdesire** [comment]
Cool. @subho007 When can this change be released as stable release?

**Comment by ybdesire** [comment]
Thanks a lot @subho007 for this branch. It really help us. Any test have been passed on this branch ?

**Comment by reox** [comment]
See also #208

**Comment by reox** [comment]
I think this can be closed now ;)
