### ISSUE TITLE
getting activity list or any elements list fails (unicode error)

### ISSUE THREAD

**Issue by ranjeetDT** [androguard/androguard#148]
def get_elements(self, tag_name, attribute):
        """
            Return elements in xml files which match with the tag name and the specific attribute

```
        :param tag_name: a string which specify the tag name
        :param attribute: a string which specify the attribute
    """
    l = []
    for i in self.xml:
        for item in self.xml[i].getElementsByTagName(tag_name):
            value = item.getAttributeNS(NS_ANDROID_URI, attribute)
            value = self.format_value(value).encode('ascii', 'ignore') <-- this line should be added
            l.append(str(value))
    return l
```

test 'callsign android app' , https://play.google.com/store/apps/details?id=com.callsign.android.app

error is 

File "lib/androguard/core/bytecodes/apk.py", line 647, in get_activities
    return self.get_elements("activity", "name")
  File "lib/androguard/core/bytecodes/apk.py", line 569, in get_elements
    value = self.format_value(value).decode('ascii', 'ignore')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0493' in position 2: ordinal not in range(128)

**Comment by ThomasBordenave** [comment]
I have the same error when using API get_services(). Of course, get_elements() is called.

```bash
Traceback (most recent call last):
    File "test.py", line 53, in <module>
        for s in a.get_services():

    File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 510, in get_services
    File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 436, in get_elements
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-3: ordinal not in range(128)
```

**Comment by leonid-s-usov** [comment]
Not sure which version of the code you are using. I know that master is broken as many report, but it contains a my pull request merged, where I have fixed a big mess in the encoding when reading string blocks from packed files. Try patching your version with this https://github.com/leonid-s-usov/androguard/commit/ab2fbac1b11002581a454048417a3930c7d88b32

**Comment by ThomasBordenave** [comment]
Thanks for your answer, I'm using the last stable version. I have almost the same issue with this patch:

```bash
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    for s in a.get_services():
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 572, in get_services
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 488, in get_elements
UnicodeEncodeError: 'ascii' codec can't encode character u'\u02ce' in position 2: ordinal not in range(128)
```

**Comment by leonid-s-usov** [comment]
OK,

we don't have line matching version, but I suspect the the problematic line is

[`l.append(str(value))`](https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/apk.py#L530)

please change str() to unicode() and try again, still having my patch applied

**Comment by ThomasBordenave** [comment]
Thank you it's working. The encoding is in fact a mess, I'll wait your patch in the next release :).

**Comment by leonid-s-usov** [comment]
Good to know. 

I suspect that the `unicode()` fix will remove the crash also if the patch is not applied, but it may return a corrupt string without the patch. Would appreciate if you could confirm this.

Cheers!

**Comment by ranjeetDT** [comment]
Thanks for you reply,

Yes the unicode() fix removes the crash but sometimes it returns a corrupt string without the patch.

**Comment by leonid-s-usov** [comment]
Would be great if one of you created a pull request with replacing `str()` to `unicode()` in all places, given that you possess the appropriate APKs to test on.

**Comment by ThomasBordenave** [comment]
Indeed, it works with the unicode() without the patch (In my case).

**Comment by ranjeetDT** [comment]
created a pull request for the change. Please check 
https://github.com/androguard/androguard/pull/159

**Comment by reox** [comment]
@ranjeetDT @leonid-s-usov Can you check if this one is still an issue? I think the unicode errors are gone now?

**Comment by ranjeetDT** [comment]
@reox : This seems to be fixed. You can close it.
