### ISSUE TITLE
how to install the androguard in the Mac OS X EI Capitan?

### ISSUE THREAD

**Issue by micxu** [androguard/androguard#156]

**Comment by xzhou** [comment]
I tried but failed, seems too many dependencies.

**Comment by dweinstein** [comment]
I suggest using this docker container https://github.com/dweinstein/dockerfile-androguard

**Comment by giladbeeri** [comment]
Which errors do you get? I succeeded installing it in OS X 10.11.

**Comment by micxu** [comment]
how to install python? could you give me detailed information? like install steps?


________________________________
发件人: Gilad Beeri <notifications@github.com>
发送时间: 2016年1月25日 19:26
收件人: androguard/androguard
抄送: micxu
主题: Re: [androguard] how to install the androguard in the Mac OS X EI Capitan? (#156)


Which errors do you get? I succeeded installing it in OS X 10.11.

―

**Comment by gnaix92** [comment]
@giladbeeri how to install androguard in OS X 10.11

**Comment by reox** [comment]
It would be nice to test androguard on travis with OS X. Last time I tried, I failed to get everything set up...
Who has an idea?

**Comment by reox** [comment]
seems this works now out of the box, so closing this.
