### ISSUE TITLE
multidex support in parsing a classes.dex file while passing APK

### ISSUE THREAD

**Issue by ranjeetDT** [androguard/androguard#158]
In dvm.py file, the below code does not support multiple dex files

 class DalvikVMFormat(bytecode._Bytecode):

```
def __init__(self, buff, decompiler=None, config=None, using_api=None):
    #to allow to pass apk object ==> we do not need to pass additionally target version
    if isinstance(buff, APK):
        self.api_version = buff.get_target_sdk_version()
        buff = buff.get_dex()  #getting dex from APK file <---- should it not be buff.get_all_dex() ????
    elif using_api:
        self.api_version = using_api
```

get_dex() only will return a single dex file buffer, I think this needs to be modified to support multiple dex.

**Comment by wjk20120522** [comment]
As I understand it, each DalvikVMFormat object is just a dex file. So the 'buff' variable is just the content of one dex file. I don't think  the buff can be 'APK' type, because in _load() function, the 'buff' must be the content of one dex file.

**Comment by ranjeetDT** [comment]
well; if that is the case, then there is no need to check if 'buff' is an instance of APK and get the dex from it;

**Comment by reox** [comment]
I think (but never tested it) that multidex is implemented already. Each DalvikVMFormat is for a single dex file only, but the Analysis object can handle multiple dex files and also reference between them.

**Comment by reox** [comment]
I'll close this now. In my opinion multidex is working, but there might be some other work to do for better usability. please create new specific issues if needed.
