### ISSUE TITLE
unable to parse AndroidManifest having unicode characters

### ISSUE THREAD

**Issue by ranjeetDT** [androguard/androguard#160]
If the AndroidManifest file is not properly formed and cannot be parsed; (but the apk is generated), the exception is raised. Need to handle such errors.

self.xml[i] = minidom.parseString((self.axml[i].get_buff())) <-- exception in this line

app to test : https://play.google.com/store/apps/details?id=com.jpmorgan 

Below is the stacktrace: 

Error
Traceback (most recent call last):
  File "/Users/ranjeet/Downloads/DT_home/DT_projects/androguard/tests/test_apk.py", line 18, in testAPK
    1)
  File "/Users/ranjeet/Downloads/DT_home/DT_projects/androguard/androguard/core/bytecodes/apk.py", line 204, in **init**
    self.xml[i] = minidom.parseString((self.axml[i].get_buff()))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: not well-formed (invalid token): line 52, column 0

**Comment by leonid-s-usov** [comment]
See #140 for a solution

**Comment by leonid-s-usov** [comment]
Or better, #148

**Comment by ranjeetDT** [comment]
understood, on further analysis, I found that there are some apks for which the AndroidManifest file is not properly formatted i.e. it cannot be parsed using xml parsers but still the apk is generated. One such app is  https://play.google.com/store/apps/details?id=com.jpmorgan. So, an exception is raised and APK object is not initialised.

**Comment by leonid-s-usov** [comment]
I can't check it currently, but it may be something I fixed in a pull request https://github.com/androguard/androguard/pull/155

**Comment by ranjeetsinha13** [comment]
Something similar issue I am getting it for below app as well 
[https://play.google.com/store/apps/details?id=com.nanoo.darksword&hl=en] 

The AndroidManifest.xml is not getting parsed using minidom parser. However, if I use lxml it works perfectly fine. Please have a look.

**Comment by reox** [comment]
@ranjeetsinha13 this manifest is especially nasty... It uses an empty namespace, which gives me an error when using lxml:
```
In [25]: etree.fromstring(axml.get_buff())
  File "<string>", line 3
XMLSyntaxError: xmlns:Liapp_Empty_00: Empty XML namespace is not allowed, line 3, column 24
```
how did you opended it? Did you applied the patches in the PR's?

there are now several PR's for the same thing:
#155 #159 so we need to really consolidate things there...

**Comment by subho007** [comment]
@reox will try to test this out

**Comment by reox** [comment]
Run into this issue now again.
It looks like the Liapp Packer uses an empty namespace to fool XML parsers.
The AXML file iteself is read fine.

But the attribute of the Namespace tag resolves to an empty string... I'm not sure how to deal with that. We could just add a fake URI, so the parser is happy.

**Comment by reox** [comment]
Please reopen new tickets if something fails with the AXML Parser, so we can keep track of it more easily.
