### ISSUE TITLE
READ_CONTACTS abusively reported for openInputStream

### ISSUE THREAD

**Issue by cryptax** [androguard/androguard#166]
Hi,
Androguard is reporting use of READ_CONTACTS whenever there is this in the code:

``` java
localInputStream =
this.context.getContentResolver().openInputStream(paramUri);
```

This is abusive, because depending on paramUri, the code above can be used to load an image or plenty of other things. Contacts are really read only if you access ContactsContract.xxxx.

In Androguard's code, you should probably re-visit api_permissions.py and modify/remove:

``` python
"READ_CONTACTS" : {
    "Landroid/app/ContextImpl$ApplicationContentResolver;" : [
        ("F", "openFileDescriptor", "(Landroid/net/Uri; Ljava/lang/String;)"),
        ("F", "openInputStream", "(Landroid/net/Uri;)"),
        ("F", "openOutputStream", "(Landroid/net/Uri;)"),
        ("F", "query", "(Landroid/net/Uri; [L[Ljava/lang/Strin; Ljava/lang/String; [L[Ljava/lang/Strin; Ljava/lang/String;)"),
    ],
```

**Comment by reox** [comment]
this might be also the case for wrong permission/api calls mappings...
related: #180 #222

**Comment by reox** [comment]
as new permission mappings are used now, I'll close this one
