### ISSUE TITLE
******ImportError: No module named elsim ****** base on github new version

### ISSUE THREAD

**Issue by GitHubJJW** [androguard/androguard#167]
Dear androguard tream,

Can you get me a hand, please help me check what happen.

---

apkTemp# androsim.py -i circle.apk circle1.apk -c ZLIB -n
Traceback (most recent call last):
  File "/usr/local/bin/androsim.py", line 4, in <module>
    **import**('pkg_resources').run_script('androguard==3.0', 'androsim.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/androguard-3.0-py2.7.egg/EGG-INFO/scripts/androsim.py", line 31, in <module>

ImportError: No module named elsim

---

Thanks a lot and have a nice day.

Best Regards,
Jay Wang.

**Comment by lengyu2014** [comment]
I meet the same problem @GitHubJJW

**Comment by reox** [comment]
elsim is unfortunately not installed by default when using `setup.py`.
In the setup.py you could add something like
```
packages = find_packages() + find_packages("elsim")
```
before you should run `make` to build the libs.
Maybe there is some more stuff to do, e.g. copying the libs to the correct place.
The debian version (https://packages.debian.org/stretch/androguard) uses a patch to install elsim as well with the libs in the right place.

**Comment by reox** [comment]
as elsim is removed, i'll close this ticket for now
