### ISSUE TITLE
Issue with resource file string entry, string decode size calculation 

### ISSUE THREAD

**Issue by JustEnuff2BDangerous** [androguard/androguard#170]
I've come across the following issues with regards to Androguard/core/bytecodes/apk.py's `StringBlock`class when retrieving an entry from a string pool which is UTF8 encoded. 

Android does not appear to enforce/check the overflow of the string size fields in a String Pool Entry represented in `decode8` and `decode16` as `str_len` and `encoded_bytes`. It is therefore possible in a UTF8 encoded string for the `encoded_bytes` value to overflow the 0x7FFF (2 byte encoding) maximum size in this encoding. This doesn't seem to appear with UTF16 encoded strings, however this may just be due to the size of string required to overflow!

The net effect is this  leads to incorrect (truncated) string from the StringBlock entry retrieval methods and Androguard raising a warning.

Basically the `encoded_bytes` entry now becomes unreliable and should not be used in the `decode8` or `decode16` to slice the string. Since both UTF8 and UTF16 string entries should always be zero terminated I would propose the following to resolve the string retrieval issue (this is also how Android does it):

``` python
     def decode8(self, offset):
        str_len, skip = self.decodeLength(offset, 1)
        offset += skip

        encoded_bytes, skip = self.decodeLength(offset, 1)
        offset += skip

        str_end = self.m_charbuff[offset: ].find('\x00')
        data = self.m_charbuff[offset: offset + str_end]

        return self.decode_bytes(data, 'utf-8', str_len)

```

``` python

    def decode16(self, offset):
        str_len, skip = self.decodeLength(offset, 2)
        offset += skip

        encoded_bytes = str_len * 2

        str_end = self.m_charbuff[offset: ].find('\x00\x00')
        data = self.m_charbuff[offset: offset + str_end]

        return self.decode_bytes(data, 'utf-16', str_len)
```

I can't come up with a clean way around the size check, but that's not such a problem if the warning is updated to generate a specific message for this issue (For example: "Invalid decoded string length:: String larger than max string size encoding limit"). 

The problem can be reproduced using  NBA JAM ver 40008.

**Comment by reox** [comment]
Is this still an Issue?

**Comment by reox** [comment]
I had a look at the string processing, and I think this needs to be fixed.
I will see if I can rework this properly.

Matching for null bytes might not work as the string itself might contain null bytes.

**Comment by reox** [comment]
@JustEnuff2BDangerous can you check with the changes from #592 ? I tested with the NBA JAM app and it worked for me, at least for version 4.0.14:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="40014" android:versionName="04.00.14" android:installLocation="0" package="com.eamobile.nbajam_na_wf">
  <uses-sdk android:minSdkVersion="9" android:targetSdkVersion="21"/>
```
