### ISSUE TITLE
How to get apk calls API through androguard api?

### ISSUE THREAD

**Issue by tuomao** [androguard/androguard#171]
apk calls api including android sdk apis,java lib apis.

**Comment by reox** [comment]
You can get all external classes (which are basically all Android SDK and Java Libs that are not defined inside the dex itself) by using `dx.get_external_classes()` - which returns a generator object of `androguard.core.analysis.analysis.ClassAnalysis`.

Does this answer your question?

**Comment by tuomao** [comment]
Yes.Thanks!
