### ISSUE TITLE
command "a,d,dx = AnalyzeAPK(apkname,decompiler)" cannot get the dx

### ISSUE THREAD

**Issue by 2048li** [androguard/androguard#172]
Hi,
I used the script androlyze.py in androguard, after I entered the cmd, running the command "a,d,dx = AnalyzeAPK(apkname,decompiler)", i should get the value of a, d, and dx, but the result showed to me is that the d and dx is null. And I cannot use the "VMAnalysis" to get the analyzed dex object.
Any idea?
Thanks!

**Comment by 2048li** [comment]
any ideas?thanks

**Comment by jjooeey** [comment]
Hey, I am using the same commands and the values of d and dx are null to me as well. Is nobody using this ?

**Comment by reox** [comment]
What version are you using? VMAnalysis is gone and was replaced by newVManalysis.
Can you check with the newest version?

**Comment by reox** [comment]
@2048li and @jjooeey can you check if this problem still persists? If possible, please supply the APK files as well.

**Comment by cdkorzen** [comment]
I had this issue.  In my particular case, I was analyzing an APK that I had broken apart, made changes, and rebuilt.  I found out that in the session object's `add` method calls `androconf.is_android_raw()`.

`is_android_raw()` looks at the first few characters to determine the type of the file.  BUT, if it starts with `"PK"` (i.e. it's a zip), it also looks for the string `"META-INF/MANIFEST.MF"` in the data.  That file did not exist in the APK I was analyzing, I had to sign it with a private key to make the tools create that directory in the ZIP.  Then `AnalyzeAPK` worked fine.

Suggestion: 
1. Open the APK as a ZIP, 
1. look for the existence of 
   1. directory META-INF, and 
   1. the file MANIFEST.MF within it.
1. If they don't exist, sign the APK 

Hopefully, that helps a bit.

**Comment by reox** [comment]
I see. That makes sense.
It would be probably easier to change the detection from `META-INF/MANIFEST.MF` to `AndroidManifest.xml`, as this file should exists in any case.
Also the return code of `Session.add` should be checked in `AnalayzeAPK` because a return of `False` would indicate that the file could not be processed.

Have you tried to load the file manually using `APK`? it should probably work then.

**Comment by reox** [comment]
@2048li @jjooeey @cdkorzen I added a PR ( #259 ) which should resolve the issue for APKs that are not signed. Can you check if this fixes the issue for you? Thanks in advance!
