### ISSUE TITLE
Question: How to get annotations for classes/methods?

### ISSUE THREAD

**Issue by ahawker** [androguard/androguard#175]
Use case: Find all the classes/methods with a certain annotation, e.g. `@Deprecated`.

Finding all classes/methods in the DEX is trivial, but I cannot find any linking data between the classes/methods and their respective annotation data.

The raw annotation data parsed from the DEX format appears to be stored in the map_list at index 15, but I cannot figure out a mechanism for this data to be linked back to the method/class that it is attached.

Any answers or pointers towards the correct direction would be awesome!

**Comment by reox** [comment]
I just had a quick look at this: You can use DalvikVMFormat.get_method_annotations() to get a list of MethodAnnotation items. Now search for the Items where the method_idx matches your method.
Now, you can get the annotation_off which is the offset in the dexfile, where annotation_set_item can be found.
Now, you just need to look for the right one in the MapItems and then find all annotation_off_item and then read the annotation_item at this offset. This one gives you the visibility and an encoded annotation, which gives you the string ID for this annotatio....

I think we should integrate a wrapper into classes, methods and fields..

**Comment by Dellkan** [comment]
I'm quite interested in this as well.

@reox Would you be able to give me an example/gist following your explanation above? I've tried reading https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/dvm.py but honestly, there's a bit of a steep learning curve here that I haven't been able to grasp it so far.

My use case is the following:

- Search apk for all classes/methods annotated with specific annotation
- Read values of said annotation
- Get all annotations (with values) for a specified class/method

**Comment by reox** [comment]
Okay I played a little bit around with it... I even found a bug in the code while doing that :D 

So here is a little snippet I made to get all annotations for methods:
```
from androguard.misc import AnalyzeAPK

a,d,dx = AnalyzeAPK("4e2201cde26141715255d2421f0bcfb1")

for dvm in d:

    for adi in dvm.map_list.get_item_type("TYPE_ANNOTATIONS_DIRECTORY_ITEM"):
        if adi.get_method_annotations() == []:
            continue

        # Each annotations_directory_item contains many method_annotation
        for mi in adi.get_method_annotations():
            print(repr(dvm.get_method_by_idx(mi.get_method_idx())))

            # Each method_annotation stores an offset to annotation_set_item
            ann_set_item = dvm.CM.get_obj_by_offset(mi.get_annotations_off())

            # a annotation_set_item has an array of annotation_off_item
            for aoffitem in ann_set_item.get_annotation_off_item():

                # The annotation_off_item stores the offset to an annotation_item
                annotation_item = dvm.CM.get_obj_by_offset(aoffitem.get_annotation_off())

                # The annotation_item stores the visibility and a encoded_annotation
                # this encoded_annotation stores the type IDX, and an array of
                # annotation_element
                # these are again name idx and encoded_value's

                encoded_annotation = annotation_item.get_annotation()

                # Print the class type of the annotation
                print("@{}".format(dvm.CM.get_type(encoded_annotation.get_type_idx())))
                
                for annotation_element in encoded_annotation.get_elements():
                    print("   {} = {}".format(
                        dvm.CM.get_string(annotation_element.get_name_idx()),
                        # Read the EncodedValue and then the real value - which is again some object...
                        annotation_element.get_value().get_value(),
                        ))


            print()
```

I need to merge the bug fixes before this will work though (should be done in the next minutes).
Getting the annotations is super nasty and it would be nice to have them at the methods/classes/fields directly... Also DAD does not know about them.
