### ISSUE TITLE
Androlze -s won't run on ubuntu 14.04

### ISSUE THREAD

**Issue by dillrich** [androguard/androguard#177]
![screenshot from 2016-04-13 21 02 16](https://cloud.githubusercontent.com/assets/11622670/14514086/7490f36c-01bb-11e6-9a2c-911199efca86.png)

ipython 1.2.1
python 2.7.6
traitlets 4.2.1

**Comment by reox** [comment]
ipython 1.2.1 seems to be very old. I'm running debian stretch and got 5.1.0

can you try to upgrade ipython?
