### ISSUE TITLE
Can not get the app's name

### ISSUE THREAD

**Issue by AnyPython** [androguard/androguard#178]
When i tried to get the app'name, i used the "get_app_name()" but didn't work and it returned me nothing. So i found the function in the "apk.py" .
Here is what you said:
-------------------------------------------------------------------------
    def get_app_name(self):
        """
            Return the appname of the APK

            :rtype: string
        """
        main_activity_name = self.get_main_activity()

        app_name = self.get_element('activity', 'label', name=main_activity_name)
        if not app_name:
            app_name = self.get_element('application', 'label')

        if app_name.startswith("@"):
            res_id = int(app_name[1:], 16)
            res_parser = self.get_android_resources()

            try:
                app_name = res_parser.get_resolved_res_configs(
                    res_id,
                    ARSCResTableConfig.default_config())[0][1]
            except Exception, e:
                androconf.warning("Exception selecting app icon: %s", e)
                app_name = ""
        return app_name
-------------------------------------------
It returned me nothing and i guessed something wrong in the "try ....except....", So i copied the code and ran it in my own project. 
It said:
AttributeError: 'ARSCParser' object has no attribute 'get_resolved_res_configs'.

But "get_resolved_res_configs" was in the class ARSCParser, I don't know if I've did something wrong. But it makes me confused. Please reply me as soon as possible. Thank you !

**Comment by AnyPython** [comment]
Here is my code:
from androguard.core.bytecodes import apk
    FILE = "xxxx.apk"
    a = apk.APK(FILE)
    app_name = a.get_element("application","label")
    if app_name.startswith("@"):
        res_id = int(app_name[1:], 16)
        res_parser = a.get_android_resources()

        app_name = res_parser.get_resolved_res_configs(
                    res_id,
                    apk.ARSCResTableConfig.default_config())[0][1]

    print app_name
 
Traceback:
AttributeError: 'ARSCParser' object has no attribute 'get_resolved_res_configs'

**Comment by AnyPython** [comment]
I am sorry about this question. I fix it up by updating androguard.

**Comment by gurol** [comment]
Could you tell me how to update an existing androguard (1.9) installed on Linux or Mac OS to the latest version (2.0)? I couldn't update it by downloading the zip file of the repository, extract to a local directory and run the setup.py script. Codes are not changes. Thank you in advance.

**Comment by AnyPython** [comment]
Hello~
If you have installed it on Linux and want to update an existing androguard to the latest version , you must have root permission.
1.Extract the zip file to a local directory. For example, the location is '/home/username/xxx'.
2.Open the terminal and run command as 'cd /home/username/xxx' on terminal to enter directory. .
3.Run command as 'sudo python setup.py install'  on terminal to update. It will ask for permission, and then you enter the root password and it will start to update. @gurol
