### ISSUE TITLE
show_Permissions(dx) is not complete

### ISSUE THREAD

**Issue by vftaylor** [androguard/androguard#180]
Hi,

I have Androguard up and running. For some apps (not all), like 'com.facebook.katana', the output of show_Permissions(dx) seems to be incomplete both in terms of the permissions used and the instances where they are used. Am I missing something? Example output from com.facebook.katana follows:

![githubexample](https://cloud.githubusercontent.com/assets/19477986/15407329/35f69c84-1e02-11e6-8541-dedd353a259c.png)

**Comment by gurol** [comment]
Could you provide the sample or its hash?

**Comment by toppatopvt** [comment]
Of course I can:

Package: com.facebook.katana
MD5: 2f5eb2aca674c2774f3a63f0ecf0888d
SHA1: 0274645d76111793b7f9911feb234b343ae93cd5
APK: http://www.filedropper.com/comfacebookkatana

Pretty much you can just get any of the latest APKs and I believe you won't get accurate results either.

Best,
Vince.

**Comment by gurol** [comment]
Hi,
My analysis result is different from yours:

`show_Permissions(dxanalysis)
FACTORY_TEST :
R ['Landroid/content/pm/ApplicationInfo;', 'flags', 'I'] (0xa) ---> Lcom/facebook/common/dextricks/MemoryEnlargementHack;->a(Landroid/content/Context;)V
…
ACCESS_NETWORK_STATE :
1 Lcom/facebook/tools/dextr/bridge/upload/UploadConstraints;->a()Z (0x26) ---> Landroid/net/ConnectivityManager;->getActiveNetworkInfo()Landroid/net/NetworkInfo;
INTERNET :
1 Lcom/facebook/acra/util/SSLConnectionProvider;->getConnection(Ljava/net/URL;)Ljava/net/HttpURLConnection; (0xc) ---> Ljava/net/URL;->openConnection(Ljava/net/Proxy;)Ljava/net/URLConnection;
…
BROADCAST_STICKY :
1 Lcom/facebook/common/errorreporting/crashcounter/CrashCounter;->b()V (0x18) ---> Landroid/content/Context;->sendStickyBroadcast(Landroid/content/Intent;)V
READ_LOGS :
1 Lcom/facebook/acra/LogCatCollector;->collectLogCat(Ljava/lang/String;)Ljava/lang/String; (0xba) ---> Ljava/lang/Runtime;->exec([Ljava/lang/String;)Ljava/lang/Process;
CHANGE_COMPONENT_ENABLED_STATE :
1 Lcom/facebook/nodex/startup/crashloop/CrashLoop;->a(I Z)V (0xa) ---> Landroid/content/pm/PackageManager;->setComponentEnabledSetting(Landroid/content/ComponentName; I I)V
…
WAKE_LOCK :
1 Lcom/facebook/acra/ErrorReporter$ReportsSenderWorker;->acquireWakeLock()Landroid/os/PowerManager$WakeLock; (0x44) ---> Landroid/os/PowerManager;->newWakeLock(I Ljava/lang/String;)Landroid/os/PowerManager$WakeLock;
…
READ_PHONE_STATE :
1 Lcom/facebook/acra/ErrorReporter;->getConstantDeviceData()Ljava/util/Map; (0xa6) ---> Landroid/telephony/TelephonyManager;->getDeviceId()Ljava/lang/String;`

It is interesting that your output contains the 5 permissions that are union of the requested permissions (in Manifest) and required or used permissions (the 8 permissions above in my show_Permissions(dxanalysis)).

**Comment by reox** [comment]
The problem with the permission analysis is the missing references between API calls and permissions.
AFAIK there is no official way of getting the permissions and they are collected by pscope - which seems to be not reliable in some situations.

Does anyone know a good and reliable way of collecting the permissions? Also, this data needs to be updated for every new API release...
