### ISSUE TITLE
Unable to find documentation for androguard 2.0

### ISSUE THREAD

**Issue by DarthEmpty** [androguard/androguard#182]
Hey there,

I was hoping that somebody that knew would point me in the direction of the documentation for androguard 2.0? I found 1.9's documentation perfectly fine but have been unable to find anything similar for 2.0.

**Comment by luckenzo** [comment]
I don't think there is documentation for 2.0 yet!

**Comment by DarthEmpty** [comment]
Ah, fair enough!
Is it possible to get an idea of when it'll be made?

**Comment by reox** [comment]
You can build the documentation locally by using sphinx. I pushed the necessary files in this branch https://github.com/reox/androguard/tree/futurize
Build them with `python setup.py build_sphinx`. You need to have the `sphinx` and `sphinxcontrib-programoutput` package installed.

hth!

**Comment by reox** [comment]
I changed the docs folder in such a way that it would build on readthedocs: http://androguard.readthedocs.io/en/latest/

**Comment by reox** [comment]
as docs work great on readthedocs, i'll close this one.
