### ISSUE TITLE
How to get api?

### ISSUE THREAD

**Issue by dinasaif** [androguard/androguard#183]
I want to write code with java to get all api by androgaurd
any one help me how to make this or which command line must I write to get them?
I write this command :python androdd.py -i Samples.apk -o ./dd
but it create dd folder I want to get all method names only not create dd file and all these lines
Thanks alot

**Comment by reox** [comment]
what do you exactly need? to get a list of all classes use for example `androlyze.py -s` to spawn an ipython shell.
Then use 
```
a,d,dx = AnalyzeAPK("myapk.apk")
d.get_classes_names()
```
to load the APK and get all class names
or
```
for c in d.get_classes():
    print(list(map(lambda x: x.name, c.get_methods())))
```
to print out all method names for all classes
