### ISSUE TITLE
Modifying an APK using androguard

### ISSUE THREAD

**Issue by ohaz** [androguard/androguard#185]
Hey guys,

I'm currently searching for ways to change functions, packages etc in android apps. To do that, I need to be able to rename stuff, move stuff around and similar. Also, I need to be able to assemble the modified app afterwards so that it's a fully working apk again. Is there a way to do such stuff in androguard? if not, do you know any alternatives that allow me to do such things?

Kind regards,
ohaz

**Comment by cryptax** [comment]
You can edit the code for each method, but that's going to be particularly long and tedious...

See method.get_code() and method.get_instructions().

**Comment by ohaz** [comment]
Hm, thank you. Going to try using smali then
