### ISSUE TITLE
show_Permissions(dx) and other show_xx() have disappeared

### ISSUE THREAD

**Issue by cryptax** [androguard/androguard#188]
I have downloaded the sources from git cloning. Hence, androlyze 3.0-dev.

There used to exist a method show_Permissions(dx), show_DynCode(), show_NativeMethods() and show_Paths. Those were in androguard/core/analysis and they clearly are no longer there :(

Where have they gone? or how have they been replaced?

**Comment by reox** [comment]
for the dyncode and native methods, take a look at the xrefs of classes and methods. You need a list of potential classloader functions and just gather the xrefs of them.

For the permissions, I'm not sure how to get this now. You probably need a list of API functions and their permissions from somewhere and then look for those calls in the `get_external_classes` function of `newVMAnalysis`

**Comment by reox** [comment]
@adesnos this function was used quite often I think. Is there still a way to get the permissions for all used API functions?
I think what one needs to do is, uise the api_permission_mappings and intersect that dictionary with the external classes.

**Comment by reox** [comment]
related #222 #180 #166

**Comment by baolingfeng** [comment]
Hi, I want to use the function show_Permissions(), but find it has been removed in the latest version of Androguard. I look into the commits of this repository and find it was removed in the commit 6b24ddf7d385e8a9062de7ae95d7e8dfb12f7b1c . 

Are there any new APIs that have the same function as show_Permissions?

please kindly advise. Thank you very much!

**Comment by reox** [comment]
Have a look at the code here: https://github.com/androguard/androguard/issues/222

But the permissions mapping is not correct/complete. So use it with caution.
