### ISSUE TITLE
No androrisk.py in Androguard 2.0

### ISSUE THREAD

**Issue by wipup** [androguard/androguard#190]
Hello.

There used to exist a script androrisk.py in Androguard 1.9 but it has disappeared in version 2.0.
Was it replaced by any other script? Or is there any function in Androguard 2.0 that I can use to calculate risk value of APK files like androrisk.py?

Thanks

**Comment by reox** [comment]
A lot of stuff was deleted in this commit 6b24ddf7d385e8a9062de7ae95d7e8dfb12f7b1c 

I have no clue why the whole Tainted Stuff was removed, it seems it was removed and not replaced. Maybe there is a new method now? Anyone has information on that?

**Comment by reox** [comment]
After looking into androguard a little bit deeper, i found out that the old "tainted" tools are not required, as you can work with the xref stuff now. So for example, where you first would search for all calls of a method, you can now just ask the method for the xref_from list.

For the risk calculation: This part was in my opinion not really reliable and would easily overestimate the risk. Also the permission model in android changed a lot and new API functions are introduced. Maybe it is better to write your own risk analysis module, that calculates the risk how you see it...
You can still use the old script if you need to (I'm not sure if it will still work though):
https://github.com/androguard/androguard/blob/008f1dc438fb0a4cb846045fbbbb180115ad9224/androguard/core/analysis/risk.py

**Comment by adesnos** [comment]
It is not anymore supported !
