### ISSUE TITLE
No Attribute s.get_objects_apk 

### ISSUE THREAD

**Issue by acsudeep** [androguard/androguard#192]
$ python androguard_ANALYSIS.py 
Traceback (most recent call last):
  File "androguard_ANALYSIS.py", line 93, in <module>
    a, d, dx = s.get_objects_apk(TEST)
AttributeError: 'Session' object has no attribute 'get_objects_apk'

**Comment by xgusix** [comment]
This has been opened for a while but I am getting the same issue, for some reason the class Session does not have the method 'get_objetcs_apk' even if appears in the file sessions.py.
```
from androguard.session import Session

s = Session()
path_apk = <your apk>
with open(path_apk, "r") as fd:
    s.add(path_apk, fd.read())

a, d, dx = s.get_objects_apk(path_apk)
```
This throws an error: AttributeError: 'Session' object has no attribute 'get_objects_apk'

Actually, doing ```dir(s)``` doesn't appear in the list of methods:

```
dir(s)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add', 'addAPK', 'addDEX', 'analyzed_apk', 'analyzed_dex', 'analyzed_digest', 'analyzed_files', 'get_analysis', 'get_classes', 'get_digest_by_class', 'get_filename_by_class', 'get_format', 'get_nb_strings', 'get_strings', 'isOpen', 'load', 'reset', 'save', 'setupObjects']
```
There is no __version__ to be sure what version of androguard I am running, but I just cloned the repo and it seems like I am running the correct version:

```
/usr/local/lib/python2.7/dist-packages/androguard-3.0-py2.7.egg
/usr/local/lib/python2.7/dist-packages/androguard-3.0-py2.7.egg-info
/usr/local/lib/python2.7/dist-packages/androguard-3.0-py2.7.egg-info/PKG-INFO
/usr/local/lib/python2.7/dist-packages/androguard-3.0-py2.7.egg-info/SOURCES.txt
/usr/local/lib/python2.7/dist-packages/androguard-3.0-py2.7.egg-info/dependency_links.txt
/usr/local/lib/python2.7/dist-packages/androguard-3.0-py2.7.egg-info/installed-files.txt
/usr/local/lib/python2.7/dist-packages/androguard-3.0-py2.7.egg-info/requires.txt
/usr/local/lib/python2.7/dist-packages/androguard-3.0-py2.7.egg-info/top_level.txt
```

**Comment by xgusix** [comment]
Okay, it seemed to be a problem with the version. For some reason I didn't remove the previous version from the library, and even if it looked like it was the correct version, a closer look showed me that is wasn't the correct one.

To solve the issue I just needed to remove the old library manually and ```python setup.py install``` androguard again.
