### ISSUE TITLE
What is tainted packages?

### ISSUE THREAD

**Issue by ybdesire** [androguard/androguard#193]
The description of androguard function [get_tainted_packages()](http://doc.androguard.re/html/analysis.html#androguard.core.analysis.analysis.VMAnalysis.get_tainted_packages) is "Return the tainted packages". It seems all classes defined for the APP will be returned from my testing of this function. But what is the meaning of tainted packages ?

**Comment by ybdesire** [comment]
Anyone can help?

**Comment by leonid-s-usov** [comment]
Tainted packages are those that are referenced at least once from the code of the application.
This is detected by inspecting every opcode of every code block in the application bundle and looking for types of opcodes that reference fields or make calls to the classes. Then all such cases are collected and the related packages are extracted. (A very generic description of the process, please refer to the code for details)

This is done in the VxAnalysis, if I remember correctly. Look for TaintedFeild and TaintedMethod structures, track it from there. Sorry don’t have more time to direct your further.

**Comment by ybdesire** [comment]
Thank you very much @leonid-s-usov  for your answer. It’s very helpful for me.
