### ISSUE TITLE
What is the version of androguard permission api mapping？

### ISSUE THREAD

**Issue by Sophiexuer** [androguard/androguard#194]
Hi,

When I use the permission api mapping function in androguard, I wonder what is the current version. Does the version match with Android M or N? And if I find the mapping document, how can I replace it in androguard.

Waiting for your response.

Thanks.

**Comment by simoneaonzo** [comment]
Look at [api_permission_mappings_api22.py](https://raw.githubusercontent.com/androguard/androguard/master/androguard/core/api_specific_resources/api_permission_mappings/api_permission_mappings_api22.py)

Api 22 corresponds to Android 5.1 (Lollipop)

**Comment by Sophiexuer** [comment]
Thanks.

2017-01-09 16:43 GMT+08:00 SiX110 <notifications@github.com>:
