### ISSUE TITLE
Old Docs Issue (ex: VMAnalysis() --> newVMAnalysis())

### ISSUE THREAD

**Issue by Jack2** [androguard/androguard#201]
`class androguard.core.analysis.analysis.VMAnalysis(_vm)`

I refrenced this class, but error occurred.

so I checked androguard source, then `VMAnalysis()` func changed to `newVMAnalysis()`

but, Document didn't updated. Check Plz

URL : http://doc.androguard.re/html/androlyze.html

**Comment by ryantzj** [comment]
The same with this too 
http://doc.androguard.re/html/analysis.html

**Comment by reox** [comment]
yep, the page with the documentation is for a really old version, see also https://github.com/androguard/androguard/issues/182
