### ISSUE TITLE
How to get field value?

### ISSUE THREAD

**Issue by ZippoZeng** [androguard/androguard#204]
In Java Code：
  public static final String SDK_VERSION = "1.2.0"

how to use androguard to get" SDK_VEDRSION" the value of this field。

**Comment by reox** [comment]
You mean like:

```
a,d,dx = AnalyzeAPK("apk")
d.get_class("Lyour/class/path;").get_fields()[0].show()
```

This would print out the first field in `Lyour/class/path;` class.

**Comment by ZippoZeng** [comment]
How to get the string "1.2.0"？

**Comment by reox** [comment]
I think it should be:
```
d.get_class("Lyour/class/path;").get_fields()[0].get_init_value().get_value()
```

**Comment by reox** [comment]
You coud try to call the reset() Method on the Session (e.g. CONF["SESSION"].reset())

At least for me that helped sometimes. But still, the RAM gets fuller and fuller. I also want to investiagte in this, but I'm still on the way to make androguard useable with python2/3
