### ISSUE TITLE
Problems with Demo Visitors

### ISSUE THREAD

**Issue by cdkorzen** [androguard/androguard#207]
For dad_emul.py and dad_print.py:

-  To run the demos, you must have magicspiral.apk.  They will not work out of the box

Even if you modify them to point to another APK, there are other issues.  For dad_print.py, many of the visitor calls now pass along keyword arguments and so the signatures don't match up:

- visit_base_class
- visit_param
- visit_astore
- etc.

The signature for visit_invoke now is called with many more arguments than the dad_print visitor expects.

I don't know if dad_emul works on a different APK.

**Comment by reox** [comment]
yeah, most of the demos are somehow broken because they use an old version of the API.
I think all non-functional demos should be sorted out or at least be marked as non-functional (or use with this and that version only)
