### ISSUE TITLE
[RFP] Contributor Guidelines

### ISSUE THREAD

**Issue by subho007** [androguard/androguard#209]
Creating a Discussion to discuss details on Contribution Guidelines. Feel free to discuss and add/edit the Wiki located: https://github.com/androguard/androguard/wiki/Contributions

We can discuss here for anything else

**Comment by reox** [comment]
should we define some coding standard? like use PEP8 and reST style comments?

**Comment by eighthave** [comment]
I'm fine with PEP8, but I'd rather have no PEP8 enforcement than have it
blocking merging the backlog.
