### ISSUE TITLE
Arguments decompiler has no effect for AnalyzeAPK and AnalyzeDEX

### ISSUE THREAD

**Issue by reox** [androguard/androguard#210]
the argument `decompiler` for the Functions `AnalyzeAPK` and `AnalyzeDEX` has no effect, as it is not propagated to the session and in `Session` only DAD is used.
Those methods should also support other decompilers

**Comment by adesnos** [comment]
You're right ! I will try to fix that

**Comment by reox** [comment]
Today I found out, that in DalvikVMFormat you can also set the decompiler, but it will not have much effect, as the arguments to DecompilerDAD are a DalvikVMFormat and Analysis.
Therefore I think you can also remove this argument from DalvikVMFormat? Otherwise you would have some cyclic dependency...
