### ISSUE TITLE
Move log message to a python library

### ISSUE THREAD

**Issue by adesnos** [androguard/androguard#220]
Hi,

right now there is multiples things in the code like 'print'/'debug' etc but with no consistency.

We should use a python library to handle that. Any idea ?

**Comment by eighthave** [comment]
I know of two good options:
* _warnings_ which provides compiler-style warning/error messages
* _logging_ which provides syslog style logging, like for daemons

The choice depends on how people are reading the logs, and what its reporting.  Seems like androguard has more compiling/decompiling interactions than process/daemon interactions, so my guess is that _warnings_ will make more sense.

**Comment by reox** [comment]
Thats a hard question to answer... If you are using androguard in a automated way, you probably want the logging classes, as you can then put all the stuff into your own logfile. For standalone/ipython style working the warnings are probably better but must be propagated to the user correctly, e.g. when using the GUI.

**Comment by eighthave** [comment]
The messages can be sent wherever with both libraries, its more about
the style of the logging messages, and whether you need levels like
error/warning/debug or
emergency/alert/critical/error/warning/notice/info/debug.

**Comment by subho007** [comment]
We can simply use `from logging import warn, info, error, debug` These gets propagated properly. If any other tools imports androguard, the errors are properly propagated even if a custom classes are made. Do you want me to work on it @adesnos ?

**Comment by reox** [comment]
Recently I took a closer look to the logging in androconf. I needed to adopt it a little bit, as `warning` would always read the traceback. 
actually the androconf's logging is already the python `logging`.

I would start to use logging in a better fashion, like creating the log handlers in the classes directly rather than using androconf.

afair, there are no print's anymore :)
