### ISSUE TITLE
Taint analysis

### ISSUE THREAD

**Issue by adesnos** [androguard/androguard#221]
Taint analysis could be really useful in Androguard and could reduce significantly an analysis.

Let's do:

- [ ] quick review of the algorithm we want to add
- [ ] first version of a generic support in the analysis to improve/change the algorithm
- [ ] add the corresponding code in the GUI

**Comment by subho007** [comment]
This is awesome. We did had Taint Analysis in Androguard 2.0 why did we remove it in the first place @adesnos ?

**Comment by reox** [comment]
I think the xrefs replaced a lot of it? I rewrote parts of my tools that used tainted to use xrefs which works pretty good (but it is a little bit harder to use...)

**Comment by hallucino** [comment]
@subho007 It was not really good and took a lot of memory.

**Comment by adesnos** [comment]
@subho007 I removed it because it is inefficient, took a lot of memory and we need a clear design

**Comment by the-house** [comment]
@adesnos am happy to contribute to getting taint analysis working again, let me know how I might assist.

**Comment by subho007** [comment]
In the meantime I have ported the old Taint Analysis - https://github.com/appknox/androguard/tree/add-tainted-analysis

commit - https://github.com/appknox/androguard/commit/7af65537ba7051feb67530ab47041985097d5ce6

I think it is better to keep it until a newer implementation is done. Lot of tool depends on the analysis, and it is very difficult to refactor all the tools which uses androguard.

@adesnos @reox thoughts ?

PS: My fork is a re-fork of the current androguard implementation

**Comment by reox** [comment]
Wow, very impressive! I would merge it!

**Comment by reox** [comment]
But is there anything in tainted, that can not be done with the xrefs? I rewrote some parts that used tainted before and it wasn't too hard... 
What are the functions we need?

I think we can do some quick changes to support at least the following things:
* find all calls to / from X
* find all occurences of a string
* find all usages of a package
* ???

**Comment by subho007** [comment]
@reox that is exactly why I didn't send a PR. We can do most of the tainted analysis with XREFs. 

One important thing which we require was `find all instances of Ljavax/crypto/` which is not possible to find from XREF alone, `Ljavax/crypto/` is a system package, it is found in the descriptor of the current method.

**Comment by reox** [comment]
I started to refactor a little bit the Analysis module. If you have nice ideas for the functions we should implement, please share :)

**Comment by reox** [comment]
@subho007 regarding the javax.crypto: if such a module is used, it should end up in the external methods, right? Do you have an APK to test this on? I think this should work already...

**Comment by waqarrashid33** [comment]
CuckooDroid still uses the androguard 1.9. I am to upgrade it to Androguard 3.2 but I don't even know how to begin with some of that stuff like Dynamic Code, checking for permissions etc. Here is are the two files that needs to be changed:
[apkinfo.py](https://github.com/idanr1986/cuckoo-droid/blob/1350274639473d3d2b0ac740cae133ca53ab7444/modules/processing/apkinfo.py)
[androguard_extentions.py](https://github.com/idanr1986/cuckoo-droid/blob/master/lib/cuckoo/api/androguard_extentions.py)

**Comment by reox** [comment]
Either you start implementing those missing methods again or remove them from cuckoodroid...
See also #505 
bring back all those is_* methods should be only a matter of researching all the current API classes which are used. Then use the XREF system to find calls to them.

**Comment by reox** [comment]
This one is probably also interesting for you: #222

**Comment by waqarrashid33** [comment]
I am almost done, one last thing. Do you remember what was the `path.get_access_flag()`. Is it the access flag of caller or callee. I am still trying to figure it out from the source code but any help would be appreciated.

**Comment by waqarrashid33** [comment]
Any hints for `vmx.get_permissions()`?

**Comment by reox** [comment]
For the `get_access_flag` I have unfortunately no clue... The source is also not documented...

The `get_permissions` method was used to retreive a list of actually used permissions - right?
I think the code I posted in #222 should work for that... But the documentation is also very vague on that...

**Comment by reox** [comment]
So I had a look at the old code and found some things:

`PathP.get_access_flag()` was used to code if the object was created or called. Similar information is already available on the xrefs of each `ClassAnalysis`.
the `PathP.get_idx()` function simply returns the offset in the bytecode, which is already stored in all xrefs.

The Tainted stuff had the following advantage over the current system:
* It can give you a string usage per Method, currently we store it the way around (methods using string x)
* You could do the same for fields, currently we also store the way around.
* xrefs between methods are package name based and not by method, this information is stored in the PathP object.

Hence: most information is already in the xrefs. We just need a better system of looking them up.

Funfact: while looking at the old code, I found plenty of stuff which did not worked back than either... With this code, the biggest question is "how was it meant to work?" which I can not answer, as there is only sparse documentation and even less tests.

**Comment by reox** [comment]
So I added offsets now in #730 
I left the old behaviour of the get_xref_xxx functions, so nothing should break which relies on a tuple with two items being returned. Maybe we can change that in the future.
A much larger question is now, how we store this information directly at the method level?
This involves probably just iterating over all fields and strings once and adding the information to the MethodClassAnalysis item. One question is though, how can we implement this in a memory efficient manner?
