### ISSUE TITLE
Slow androguard start due to import of api permission mappings

### ISSUE THREAD

**Issue by reox** [androguard/androguard#223]
I noticed that impoting something from androguard takes some time. In my case, it can take up to 5 seconds.
I narrowed it down to the imports of `androguard/core/api_specific_resources/api_permission_mappings/api_permission_mappings.py`, where each import of an api needs about 0.5 seconds.

It seems to me, that this dict is not used beside in the `load_api_specific_resource_module` function. Maybe the import should be just in this function, so it is only slow if this function is needed?
I do not have the broad overview about the potential usage of this dict, so I ask first ;)

**Comment by adesnos** [comment]
+1
