### ISSUE TITLE
help ! give me idea how to use androguard in anaconda for reverse engineering 

### ISSUE THREAD

**Issue by Adhiraj1234** [androguard/androguard#233]
i downloaded the zip file to all the files of androguard here 
can anyone tell me how to install it in windows 
i have no idea please help
and how to run it

**Comment by berfintanriverdi** [comment]
Are you try this?

"Using Windows

Using Anaconda with python3, most of the used packages are pre-installed.

Additional packages, that might be required are:

pyperclip sphinxcontrib-programoutput future pydot

You can simply run

python setup.py install

to install androguard.

and

python setup.py build_sphinx

to create the documentation.
"

**Comment by reox** [comment]
As @berfintanriverdi  already mentioned, there is already some information in the documentation.

You might need to install the packages by hand, e.g. `pip install future` before installing androguard.

Make sure you run it as Administrator, if you did not install Anaconda only for your user.

If something does not work during the installation process, please feel free to open a new ticket!
