### ISSUE TITLE
AttributeError: 'DalvikVMFormat' object has no attribute 'dotbuff'

### ISSUE THREAD

**Issue by berfintanriverdi** [androguard/androguard#234]
when i run this command ->
"./apkviewer.py TheTruthSpy_7.7.apk -o ../cikti2" i got this error message:

AttributeError: 'DalvikVMFormat' object has no attribute 'dotbuff'

What can i do? this is important for me .please help

**Comment by reox** [comment]
Do you know a version of androguard where this worked? Seems like the dotbuff method was removed someday...

**Comment by reox** [comment]
I found out, it was removed in e0dd6b223ce97250e5aae34b90dfd7fbd7eb6f2a.

I think a quick fix would be:
```
diff --git a/androguard/core/data/data.py b/androguard/core/data/data.py
index d997e79..00f0d74 100644
--- a/androguard/core/data/data.py
+++ b/androguard/core/data/data.py
@@ -153,7 +153,7 @@ class DexViewer(object):
         idx = i.start
         label = ""
         for ins in i.get_instructions():
-            c_label = "%x %s\n" % (idx, self.vm.dotbuff(ins, idx))
+            c_label = "%x %s\n" % (idx, ins)
             idx += ins.get_length()
             label += c_label
             width = max(width, len(c_label))
```

As this is the only occurence of dotbuff everywhere... The other question is, if  apkviewer is still working, as it was removed, also with the dependency of ganalysis...

**Comment by piec** [comment]
Hi, it should rather be:
```
c_label = "%x %s %s\n" % (idx, ins.get_name(), ins.get_output(idx))
```
Cheers,
Pierre
