### ISSUE TITLE
DAD generates incorrect graph and uses wrong node for a switch's follow property

### ISSUE THREAD

**Issue by cdkorzen** [androguard/androguard#235]
I'm reverse engineering a large function, and DAD is using the wrong node to follow the switch.

The method is essentially a resource loader.  It does a switch on one of its arguments, and then in most or all of the cases tries to open a file.  It reads/processes that file, then breaks.  Before the function exists, it tests if the file variable is not null, and if so closes the file, otherwise just exits.

Expected source should look something like this:
```
{
    switch (p13) {
        case 1:
              \\do stuff
              break;
        case 2:
              \\do other stuff
              break;
        case 3:
              \\do different stuff
              break;
        default:
              \\do default stuff
              break;
    }
    if (file not null) {
        file.close();
    }
    return;
}
```

What the source looks like is that only in the first conditionals and the first switch case is the file variable tested, and closed if necessary.  When elaborating over the other cases, it sees that it already visited the test/close nodes and so ignores them.  I've tried reproducing it in a small example, but I'm unable to do so.

Here's a bit of what it looks like, from a subclassed writer to try and capture the node flow:
```
    void r(int p13, int p14, int p15)
    {
\\Visiting node 2-Switch(r-BB@0x0)
        v0_0 = 0;
        switch (p13) {
            case 0:
\\Visiting node 475-If(r-BB@0x12a)
                if (p14 != 0) {
\\Visiting node 492-If(r-BB@0x35c)
                    if (p15 != 11) {
\\Visiting node 493-SC(500-If(r-BB@0x3be) || 501-If(r-BB@0x3c6))
                        if ((p15 < 13) || (p15 > 18)) {
\\Visiting node 510-If(r-BB@0x5de)
                            if (p15 != 19) {
\\Visiting node 511-If(r-BB@0x5fe)
                                if (p15 != 20) {
\\Visiting node 512-If(r-BB@0x61e)
                                    if (p15 != 21) {
\\Visiting node 513-If(r-BB@0x63e)
                                        if (p15 != 22) {
\\Visiting node 514-If(r-BB@0x65e)
                                            if (p15 != 10) {
\\Visiting node 515-Statement(r-BB@0x67e)
\\Starting analysis of node 515-Statement(r-BB@0x67e)
\\Successors: [522-If(r-BB@0xa)]
                                                v0_0 = this.getResources().getAssets().open(new StringBuilder(String.valueOf(this.gO[p15])).append(".img").toString());
                                                v1_273 = ((v0_0.read() & 255) | ((v0_0.read() & 255) << 8));
                                                v2_401 = new byte[v1_273];
                                                v0_0.read(v2_401);
                                                this.aM[p14] = this.b(v2_401, 0, v1_273);
\\Done, visiting first successor
\\Visiting node 522-If(r-BB@0xa)
                                                if (v0_0 == 0) {
\\Visiting node 524-Statement(r-BB@0x14)
\\Starting analysis of node 524-Statement(r-BB@0x14)
\\Successors: [525-Return(r-BB@0x1a)]
                                                    this.bn = 1;
\\Done, visiting first successor
\\Visiting node 525-Return(r-BB@0x1a)
\\Node in follow set  (self.if_follow[-1], self.switch_follow[-1],
\\                    self.loop_follow[-1], self.latch_node[-1],
\\                    self.try_follow[-1])
```
here it's done, so it goes on to do other conditions.

Then, throughout that method, the various cases and conditions, I see:
```
\\Visiting node 522-If(r-BB@0xa)
\\Node not return and has been visited
```

Here's what the end of the function looks like:
```
\\Node not return and has been visited
                break;
            default:
\\Visiting node 522-If(r-BB@0xa)
\\Node not return and has been visited
        }
\\Visiting node 525-Return(r-BB@0x1a)
        return;
    }
```
You can see that even in the default case, it knows it should jump to that if statement, but it was already visited and processed so it doesn't.

**Comment by reox** [comment]
Is it possible that this one got fixed as well with #263 ?

**Comment by cdkorzen** [comment]
I've done some more investigation and while I don't know enough of the theory, I think I've found the location of concern:

When the decompiler calls `switch_struct`, I've found that the switch node at issue (at the start of the method), ends up going into the unresolved set.  When it gets to another switch node, it ends up with two nodes in the `ldominates` list.  One is the node that should follow the switch node, the other is the return node that follows.  The function calls `max` and then sets that as the follow node for the inside switch and the unresolved switch.  Not sure what it's using `max`.

I'm going to try seeing what happens with a toy demonstration when I get a chance.

**Comment by cdkorzen** [comment]
I think I understand the issue finally.

The function I'm analyzing is a resource loader.  So the switch is "which resource", and in almost every case it opens a file, and then ends by closing the file if it's opened.  However, there are one or two cases where it instead instantiates a specialty class to handle it.

Therefore, the function control flow looks like:
```
  switch node -> case 1    -> file close block  -> return block
                      -> case 2    -> file close block  -> return block
                      -> case 3    -> file close block  -> return block
                      ...
                      -> case n                                   -> return block
```
The method just uses the same file close code for each case.  The writer, when working on the next case, thinks it's visited when it hasn't necessarily.

I don't know how to code it up in Java, goto statements would be involved.  When I copy and paste, the compiler isn't smart enough to optimize it all into one block.  Perhaps smali is required for a test case.  Or there's a pattern I'm unfamiliar with.

Thus, using the return block for the follow node IS the correct behavior.  The writer, however, will need to be modified to handle this situation so it doesn't skip showing code and lose the semantic information.
