### ISSUE TITLE
Push to pypi

### ISSUE THREAD

**Issue by matlink** [androguard/androguard#236]
Since today, `pip install androguard` fails due to `distribution` dependency which is deprecated.
I saw that you have changed it by `setuptools`. However the pypi version stills have the old `setup.py`.
Could you please push to pypi?

**Comment by subho007** [comment]
@adesnos you can push it to pypi

**Comment by reox** [comment]
I think the master is good, but maybe has some flaws. Also there are a lot of API changes which might confuse the users. 
I had to rewrite several parts of an application which used androguard completly, thus it might be good to wait until we have a stable documentation?

**Comment by eighthave** [comment]
I see there is already 3.0.1 on pypi.  It would be great to have a git tag that matches that release, a signed tag would be even better :smile:. So like `git tag -s 3.0.1 -m "tagging v3.0.1 release" 01234567`

**Comment by reox** [comment]
unfortunately the version on pypi is not our release but this fork: https://github.com/jbremer/androguard

**Comment by eighthave** [comment]
@jbremer can we get all synced up so that there is only one androguard?  There has been a ton of great work here since your fork.

I guess the next release from this repo should probably be called 4.0 or 3.1 to avoid the 3.0 confusion.

**Comment by jbremer** [comment]
Sure thing - let's bump to `3.1`? I'll give it a look soon'ish.

**Comment by eighthave** [comment]
Excellent!  My inclination would be to say 4.0 because there has been quite a bit of work recently.  In case you haven't seen it, there is now a working python3 port, and its nearing completion for a release.  But 3.1 is also fine.

**Comment by jbremer** [comment]
I haven't seen that yet, no :) I'm personally not big on bumping major versions, but provided this is not my project I'll let that decision up to you guys. FWIW, I sent @adesnos an email exactly one year ago (30/6/2016) that I can add him to the PyPI repository so that he can release updates as he sees fit - that offer is naturally still on the table.
What do you think about improving the unit tests & reporting the code coverage? Especially with a major change like Python 3 support I think there are lots of unit tests lacking (provided the last change in `tests/` was 3 months ago) :P

**Comment by reox** [comment]
Tests are always welcome ;)

I tested most of the py3 stuff by running analysis and decompilation in thousands of APKs. I then collected all exceptions.
The problem is, it takes ages..  About 2 weeks for 1k apks...

**Comment by adesnos** [comment]
@jbremer sure you can give me access and @reox too if possible !

**Comment by JohanLorenzo** [comment]
Hi guys! Thank you for putting up this library 😃 I would love to use it in https://github.com/mozilla-releng/mozapkpublisher. However, 3.0.1 doesn't have the Py3 compatibility.

@jbremer, would it be possible to release a new version?

**Comment by JohanLorenzo** [comment]
Ping @jbremer

**Comment by reox** [comment]
@jbremer can you add me on pypi? this is my profile: https://pypi.org/user/reox/

**Comment by reox** [comment]
@jbremer ping

**Comment by jbremer** [comment]
@reox Thanks. Sorry for long delay, for some reason all the previous pings came in at times where I didn't have access to my PyPI login information & forgot about it. Looking forward to seeing new versions..

**Comment by reox** [comment]
nice! thank you! I'll upload the latest version then!

**Comment by reox** [comment]
v 3.1.0rc2 is on pypi (actually it is the current master... but anyways... 3.1.0 will come soon!)
