### ISSUE TITLE
get_certificate() error

### ISSUE THREAD

**Issue by 18z** [androguard/androguard#237]
Hi @reox 

In this [commit](https://github.com/androguard/androguard/commit/460076a0050b1e02b94bd197542c24fa614d9325#diff-ccb060c0dbd91f494fe6a7957713cb00), chilkat certificate parsing was removed and was replaced by pyasn and cryptography.
However, when I try to use  get_certificate(). The following error shows.

```
Traceback (most recent call last):
  File "ag.py", line 76, in <module>
    apkinfo['cert'] = result['apk'].get_certificate(fn)
  File "/home/dean/Documents/viper/lib/python2.7/site-packages/androguard/core/bytecodes/apk.py", line 841, in get_certificate
    cert = cert[2 + (cert[1] & 0x7F) if cert[1] & 0x80 > 1 else 2:]
TypeError: unsupported operand type(s) for &: 'str' and 'int'
```

I use Python 2.7.6

Anything I missed to make this method work? : )

**Comment by reox** [comment]
You are right. In python 2 encode returns a str, and cert[1] returns a str as well. In python 3, encode returns bytes, thus cert[1] is an int.
But load_der_x509_certificate can not work with bytearrays, so I'm thinking about a clean solution here...

**Comment by reox** [comment]
I believe this is fixed now, if the error still persists then please reopen the ticket

**Comment by 18z** [comment]
@reox 

Thanks : )
