### ISSUE TITLE
How to get CFG (control flow graph) of whole android application?

### ISSUE THREAD

**Issue by zhufx** [androguard/androguard#241]
I read some paper about android static analysis , some said that they use androguard to extract CFG of whole android application.However, I can't find any method/API  about this. Can someone show me how to do this ? Thanks a lot ^_^

**Comment by zhufx** [comment]
@reox @adesnos  Please give me a hint^_^

**Comment by zerjioang** [comment]
@zhufx  you may need to take a look to **this** androguard post.

Please, check this out: https://androguard.blogspot.com.es/2011/02/android-apps-visualization.html

**Comment by zhufx** [comment]
@zerjioang I have seen this page before. But I can't find androxgmml.py after androguard 2.0. 
Then I find that APKViewer.py and androdd.py can generate the CFG of one class. It seems that there is no link between CFGs of different classes. What I want is a whole CFG of an android application which contains the link of different class' function call relationship, not separate CFG of  one method or one class.

**Comment by reox** [comment]
I'm not completly sure, as I never used androguard for CFG generation, but it might be the case that there is currently no script that can generate this, as the API changed a lot.
What you can still do is either use an old version of androguard that has the scripts or write your own script using the current API.

**Comment by ajilling** [comment]
If you install v1.9 or lower, you can just call
`python apkviewer -i <path_of_first_apk> -o <path_to_output_folder>`

Demo shown here in  part 4 http://www.technotalkative.com/part-2-deep-analysis-using-androguard-tools-2/

Since ApkViewer was either moved or deprecated in v2.0, I'm still trying to figure out how do it there. Will post here if/when I do.

**Comment by ajilling** [comment]
@zhufx I had the same issue with creation of multiple classes with CFGs. Again, it's a weird versioning issue. If you use the version in this link, it will create a single graph of the entire program in grapheml format.

[https://code.google.com/archive/p/androguard/source](https://code.google.com/archive/p/androguard/source)

**Comment by reox** [comment]
code.google.com is totally obsolete. It's better to use the versions from here https://github.com/androguard/androguard/releases
I think the 1.9 version should still have all the features, maybe you can use 2.0 as well.

**Comment by zhufx** [comment]
@ajilling  Thanks for replying.
I have used apkviewer at androguard at v2.0. It seems that apkviewer can generate the graph of function call and it can also generate the CFG of one function in graphml format.(However the instructions in CFG not display well)
![image](https://user-images.githubusercontent.com/10691415/26917690-d5f946c6-4c61-11e7-90d8-7fc6d28f05f0.png)

**Comment by waqarrashid33** [comment]
@reox A lot has been changed in the new release. Can you give me some hints on how to get the control flow graph of  whole app. I can get CFG for methods but connections between methods and classes is unclear to me.

**Comment by reox** [comment]
I think the way to go is using the xrefs:
https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/dvm.py#L3038
https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/dvm.py#L3637
