### ISSUE TITLE
How to get details of instructions?

### ISSUE THREAD

**Issue by zhufx** [androguard/androguard#243]
Recently , I use Androguard for some static analysis research and get some problems.
Eg:  I get an instruction like below.It is a function call statement. ( ClientActivity is the class that implements startDeviceSearch() method )

![image](https://user-images.githubusercontent.com/10691415/27003379-0380fe1e-4e28-11e7-9f8d-682e56044a72.png)

Androguard has convenient api get_output() to reach additional output of the instruction. The output is shown below.

![image](https://user-images.githubusercontent.com/10691415/27003410-8e0562fa-4e28-11e7-8a5a-d3f342fccafa.png)

However,I want more details about additional output. Such as the name/id of callee function like startDeviceSearch() mentioned by example , or the class name that implemented function.
So is there any way to get this? I have reviewed the source code of get_output()  function in Androguard. But I'm still confused about this.

**Comment by zhufx** [comment]
I think I have found the correct API to get details of instructions^-^

`cm = DaivilkVMFormat.get_class_manager()
 ref_kind = instruction.get_ref_kind()
 method = cm.get_method_ref(ref_kind)
 print method.get_name()   #get the method name
 print method.get_class_name()  #get the class name that implement method`

The document of androguard is too brief , some make confused . Maybe it can be a future work to  maintain a more complete document.

**Comment by reox** [comment]
nice to hear!

I agree, there are too few examples. If you like you can put this into a short demo script and create a PR?

**Comment by zhufx** [comment]
OK , I will have a try.
