### ISSUE TITLE
Python3 bug in constwidehigh16

### ISSUE THREAD

**Issue by Rafiot** [androguard/androguard#245]
I didn't investigate much, but this is what happen when calling this method in viper: https://github.com/viper-framework/viper/blob/master/viper/modules/apk.py#L142

The stack trace: https://travis-ci.org/viper-framework/viper/jobs/241524912#L833

And the APK file: https://github.com/viper-framework/viper-test-files/blob/master/test_files/hello-world.apk

**Comment by reox** [comment]
I think you just hit this bug i found some while ago in theory: #45 
I never found a sample where this happend... so it should be easier now to fix it!

**Comment by Rafiot** [comment]
Happy to help, and thanks! :)

**Comment by reox** [comment]
I tried to reproduce this issue using this program and your APK:
```
from androguard.core.bytecodes.apk import APK
from androguard.core.bytecodes.dvm import DalvikVMFormat
from androguard.core.analysis.analysis import Analysis
from androguard.decompiler.decompiler import DecompilerDAD
from androguard.decompiler.dad.decompile import DvMethod

def andro_dump(vm, vmx):
    for method in vm.get_methods():
        print(method.get_class_name(),  method.get_name())
        mx = vmx.get_method(method)
        if method.get_code() is None:
            continue
        ms = DvMethod(mx)
        ms.process()
        ms.get_source()

a = APK("hello-world.apk")
d = DalvikVMFormat(a)
dx = Analysis(d)
d.set_vmanalysis(dx)
d.set_decompiler(DecompilerDAD(d, dx))
andro_dump(d,dx)
```

But I do not get the error.

Can you tell me in which method this one fails?

Maybe this one is already fixed, as your line says:
```
>       value = unpack('=d', '\x00\x00\x00\x00\x00\x00' + pack('=h', ins.BBBB))[0]
```
and is missing the `b`: https://github.com/androguard/androguard/blob/master/androguard/decompiler/dad/opcode_ins.py#L288
which was fixed here: https://github.com/androguard/androguard/commit/161c674f052dc5e69be78a4307c4b72b418de53d

**Comment by Rafiot** [comment]
It is probably related to the cache on travis... I just deleted it and re-ran the tests, we will know in a few min.

**Comment by Rafiot** [comment]
My bad, it works... Sorry for that.
