### ISSUE TITLE
Generate new API Permission mappings

### ISSUE THREAD

**Issue by reox** [androguard/androguard#252]
We should generate the newest permission mappings.

How was this done in the past?
Can we automate it?
Is there any new, better tool we can use?

* [x] Generate new Permission Mappings
* [x] Generate System resources for AXML
* [x] Generste System Resources for references in resource files
* [x] Generate new Permission lists, check not only the Manifest of the framework but all framework tools.
* [x] what is androguard/core/bytecodes/api_permissions.py
* [x] what is androguard/core/bytecodes/dvm_permissions.py
* [x] reverse lookup? Do we need that?

**Comment by eighthave** [comment]
I'm not entirely clear what "API Permission mappings" means.  Do you mean these from _AndroidManifest.xml_?
* `<uses-permission>`
* `<uses-permission-sdk-23>`
* `<permission>`
* `<permission-group>`
* `<permission-tree>`

**Comment by reox** [comment]
No, there is a reverse mapping of API Calls to Permissions. For example https://github.com/androguard/androguard/blob/master/androguard/core/api_specific_resources/api_permission_mappings/api_permission_mappings_api22.py

As google does not provide those information, there are some crawlers to just search in the documentation and create those files. Some tools are mentioned here: https://stackoverflow.com/a/24019120/446140

Maybe we can use the mappings from here? http://axplorer.org/
The Problem with PScout is, that it is not very precise...

**Comment by reox** [comment]
related #266 

maybe we should generate the android package resources as well.

**Comment by reox** [comment]
We need also regenerate the SYSTEM ATTRIBUTES for the AXML parser.

**Comment by reox** [comment]
axplorer has now mappings up to level 25: https://github.com/reddr/axplorer

**Comment by reox** [comment]
@eighthave how would you implement this, especially when it comes to packaging: I have now used axplorer as a submodule and wrote a script to parse the files and convert them into the format that is used in androguard. those files are stored as JSON in the old folders and are loaded on demand.
should we generate the files and commit them or should this be done on install time? Of course we can also do both...

**Comment by eighthave** [comment]
Either should be easy, so whatever is easier for you:
* including them in git/source tarball
* generating them as part of the build is easy

But keep in mind all the files needed to generate them need to be either in the source tarball or an existing Debian package.

**Comment by reox** [comment]
Currently I commit the generated json files, see #417 
Otherwise we can also use the submodule - are these included in the tarballs? then the generation is not that hard.

**Comment by reox** [comment]
I'm thinking about adding platform_framework_base as a submodule as it contains all the necessary files to generate our stuff from... But this repo is huge! Any better ideas?

**Comment by eighthave** [comment]
you can download the tarball, which is about 25MB, from their git web
view.  Look for the [tgz] link at the upper-ish right.

https://android.googlesource.com/platform/frameworks/base/+/android-8.1.0_r14

For example, you can download the "android-8.1.0_r14" release tag:

https://android.googlesource.com/platform/frameworks/base/+archive/android-8.1.0_r14.tar.gz
