### ISSUE TITLE
Use third party APKs for tests?

### ISSUE THREAD

**Issue by reox** [androguard/androguard#257]
Sometimes I find issues with APKs. It would be neat to use them as a unittest, because they have some unique properties (like no App name or missing resources file).

@androguard/external-contributors: Does anybody know what the legal status is, if we use such APKs as a test and publish them in the git repo? What about malicious files?

**Comment by eighthave** [comment]
Officially, if it does not have a free software license or a license
that allows redistribution, then you cannot redistribute them.  I think
standard practice is to freely share malware files, but random real apps
would be more clearly not allowed.

There are thousands of APKs in f-droid.org, any and all of those can be
freely redistributed.

**Comment by reox** [comment]
true. I'll see if there are any "exotic" files in f-droid. The problem is that usually malware and paid apps are the source of problems :D

**Comment by reox** [comment]
f-droid would be an interesting test field, as the sources should be available.
We could build some test to see how far off the results are.
For the xml decompilation this should be easy, for real source code I doubt there is a good solution...

**Comment by adesnos** [comment]
I think you could setup a repo outside of Androguard to host these APKs, and in the test you could download on the fly these apps for testing.
