### ISSUE TITLE
Question regarding change in decompiler output between v2.0 and latest

### ISSUE THREAD

**Issue by cdkorzen** [androguard/androguard#262]
When I ran the decompiler after switching from the 2.0 tagged release to the master, the output changed fairly radically.  It's not apparent to me just why that happens.

It seems that DAD was updated to be much more literal.  Compound expressions are broken down and the version attachment to the variables is gone.  It can sometimes affect readability, like how 
in v2.0:
```
                byte[] v4_8 = ((v3_5[v1_19] & 255) | ((v3_5[(v1_19 + 1)] & 255) << 8));
```
now is
```
                    v4 = v3[v1];
                    v4 &= 255;
                    v5 = (v1 + 1);
                    v5 = v3[v5];
                    v5 &= 255;
                    v5 <<= 8;
                    v4 |= v5;
```

Any thoughts?

**Comment by reox** [comment]
The only change I noticed was regarding the decompilation of methods. There is a try/except all clause which results in not complete classes: https://github.com/androguard/androguard/blob/master/androguard/decompiler/dad/decompile.py#L264


I'm not sure where this comes from - have you tried to bisect the commits to see where this gone wrong?

**Comment by reox** [comment]
Yep, i can confirm this one:

```
class Test{

    public int aTestMethod(int z){
        int x = 23;

        x = (x - z) | 72 - (2 * x) & 0x42 + z;

        return x;
    }
}
```

Makefile:
```
all: Test.dex

%.class: %.java
	javac -source 1.7 -target 1.7 $^

%.dex: %.class
	/usr/lib/android-sdk/build-tools/debian/dx --dex --output $@ $^
```

decompile.py
```
from androguard.misc import AnalyzeDex

h, d, dx = AnalyzeDex("Test.dex")

z, = d.get_classes()

z.source()
```

decompile_old.py:
```
from androguard.misc import AnalyzeDex

d, dx = AnalyzeDex("Test.dex")

z, = d.get_classes()

z.source()
```

```
reox@helios ~/git/androguard/examples/tests (git)-[master] % python3 decompile.py
class LTest {

    Test()
    {
        return;
    }

    public int aTestMethod(int p3)
    {
        int v0 = 23;
        v0 -= p3;
        int v1 = (p3 + 66);
        v1 &= 26;
        v0 |= v1;
        return v0;
    }
}

reox@helios ~/git/androguard/examples/tests (git)-[master] % python decompile_old.py 
class LTest {

    Test()
    {
        return;
    }

    public int aTestMethod(int p3)
    {
        return ((23 - p3) | ((p3 + 66) & 26));
    }
}
```

Python3 is the current master, where python is the version from debian (2.0).

clearly something changed.

**Comment by reox** [comment]
Bisecting the commits, it seems it was introduced in 7c8e615607666fa98fbad09b5d3c7650651ce096

The problem is, that the commits afterwards do not work, as there are syntax errors and then it starts.

The first commit that produces again source code is b3ff2a0
but only the class frame is decompiled:
```
class LTest {
}
```

In 3604ecd this was resolved but the methods do not print pretty but in the new "expanded" form... 
So obiously in between of v2.0 and 3604ecd is the problem...

**Comment by reox** [comment]
Okay I found the cause at least... 
https://github.com/androguard/androguard/compare/8da45ea5e5f1ebdbd7616f8bcf3f3ad883f40db5...3604ecd#diff-d0e286b6e60779f198414dca0da566b1R18

If you remove this line it works as expected.
Looks like the builtin.zip behaves quite different... Need to investigate more ;)

**Comment by reox** [comment]
It wasn't so easy to find ;) But I think the PR should fix the problem.
I'll add a testcase too later...
