### ISSUE TITLE
Renaming fields/methods and shared strings

### ISSUE THREAD

**Issue by cdkorzen** [androguard/androguard#265]
I wanted to rename a class method's name by using the EncodedMethod object's set_name member function.  While the change would not be written back to the APK, DAD and Xrefs would see the new name.

I expected the method's name to change, the function to be in the Python namespace with that new name, and to not rename other methods.  Instead, I found the names of methods throughout the APK were changed.

I have a suspicion of what's wrong but I'm not sure how to fix it.  Basically, when you call `set_name`, it sends a message to the `ClassManager` to set the method name (set_hook_method_name), and then reload to pull in the new name.  The CM method changes the name by modifying the entry in the string table and then doing other reloads.

The issue is if you have an obfuscated APK which uses overloading and simple, single letter method names.  In that case, you could have methods throughout the APK with the method name of 'a', 'b', 'c', etc... by setting the entry in the string table and reloading,  In other words, the `MethodIdItem.name_idx` is common to multiple methods, some with possibly entirely different purposes.

**Comment by reox** [comment]
Is this one related to #253 ?
Maybe there is just more to do than just have the correct method names...

**Comment by cdkorzen** [comment]
It's possible the two are related, but I think there are a few fundamental differences.  #253 was just calling methods of objects that weren't there or renamed.

The issue here is deeper: the way I think about it, `DalvikVMFormat` is a very direct translation of the DEX file.  It retains indices to objects, such as storing string indices for function names.  When you update the name, it very literally updates the name by updating the string in the pool.

A possible solution is to add another layer -- some object that represents all the classes in the DEX, containing just Classes, Fields, and Methods.  In this layer, the index data is removed.  If a method calls another method via invoke, the Instruction object doesn't contain the index and look it up using the ClassManager, the object just contains a reference to the other method.  

Another option: since the objects cache the string they refer to, set_name could update the string in `MethodId`/`FieldId`, but leave the string pool alone.  It would break consistency, the name index might refer to string "xyz" but the name is "abc".

Does any of that make sense?  I'm bad at describing what I'm thinking in understandable fashions.
