### ISSUE TITLE
Unicode errors when trying to get DalvikVMFormat for any dex file containing unicode characters.

### ISSUE THREAD

**Issue by ranjeetDT** [androguard/androguard#268]
### Describe what you wanted to do

- When I try to get the DalvikVMFormat for any Dex file containing unicode characters. 
e.g. Try the following code on this apk [WellsFargo Tablet](https://play.google.com/store/apps/details?id=com.wf.wellsfargomobile.tablet)

self._androguard_app = apk.APK(self.get_path())
        for dex in self._androguard_app.get_all_dex():
            _vm = dvm.DalvikVMFormat(dex) <-- Exception comes here.
            self._androguard_vm_list.append(_vm) 

### Describe what you expected
Expected the Vm object to get created without errors.

### Describe what actually happened

Below is the stacktrace.
```
  _vm = dvm.DalvikVMFormat(dex)
  File "lib/androguard/core/bytecodes/dvm.py", line 7600, in __init__
    self._load(buff)
  File "lib/androguard/core/bytecodes/dvm.py", line 7611, in _load
    self.map_list = MapList(self.CM, self.__header.map_off, self)
  File "lib/androguard/core/bytecodes/dvm.py", line 7493, in __init__
    i.reload()
  File "lib/androguard/core/bytecodes/dvm.py", line 7109, in reload
    self.item.reload()
  File "lib/androguard/core/bytecodes/dvm.py", line 2564, in reload
    i.reload()
  File "lib/androguard/core/bytecodes/dvm.py", line 2427, in reload
    self.proto_idx_value = self.CM.get_proto(self.proto_idx)
  File "lib/androguard/core/bytecodes/dvm.py", line 7327, in get_proto
    return [proto.get_parameters_off_value(),
  File "lib/androguard/core/bytecodes/dvm.py", line 2147, in get_parameters_off_value
    self.parameters_off_value = '({})'.format(' '.join(params))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u02ca' in position 28: ordinal not in range(128)
```
### System Information

- Androguard Version: master
- Python Version: 2.7/3.5/...
- Operating System

### Further Log Files and Output

- please report logs, tracebacks and other useful information
- if possible report the files you tried to analyze!

I think the solution to this would be to return unicode from the method 'def get_parameters_off_value(self)' in class ProtoIdItem in file 'androguard/core/bytecodes/dvm.py' file. Below is the code snippet that fixes the issue:
```
    def get_parameters_off_value(self):
        """
            Return the string associated to the parameters_off

            :rtype: string
        """
        if self.parameters_off_value is None:
            params = self.CM.get_type_list(self.parameters_off)
            self.parameters_off_value = u'({})'.format(' '.join(params)) <-- return unicode instead of string
        return self.parameters_off_value
```

**Comment by reox** [comment]
Okay, this one is a python 2.x error only. I'll take a look at it!

**Comment by cy-bai** [comment]
I also got stuck in this problem, have you solved that? Please help me!

**Comment by reox** [comment]
Can you test if this probloem still occours in the latest master? I changed the MUTF-8 parser, maybe that helpend...
If not, I would be happy about failing samples!
