### ISSUE TITLE
create_tags

### ISSUE THREAD

**Issue by jimmy-sonny** [androguard/androguard#269]
The "create_tags" method in "androguard/androguard/core/analysis/analysis.py" has been removed from the last release 2.0. Hence, the method get_tags of MethodAnalysis raises an Exception if called.

In order to test it, execute tags.py in androguard/demos/

**Comment by reox** [comment]
I would take all demos with a grain of salt. There is a lot of stuff that was changed or removed, maybe because it was not reliable enough? 
I'm not sure why create_tags was removed, maybe because it depended on the tainted analysis?

**Comment by the-house** [comment]
@jimmy-sonny I am looking at printing out the tags for methods but have run into the same issue you have.  Have you found a workaround?

**Comment by reox** [comment]
Oh I see: create_tags depends on tainted analysis, which was removed: https://github.com/androguard/androguard/commit/0cf5b8fe8c590280a5c589b26596d787d9f1fd3b#diff-d79598dab3d19b4148ec99584144b7a5L541
I think tainted depends heavily on the API Permission Mappings, which are not reliable. @adesnos had the plan to rewrite tainted (see #221 )

**Comment by reox** [comment]
I think there are no more tags anywhere, so i'll close this issue. If you like tags back, please open a new issue.
