### ISSUE TITLE
Error handling in AnalyzeAPK

### ISSUE THREAD

**Issue by cdkorzen** [androguard/androguard#270]
When I had an error like the one described in #172 and fixed by #259, AnalyzeAPK returned None instead of a tuple.  I called it like `a,d,dx = AnalyzeAPK` and when it failed, got an error that NoneType wasn't iterable.

Should the way the loading handles errors be different?  For example, if AnalyzeAPK fails, should it return `None, None, None` instead of None, so that it doesn't cause an exception on the assignment?  

Another option is an exception be generated right where the failure happened.  That way, instead of getting an error about None not being iterable, you get an exception that it tried to load something that wasn't judged to be an APK, or other errors that could go wrong during that processing.

**Comment by reox** [comment]
I think raising an exception is the way to go. I'm usually against guarding too much (see also #232 for example).

**Comment by reox** [comment]
this one should be resolved, it will return None, None, None or raise some exception
