### ISSUE TITLE
Change xml.dom.minidom.Document to xml.etree.ElementTree for AndroidManifest.xml?

### ISSUE THREAD

**Issue by reox** [androguard/androguard#273]
What are the pro's and con's of switching the XML parser to xml.etree.ElementTree?

I would like to have a faster access to the xml file for example with xpath. Maybe we should even go to lxml?

But it is quite easy to transform it by your own:
```
from lxml import etree
e = etree.fromstring(a.get_android_manifest_xml().toxml())
```

**Comment by subho007** [comment]
@reox I have been using lxml on our fork of androguard - https://github.com/appknox/androguard/commit/c98ca6df61497867bc82da008cfec59aa0f7f46c

lxml is very performant and a better parser. You can see the comparison here: https://stackoverflow.com/a/8342620/122840

**Comment by reox** [comment]
nice! I'll try to cherry pick this commit then.
