### ISSUE TITLE
Crash when decompiling (file attached)

### ISSUE THREAD

**Issue by Rafiot** [androguard/androguard#277]
Probable regression found during the tests with viper: https://travis-ci.org/viper-framework/viper/jobs/251812309#L1195 (I re-ran the tests after removing the cache and using the HEAD of androguard)

The related file is available here: https://github.com/viper-framework/viper-test-files/blob/master/test_files/hello-world.apk?raw=true

**Comment by reox** [comment]
I tried to replicate the bug with this script:
```
from androguard.misc import AnalyzeAPK
a,d,dx = AnalyzeAPK(r"D:\Downloads\hello-world.apk")
print(a, d, dx)

for c in d.get_classes():
    print(c.get_source())
```

But it seems to work? Can you test with the latest master or create a short script how I can replicte the bug?

**Comment by Rafiot** [comment]
It is still failing, even after deleting the caches: https://travis-ci.org/viper-framework/viper/builds/270385120

I don't have much time today to investigate but I'll have a look later.

**Comment by reox** [comment]
Nevermind, I looked at your code and found at least the issue:
```
from androguard.misc import AnalyzeAPK
from androguard.decompiler.dad.decompile import DvMethod
a,d,dx = AnalyzeAPK(r"D:\Downloads\hello-world.apk")
print(a, d, dx)
c = d.get_class("Landroid/support/annotation/RestrictTo$Scope;")

for m in c.get_methods():
    if m.get_name() == "valueOf":
        met = m
    if m.get_name() == "values":
        met2 = m

mx = dx.get_method(met2)
ms = DvMethod(mx)
ms.process()

mx = dx.get_method(met)
ms = DvMethod(mx)
ms.process()
```

In decompiler.dad.dataflow group_variables, the thing fails because the list contains int and str:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.4\helpers\pydev\pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.4\helpers\pydev\pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/bachmann.s/PycharmProjects/androguard/buggyapks.py", line 27, in <module>
    ms.process()
  File "C:/Users/bachmann.s/PycharmProjects/androguard\androguard\decompiler\dad\decompile.py", line 147, in process
    split_variables(graph, self.var_to_name, def_uses, use_defs)
  File "C:/Users/bachmann.s/PycharmProjects/androguard\androguard\decompiler\dad\dataflow.py", line 359, in split_variables
    variables = group_variables(lvars, DU, UD)
  File "C:/Users/bachmann.s/PycharmProjects/androguard\androguard\decompiler\dad\dataflow.py", line 331, in group_variables
    for var, loc in sorted(DU):
TypeError: '<' not supported between instances of 'str' and 'int'
```

The list looks like this:
```
x = defaultdict(list, {(0, 0): [1], ('tmp1', 1): [2], (0, 2): [3], (0, 3): [4]})
```
and you can workaround by setting a custom sorter and cast everything to str:
```
sorted(x, key=lambda x: (str(x), str(x)))
```

When using `c.get_source()`, the exception is masked by the Exception handler in DvClass.process - see also #232 

I need to investigate what is expected here and what the `tmp1` variable does... 
@Lircyn is it correct that the list should be sorted like this:
```
defaultdict(list, {(0, 0): [1], ('tmp1', 1): [2], (0, 2): [3], (0, 3): [4]}) --> [('tmp1', 1), (0, 0), (0, 2), (0, 3)]
```

**Comment by reox** [comment]
Okay, there is more. When applying the sorting it fixes it for countless methods, but then a new error appears, which was probably masked by the sort error:
```
Traceback (most recent call last):
  File "C:/Users/bachmann.s/PycharmProjects/androguard/buggyapks.py", line 25, in <module>
    ms.process()
  File "C:\Users\bachmann.s\PycharmProjects\androguard\androguard\decompiler\dad\decompile.py", line 151, in process
    place_declarations(graph, self.var_to_name, def_uses, use_defs)
  File "C:\Users\bachmann.s\PycharmProjects\androguard\androguard\decompiler\dad\dataflow.py", line 466, in place_declarations
    if (not isinstance(dvars[var], Variable) or
KeyError: 'tmp2'
```

**Comment by reox** [comment]
I guessed now a lot and this commit seems to fix it:
https://github.com/reox/androguard/commit/6a913f05833a49bf681b481cfab0d7ef388e5116

I can decompile the APK now without any problems.

I also removed the exception handler in DvClass.

@Lircyn do you have by chance some time to review it?

**Comment by reox** [comment]
@Rafiot can you check against the latest master? I believe this one is fixed now.

**Comment by Rafiot** [comment]
Looks good: It works fine in python3.4 to 3.6.

But fails with python2.7: https://travis-ci.org/viper-framework/viper/jobs/270385121#L1277

**Comment by reox** [comment]
thanks for testing! Seems like in python2.7 it is not a str... anyways - i fixed it now and also added this as a testcase. It looks good: https://travis-ci.org/androguard/androguard/builds/273253145
And we have now 2100 more testcases :D

**Comment by reox** [comment]
I merged it into master btw. You might want to test it again on your side.

**Comment by Rafiot** [comment]
Nice! I love test cases :) 

It works on my end, thank you very much for the fixes.
