### ISSUE TITLE
AnalyzeAPK() for some APKs give a variety of xml.parsers.expat.ExpatError: errors

### ISSUE THREAD

**Issue by wdormann** [androguard/androguard#281]
### Describe what you wanted to do

When parsing https://play.google.com/store/apps/details?id=com.shopgate.android.app13182 with Androguard's androlyze.py, I get: xml.parsers.expat.ExpatError: unbound prefix: line 108, column 0

Other apps have similar errors in expat, but it's not clear if the underlying cause is the same.  The whole set of unique expat errors I've seen is:
$ grep ExpatError invalid.err | sort | uniq
xml.parsers.expat.ExpatError: duplicate attribute: line 101, column 0
xml.parsers.expat.ExpatError: duplicate attribute: line 110, column 0
xml.parsers.expat.ExpatError: duplicate attribute: line 121, column 0
xml.parsers.expat.ExpatError: duplicate attribute: line 164, column 0
xml.parsers.expat.ExpatError: duplicate attribute: line 81, column 0
xml.parsers.expat.ExpatError: duplicate attribute: line 98, column 0
xml.parsers.expat.ExpatError: must not undeclare prefix: line 2, column 0
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 154, column 0
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 205, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 338, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 349, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 397, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 509, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 569, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 57, column 0
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 5, column 24
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 602, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 611, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 614, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 629, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 642, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 670, column 6
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 704, column 6
xml.parsers.expat.ExpatError: unbound prefix: line 101, column 0
xml.parsers.expat.ExpatError: unbound prefix: line 104, column 0
xml.parsers.expat.ExpatError: unbound prefix: line 108, column 0
xml.parsers.expat.ExpatError: unbound prefix: line 151, column 0
xml.parsers.expat.ExpatError: unbound prefix: line 178, column 0
xml.parsers.expat.ExpatError: unbound prefix: line 199, column 0
xml.parsers.expat.ExpatError: unbound prefix: line 2183, column 0
xml.parsers.expat.ExpatError: unbound prefix: line 246, column 0
xml.parsers.expat.ExpatError: unbound prefix: line 299, column 0
xml.parsers.expat.ExpatError: unbound prefix: line 681, column 0

### Describe what you expected

Parse w/o error

### Describe what actually happened

In [4]: a,d,dx = AnalyzeAPK('com.shopgate.android.app13182.apk')
WARNING: AXML parsing failed: unbound prefix: line 108, column 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/androguard/core/bytecodes/apk.py", line 203, in __init__
    self.xml[i] = minidom.parseString(self.axml[i].get_buff())
  File "/usr/lib/python3.5/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: unbound prefix: line 108, column 0

### System Information

Androguard Version: master
Python Version: 3.5.2
Operating System: Ubuntu 16.04

### Further Log Files and Output

If this warrants a separate bug for each expat error type, let me know.  But possibly fixing one may fix others?

**Comment by reox** [comment]
It seems like they are using some kind of packer for the manifest file, so the decompilation fails...
Such problem are really a PIA because packer vendors will always find some way to disturb automated processes such as androguard.

Just out of curiosity: have you tried to use a different xml parser? Maybe it will still work with other parsers than minidom. Minidom is fine, but sometimes quite limited.

**Comment by wdormann** [comment]
Attached is the manifest file from com.shopgate.android.app13182, which has been extracted using apktool.   Both etree and minidom handle it fine, and it doesn't seem to be malformed in any way.  However, this is *after* it's been parsed with apktool, so perhaps that's because it's after apktool fixes it up in some way?

[AndroidManifest.xml.txt](https://github.com/androguard/androguard/files/1190577/AndroidManifest.xml.txt)

**Comment by reox** [comment]
So I took a look at some of my files with this error. It seems they do not start with the usual AXML Header of `0x00080003` but with `0x00080503`. So they already fail in line 1225 of the AXMLParser.
I'm not sure why it is a separate header but this fixes it:
```
diff --git a/androguard/core/bytecodes/apk.py b/androguard/core/bytecodes/apk.py
index 1d4d780..458a76a 100644
--- a/androguard/core/bytecodes/apk.py
+++ b/androguard/core/bytecodes/apk.py
@@ -1222,7 +1222,7 @@ class AXMLParser(object):

         axml_file = unpack('<L', self.buff.read(4))[0]

-        if axml_file == CHUNK_AXML_FILE:
+        if axml_file == CHUNK_AXML_FILE or axml_file == 0x00080503:
             self.buff.read(4)

             header = ARSCHeader(self.buff)
```

Who has more knowledge of the AXML format and might answer the question with the different headers?

**Comment by wdormann** [comment]
It looks to still error in the same way after the above modification:

WARNING: AXML parsing failed: unbound prefix: line 108, column 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/androguard/core/bytecodes/apk.py", line 203, in __init__
    self.xml[i] = minidom.parseString(self.axml[i].get_buff())
  File "/usr/lib/python3.5/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: unbound prefix: line 108, column 0

Are you sure this is the right fix?  With the above patch, com.shopgate.android.app13182.apk fails in the same way that it did before.

**Comment by wdormann** [comment]
Actually, **all** of the APKs that I currently have that fail to be processed by androguard have axml_file = 0x80003, which is the expected CHUNK_AXML_FILE value.  I'm not sure why you'd be seeing 0x00080503 in any APK file.  But if you are, I suppose that'd be a different problem than I'm seeing.

**Comment by reox** [comment]
oh okay. so I have yet another error... I'll try to debug this.

**Comment by reox** [comment]
For this shopgate app, I get a more desciptive error message when using lxml:
```
In [22]: etree.fromstring(y)
  File "<string>", line 116
XMLSyntaxError: Namespace prefix ns for theme on application is not defined, line 116, column 1
```

in the xml, it looks like this:
```
<application                                                                                                                      
ns:theme="@7F0A0143"                                                                                                              
ns:label="Babyshop UK"                                                                                                            
ns:icon="@7F020076"                                                                                                               
ns:name="com.shopgate.android.app.SGApplication"                                                                                  
ns:debuggable="false"                                                                                                             
ns:allowBackup="false"                                                                                                            
ns:hardwareAccelerated="true"                                                                                                     
>   
```
And below that, there are more ns:, instead of android:

When I look at the AXML file itself using 010 editor, the namspace seems to be fine - so I do not really know where this one comes from...

**Comment by reox** [comment]
Actually it doesn't look to bad. The problem was, that namespaces where not acknowledged if the uri was already parsed. I changed that behaviour.
In the case of this APK, the xmlns:ns part is now directly in the application tag. Looks like the XML Parser is happy then.

@wdormann Can you check if the changes in https://github.com/reox/androguard/tree/fix-axml-missing-ns work for you?

**Comment by wdormann** [comment]
As with issue 280, nothing seems to be fixed here.   Do you want a copy of an offending APK?
