### ISSUE TITLE
AnalyzeAPK: xml.parsers.expat.ExpatError: not well-formed (invalid token):

### ISSUE THREAD

**Issue by wdormann** [androguard/androguard#294]
Some APKs fail to be parsed with AnalyzeAPK

### Describe what you wanted to do

I've seen this error with 46 APKs.   An example:

a,d,dx = AnalyzeAPK('com.tslstudio.tsladsudoku.apk');

https://drive.google.com/open?id=0BzrbzLF_CbEYYkJ4UUlDVThNQk0

### Describe what you expected

Parse OK, as it's currently in the Google Play store.

### Describe what actually happened

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/androguard-3.1.0.dev0-py3.5.egg/androguard/core/bytecodes/apk.py", line 158, in _apk_analysis
    self.xml[i] = minidom.parseString(raw_xml)
  File "/usr/lib/python3.5/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 57, column 0

### System Information

- Androguard Version: master
- Python Version: 3.5.2
- Operating System: Ubuntu 16.04

**Comment by reox** [comment]
This is clearly some obfuscated manifest. In 010 editor, the template seems to work fine, but with androguard it is just a mess.
This is also the first Manifest which uses TEXT tags...

**Comment by reox** [comment]
Does anyone has more information on this thing?
It seems they use TEXT chunks to code some of the information.
When using `aapt d xmltree com.tslstudio.tsladsudoku.apk AndroidManifest.xml`, there is this part:
```
E: span (line=21)
  A: class="tag" (Raw: "tag")
  C: "\n<uses-permission\n"
E: span (line=24)
  A: class="atn" (Raw: "atn")
  C: "\nandroid:name\n"
E: span (line=27)
  A: class="pun" (Raw: "pun")
  C: "\n=\n"
E: span (line=30)
  A: class="atv" (Raw: "atv")
  C: "\n\"com.android.vending.BILLING\"\n"
E: span (line=33)
  A: class="tag" (Raw: "tag")
  C: "\n/>\n"
```

It seems like they injected the permission in there...
This get's translated into:
````
<span
class="tag"
>

<uses-permission

</span>
<span
class="atn"
>

android:name

</span>
<span
class="pun"
>

=

</span>
<span
class="atv"
>

"com.android.vending.BILLING"

</span>
<span
class="tag"
>

/>

</span>
```

So they code the permission with the span tags?!

I added the _escape method to the text, which seems to work, as aapt does not recognize the billing permission:
```
package: com.tslstudio.tsladsudoku
uses-permission: android.permission.INTERNET
uses-permission: android.permission.ACCESS_NETWORK_STATE
uses-permission: android.permission.READ_PHONE_STATE
uses-permission: android.permission.RECEIVE_BOOT_COMPLETED
uses-permission: android.permission.ACCESS_WIFI_STATE
uses-permission: android.permission.ACCESS_FINE_LOCATION
uses-permission: android.permission.ACCESS_COARSE_LOCATION
uses-permission: android.permission.KILL_BACKGROUND_PROCESSES
uses-permission: com.google.android.providers.gsf.permission.READ_GSERVICES
```

**Comment by reox** [comment]
@wdormann can you check the PR #296 if it works for all the APKs?

**Comment by wdormann** [comment]
I had 80 failing APKs, and now it's down to 65.   Would it make sense to file new tickets for remaining issues (most, but not all still "not well-formed (invalid token)")

**Comment by reox** [comment]
Can you send me all of them? The error might be the same, but the cause might be different.

**Comment by wdormann** [comment]
The entire set of APKs is 1.7GB.  How would you like them?

**Comment by reox** [comment]
It should be sufficiant to extract the AndroidManifest.xml files and just upload them.

**Comment by wdormann** [comment]
Ah, well that makes a lot more sense!   Here they are.

[bad_manifests.tgz.zip](https://github.com/androguard/androguard/files/1282194/bad_manifests.tgz.zip)

**Comment by reox** [comment]
Thanks! I'll have a look at them.

**Comment by reox** [comment]
Some of the AndroidManifest.xml are packed with Liapp. It looks like, I'm not able to format them in such a way that they are readable by an XML parser... I add a flag to indicate that the Manifest was packed.

**Comment by reox** [comment]
I got most of the errors fixed. 18 files are packed with Liapp, thus the XML parser is not happy... If you want to take a look, you can still use `axml.get_buff()` to see the "raw" xml.

In added a function on the AXMLPrinter called `is_packed()` which returns True if I believe that the AXML file is packed and we will have troubles reading it.

Can you test PR #303 on your files please? If you have more failing AXML files, please keep them coming!

**Comment by wdormann** [comment]
The only remaining failures here are 18, so I assume they are the same liapp-packed apps.  I can still extract the AndroidManifest.xml file using apktool, though.   Is it perhaps possible to use whatever technique that apktool is using?

Here's the AndroidManifest.xml file from the first failing APK in my list: com.nextgenreality.wrk:
[AndroidManifest.xml.txt](https://github.com/androguard/androguard/files/1285677/AndroidManifest.xml.txt)

**Comment by reox** [comment]
You will get a similar output when using something like this:
```
from androguard.core.bytecodes.axml import AXMLPrinter
with open(filename, "rb") as fd:
    a = AXMLPrinter(fd.read())
    print(a.get_buff().decode("UTF-8"))

# try to load with an XML Parser:
from lxml import etree
# this one will fail:
etree.fromstring(a.get_buff())
```
(btw the androguard output is even more correct, as it acknowledges the namespace prefixes before the liapp crypted attributes)

The only problem is the empty namespace, which is added by Liapp:
```
xmlns:Liapp_Empty_00=""
```

This can not be parsed by an XML parser like xml.minidom or lxml.
Even if you set it to some value, you will have no chance parsing the file because the Manifest file is also crypted in such a way, that you can not read the entries:
```
 <application f3RNY="@style/Theme.AppCompat.Light" CRyfs="@string/app_name" BH2l8="@drawable/app_icon" nGvIZ="com.lockincomp.liapp.LiappCommon" 2SKNT="false">
```

I talked to a colleage and he said that the liapp packer will probably load the manifest, decrypt it and then run the main application.

In this case you would need to crack liapp first to decode the AXML file :/ From my current point of view, this is all I can do :(

**Comment by wdormann** [comment]
Ah, so here's where my workflow is failing.  I have a script that accomplishes something like what androapkinfo.py used to do

```
from androguard.core.bytecodes import apk
a = apk.APK(apkpath)
if a.is_valid_APK():
    get_apk_info(a, apkfile)
```

where get_apk_info simply retrieves several properties from the APK object, including:

- files
- declared_permissions
- requested_permissions
- main_activity
- activities
- providers
- certificate

I'm currently unable to get any of these details for liapp-protected applications, as androguard isn't reporting that the APK is valid.  However, getting the files and certificate doesn't require a valid Manifest.  So I can easily just proceed with extracting that info from the APK object, avoiding the manifest-based properties in the case of a liapp-protected application.

My main question at this point is how such "invalid" applications can get into the Play store in the first place.  Apparently they're valid enough for Google?  And Google can understand the properties of the application?

I suppose after looking at the manifest produced by apktool, my suggestion at this point is that perhaps:

1.  APK.is_valid_APK() should probably return True for liapp-protected apps.  After all, the apps in question are valid and approved by Google.
2.  If you look at the XML file produced by apktool, you'll see that some properties like "uses-permission", "uses-feature", intent filter / receiver, etc. are unobfuscated.  So even if some parts are obfuscated, and perhaps even if the XML file as a whole isn't valid, I wonder if there is some subset of data that can be extracted about the app.   Which is better than nothing.

**Comment by reox** [comment]
> My main question at this point is how such "invalid" applications can get into the Play store in the first place. Apparently they're valid enough for Google? And Google can understand the properties of the application?
this is actually a good question. Most of the current packers produce APKs that are valid for Google Play but fail on analysis. 
I think for Google Play only those information are required: Package Name and permissions. (But I dont know for sure, I never uploaded something to the Play store)

It is true, we could potentially parse those information from the Manifest, but not with the current setup.
This would lead to bigger refactoring, also see #273, as we would need to use some other xml parser.

> APK.is_valid_APK() should probably return True for liapp-protected apps. After all, the apps in question are valid and approved by Google.

As I did not developed all those stuff, I'm not sure what the intention was for this function.
Recently, i added another check for APK's, to run testzip on the ZIP file. If the file is readable without errors, it is also somehow valid.
I agree with you that we probably should change that behaviour.

> If you look at the XML file produced by apktool, you'll see that some properties like "uses-permission", "uses-feature", intent filter / receiver, etc. are unobfuscated. So even if some parts are obfuscated, and perhaps even if the XML file as a whole isn't valid, I wonder if there is some subset of data that can be extracted about the app. Which is better than nothing.

This is a good idea. But this needs some major refactoring.

**Comment by reox** [comment]
I opened up a new issue: #306 

If you have any more failing Manifests, please hand them in!

**Comment by wdormann** [comment]
Aside from the liapp stuff, the only two remaining APKs I can't get info for (so far) are due to corrupt zip files.   But they're apparently good enough to be accepted into the Google Play store:

```
Traceback (most recent call last):
  File "androapkinfo.py", line 203, in main
    display_dvm_info(a, apkfile)
  File "androapkinfo.py", line 97, in display_dvm_info
    apkinfo['files'] = tuple(i for i in apk.get_files_information())
  File "androapkinfo.py", line 97, in <genexpr>
    apkinfo['files'] = tuple(i for i in apk.get_files_information())
  File "/usr/local/lib/python3.5/dist-packages/androguard-3.1.0-py3.5.egg/androguard/core/bytecodes/apk.py", line 458, in get_files_information
    yield k, self.get_files_types()[k], self.get_files_crc32()[k]
  File "/usr/local/lib/python3.5/dist-packages/androguard-3.1.0-py3.5.egg/androguard/core/bytecodes/apk.py", line 422, in get_files_types
    buffer = self.zip.read(i)
  File "/usr/lib/python3.5/zipfile.py", line 1233, in read
    return fp.read()
  File "/usr/lib/python3.5/zipfile.py", line 830, in read
    buf += self._read1(self.MAX_N)
  File "/usr/lib/python3.5/zipfile.py", line 920, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid code lengths set
Getting apkinfo for by_sha256/3c/2b/9f/3c2b9f52bc86c9bc56510c797ea052aac01ea9b586c6ab9ce0e05a1829a4ebba/com.greenboat.appbook.okcauseyoulovedTabFree.apk
by_sha256/3c/2b/9f/3c2b9f52bc86c9bc56510c797ea052aac01ea9b586c6ab9ce0e05a1829a4ebba/com.greenboat.appbook.okcauseyoulovedTabFree.apk - ERROR Error -3 while decompressing data: invalid code lengths set
Traceback (most recent call last):
  File "androapkinfo.py", line 203, in main
    display_dvm_info(a, apkfile)
  File "androapkinfo.py", line 97, in display_dvm_info
    apkinfo['files'] = tuple(i for i in apk.get_files_information())
  File "androapkinfo.py", line 97, in <genexpr>
    apkinfo['files'] = tuple(i for i in apk.get_files_information())
  File "/usr/local/lib/python3.5/dist-packages/androguard-3.1.0-py3.5.egg/androguard/core/bytecodes/apk.py", line 458, in get_files_information
    yield k, self.get_files_types()[k], self.get_files_crc32()[k]
  File "/usr/local/lib/python3.5/dist-packages/androguard-3.1.0-py3.5.egg/androguard/core/bytecodes/apk.py", line 422, in get_files_types
    buffer = self.zip.read(i)
  File "/usr/lib/python3.5/zipfile.py", line 1232, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib/python3.5/zipfile.py", line 1289, in open
    % (zinfo.orig_filename, fname))
zipfile.BadZipFile: File name in directory 'res/layout-v17/activity_cache_clean.xml' and header b'res/layo?S\xc0l{d\xfa\x85\x02\xf2\x94g\xe7\x00\xa9\x16cache_clean.xml' differ.
Getting apkinfo for by_sha256/dc/43/89/dc4389e419bfae5fc54e6ef96829b50b846aec2289b0de1fc43b726c2e13dd8f/com.memorycleaner.junkcleaner.supercleaner.spacecleaner.apk
by_sha256/dc/43/89/dc4389e419bfae5fc54e6ef96829b50b846aec2289b0de1fc43b726c2e13dd8f/com.memorycleaner.junkcleaner.supercleaner.spacecleaner.apk - ERROR File name in directory 'res/layout-v17/activity_cache_clean.xml' and header b'res/layo?S\xc0l{d\xfa\x85\x02\xf2\x94g\xe7\x00\xa9\x16cache_clean.xml' differ.
```

**Comment by reox** [comment]
wow, I never saw such things - alltough I have a huge collection of really broken files... I always thought they were corrupted during transfer or something but not that they are actually on GP. Can you install them on a real android device?

**Comment by wdormann** [comment]
Actually, now that I look, neither of the above apps can be installed directly from GP onto a phone.  The former gives:
Error code: 960

And the latter gives:
Error code: -504
