### ISSUE TITLE
typo "anguage" instead of "language"

### ISSUE THREAD

**Issue by waqarrashid33** [androguard/androguard#312]
https://github.com/androguard/androguard/blob/a13c156d07454234fdfb431cf9e57878ed6a4bee/androguard/core/bytecodes/axml.py#L928

**Comment by reox** [comment]
thanks for reporting! I fixed that now. We should really do more testing for such things...

**Comment by waqarrashid33** [comment]
I am using for feature extraction from malware samples, I am new to it so its a bit unlikely that I would be of much help but I will gladly report anything I find.

**Comment by reox** [comment]
please do so! If you find files that does not work with androguard, please report them.

**Comment by waqarrashid33** [comment]
I did came across a multiple apk files with which androguard is throwing warnings, but I am not sure whether it is because of androguard or because of  corrupt or invalid files.
[7f1b7ae2859bad220941924e2adea612.zip](https://github.com/androguard/androguard/files/1296322/7f1b7ae2859bad220941924e2adea612.zip)

To produce the error, remove the zip extension(just changed it for uploading):
`apk = APK("7f1b7ae2859bad220941924e2adea612")`

`Dvmformat = DalvikVMFormat(apk.get_dex())`

The message is:
`WARNING: unknown string item @ 0x2546(56)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/androguard-3.1.0-py2.7.egg/androguard/core/bytecodes/dvm.py", line 7285, in get_string
    return self.__strings_off[off].get()
KeyError: 9542
`

**Comment by waqarrashid33** [comment]
One more file giving warning:
[e682404e81fcf4a8463ca323e76d2a76.zip](https://github.com/androguard/androguard/files/1296356/e682404e81fcf4a8463ca323e76d2a76.zip)
`apk= APK("e682404e81fcf4a8463ca323e76d2a76")`

The warning message is:
`WARNING: Styles Offset given, but styleCount is zero.
Traceback (most recent call last):
  File "/usr/lib/python2.7/idlelib/run.py", line 111, in main
    seq, request = rpc.request_queue.get(block=True, timeout=0.05)
  File "/usr/lib/python2.7/Queue.py", line 176, in get
    raise Empty
Empty`

**Comment by waqarrashid33** [comment]
@reox Do you know any good resource or book for Android reversing?
I had done some work in reversing but not in android and my java is not that good. Which things do you suggest that I should learn first that can help me start quickly in this area. I am so far impressed by androguard but my understanding is not to the level that I can contribute enough.

**Comment by reox** [comment]
can you create new issues for each report please?

for books: there is 
* Android Hacker's Handbook
* Android Security Internals: An In-Depth Guide to Android's Security Architecture
* The Mobile Application Hacker's Handbook
and probably more
