### ISSUE TITLE
APK signing/validation in pure python

### ISSUE THREAD

**Issue by reox** [androguard/androguard#313]
It would be nice to be able to validate signatures of APKs using pure python code.

We would need to create the MANIFEST.MF file and check against the signature.

Then we could return all items that are not signed but in the APK or all items that are signed but create a wrong signature (e.g. wrong hash).

**Comment by subho007** [comment]
Ref: https://github.com/androguard/androguard/issues/332#issuecomment-334009259

**Comment by eighthave** [comment]
F-Droid would also love this feature, we're tracking it here: https://gitlab.com/fdroid/fdroidserver/issues/94

These two libraries also look promising:

* https://pypi.python.org/pypi/javatools
* https://pypi.python.org/pypi/javalang

**Comment by eighthave** [comment]
Also https://penguindreams.org/blog/signature-verification-between-java-and-python/

**Comment by reox** [comment]
@shuxin maybe we can integrate your https://github.com/shuxin/apk-signature-verify into androguard?

**Comment by reox** [comment]
Yes sure, i meant integrating by the means of using it as a module!

**Comment by shuxin** [comment]
Yeah, If you like it, I'll port it to python3, and rewrite it with api friendly.

- support rsa(md5/sha1/sha256/sha512)/dsa(sha1/shasha256/sha512)/ecdsa(sha256/sha512),
- without build,
- without openssl/cryptography/M2Crypto,
- without any binary like so/pyd/dll/dylib,

**Comment by eighthave** [comment]
That would be amazing!  _fdroid_ would use it.    In case you haven't seen it already, there is a nice collection of APKs for testing signature verification.  Its part of the source repo for _apksigner_:

https://android.googlesource.com/platform/tools/apksig/+/refs/heads/master/src/test/resources/com/android/apksig

**Comment by shuxin** [comment]
Thanks for the testing information. try my new version. https://github.com/shuxin/apk-signature-verify
