### ISSUE TITLE
TAG_ANDROID method printing?

### ISSUE THREAD

**Issue by the-house** [androguard/androguard#320]
How can I print the TAG_ANDROID for a method given that analysis.VMAnalysis() is no longer present?

Thank you.

**Comment by reox** [comment]
analysis.VMAnalysis was renamed to analysis.Analysis.

hth!

**Comment by the-house** [comment]
Thank you for the quick reply!  

I am still not seeing a way to get the tags as the analysis.Analysis object does not have get_methods() only get_method() which cannot call get_tags().  Thoughts?

**Comment by reox** [comment]
I think I never used this feature in the old versions. Can you give me an example how it used to work and what the output was?

**Comment by reox** [comment]
duplicate of #269, please put your information there.
