### ISSUE TITLE
stylecount zero warning when I try to open attached file 

### ISSUE THREAD

**Issue by waqarrashid33** [androguard/androguard#322]
One more file giving warning:
[e682404e81fcf4a8463ca323e76d2a76.zip](https://github.com/androguard/androguard/files/1296356/e682404e81fcf4a8463ca323e76d2a76.zip)
`apk= APK("e682404e81fcf4a8463ca323e76d2a76")`

The warning message is:
`WARNING: Styles Offset given, but styleCount is zero.
Traceback (most recent call last):
  File "/usr/lib/python2.7/idlelib/run.py", line 111, in main
    seq, request = rpc.request_queue.get(block=True, timeout=0.05)
  File "/usr/lib/python2.7/Queue.py", line 176, in get
    raise Empty
Empty`

**Comment by reox** [comment]
The warning is just from the AXML parser. It looks like a packed Manifest file.

But the error is not from androguard itself. It looks like it is from a tool you are using?
I can process the APK just fine, e.g. in androlyze.py -s:
```
In [20]: a, d, dx = AnalyzeAPK("e682404e81fcf4a8463ca323e76d2a76.zip")
WARNING: Styles Offset given, but styleCount is zero.

In [21]: a
Out[21]: <androguard.core.bytecodes.apk.APK at 0xbb312b0>

In [22]: d
Out[22]: <androguard.core.bytecodes.dvm.DalvikVMFormat at 0xbb31080>

In [23]: dx
Out[23]: <androguard.core.analysis.analysis.Analysis at 0xcea3080>

In [24]: a.is_valid_APK
Out[24]: <bound method APK.is_valid_APK of <androguard.core.bytecodes.apk.APK object at 0x000000000BB312B0>>

In [25]: a.is_valid_APK()
Out[25]: True

In [26]: a.get_android_manifest_xml()
Out[26]: <xml.dom.minidom.Document at 0xd8d02e8>
```
