### ISSUE TITLE
DexViewer.export_to_gml() broken, no dotbuff() in DalvikVMFormat

### ISSUE THREAD

**Issue by waqarrashid33** [androguard/androguard#324]
In attempting to get gml file, the function gives the following error:
`  File "/usr/local/lib/python2.7/dist-packages/androguard-3.1.0-py2.7.egg/androguard/core/data/data.py", line 149, in export_to_gml
    buff_nodes += self.add_node(i, id_i)
  File "/usr/local/lib/python2.7/dist-packages/androguard-3.1.0-py2.7.egg/androguard/core/data/data.py", line 73, in add_node
    c_label = "%x %s\n" % (idx, self.vm.dotbuff(ins, idx))
AttributeError: 'DalvikVMFormat' object has no attribute 'dotbuff'
`

The code to produce this error is:
```
apk = APK("file.apk")
vm = DalvikVMFormat(apk.get_dex()) 
vmx = Analysis(vm)

dexviewer = DexViewer(vm,vmx,vmx) # What is this third parameter? seems unused in DexViewer
gml = dexviewer.export_to_gml()

```

**Comment by reox** [comment]
looks like another occurrence of #234

**Comment by reox** [comment]
I think I'll remove this module... It creates the gml in a very complicated way instead of using the export methods of networkx. Also the GVMAnalysis is gone...
And I have no clue what those things do :/ But creating CG and CFGs is now possibloe with other tools.
