### ISSUE TITLE
Why some of instruction formats are not implemented in dvm.py and how to get operand type?

### ISSUE THREAD

**Issue by waqarrashid33** [androguard/androguard#325]
A question about instruction and instruction<ID> classes in dvm.py:

I was looking at the code of dvm.py to get the types of operands of each instruction. I was comparing the implementations of instruction<ID> classes with [Dalvik Executable instruction formats ](https://source.android.com/devices/tech/dalvik/instruction-formats#bitwise). I found that some of the instruction formats are not implemented and I found a few implementation which are not in the that list.

Further more, is there a way of getting operand formats (like reg, memory or immediate) without changing the code. I was thinking about adding a method to these instruction classes where I would just manually write a list of the operand types for each instruction format and will return it, but I think it is not a good idea. Does anyone know of way of getting these types without modifying androguard code?

Waqar

**Comment by reox** [comment]
yes, the instructions need to be updated, also in order to work with DEX v038: #318 

what do you mean by operand formats? Can you give me an example? You mean for example if the opcode is `move v1 v2` you get register for both operands and if the opcode is `goto 0x1337` you get address?

**Comment by waqarrashid33** [comment]
Yes. But I did that already.
I couldn't figure it out without modifying `colorize_operands()` in `DalvikVMFormat`.
Just replace the color by register or offset etc.
