### ISSUE TITLE
MethodAnalysis.get_tags() broken, no "tags" in "MethodAnalysis"

### ISSUE THREAD

**Issue by waqarrashid33** [androguard/androguard#326]
The error message is:
`AttributeError: 'MethodAnalysis' object has no attribute 'tags'`

There is no `tags` member in `MethodAnalysis` class.

**Comment by reox** [comment]
can you provide a sample and demo code where this happens? thanks in advance!

**Comment by waqarrashid33** [comment]
It wasn't a problem with code, solved by #328

**Comment by waqarrashid33** [comment]
```
apk = APK(path_to_apk)
dvm = DalvikVMFormat(apk.get_dex())
vmx = Analysis(dvm)
vmx.create_xref()

m = dvm.get_methods()[1]
mx = vmx.get_method(m)

tags = mx.get_tags()
```

**Comment by reox** [comment]
closing this, as get_tags function was removed.
