### ISSUE TITLE
ClassAnalysis.get_xref_to() and from() return empty dictionaries, had to call Analysis.create_xref() manually

### ISSUE THREAD

**Issue by waqarrashid33** [androguard/androguard#328]
Hello,
While trying to xref from ClassAnalysis, I was getting empty dictionaries and also the list of methods was empty.  Below is the code snippet:
```
apk = APK(path_to_apk)
vm = DalvikVMFormat(apk.get_dex())  #
vmx = Analysis(vm)  # Analysis object
#vmx.create_xref() #Without this cx.xref* and cx.methods are empty
classes = vm.get_classes() # ClassDefItem object


for class_ in classes[:1]:
    cx = vmx.get_class_analysis(class_.get_name()) # ClassAnalysis object

    print(class_.get_name())
    print(cx.get_xref_from().values())
    print(cx.get_xref_to().values())
    print(len(cx.get_methods()))
    print(len(class_.get_methods()))

```

I don't know if this is something forgotten by the developers or left due to some reason. I was expecting that all the objects of ClassAnalysis in an Analysis object would be properly populated.

**Comment by ksg97031** [comment]
You have to do `vmx.create_xref()`.
if you want to create per class's xref, you should be customize this [source](https://github.com/androguard/androguard/blob/master/androguard/core/analysis/analysis.py#L760).

**Comment by waqarrashid33** [comment]
Yeah but I don't want to customize important parts of code because I want it to be compatible with the anrdoguard version that is living here.
This post was just for information so that if someone is missing the point like me, they can see it here.
