### ISSUE TITLE
androguard and android-21

### ISSUE THREAD

**Issue by kvarga** [androguard/androguard#33]
Looks like there is an issue with androguard and android-21. Specifically the get_android_resources() function seems to be having an issue parsing the resources.arsc file successfully. We discovered issue on some internal builds and I'm going to try to recreate a simple apk to demonstrate, but wanted to go ahead and create issue in case anyone has any ideas.

**Comment by kvarga** [comment]
@adesnos Have you had a chance to look at this?

**Comment by Colbert337** [comment]
@kvarga @subho007 I met the same problem!!! It occur in  the "> or = Android-SDK-21" apps.I think the problem might be that  "self.header = unpack('<h', buff.read(2))[0]"   is 0,it is not correct.

**Comment by xia0pin9** [comment]
Don't know if it's related, but I get a similar error when open an apk file, the stack trace shows the error happened in zipfile.py (http://bugs.python.org/issue14315). The androguard included version (md5: 1e042f0661f8966e7a15c81651b4dfb9) generate an "unpack" error, but the (previously mentioned) patched version of zipfile.py works without any problems.

**Comment by subho007** [comment]
This seems to be fixed at uTest/Androguard
Although, a small bug remains which can be patched according to my comments at https://github.com/uTest/Androguard/pull/1

**Comment by subho007** [comment]
I have implemented the fix in my repo too at https://github.com/xysec/androguard/pull/8
