### ISSUE TITLE
Failed to sign apk file

### ISSUE THREAD

**Issue by NoAnyLove** [androguard/androguard#332]
In old version of androguard, the signature of `sign_apk` function is `def sign_apk(filename, keystore, alias_name, storepass) :`, which requires an `alias_name` parameter. But I found in recent version of androguard, the signature became `def sign_apk(filename, keystore, storepass):`.

As a result, the command-line was

```
jarsigner -sigalg MD5withRSA -digestalg SHA1 -storepass "foo" -keystore "a path to cert" Simplenote-debug_ins.apk "bar"
```

and now becomes, which directly use the string "alias_name" as the parameter.

```
jarsigner -sigalg MD5withRSA -digestalg SHA1 -storepass "foo" -keystore "a path to cert" Simplenote-debug_ins.apk "alias_name"
```

I'm afraid it is not correct to use "alias_name" as a command-line parameter, it reports the following error on my machine,

```
jarsigner: Certificate chain not found for: alias_name.  alias_name must reference a valid KeyStore key entry containing a private key and corresponding public key certificate chain.
```

**Comment by reox** [comment]
it must have been pre-git where this change was made... jarsigner is probably not the best choice either, we should change it to apksigner as well.

**Comment by subho007** [comment]
@reox I made a pure pythonic way to sign - https://github.com/appknox/pyjarsigner

worth integrating? can take a dig if useful

**Comment by reox** [comment]
@subho007 looks promising! I'm not sure if signing is a functionality we actually need to support, but it looks like some users might like it.
At least it would be much easier than calling other external tools.
