### ISSUE TITLE
can't get app name of or file types for sonicspy malware, malware apk attached

### ISSUE THREAD

**Issue by waqarrashid33** [androguard/androguard#333]
I am trying to analyze a sonicspy malware but having issues getting the app name and file types contained in apk.

```
a, d, dx = AnalyzeAPK(filename.apk)
a.get_files_types()
```
The error is:
`BadZipFile: Bad CRC-32 for file 'resources.arsc`

The file is attached here. [WARNING: THIS IS A MALWARE FILE]
[3528e219fd190445a9918065289738175d311def.zip](https://github.com/androguard/androguard/files/1369185/3528e219fd190445a9918065289738175d311def.zip)

Just renamed it to zip for uploading.

**Comment by reox** [comment]
works fine for me - what python, androguard, library, OS, ... version do you use?

**Comment by waqarrashid33** [comment]
I am using Androguard Second pre-release of version 3.1.0 with python 3.5. My OS is Ubuntu 16.04. Not sure why it isn't working here. I will check it tomorrow again.

**Comment by waqarrashid33** [comment]
Let me check if uploaded the correct file. These hashes are really hard to recognize manually.

**Comment by waqarrashid33** [comment]
Now check it. Last time I uploaded another file. This is the one I am having trouble with.

**Comment by reox** [comment]
Looks like the APK file itself is broken:
```
$ zip --test 3528e219fd190445a9918065289738175d311def.zip 
resources.arsc          bad CRC 0b096702  (should be 86eaf755)
test of 3528e219fd190445a9918065289738175d311def.zip FAILED

zip error: Zip file invalid, could not spawn unzip, or wrong unzip (original files unmodified)
```
