### ISSUE TITLE
the way for checking if a file is APK is not so accurate 

### ISSUE THREAD

**Issue by ahMengli** [androguard/androguard#334]
Hi all:
I just found one file whose first two bytes is "PK" and after being unzipped it contains the AndroidManifest.xml file but it's not APK file, the file is identified as APK file by androguard but in fact it doesn't contain classes.dex file, and I tried to install it on the mobile phone, it failed.
so when checking if a file is APK or not, it's more accurate to adding another condition for checking if it contains AndroidManifest.xml file and classes.dex at the same time after being unzipped.

androguard version: Androguard 2.0
python version: 2.7

the wrongly judged file is in the attachment.
[libandroid-phone-businesscommon-language.zip](https://github.com/androguard/androguard/files/1369984/libandroid-phone-businesscommon-language.zip)

**Comment by reox** [comment]
Checking for AndroidManifest.xml is the valid way. An APK is not obligated to contain classes.dex or resources.arsc nor any other files but must have a AndroidManifest.xml.
If the file is installable on an android device is another question, but as far as i know we can unfortunately not check that...
