### ISSUE TITLE
Anyone else facing this warning with some apks?

### ISSUE THREAD

**Issue by waqarrashid33** [androguard/androguard#335]
I am getting this warning with some apks. Does anyone facing the same problem or know the reason for this?

```
KeyError: 1952385
WARNING: unknown string item @ 0x1dca96(43277)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/androguard-3.1.0-py3.5.egg/androguard/core/bytecodes/dvm.py", line 7323, in get_raw_string
    return self.__strings_off[off].get()
```

**Comment by waqarrashid33** [comment]
It happened when I tried to process big apks like facebook or whatsapp.

**Comment by reox** [comment]
I think this is from the map parsing - but it should not be a problem because the map is reloaded after it is fully parsed. 

Do you see any issues after the APK is loaded?

**Comment by waqarrashid33** [comment]
No, I hadn't faced any issue after the apk is loaded. I can't decompile some methods but I am not sure if its related to this or not. I posted it because it throw this warning hundreds of times.

**Comment by reox** [comment]
I think the warning is nothing you need to be concerned about. If you have exceptions decompiling methods, you can create bugreports for them.
