### ISSUE TITLE
TypeError: 'generator' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by FabioNevesRezende** [androguard/androguard#336]
### Describe what you wanted to do

- use androdd to dump methods to image files
- tested only in one apk

### Describe what you expected
- to generate the image files and sources decompiled

### Describe what actually happened
- error as described below
### System Information

- Androguard Version: master
- Python Version: 2.7.14/3.6.2/
- Arch Linux (blackarch)

### Further Log Files and Output
$ androdd -i air.com.apk.apk.apk -o ./dd 
Clean directory ./dd
Decompilation ... End
Dump Lair/com/apk/apk/AppEntry$1; <init> (Lair/com/apk/apk/AppEntry;)V ... source codes ... bytecodes ... Traceback (most recent call last):
  File "/usr/bin/androdd", line 218, in <module>
    main(options, arguments)
  File "/usr/bin/androdd", line 204, in main
    options.jar, options.decompiler, options.format)
  File "/usr/bin/androdd", line 192, in export_apps_to_format
    bytecode_buff = dvm.get_bytecodes_method(vm, vmx, method)
  File "/usr/lib/python2.7/site-packages/androguard/core/bytecodes/dvm.py", line 8643, in get_bytecodes_method
    return get_bytecodes_methodx(method, mx)
  File "/usr/lib/python2.7/site-packages/androguard/core/bytecodes/dvm.py", line 8672, in get_bytecodes_methodx
    if ins == instructions[-1] and i.childs != []:
TypeError: 'generator' object has no attribute '__getitem__'

**Comment by reox** [comment]
this should be fixed as well with #340 
can you also check if it works for you?
