### ISSUE TITLE
Deprecated documentation 

### ISSUE THREAD

**Issue by soupwaylee** [androguard/androguard#337]
I can't find the `get_AndroidManifest()` method in the apk.py script that is mentioned in the documentation. Maybe the documentation is deprecated? 

APK class can't call `get_AndroidManifest()` method that is listed in the [documentation](http://androguard.readthedocs.io/en/latest/api/androguard.core.bytecodes.html#module-androguard.core.bytecodes.apk).

- Androguard Version: 2.0
- Python Version: 3.6
- Operating System: macOS v10.12.6

**Comment by reox** [comment]
You can always trigger a new build: http://readthedocs.org/projects/androguard/builds/

@adesnos automatic builds would be really nice. Can you activate the webhook for readthedocs? (See http://docs.readthedocs.io/en/latest/webhooks.html#github)
