### ISSUE TITLE
TypeError: 'generator' object is not subscriptable when using  androdd.py

### ISSUE THREAD

**Issue by WadeaHijjawi** [androguard/androguard#339]
I downloaded androguard and installed it using setup.py (the installation completed successfully) but when I try to get the source code all the classes packaged in an APK file using the androdd tool I have occurred the following error message:
" TypeError: 'generator' object is not subscriptable " 

any help to solve this problem.

### System Information

- Androguard Version: master (and I have tried 3.1.0-pre.2)
- Python Version: 3.6
- Operating System: Windows 10 64bit.

### Further Log Files and Output

E:\androguard>python androdd.py -i 2e1ca8258fe04841e8966847fb16b7a4.apk -o bb
WARNING: unknown string item @ 3617251421
Traceback (most recent call last):
  File "E:\androguard\androguard\core\bytecodes\dvm.py", line 7326, in get_raw_string
    off = self.__manage_item["TYPE_STRING_ID_ITEM"][idx].get_string_data_off(
IndexError: list index out of range
Dump information 2e1ca8258fe04841e8966847fb16b7a4.apk in bb
Create directory bb
Decompilation ... End
Dump Landroid/a; <init> ()V ... source codes ... bytecodes ... Traceback (most recent call last):
  File "androdd.py", line 218, in <module>
    main(options, arguments)
  File "androdd.py", line 204, in main
    options.jar, options.decompiler, options.format)
  File "androdd.py", line 192, in export_apps_to_format
    bytecode_buff = dvm.get_bytecodes_method(vm, vmx, method)
  File "E:\androguard\androguard\core\bytecodes\dvm.py", line 8643, in get_bytecodes_method
    return get_bytecodes_methodx(method, mx)
  File "E:\androguard\androguard\core\bytecodes\dvm.py", line 8672, in get_bytecodes_methodx
    if ins == instructions[-1] and i.childs != []:
TypeError: 'generator' object is not subscriptable

**Comment by reox** [comment]
getInstruction was changed to return a generator... I missed that one.

can you check if the changes in #340 work for you?
