### ISSUE TITLE
apk.show() isn't returning intent filters

### ISSUE THREAD

**Issue by diarmaid-mcmanus** [androguard/androguard#354]
### Describe what you wanted to do

By calling androguard/androguard/core/bytecodes/apk.APK('file.apk').show(), no intent-filters are returned in the printout.

- is this error specific to a single file?
No
- if possible give a minimal working example where the error happens
For use in androlyze.py -s
`from androguard.core.bytecodes import apk
a = apk.APK('example.apk')
a.show()`

### Describe what you expected
Intent filters to be printed after the name of activities, etc

### Describe what actually happened
They're not printed.

### System Information

- Androguard Version: master
- Python Version: 3.5.2
- Operating System Ubuntu 16.04.3

### Resolution
The following line submits bytes to get_intent_filters. These bytes need to be decoded with .decode
https://github.com/androguard/androguard/blob/9f88ec774ec9b089f060e075785fe091465d8e22/androguard/core/bytecodes/apk.py#L986

I'll submit PR and fix for this and some other issues this or next week.

**Comment by diarmaid-mcmanus** [comment]
Should .decode for this live within show() or should there be a sanity check in get_intent_filters? This affects not only activities (as my example) but also services, receivers

**Comment by reox** [comment]
maybe the xml parsing has some issues - i changed it to lxml lately.

It would be very nice if you could provide a fix!

**Comment by reox** [comment]
Looks like this is a python3 issue: I think decode should be already in the a.get_activities() function.

If you have some nice AndroidManifest.xml files with a lot of different intent filters, they would also be well suited for a unittest.

**Comment by diarmaid-mcmanus** [comment]
I can create one. I have an AndroidManifest.xml with such but it's a random manifest from the play store. Is this OK to use?

I plan to fix this and provide a patch for something else I think is a bug (question incoming) this week, hopefully early this week but Sunday at any rate.

**Comment by diarmaid-mcmanus** [comment]
Hey, the following line turns an str into a byte array. Do you know/remember why it was implemented like this? 

https://github.com/androguard/androguard/blob/9f88ec774ec9b089f060e075785fe091465d8e22/androguard/core/bytecodes/apk.py#L538

By removing .encode() on this line it works as I'd expect, and all test_*.py files pass. I'm not sure if that's appropriate as a fix though - will it break something else?
