### ISSUE TITLE
apk.new_zip only adds new_files to a zip if deleted_files is not None

### ISSUE THREAD

**Issue by diarmaid-mcmanus** [androguard/androguard#355]
Hello, I'm unsure if this is a bug or intended feature. Please tag this with question, I don't seem to have access to tags.

When calling `apk.new_zip('example.apk', new_files={'Anything':'content'})` file 'Anything' does not get written. 
file 'Anything' only gets written if deleted_files='no-thing' i.e. is any string other than the file name in new_files. In this example, deleted_files must be something other than 'Anything'.

https://github.com/androguard/androguard/blob/9f88ec774ec9b089f060e075785fe091465d8e22/androguard/core/bytecodes/apk.py#L870

I would expect one of the following two things to happen:

1. new_files and deleted_files to work independently, or
2. new_files to work if the new_files file is also in the deleted_files string.

My preference would be for 1 - if deleted_files=None, then new_files are still written into the zip. Existing files are overwritten.

I could understand 2 - if a file is to be deleted, then it's overwritten with the file in new_files.

I don't understand why it works as in the code at the moment - new_files are written to the zip, if deleted_files is not None, and if the file name in deleted_files does not match new_files.

As on my other issue happy to provide a patch for this, once I know what the expected behaviour is.

**Comment by reox** [comment]
I never used the function :D But it looks like either the documentation is wrong or the implementation.
I think it is the implementation :) I think you should be able to create new files with a given dict of files and also remove files from the APK if necessary.

I would be glad if you can provide a patch!

**Comment by diarmaid-mcmanus** [comment]
Current plan to replace the code at https://github.com/androguard/androguard/blob/9f88ec774ec9b089f060e075785fe091465d8e22/androguard/core/bytecodes/apk.py#L867

```python
for item in self.zip.infolist():
    if deleted_files is not None:
        if re.match(deleted_files, item.filename) is None:
            buffer = self.zip.read(item.filename)
            zout.writestr(item, buffer)
    if new_files is False:
        if item.filename in new_files:
            zout.writestr(item, new_files[item.filename])
zout.close()
```

I haven't tested that the new_files conditional block will overwrite existing files, I'll do this tomorrow.
