### ISSUE TITLE
PROBLEM when running python setup.py build_sphinx 

### ISSUE THREAD

**Issue by david-lambropoulos-91** [androguard/androguard#356]
I have installed following python packages

pip install ipython pyperclip networkx future pyasn1 cyptography filemagic mock pydot sphix sphinxcontrib.programoutput sphinx_rtd_theme

Then ran 

python setup install

Followed by

python setup.py build_sphinx and was presented with the following

running build_sphinx
Running Sphinx v1.6.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] api/androguard.patch                                                   
                                       
/Users/thanatos/androguard/docs/api/androguard.patch.rst:10: WARNING: autodoc: failed to import module u'androguard.patch.zipfile'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/thanatos/gort-env/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named patch.zipfile

/Users/thanatos/androguard/docs/api/androguard.patch.rst:19: WARNING: autodoc: failed to import module u'androguard.patch'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/thanatos/gort-env/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named patch
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                          
generating indices... genindex py-modindex
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/Users/thanatos/androguard/docs/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 3 warnings.

How can I resolve the issue with androguard.patch and androguard.patch.zipfile?

**Comment by reox** [comment]
These are removed modules... the documentation was partly autogenerated from the source code, so those modules must also be removed from the documentation...

I added doc building now on travis, so we can see such errors eariler - see #357
