### ISSUE TITLE
handle no resource file in APK

### ISSUE THREAD

**Issue by reox** [androguard/androguard#360]
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do

get the icon from an APK where the resource file is missing / could not be parsed:

```
    icon = a.get_app_icon()
  File "/usr/local/lib/python3.5/dist-packages/androguard/core/bytecodes/apk.py", line 301, in get_app_icon
    res_id = self.get_android_resources().get_res_id_by_key(self.package, 'mipmap', 'ic_launcher')
AttributeError: 'NoneType' object has no attribute 'get_res_id_by_key'
```

### Describe what you expected

icon should at least return None but not raise an Error

### Describe what actually happened

error is raised.

### System Information

- Androguard Version: master
- Python Version: 3.5
- Operating System: linux

**Comment by subho007** [comment]
@reox we only check first if `self.get_android_resources()` is None or not and accordingly proceed.

**Comment by reox** [comment]
yes, that would be the solution. We need also check where the resource file is queried and no None check is made.
