### ISSUE TITLE
Documentation: get_classes_def_item() return type does not match readthedocs.io

### ISSUE THREAD

**Issue by diarmaid-mcmanus** [androguard/androguard#365]
### Describe what you wanted to do

http://androguard.readthedocs.io/en/latest/api/androguard.core.bytecodes.html#androguard.core.bytecodes.dvm.DalvikVMFormat.get_classes_def_item 

This claims the return type will be a `ClassDefItem` object, when it instead returns a `ClassHDefItem`.

### System Information

- Androguard Version: master
- Python Version: 3.5.2
- Ubuntu 16.04

### Further Log Files and Output

```
a, d, dx = AnalyzeAPK('example.apk')
type(d[0].get_classes_def_item())
androguard.core.bytecodes.dvm.ClassHDefItem
```

**Comment by diarmaid-mcmanus** [comment]
get_classes_def_item().get_obj() returns the type defined in the documentation

**Comment by reox** [comment]
Yeah, if the documentation is not missing, it is often not even right :D
