### ISSUE TITLE
Alternative to old getElementsByTagName and attributes on the manifest file

### ISSUE THREAD

**Issue by clviper** [androguard/androguard#368]
Hi there.
I was still using androguard available via pip that is the 3.0.1 and a lot change on version 3.1.0.
I have been looking in the source code but is still not clear to me the best way to do this,for example being able to determine if a particular component is exported.
In the past I had something like:

```
manifest = .a.get_AndroidManifest().getElementsByTagName("manifest")[0]
activities = application.getElementsByTagName("activity")
```
And for each activity I would be able to access the attributes via  `activity.attributes["android:exported"].value`

I've noticed that now there is a get_elements() available, but so far it does not appear to be the best way to get this information.

What would the best way to get this information?

Thank for the help and for the amazing job in the continuous work on this framework.

**Comment by reox** [comment]
maybe this is due to the change to LXML? (See #348 )
Maybe it is because LXML renames the namespaces... But this should be changed back to the old behaviour! (i.e. to be able to have the android: namespace instead of ns00:

**Comment by clviper** [comment]
Hi @reox . I might have not been clear with my doubt. Basically the function get_AndroidManifest() no longer exists in androguard 3.1.0 and with the new function get_android_manifest_xml() I don't have the function getElementsByTagName().

Just wondering what would be the best approach to parse the manifest file for certain attributes I need to check like the android:exported for example.
