### ISSUE TITLE
Add corresponding vm to Analysis object for ClassAnalysis

### ISSUE THREAD

**Issue by subho007** [androguard/androguard#373]
Currently a very hackish way is implemented at https://github.com/androguard/androguard/blob/master/androguard/session.py which breaks Xrefs from different dex files in multi-dex.

The idea is to create a reference of `vm` in `ClassAnalysis` at
- https://github.com/androguard/androguard/blob/master/androguard/core/analysis/analysis.py#L762-L775
- https://github.com/androguard/androguard/blob/master/androguard/core/analysis/analysis.py#L649

Single `Analysis` object should contain the analysis across all the dex file, and on getting an `xref` it should also have a reference of the `vm` object which it is related to.

@reox thoughts ?

**Comment by reox** [comment]
Should it be enough to reference each class to it's vm? Or is it possible that a class is defined twice?

There is also this thing here: https://github.com/androguard/androguard/blob/6b3a6120eb501d14e10a7a3c6024727bfa53109a/androguard/core/analysis/analysis.py#L784
The xref is always created over the last VM.

And here is just another thing: If dex file A contains a class CLASS_A and this one xrefs to CLASS_B, which is in dex file B. Then CLASS_B is external in A, right? Which means, that after we see dex file B, we need to rewrite the whole classes dict anyways?
That would mean, we should generally rework Analysis in such a way that you can call create_xref and it will generate xrefs over all VMs.
Unfortunatly I'm not so experienced with multidex files...

**Comment by reox** [comment]
See also Issue #359
