### ISSUE TITLE
Better way to get multiple dex files

### ISSUE THREAD

**Issue by subho007** [androguard/androguard#374]
Added 2 commits:

1. https://github.com/androguard/androguard/commit/13fa6791eeaac8880c022b950720cdffdfff37d3

2. https://github.com/androguard/androguard/commit/1e77df4e2a15fd5fb0610c92fba18ed181046c43

@reox this is FYI. You can close this issue once you do a review on the above commits

**Comment by reox** [comment]
looks much better than my hack :D
