### ISSUE TITLE
namespace is ns00 instead of android

### ISSUE THREAD

**Issue by reox** [androguard/androguard#377]
during the conversion from SAX to DOM, the namespaces are renamed.

here is an example:
```
import lxml.sax
from xml.dom.pulldom import SAX2DOM
from lxml import etree


xmlbuff = b'<?xml version="1.0" encoding="utf-8"?>\n<manifest xmlns:android="http://schemas.android.com/apk/res/android"\n    package="tests.androguard"\n    android:versionCode="1"\n    android:versionName="1.0" >\n\n    <uses-sdk\n        android:minSdkVersion="9"\n        android:targetSdkVersion="16" />\n\n    <application\n        android:allowBackup="false"\n        android:icon="@drawable/icon"\n        android:label="@string/app_name" >\n        <activity\n            android:name="TestActivity"\n            android:label="@string/app_name" >\n            <intent-filter>\n                <action android:name="android.intent.action.MAIN" />\n\n                <category android:name="android.intent.category.LAUNCHER" />\n            </intent-filter>\n        </activity>\n    </application>\n\n</manifest>'

parser = etree.XMLParser(recover=True, resolve_entities=False)
tree = etree.frostring(xmlbuff, parser=parser)
handler = SAX2DOM()
lxml.sax.saxify(tree, handler)
handler.document.toprettyxml()
```
will output
`'<?xml version="1.0" ?>\n<manifest ns00:versionCode="1" ns00:versionName="1.0" package="tests.androguard" xmlns:ns00="http://schemas.android.com/apk/res/android">\n\t\n\n    \n\t<uses-sdk ns00:minSdkVersion="9" ns00:targetSdkVersion="16"/>\n\t\n\n    \n\t<application ns00:allowBackup="false" ns00:icon="@drawable/icon" ns00:label="@string/app_name">\n\t\t\n        \n\t\t<activity ns00:label="@string/app_name" ns00:name="TestActivity">\n\t\t\t\n            \n\t\t\t<intent-filter>\n\t\t\t\t\n                \n\t\t\t\t<action ns00:name="android.intent.action.MAIN"/>\n\t\t\t\t\n\n                \n\t\t\t\t<category ns00:name="android.intent.category.LAUNCHER"/>\n\t\t\t\t\n            \n\t\t\t</intent-filter>\n\t\t\t\n        \n\t\t</activity>\n\t\t\n    \n\t</application>\n\t\n\n\n</manifest>\n'`

the question is, why we need DOM and not use Etree? The other question is, if we like to use DOM, how can we keep the namespace names?

**Comment by subho007** [comment]
`etree.tostring(tree, pretty_print=True)` solves it. Although I have encountered mangled manifest files which when parsed with AXML parser gives out invalid xml.

**Comment by reox** [comment]
But the problem seems to be in the SAX2DOM parser? the Etree is fine, the problem is that we use minidom everywhere else. Probably we could use Etree, which seems to be easier as well.

**Comment by subho007** [comment]
I agree, Etree is fine, the only reason I went ahead with a SAX2DOM parser was because many tools using androguard uses minidom which requires it. Since this is a rewrite of sorts, going ahead with etree as parser is good to go 👍

**Comment by subho007** [comment]
@reox I remember this problem. SAX2DOM doesn't play well with `xmlns` instead it needs to be `xmlnamespace` attribute. 

see - https://github.com/appknox/androguard-old/commit/fd63ec02ce517a7f7b3144eb34473231ea7eac1f

**Comment by subho007** [comment]
try this:

```
import lxml.sax
from xml.dom.pulldom import SAX2DOM
from lxml import etree


xmlbuff = b'<?xml version="1.0" encoding="utf-8"?>\n<manifest xmlnamespace:android="http://schemas.android.com/apk/res/android"\n    package="tests.androguard"\n    android:versionCode="1"\n    android:versionName="1.0" >\n\n    <uses-sdk\n        android:minSdkVersion="9"\n        android:targetSdkVersion="16" />\n\n    <application\n        android:allowBackup="false"\n        android:icon="@drawable/icon"\n        android:label="@string/app_name" >\n        <activity\n            android:name="TestActivity"\n            android:label="@string/app_name" >\n            <intent-filter>\n                <action android:name="android.intent.action.MAIN" />\n\n                <category android:name="android.intent.category.LAUNCHER" />\n            </intent-filter>\n        </activity>\n    </application>\n\n</manifest>'

parser = etree.XMLParser(recover=True, resolve_entities=False)
tree = etree.fromstring(xmlbuff, parser=parser)
handler = SAX2DOM()
lxml.sax.saxify(tree, handler)
handler.document.toprettyxml()
```

will give you output

```
'<?xml version="1.0" ?>\n<manifest android:versionCode="1" android:versionName="1.0" package="tests.androguard" xmlnamespace:android="http://schemas.android.com/apk/res/android">\n\t\n\n    \n\t<uses-sdk android:minSdkVersion="9" android:targetSdkVersion="16"/>\n\t\n\n    \n\t<application android:allowBackup="false" android:icon="@drawable/icon" android:label="@string/app_name">\n\t\t\n        \n\t\t<activity android:label="@string/app_name" android:name="TestActivity">\n\t\t\t\n            \n\t\t\t<intent-filter>\n\t\t\t\t\n                \n\t\t\t\t<action android:name="android.intent.action.MAIN"/>\n\t\t\t\t\n\n                \n\t\t\t\t<category android:name="android.intent.category.LAUNCHER"/>\n\t\t\t\t\n            \n\t\t\t</intent-filter>\n\t\t\t\n        \n\t\t</activity>\n\t\t\n    \n\t</application>\n\t\n\n\n</manifest>\n'
```

**Comment by reox** [comment]
But isn't `xmlnamespace` something different then `xmlns`? I could not find a single resource that says you can define namespaces like that...

**Comment by subho007** [comment]
True, but that is the hack I used to solve this. I think it is better to use etree directly.
