### ISSUE TITLE
Is there a better implementation for MUTF-8 Strings?

### ISSUE THREAD

**Issue by reox** [androguard/androguard#381]
This is the current implementation: https://github.com/androguard/androguard/blob/aa18f723c115c902cb495476a178eb1f9c0ec014/androguard/core/bytecodes/dvm.py#L1800-L1847

We would like to read the Strings from the DEX file and have them in a useful format - i.e. unicode?

I read in the documentation of Android, that the good thing about MUTF-8 is, that the strings will be always null terminated! This means, we can simply get the null terminated string from the dex file and parse it later!
I found this implementation: https://github.com/google/enjarify/blob/master/enjarify/mutf8.py
Maybe we should stick to that one?

**Comment by reox** [comment]
I just tested that mutf8.py and it looks like it does not support some surrogates... need to investigate more

**Comment by reox** [comment]
I just rewrote the MUTF-8 implementation. Now it looks more solid.
I also added testdata for some cases.

**Comment by subho007** [comment]
this is awesome !
