### ISSUE TITLE
How could I get the parameter values of API calls by data-flow analysis？

### ISSUE THREAD

**Issue by ChenJunHero** [androguard/androguard#383]
Hi！
I have get the api calls (external methods) of a apk file by androguard-3.0，and I also want to get some prarameters value of sensitive apis. Are there some fuctions or methods helping me achieve simple data-flow analysis.
Thanks.

**Comment by reox** [comment]
this is related to #252 

There is a tool to generate the mapping of API calls to their permissions. With this map you are able to determine so to say sensitive APIs.
But it is not very stable and produces a lot of wrong mappings...

Therefore I would suggest that you create a list of API calls you like to monitor.

**Comment by ChenJunHero** [comment]
Sorry,maybe I said not clearly yesterday. I don`t want to get the mapping of API to their permission.
I  want get the parameter value of some special APIs.
For example:
- what is the flag values when calling setFlags() or addFlags() methods in the classes of Intent?
- what specific parameters are delivered to the methods of write(),append(),indexOF() and so on ?

Are there some simple static data-flow analysis methods can help me achieve it?
Thank you very much!

**Comment by reox** [comment]
given that example:
```
String x = "bla";
someobject.do_something(x);
```
you like to get `"bla"` for the call of `do_something(String x)`?

I'm not sure if this possible with the current setup...

**Comment by ChenJunHero** [comment]
Yeah，that`s exactly what I mean.
I  have a primary approach which  get parameter values on the base of CFG obtained by androguard.
whatever I will try.
Thank you.

**Comment by sajidrahman** [comment]
Can AndroGuard be set up to do a source-sink analysis? For example, I want to check if a certain input field's value (e.g., full name) has been used as a parameter in an API method (e.g., setUserName()). Is it feasible?
