### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'get_method_analysis' "  error occured while using AnalyzeAPK() in Androlyze.py -s

### ISSUE THREAD

**Issue by TinyMagicka** [androguard/androguard#386]
my python version :python 3.6.4
my installation method:
     git clone git@github.com:androguard/androguard.git 
     cd androguard
     pip3 install .

after installation i used androlyze.py . The whole screen output as follow:
/////////////////////////////////////////////////////////////////////////////////////////////////////////////
$ androlyze.py -s
Androguard version 3.1.0
In [1]:  a, d, dx = AnalyzeAPK("d:\\WorkSpace\\APKtool\\meiyingwifi.apk")

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\python36\lib\site-packages\androguard-3.1.0-py3.6.egg\EGG-INFO\scripts\androl                                                                 yze.py in <module>()
----> 1 a, d, dx = AnalyzeAPK("d:\\WorkSpace\\APKtool\\meiyingwifi.apk")

C:\python36\lib\site-packages\androguard-3.1.0-py3.6.egg\androguard\misc.py in A                                                                 nalyzeAPK(_file, session, raw)
     50             filename = _file
     51
---> 52     digest = session.add(filename, data)
     53     return session.get_objects_apk(filename, digest)
     54

C:\python36\lib\site-packages\androguard-3.1.0-py3.6.egg\androguard\session.py i                                                                 n add(self, filename, raw_data, dx)
    164             dx = self.analyzed_vms.get(digest)
    165             for dex in dex_files:
--> 166                 _, d, dx = self.addDEX(filename, dex, dx)
    167         elif ret == "DEX":
    168             digest, d, _ = self.addDEX(filename, raw_data)

C:\python36\lib\site-packages\androguard-3.1.0-py3.6.egg\androguard\session.py i                                                                 n addDEX(self, filename, data, dx)
    109         if self.export_ipython:
    110             log.debug("Exporting in ipython")
--> 111             d.create_python_export()
    112
    113         if dx is None:

C:\python36\lib\site-packages\androguard-3.1.0-py3.6.egg\androguard\core\bytecod                                                                 es\dvm.py in create_python_export(self)
   8093
   8094         for _class in self.get_classes():
-> 8095             self._create_python_export_class(_class)
   8096
   8097     def _delete_python_export_class(self, _class):

C:\python36\lib\site-packages\androguard-3.1.0-py3.6.egg\androguard\core\bytecod                                                                 es\dvm.py in _create_python_export_class(self, _class, delete)
   8110                 setattr(_class, "F", ExportObject())
   8111
-> 8112             self._create_python_export_methods(_class, delete)
   8113             self._create_python_export_fields(_class, delete)
   8114

C:\python36\lib\site-packages\androguard-3.1.0-py3.6.egg\androguard\core\bytecod                                                                 es\dvm.py in _create_python_export_methods(self, _class, delete)
   8122             setattr(method, "XT", ExportObject())
   8123
-> 8124             m_a = self.CM.get_vmanalysis().get_method_analysis(method)
   8125             if m_a:
   8126                 xrefs_from = m_a.get_xref_from()

AttributeError: 'NoneType' object has no attribute 'get_method_analysis'
////////////////////////////////////////////////////////////////////////////////////////////////////////////////

But it is okay to use function AnalyzeAPK() directly in program. 
So i debugged it only to find that changing "    CONF["SESSION"] = Session(True)" in line 52 of file androlyze.py to  "    CONF["SESSION"] = Session(False)"  can fix this problem. 
 but I don't know the reason.

**Comment by reox** [comment]
can you share the APK that is causing the problem?

**Comment by TinyMagicka** [comment]
![meiyingwifi_apk](https://user-images.githubusercontent.com/23069620/34212130-4dfed3a8-e5d6-11e7-8580-0d0a85e9e1a7.gif)
I have tested several apk files. all of them have the same problem.
this file is one of apk files
change file extension "gif" to "apk"

**Comment by damadamn** [comment]
I've got the same problem with all my apk, official or not
When I use the debug method of @TinyMagicka , androguard blocked like that : 

In [1]: a,d,dx = AnalyzeAPK("/home/damien/Documents/pst4_user_tracking/apk/com.u
   ...: bercab.apk")

and below all errors when I interrupted it : 

---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/home/damien/Téléchargements/androguard-master/androlyze.py in <module>()
----> 1 a,d,dx = AnalyzeAPK("/home/damien/Documents/pst4_user_tracking/apk/com.ubercab.apk")

/home/damien/Téléchargements/androguard-master/androguard/misc.pyc in AnalyzeAPK(_file, session, raw)
     50             filename = _file
     51 
---> 52     digest = session.add(filename, data)
     53     return session.get_objects_apk(filename, digest)
     54 

/home/damien/Téléchargements/androguard-master/androguard/session.pyc in add(self, filename, raw_data, dx)
    164             dx = self.analyzed_vms.get(digest)
    165             for dex in dex_files:
--> 166                 _, d, dx = self.addDEX(filename, dex, dx)
    167         elif ret == "DEX":
    168             digest, d, _ = self.addDEX(filename, raw_data)

/home/damien/Téléchargements/androguard-master/androguard/session.pyc in addDEX(self, filename, data, dx)
     98 
     99         log.debug("Parsing format ...")
--> 100         d = DalvikVMFormat(data)
    101         log.debug("added DEX:%s" % digest)
    102 

/home/damien/Téléchargements/androguard-master/androguard/core/bytecodes/dvm.pyc in __init__(self, buff, decompiler, config, using_api)
   7565 
   7566         self._preload(buff)
-> 7567         self._load(buff)
   7568 
   7569     def _preload(self, buff):

/home/damien/Téléchargements/androguard-master/androguard/core/bytecodes/dvm.pyc in _load(self, buff)
   7576             log.warning("no map list ...")
   7577         else:
-> 7578             self.map_list = MapList(self.CM, self.__header.map_off, self)
   7579 
   7580             self.classes = self.map_list.get_item_type("TYPE_CLASS_DEF_ITEM")

/home/damien/Téléchargements/androguard-master/androguard/core/bytecodes/dvm.pyc in __init__(self, cm, off, buff)
   7458             log.debug("Reloading %s" % TYPE_MAP_ITEM[i.get_type()])
   7459             started_at = time.time()
-> 7460             i.reload()
   7461             diff = time.time() - started_at
   7462             minutes, seconds = float(diff // 60), float(diff % 60)

/home/damien/Téléchargements/androguard-master/androguard/core/bytecodes/dvm.pyc in reload(self)
   7067                     i.reload()
   7068             else:
-> 7069                 self.item.reload()
   7070 
   7071     def show(self):

/home/damien/Téléchargements/androguard-master/androguard/core/bytecodes/dvm.pyc in reload(self)
   2553     def reload(self):
   2554         for i in self.methods:
-> 2555             i.reload()
   2556 
   2557     def show(self):

/home/damien/Téléchargements/androguard-master/androguard/core/bytecodes/dvm.pyc in reload(self)
   2416     def reload(self):
   2417         self.class_idx_value = self.CM.get_type(self.class_idx)
-> 2418         self.proto_idx_value = self.CM.get_proto(self.proto_idx)
   2419         self.name_idx_value = self.CM.get_string(self.name_idx)
   2420 

/home/damien/Téléchargements/androguard-master/androguard/core/bytecodes/dvm.pyc in get_proto(self, idx)
   7285             self.__cached_proto[idx] = proto
   7286 
-> 7287         return [proto.get_parameters_off_value(),
   7288                 proto.get_return_type_idx_value()]
   7289 

/home/damien/Téléchargements/androguard-master/androguard/core/bytecodes/dvm.pyc in get_parameters_off_value(self)
   2135         """
   2136         if self.parameters_off_value is None:
-> 2137             params = self.CM.get_type_list(self.parameters_off)
   2138             self.parameters_off_value = '({})'.format(' '.join(params))
   2139         return self.parameters_off_value

/home/damien/Téléchargements/androguard-master/androguard/core/bytecodes/dvm.pyc in get_type_list(self, off)
   7266             return []
   7267 
-> 7268         for i in self.__manage_item["TYPE_TYPE_LIST"]:
   7269             if i.get_type_list_off() == off:
   7270                 return [type_.get_string() for type_ in i.get_list()]

KeyboardInterrupt:

**Comment by reox** [comment]
okay, yes I can confirm that!

**Comment by reox** [comment]
the ipython export should have been after the analyis object are set in the DalvikVMObjects.
Can you check if #387 works for you? (it does for me)

**Comment by TinyMagicka** [comment]
okay! it works
