### ISSUE TITLE
Return dex names as well

### ISSUE THREAD

**Issue by reox** [androguard/androguard#395]
https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/apk.py#L492-L507

need a second method that returns the name of the dexfile too.

**Comment by ksg97031** [comment]
https://github.com/androguard/androguard/pull/398

**Comment by ksg97031** [comment]
https://github.com/androguard/androguard/pull/399 check pls

**Comment by reox** [comment]
this is actually resolved
