### ISSUE TITLE
how to extract used permisssions?

### ISSUE THREAD

**Issue by AnasMK** [androguard/androguard#414]
I read the code in androguard/core/bytecodes/apk.py , it seems that I can only get the declared permissions (from Manifest file) but cannot extract the used permissions. Also, the get_requested_permissions method is deprecated and returns declared permissions not the actually requested ones. 

can any one confirm to me if I'm right? and If there is a way to get the used permissions form an apk, please tell me what is it?
@reox  can you help with this?

**Comment by reox** [comment]
Try this code #222 

The problem is, that the API permission mappings are not correct.
I started to implement axplorer, which might have some better mappings, but this is far from useable: https://github.com/reox/androguard/tree/permission-mappings

**Comment by reox** [comment]
axplorer mappings are now in master. It would be very nice if you could test that and send in any bugs you might find!
