### ISSUE TITLE
better androlyze

### ISSUE THREAD

**Issue by reox** [androguard/androguard#422]
androlyze shell is quite neat but has a big problem: if you use it for example to search for stuff in apks, you often encounter generators and long lists or just objects and you have no string to search for them.
therefore it would be nice to have helperfunctions in androlyze.
I had a look at viper, which makes this really beautifully! Maybe we could improve on the apk module and have more androlyze shell functions there? @Rafiot what do you think about that? For example is it possible to spawn an ipython shell in viper? Like an androlyze inside viper?

**Comment by Rafiot** [comment]
It is currently not possible, but at some point, it might be good to have ipython as default console in viper.

No idea when I'll have time to work on it, but it is an interesting idea
