### ISSUE TITLE
Android Studio allows to generate invalid x509 certificates

### ISSUE THREAD

**Issue by U039b** [androguard/androguard#424]
Hi!
Android Studio allows to generate invalid x509 certificates. The form allows you to specify a country name on any number of chars. RFC specifies that the country name must be a 2 character country code.

Androguard uses the cryptography library to parse x509 certificates which had signed the APK. If the country name of the certificate is invalid, the cryptography library raises this error:
```
ssl/x509.py", line 102, in issuer
    return _decode_x509_name(self._backend, issuer)
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 66, in _decode_x509_name
    attribute = _decode_x509_name_entry(backend, entry)
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 57, in _decode_x509_name_entry
    return x509.NameAttribute(x509.ObjectIdentifier(oid), value, type)
  File "[edited]/exodus-standalone/venv/lib/python3.5/site-packages/cryptography/x509/name.py", line 50, in __init__
    "Country name must be a 2 character country code"
ValueError: Country name must be a 2 character country code
```
The `cryptography` library issue https://github.com/pyca/cryptography/issues/3857

Plus, it seems that Androguard does not handle the [APK Signature Scheme v2 ](https://source.android.com/security/apksigning/v2).

**Comment by reox** [comment]
I hope the cryptography library will support reading malformed certificates soon :)

for the v2 schema: do you know if there are APKs that do not use v1 schema but solely the v2? I think at the moment this will not work. Otherwise, I think @subho007 implemented a pure python way of signing and verifying APKs, right? Maybe we should merge that. For the v2 Schema, we basically need to patch the ZipFile implementation... I thought about making APK a instance of ZipFile, so it has all methods from ZipFile and will be extendable.

**Comment by reox** [comment]
See also #313

**Comment by U039b** [comment]
Hi @reox!
Thank you for your answer. Since v2 signing schema was introduced in Android 7.0, v1 will remain the preferred signing schema.

**Comment by eighthave** [comment]
In F-Droid, we're starting to see APKs that are only signed by v2.  That is valid if the app has a min SDK of 7.0, or whenever v2 support was added.

**Comment by reox** [comment]
See #425  and #427 - starting with some improvements for the v2 signature

**Comment by reox** [comment]
If you are really desperate, you can do the following monkey patch:
```
import six
from cryptography.x509.name import _SENTINEL, ObjectIdentifier, _NAMEOID_DEFAULT_TYPE, _ASN1Type, NameAttribute
def _my_name_init(self, oid, value, _type=_SENTINEL):
    if not isinstance(oid, ObjectIdentifier):
        raise TypeError("oid argument must be an ObjectIdentifier instance.")
    if not isinstance(value, six.text_type):
        raise TypeError("value argument must be a text type.")
    if len(value) == 0:
        raise ValueError("Value cannot be an empty string")
    if _type == _SENTINEL:
        _type = _NAMEOID_DEFAULT_TYPE.get(oid, _ASN1Type.UTF8String)
    if not isinstance(_type, _ASN1Type):
        raise TypeError("_type must be from the _ASN1Type enum")
    self._oid = oid
    self._value = value
    self._type = _type
NameAttribute.__init__ = _my_name_init
```

I tested it here for a project and it works. But as soon as the library is changed it will probably fail.

**Comment by reox** [comment]
With the switch to asn1crypto, this should work now I hope...

**Comment by reox** [comment]
I just tested that and can happily close this issue now ;)
thanks to @shuxin !
