### ISSUE TITLE
Dex classes not available from session.get_classes

### ISSUE THREAD

**Issue by udgover** [androguard/androguard#435]
Using version 3.0.1 (installed from pip in a virtualenv), session.get_classes() yielded classes whatever the type of file (APK, DEX, DEY). 

After updating to master branch I expected to obtain the same result.

Nevertheless calling session.get_classes() from master branch not longer gives access to classes for DEX files. 

After looking at the code, it seems, analyzed_vms is only populated for APK type but neither for DEX or DEY files. I currently use the following workaround:

for digest in session.analyzed_dex:
   for vm in session.analyzed_dex[digest].vms:
      _class = vm.get_classes()

It works but it is no longer "agnostic" because I have to know if I deal with APK, DEX or DEY.

Is this voluntary?

Thanks.

**Comment by reox** [comment]
> Is this voluntary?
probably not... there was a lot of restructuring in this module. I'll have a look!

**Comment by reox** [comment]
can you provide a short example how you used session before?

**Comment by udgover** [comment]
Sure!

On version 3.0.1 I used the following code:

from androguard.session import Session

def extractTargets(filename):
    with open(filename, "rb") as fd:
        data = fd.read()
        filename = fd.name
    session = Session()
    digest = session.add(filename, data)
    targets = set()
    for idx, filename, digest, classes in session.get_classes():
        for _class in classes:
            source = _class.get_source()

**Comment by reox** [comment]
thanks!

I tested it now with my changes and it seems to work...

**Comment by udgover** [comment]
Great! Thanks for your quick answer!

**Comment by udgover** [comment]
Just seen your PR. Thanks!

**Comment by reox** [comment]
So I found out that the PR broke some stuff, so I removed it.

For now you can get the DEX files from the Analysis Object... But the session module needs some rework after all.
