### ISSUE TITLE
I got error when I analysis apk  ('list' object has no attribute 'get_methods')

### ISSUE THREAD

**Issue by kaloon2009** [androguard/androguard#445]
Hello, 
I have 
I have tried to analysis an app that I download it from the google store. 
I test them as follow: 
```
$./androlyze.py -s
$ a,d,dx = AnalyzeAPK("/Volumes/BOOTCAMP/26-2-2018/Device_ID_Without_Permi
   ...: stion/Log_API_log/base2.apk")
```

The problem is when I execute the next command is "d.get_methods()" I got an error:
```
In [2]: d.get_methods()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/khalidalkhattabi/Downloads/androguard-master/androlyze.py in <module>()
----> 1 d.get_methods()

AttributeError: 'list' object has no attribute 'get_methods'
```

**Comment by reox** [comment]
`d` is now a `list` of dex files. So either do something like
```
for dex in d:
    print(d.get_methods())
```

or use the method `get_methods()` on the dx object.

**Comment by kaloon2009** [comment]
Thanks, Rex.
I have another question. 
I am trying to get the source code of the class. 
I tried using the next command: 
```
 $ a.get_main_activity()      // to get my target class that I want to view  its source code
   'com.example.kaloon.headerparser.MainActivity'

 $ for d1 in d:
     print(d1.get_class("com.example.kaloon.headerparser.MainActivity").source())
```
Is there way to found if an app have used specific APIs e.g Settings.Secure.getString?

**Comment by reox** [comment]
The names of classes are sligtly different: The Java Name is `a.b.c.d`, but the name inside the DEX is `La/b/c/d;` See: https://source.android.com/devices/tech/dalvik/dex-format
So If you are searching for classnames, you need to convert the name too.

To search for class/method/field usage, you can use the Analysis object (the dx you got from AnalyzeAPK). It has all this information.

**Comment by kaloon2009** [comment]
Thanks reox,
I tried  this : 
```
dx.get_class("com/example/kaloon/headerparser/MainActivity").source()
```
I got this error
```
AttributeError: Analysis instance has no attribute 'get_class'
```

**Comment by reox** [comment]
What you need is this: https://github.com/androguard/androguard/blob/master/androguard/core/analysis/analysis.py#L1075

```
dx.get_class_analysis("Lcom/example/kaloon/headerparser/MainActivity;").get_vm_class().source()
```

**Comment by kaloon2009** [comment]
Thanks reox, 
It works :)

**Comment by reox** [comment]
you're welcome!
