### ISSUE TITLE
how can I search for the specific strings or specific APIs if they have been used within the app or not? 

### ISSUE THREAD

**Issue by kaloon2009** [androguard/androguard#449]
Hello 

I know that if want to search for classes or methods and I can use the Analysis object (the dx from AnalyzeAPK.However, when I print "dx",  it told me there are more than 10000 classes. my app has just 10 classes. how can I show just my classes within the app? 
I used this command: 
```
 a,d,dx = AnalyzeAPK("/test.apk")
```
when I print just dx
```
In [70]: dx
Out[70]: <analysis.Analysis VMs: 2, Classes: 10376, Strings: 19630>
```

I have another question: 
how can I search for the specific strings or specific APIs if they have been used within the app or not?

**Comment by reox** [comment]
Have you looked at the methods in `Analysis`?
Unfortunately we can not rebuild the documentation right now, as the repo on rtd is owned by someone else, but you can build it yourself: `python setup.py build_sphinx`. Then open `file:///path/to/androguard/build/sphinx/html/api/androguard.core.analysis.html#module-androguard.core.analysis.analysis` in a webbrowser (adjust `path/to/androguard`)

It looks like that your APK contains of two dex files. So the number of classes might actually be true. Did you add the support libaries? They alone are a few thousand classes...

**Comment by kaloon2009** [comment]
thanks reox, 
I'm sorry for late. when I tried to execute python setup.py build_sphinx , I got an error every time I was tried to fix it. 
I execute the command 
```
python setup.py build_sphinx
```

I got this result
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'build_sphinx'
```

Regarding to "Did you add the support libaries? "
 yes. I just create test app. My plan to test many of android app that available on google store. I stuck on this since last week. 
I just want to find if any app used specific API such as HTTPConnnection ? 
please any suggestion!

**Comment by reox** [comment]
have you shpinx installed? just try the following: pip install -U androguard[docs]

for the API specific stuff: If an API is used, it will show up in the dx object as a class (usually). That means you can just search for the class/method you like to find and check the xrefs.
