### ISSUE TITLE
Adaptive Icons

### ISSUE THREAD

**Issue by reox** [androguard/androguard#455]
an xml file is returned as icon, not an image file - what to do?

See PR #454 

* the xml file that is returnes looks actually to be correct
* but it will probably confuse the user if an xml file is returned and not an image file

**Comment by reox** [comment]
It would be possible to parse the adaptive icon file and create a png out of it... maybe this is total overkill

**Comment by reox** [comment]
okay it looks like that most apps should implement a fallback to png, if a lower resolution is used. So maybe the best way would be to check if an adaptive icon is used and try the lower dpi ranges.

**Comment by reox** [comment]
I could be wrong: but it looks like that Adaptive icons are loaded for a DPI >=65534
So if we patch get_app_icon to use a DPI with 65533, it would return a png.

**Comment by reox** [comment]
okay actually the dpi resolver is wrong :D the xml resource is marked as anydpi, thus it should always return this resource, for any dpi. But the resource has the API level set `anydpi-v26`. that means, that it should only be loaded on a v26 device.
I also added some tests in #456

**Comment by reox** [comment]
Could use https://gitlab.com/Hyperion777/VectorDrawable2Svg

**Comment by Bubu** [comment]
For F-Droid we'd be interested in having a way to get the fallback png icon. A good testcase for why this is sometimes complicated is K-9 mail as documented here: https://gitlab.com/fdroid/fdroidserver/issues/744#note_295316246
