### ISSUE TITLE
How to get Call graph using Androguard API

### ISSUE THREAD

**Issue by Skullflow** [androguard/androguard#464]
Hi,

i want to extract call graph of the entire application using only the API and i am using XREF in order to do it. In addition, i would distinguish external call from internal call. How can i do that?

I made a simple function that do the following:

```
# dalvik is DalvikVMFormat
for d in dalvik:
    classes = d.get_classes()
    for c in classes:
        methods = c.get_methods()
        for method in methods:
            # x is Analysis object
            method_class_analysis = x.get_method_analysis(method)
            xref_to = method_class_analysis.get_xref_to()
            #add method to graph
            #and for each method in xref_to: add method to graph and add edge
```
In the variable xref_to I can find methods of type EncodedMethod and ExternalMethod (i can distinguish external call from internal code based on this type), but when I iterate over method (for method in methods) I don't know if it is an external or internal one. This problem leads to an incorrect call graph.

Anyone can help?

Thanks.

**Comment by reox** [comment]
The methods inside a class are always internal.
I think you should use the Analysis object, from there on it is clear if the call is internal or external.

I just wrote a short demo how this could work:
```
from androguard.misc import AnalyzeAPK
from androguard.core.analysis.analysis import ExternalMethod
import matplotlib.pyplot as plt
import networkx as nx

a, d, dx = AnalyzeAPK("4e2201cde26141715255d2421f0bcfb1")

CFG = nx.DiGraph()

# Note: If you create the CFG from many classes at the same time, the drawing
# will be a total mess...
for m in dx.find_methods(classname="Lcom/elite/MainActivity;"):
    orig_method = m.get_method()
    print("Found Method --> {}".format(orig_method))
    # orig_method might be a ExternalMethod too...
    # so you can check it here also:
    if isinstance(orig_method, ExternalMethod):
        is_this_external = True
        # If this class is external, there will be very likely
        # no xref_to stored! If there is, it is probably a bug in androguard...
    else:
        is_this_external = False

    CFG.add_node(orig_method, external=is_this_external)

    for other_class, callee, offset in m.get_xref_to():
        if isinstance(callee, ExternalMethod):
            is_external = True
        else:
            is_external = False

        if callee not in CFG.node:
            CFG.add_node(callee, external=is_external)

        # As this is a DiGraph and we are not interested in duplicate edges,
        # check if the edge is already in the edge set.
        # If you need all calls, you probably want to check out MultiDiGraph
        if not CFG.has_edge(orig_method, callee):
            CFG.add_edge(orig_method, callee)

nx.draw_networkx(CFG)
plt.draw()
plt.show()
```

![figure_1](https://user-images.githubusercontent.com/431045/39084893-79ee5598-456b-11e8-8c27-a134b5a136dc.png)

Of course you need to figure out how to use the attribute of the node now...

**Comment by reox** [comment]
I just added for convenience a method to `MethodClassAnalysis` to check if the method is external. See PR #465

**Comment by Skullflow** [comment]
Maybe I miss an important thing for my analysis. I have to distinguish when a method call an android API or an external library API. Here, the ExternalMethod is a method from another class or is an API call?

**Comment by reox** [comment]
You can technically not decide if the call is an android API or something else. If the class is external, it simply means that there was no code for it in all DEX files that where present in the `Analysis` object at the time you did `create_xref()`. So it could be, that the class uses a class loader to load the missing classes at runtime or they are API methods.
Usually a good indicator if something is an API method might be to go by the name. They should all start with android - see https://developer.android.com/reference/packages.html

**Comment by reox** [comment]
That depends.

Let's say you are putting both class A and B inside a single DEX, then the call from A to B will never involve any external classes. 
if you put class A in classes.dex and B in classes1.dex, then you are required to add both dex files to `Analysis` in order to find the references.
If only classes.dex is loaded, B will be external, if only classes1.dex is loaded then A will be external.
If you load both dex files, it's back to normal and both classes are found.

Usually all the Android API classes and the java/javax stuff is not implemented inside the dex as it is available on the system, all those classes and methods end up as external.

**Comment by Skullflow** [comment]
Ok, i got it. Thanks, i will work on your code and i will use your suggestions!

**Comment by reox** [comment]
I just changed the code a little bit to get color for the methods:
```
from androguard.misc import AnalyzeAPK
from androguard.core.analysis.analysis import ExternalMethod
import matplotlib.pyplot as plt
import networkx as nx

a, d, dx = AnalyzeAPK("4e2201cde26141715255d2421f0bcfb1")

CFG = nx.DiGraph()

# Note: If you create the CFG from many classes at the same time, the drawing
# will be a total mess...
for m in dx.find_methods(classname="Lcom/elite/MainActivity;"):
    orig_method = m.get_method()
    print("Found Method --> {}".format(orig_method))
    # orig_method might be a ExternalMethod too...
    # so you can check it here also:
    if isinstance(orig_method, ExternalMethod):
        is_this_external = True
        # If this class is external, there will be very likely
        # no xref_to stored! If there is, it is probably a bug in androguard...
    else:
        is_this_external = False

    CFG.add_node(orig_method, external=is_this_external)

    for other_class, callee, offset in m.get_xref_to():
        if isinstance(callee, ExternalMethod):
            is_external = True
        else:
            is_external = False

        if callee not in CFG.node:
            CFG.add_node(callee, external=is_external)

        # As this is a DiGraph and we are not interested in duplicate edges,
        # check if the edge is already in the edge set.
        # If you need all calls, you probably want to check out MultiDiGraph
        if not CFG.has_edge(orig_method, callee):
            CFG.add_edge(orig_method, callee)

pos = nx.spring_layout(CFG)

internal = []
external = []

for n in CFG.node:
    if isinstance(n, ExternalMethod):
        external.append(n)
    else:
        internal.append(n)


nx.draw_networkx_nodes(CFG, pos=pos, node_color='r', nodelist=internal)
nx.draw_networkx_nodes(CFG, pos=pos, node_color='b', nodelist=external)
nx.draw_networkx_edges(CFG, pos, arrow=True)
nx.draw_networkx_labels(CFG, pos=pos, labels={x: "{} {}".format(x.get_class_name(), x.get_name()) for x in CFG.edge})
plt.draw()
plt.show()
```

![figure_1-1](https://user-images.githubusercontent.com/431045/39085574-4b38d8f0-4574-11e8-8d41-2cc13a721514.png)

This also shows something important: If you inherit a class and this class is for example an API class, all methods that are not overwritten are also external.
As you can see in the graph, there are methods like `startService` or `setContentView`, which are external (blue) but have the classname of an internal class.

**Comment by reox** [comment]
Btw can I ask what graphing package you are using? I find that those graphs I generated are not very readable... If you know a good visualization toolkit, we could directly implement this in androguard.

**Comment by Skullflow** [comment]
Im not using a visualization toolkit. I create the graphs and then i save them in gml format in order to be able to open it with Gephi or Cytoscape.

**Comment by reox** [comment]
networkx can write gml files, so I'll check those tools out! thanks!

**Comment by reox** [comment]
Yep, gephi looks quite good! If I have some time, I'll try to implement an CFG creating class that exports gml.

**Comment by reox** [comment]
Here is what I came up with gephi:

![2018-04-21-174546_1502x915_scrot](https://user-images.githubusercontent.com/431045/39086015-2081dc36-457b-11e8-9a74-e0d21cd0433f.png)

Just add at the end: `nx.write_gml(CFG, "test.gml", stringizer=str)`

**Comment by reox** [comment]
I used my code now to create a tool that would do that: #466 
Just call it like `androcfg.py -o somefile.gml yourapk.apk` to create the CFG for all methods.
I used the main activity only, as the graph is blowing up if you add everything (at least for files that use support libraries...)
But I think you can always filter later...

**Comment by reox** [comment]
Actually I just learned that this generates not a control flow graph (CFG) but only the call graph. 
Also if you put in all methods, you get a forest of call graphs... So I'll rename the tool toi androcg.py.

I also like to create a tool that extracts the actual control flow, which can be done by using the BasicBlocks...

**Comment by Skullflow** [comment]
That would be appreciated too. Also, IMHO in the androcg.py tools it would be useful to pass a list of attributes to assign them to the nodes.

Also, integrate other analysis like finding the entry points nodes ecc...

**Comment by reox** [comment]
yeah, isolated nodes can happen - for example the support libraries are probably not all used.
Otherwise it might be dead code or some Service/Activity/... which is only activated over some other mechanism.

Adding more attributes is a good idea!

**Comment by Skullflow** [comment]
Isolated nodes can be avoided in the graphs by suing this statement:
`if len(m.get_xref_to()) > 0: 
        CFG.add_node(orig_method, external=is_this_external)
`

**Comment by Skullflow** [comment]
Take in consideration all the nodes with in-degree == 0 as entry point?

Maybe use this method with some analysis will do the trick...

**Comment by Skullflow** [comment]
I'm using androcg.py to analyze a big APK. I don't know if this is an error but some nodes from the package Lcom/facebook/login/widget are external and some are internal.

How could it be possible?

In figure, yellow nodes are internal and the blue ones are external.
<img width="910" alt="schermata 2018-04-22 alle 13 18 52" src="https://user-images.githubusercontent.com/22097635/39094563-a514b2c8-4631-11e8-90cc-d35289629731.png">

**Comment by reox** [comment]
Looks like these are calls to inhertited methods from an class which is defined in the API.

Am 22. April 2018 13:33:34 MESZ schrieb Skullflow <notifications@github.com>:

**Comment by Skullflow** [comment]
So, if i can't use external node attribute to check if a node is an API call, i will retrieve the entire list of android package (from here as you suggested: https://developer.android.com/reference/packages.html) and then for each node i will check if the class contains at least one of these packages. Then i will update a node attribute (for example: is_api_call) to store a boolean for each node.

**Comment by Skullflow** [comment]
i suggest you to read this paper: https://arxiv.org/pdf/1612.04433.pdf. 

In particular the section "Abstracting Calls to Families/Packages"

**Comment by Skullflow** [comment]
It would be awesome if we could build a dictionary of API packages based on API level. Then, we can extract API level from the android manifest and using this information to use the correct list of packages in order to make this analysis.

**Comment by reox** [comment]
Yes, according to the paper, they just decided by the package name.
For a first test this would be sufficient i think.

Maybe @reddr can help here? Is there a way to extract all API methods and not just the ones that uses a permission?

**Comment by reox** [comment]
yeah, I thought about using the packages on maven to collect all support classes and other common libraries...

**Comment by Skullflow** [comment]
The support classes can be found here https://developer.android.com/reference/android/support/classes.html, am i right?

To find other libraries i don't know honestly... Using maven seems a good idea.

I'm reading the docs, in particular "androguard.core.bytecodes.apk.APK". I found the `get_libraries()` method: it returns a generator, but it is always empty...

**Comment by reox** [comment]
The `get_libraries` is used to retrieve lirabries that are defined in the AndroidManifest.
This is this stuff here: https://developer.android.com/guide/topics/manifest/uses-library-element.html

**Comment by reddr** [comment]
I just quickly skimmed over the topic. To answer reox question:
> Is there a way to extract all API methods and not just the ones that uses a permission?

Yes. For app analysis you typically add the android.jar from the SDK (in best case the one that matches the targetAPI level declared by the app. The SDK only contains the public API without implementation (stubs). You can load it separately and iterate over the public methods to retrieve the full set of the Android API.

**Comment by reox** [comment]
@reddr thanks for the reply! I had something like this already in mind... The question is now, how we can provide this data in androguard... Probably read the jar's and store the method names in a JSON, like we do with the permissions.

**Comment by reddr** [comment]
I wouldn't keep this data since it will be a prettly large list (per api level!) and the analysis overhead is negligible. It could be implemented as an optional parameter/argument for the analysis, i.e. path to androidsdk.jar . On WALA you can load app and SDK with different classloaders, then build an unified class hierarchy and distinguish classes based on the classloader. But for the sake of simplicity, the list can just be kept in memory. A simple helper function should then suffice to check whether it's an Android API or not.

**Comment by reox** [comment]
Okay I see an imediate show stopper here: https://developer.android.com/studio/terms.html
See especially point 3.4

So I would not put in the android jars into androguard...
I think making this part optional with providing the path to the jars seems to be a good idea.

**Comment by reddr** [comment]
Ah sorry, didn't mean that you should add the jars to androguard. Everybody can download the Android SDKs on their own, or even just download the jar files. I would simply add the functionality and the argument.

**Comment by reox** [comment]
I tried to come up now with a solution where to query for this API inside androguard... But there is a huge mess when it comes to MethodAnalysis, MethodClassAnalysis and EncodedMethod/ExternalMethod...
So first we need to fix those stuff before we can go further I think :/
references #412 #390

**Comment by reox** [comment]
@Skullflow have you seen the methods in androguard.misc? There is stuff to generate graphs based on methods... Unfortunately, only the dot format can be used there, but it's probably easily possible to use something like networkx instead and export in any format.

**Comment by Skullflow** [comment]
Yeah, i tried few days ago, but there are methods to generate the CONTROL FLOW GRAPH  and not the CALL GRAPH, am I right?

**Comment by reox** [comment]
yes! I also fixed androdd now, so you can probably use it to generate them easier... #476

**Comment by Skullflow** [comment]
Ok, but i need to generate call graph and not control flow graph...

**Comment by reox** [comment]
Ah okay, I thought you where interested in the CFG too.

**Comment by SamiraSadat** [comment]
> Hi,
> 
> i want to extract call graph of the entire application using only the API and i am using XREF in order to do it. In addition, i would distinguish external call from internal call. How can i do that?
> 
> I made a simple function that do the following:
> 
> ```
> # dalvik is DalvikVMFormat
> for d in dalvik:
>     classes = d.get_classes()
>     for c in classes:
>         methods = c.get_methods()
>         for method in methods:
>             # x is Analysis object
>             method_class_analysis = x.get_method_analysis(method)
>             xref_to = method_class_analysis.get_xref_to()
>             #add method to graph
>             #and for each method in xref_to: add method to graph and add edge
> ```
> In the variable xref_to I can find methods of type EncodedMethod and ExternalMethod (i can distinguish external call from internal code based on this type), but when I iterate over method (for method in methods) I don't know if it is an external or internal one. This problem leads to an incorrect call graph.
> 
> Anyone can help?
> 
> Thanks.

Hi.
i want to extract method calls from a dex file. similar to some first code you written, but the problem is that i can't run it in python environment. i start with 'androguard analyze' in cmd. then in a for loop starts to extract calls. it works good in cmd but how to run it in python shell?

**Comment by reox** [comment]
@SamiraSadat you just want to create a python script

**Comment by SamiraSadat** [comment]
> @SamiraSadat you just want to create a python script

Yeah, Thank you. I would ask you to tell me an example from method calls which is not API...?
As I understood he wants a way to extract **just** API calls; Not all of them. and according to your explanation, all the method calls from _Landriod_, _Ljava_ are API. So, which one of them are NOT API...?

**Comment by SamiraSadat** [comment]
@reox ,
@Skullflow,
Have you build the dictionary you mentioned in the comments...? I need something like that.

**Comment by umkhanqta** [comment]
@reox , 
@Skullflow ,
In this discussion you discuss the call graph and control flow graph.
I am able to construct the call graph with this help but now I need to get control flow graph of the specific method.
Kindly help me out,
