### ISSUE TITLE
Entry Point Detection 

### ISSUE THREAD

**Issue by reox** [androguard/androguard#470]
Detect wether a method is an entry point, for example onCreate in an activity

**Comment by reox** [comment]
The official doc says that these are all entry points:
* Activity
* Service
* BroadcastReceiver
* Content Providers

https://developer.android.com/guide/components/fundamentals.html#Components

Okay, so nothing new here... Thus we should detect entry points by the class and probably not by the method... Or at least all public methods inside such a class might be used as entry point.

**Comment by reox** [comment]
There is a problem here: If 
`class A extends someProvider`
and
`class someProvider extandroid.content.ContentProvider` 
but `someProvider` is actually some API class - there is no chance to check if `A` is a child of `ContentProvider`.

**Comment by Skullflow** [comment]
Any news about entry point detection?

**Comment by reox** [comment]
No not really... At the moment I'm using the information from the manifest.
