### ISSUE TITLE
Can I use androguard to compare the difference between two APKs now?

### ISSUE THREAD

**Issue by miniminiwhite** [androguard/androguard#474]
For some reasons I want to compare the difference between two APK files at source code level. I googled and found that androguard had a similar function before, but I can't find that tool in current version somehow.

So my question is, can androguard tell the difference between two APKs? If so, which tool shall I use and if not, are there any androguard methods or tools can help me achieve it?

**Comment by miniminiwhite** [comment]
I also found in androdiff.py that you used a module called _diff_.
Would someone please provide some more information about that module?

**Comment by reox** [comment]
androdiff used the elsim module, which was removed from androguard in version ~1.9 (?)

such a functionalitiy can be replicated by hashing all methods using a similarity preserving hash, like ssdeep or mvHash-B and comparing them to each other.

If you are interessted in elsim, I filter branched it from the last working version: https://github.com/reox/elsim

Maybe you can try to make it working again with the newest version, but as the Analysis module has changed, it might be a hard and stony way.

**Comment by miniminiwhite** [comment]
Got it. Thanks for help. 
:)
