### ISSUE TITLE
andromercury.py is obsolete and broken

### ISSUE THREAD

**Issue by Nikoli** [androguard/androguard#50]
andromercury.py is using ```from merc.lib.common import Session``` , https://code.google.com/p/androguard/wiki/Installation suggests downloading it from http://labs.mwrinfosecurity.com/tools/2012/03/16/mercury/downloads/ , but this link redirects to https://www.mwrinfosecurity.com/products/drozer/community-edition/

Seems upstream renamed mercury to drozer and most likely did a lot other changes to it, so http://androguard.blogspot.fr/2012/03/androguard-mercury.html is obsolete too.

**Comment by subho007** [comment]
The old version "mercury" works perfectly, but it seems, they have shifted to newer version. Looping in the Drozer developer here, so that we can discuss if there is any possible integration of Drozer with the current androguard.
CC @metall0id @dbradberry

**Comment by adesnos** [comment]
no more supported.
