### ISSUE TITLE
Large memory occupation when using AnalyzeAPK

### ISSUE THREAD

**Issue by miniminiwhite** [androguard/androguard#500]
I'm trying analysing multiple applications with Androguard by writing some scripts, and found that Androguard has a huge memory overhead after multiple applications have been analysed.

I checked other issues and found this [Issue #461](https://github.com/androguard/androguard/issues/461). According to your response, this is caused due to the session used, right?

So, does it mean I can box a self-defined class with class session, and dump the analysed application data or even reset the whole session when necessary, to better utilise my memory?

**Comment by reox** [comment]
Can you post the code here you are using? Are you using the session currently?
I changed the behaviour of AnalyzeAPK to not use a session at all, if the session argument is None.

**Comment by miniminiwhite** [comment]
oh I see... I just checked the latest repo, I am using an old version.

Anyway I managed to fix the problem by myself. As you mentioned, session can lead to faster analysis, so I still use it in my code, and every time I finish analysing an app I dump it from the session.

The session still keeps huge memory even after I delete elements from the session, I did some test and found it was caused by python's OrderedDict. 

In session class, member variable *analyzed_files*, *analyzed_files* and *analyzed_files* are OrderedDicts. Somehow when contents are deleted from these three members, python holds their part of memory. Therefore my solution is to save the contents I want to keep first, rebuild those three OrderedDicts completely then put the desired contents back.

Don't know if you're going to add some methods like "delete" to class *session*, hope this helps a bit if you have such a plan.

**Comment by miniminiwhite** [comment]
BTW python frees the memory OrderedDict occupies once it is rebuild or the whole OrderedDict get deleted, but has latency releasing memory when part of the key-val pair is removed.
↑ sad and don't know why. At least the python on my laptop behaves so. It's of version 3.6.5.

**Comment by reox** [comment]
I learned some days ago, that in never versions of python, dicts are actually ordered dicts... so I'll change them to normal dicts!

**Comment by miniminiwhite** [comment]
I also learned it when I was figuring out the problem. To be strict, this is kind of a side effect in 3.6 but will be a feature in 3.7

If we are really relying on the order in those member variables, maybe it's better to just add an annotation to the code first? 

Look forward to updating anyway. XD

**Comment by reox** [comment]
I think the session module needs a big cleanup anyways... See #437 
Personally I'm not using the session module at all - so I'm not sure if the ordereddict is needed for any special purpose (it is or was probably)

**Comment by miniminiwhite** [comment]
I myself use it because it boxes some useful attributes to me, like apk and vm. Plus it acts well as a cache in my scenarios, where multiple apps need to be compared.

Thank you for your time!

**Comment by reox** [comment]
If you like, work on the session object and send in a PR :) I have collected some tasks in the ticket #437

**Comment by miniminiwhite** [comment]
Would be glad to :)

**Comment by cyberalt1** [comment]
Still an issue in 2025. Please re-open.
