### ISSUE TITLE
resources and manifest

### ISSUE THREAD

**Issue by reox** [androguard/androguard#503]
We should think about a context aware AXML parser, which can handle resources on the fly.
As basically everything inside an XML can be sourced from the resources, this would be really useful.
There are several places in the code, where the values are not checked if they are resources. This means that the code gives wrong results.

Also related to #266

**Comment by eighthave** [comment]
One thing to keep in mind here is the possibility of "renaming the manifest package" which makes getting the actual value of things in the manifest a bit trickier.  Luckily, its not so common, but I think its more common in malware:  https://github.com/iBotPeaches/Apktool/issues/363

**Comment by eighthave** [comment]
For example, I had to do this to handle _rename-manifest-package_:

```python
     icon_id_str = apkobject.get_element("application", "icon")
     if icon_id_str:
         icon_id = int(icon_id_str.replace("@", "0x"), 16)
        resource_id = arsc.get_id(apk['packageName'], icon_id)
        if resource_id:
            icon_name = arsc.get_id(apk['packageName'], icon_id)[1]
        else:
            icon_name = os.path.splitext(os.path.basename(apkobject.get_app_icon()))[0]
         apk['icons_src'] = _get_apk_icons_src(apkfile, icon_name)
```
