### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [androguard/androguard#507]
Can i submit my design ?

**Comment by reox** [comment]
sure!

**Comment by subho007** [comment]
This is interesting 😄

**Comment by reox** [comment]
I think you can... read the guidelines for the python logo: https://www.python.org/community/logos/

btw have you seen the current logo? https://github.com/androguard/androguard/blob/master/docs/androguard.png

**Comment by loydjayme25** [comment]
This will be the Banner of the Project

![banner](https://user-images.githubusercontent.com/37318022/39763840-c5aa8184-5310-11e8-8e3b-6d36490a1eff.png)

**Comment by reox** [comment]
Nice! I like those!

Maybe give them a little bit more depth?

I also had a funny idea: why not give one of the snakes the android robot's head? :D

**Comment by reox** [comment]
@androguard/external-contributors what do you think?

**Comment by loydjayme25** [comment]
i also have that Idea but I think its too complex to change the snake into android head... can I submit a pull request for this ?

**Comment by reox** [comment]
Sure! Can you change it in the docs and maybe add it to the readme as well? Maybe there are other places too...

**Comment by loydjayme25** [comment]
Okay sir , Many thanks !

**Comment by loydjayme25** [comment]
I already sent a Pull Request, and i updated the ReadMe by adding a banner on it. Thanks !

**Comment by loydjayme25** [comment]
please do check my pull request, ive changed the banner into a bigger one to have a nice view of the project.

**Comment by eighthave** [comment]
any icon is fine by me.  Here's my two bits on this design: the Android
icon should be partially obscured by the Python icon to give the
impression that the Python is standing in front of the Android.  Right
now, it looks more like a little Android is standing on the Python.

**Comment by subho007** [comment]
I agree with @eighthave 

Although I am ok with any logo 😃

**Comment by loydjayme25** [comment]
so what should be the best idea for the logo ? so that i can have a new design for it.

**Comment by loydjayme25** [comment]
can i submit another logo ? because i made a wrong one that against the rules of python.

**Comment by reox** [comment]
sure!

**Comment by loydjayme25** [comment]
How about this ?
Cleaner look, and there are some part that is similar to the current logo.

![proposals](https://user-images.githubusercontent.com/37318022/40003359-b5245808-57c5-11e8-920f-6139c3615b18.png)

**Comment by reox** [comment]
Looks also very good!

**Comment by reox** [comment]
can you create a new PR with the new logo? Do you have vector graphics of the logo as well?

**Comment by loydjayme25** [comment]
Okay sir, i am very sorry for a late response.  I will send a PR after my class. Been so busy about my studies , i hope you understand

**Comment by reox** [comment]
No problem! studies go first :)

Just send your PR when you are ready!

**Comment by loydjayme25** [comment]
Many thanks for understanding sir, i will make it as soon as i have free time. i am very busy because i am a graduating student, thank you so much sir.

**Comment by loydjayme25** [comment]
Files are ready, how can i send it sir or i will make a new PR ?

**Comment by loydjayme25** [comment]
I already Updated the PR. pls do check it sir, many thanks !
