### ISSUE TITLE
Subject fields are not reported in showing certificate information

### ISSUE THREAD

**Issue by gurol** [androguard/androguard#512]
show_Certificate() function in apk.py displays issuer information instead of the subject information.

```
print("Issuer: {}".format(get_certificate_name_string(cert.issuer.native, short=short)))
print("Subject: {}".format(get_certificate_name_string(cert.issuer.native, short=short)))

```

The second print function's parameter should be `cert.subject.native`?

### System Information

- Androguard Version: 3.2.0
- Python Version: 2.7/3.5
- Operating System: macOS

**Comment by reox** [comment]
yes thats right! Can you create a PR for this fix?
