### ISSUE TITLE
Stop LinearSweepAlgorithm from yielding opcodes on error instead of raising exceptions

### ISSUE THREAD

**Issue by thecrackofdawn** [androguard/androguard#519]
Now androguard will raise `InvalidInstruction` when invalid instruction  is encountered. Is it designed in this way? I think as analysis tool androguard should parse the target file as much as possible instead of exiting when invalid instruction is encountered.

**Comment by reox** [comment]
Do you have an example file for this behaviour?

**Comment by thecrackofdawn** [comment]
The sample is a malware and I'm not supposed to share the apk file for some reasons, but here is its link in [virustotal](https://www.virustotal.com/en/file/fd31e989ea167a64af2ab1ee27b133cf7a15e74a1a67535981f62569acfbf60b/analysis/).

However I have found out what causes androguard's exception. Here is the log and traceback.
```
2018-05-28 17:42:09,925 [DEBUG   ] androguard.analysis (analysis.py): Creating basic blocks in Landroid/support/v4/os/e;->newArray(I)[Ljava/lang/Object; [access_flags=public] @ 0x76254
2018-05-28 17:42:09,925 [DEBUG   ] androguard.analysis (analysis.py): Parsing instructions
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
C:\androguard\androguard\core\bytecodes\dvm.py in get_extented_instruction(cm, op_value, buff)
   6328     try:
-> 6329         return DALVIK_OPCODES_EXTENDED_WIDTH[op_value][0](cm, buff)
   6330     except struct.error:

C:\androguard\androguard\core\bytecodes\dvm.py in __init__(self, cm, buff)
   5786         self.OP = unpack("=H", buff[0:2])[0]
-> 5787         self.BBBBBBBB = unpack("=I", buff[2:6])[0]
   5788

error: unpack requires a bytes object of length 4

During handling of the above exception, another exception occurred:

InvalidInstruction                        Traceback (most recent call last)
<ipython-input-5-ab4d2306b072> in <module>()
----> 1 h, d, dx = AnalyzeDex(r"C:\Users\Ford_Qin\Desktop\classes.dex")

C:\androguard\androguard\misc.py in AnalyzeDex(filename, session)
     97         data = fd.read()
     98
---> 99     return session.addDEX(filename, data)
    100
    101

C:\androguard\androguard\session.py in addDEX(self, filename, data, dx)
    127             dx = Analysis()
    128
--> 129         dx.add(d)
    130         dx.create_xref()
    131

C:\androguard\androguard\core\analysis\analysis.py in add(self, vm)
    942
    943         for method in vm.get_methods():
--> 944             self.methods[method] = MethodAnalysis(vm, method)
    945
    946     def _get_all_classes(self):

C:\androguard\androguard\core\analysis\analysis.py in __init__(self, vm, method)
    284         self.code = self.method.get_code()
    285         if self.code:
--> 286             self._create_basic_block()
    287
    288     def _create_basic_block(self):

C:\androguard\androguard\core\analysis\analysis.py in _create_basic_block(self)
    297
    298         log.debug("Parsing instructions")
--> 299         for i in bc.get_instructions():
    300             for j in BasicOPCODES:
    301                 if j.match(i.get_name()) is not None:

C:\androguard\androguard\core\bytecodes\dvm.py in get_instructions(self)
   6491             ins = lsa.get_instructions(self.CM, self.size, self.insn,
   6492                                           self.idx)
-> 6493             self.cached_instructions = list(ins)
   6494
   6495         for i in self.cached_instructions:

C:\androguard\androguard\core\bytecodes\dvm.py in get_instructions(self, cm, size, insn, idx)
   6393                 elif op_value in DALVIK_OPCODES_EXTENDED_WIDTH:
   6394                     try:
-> 6395                         obj = get_extented_instruction(cm, op_value, insn[idx:])
   6396                         classic_instruction = False
   6397                     except struct.error as why:

C:\androguard\androguard\core\bytecodes\dvm.py in get_extented_instruction(cm, op_value, buff)
   6329         return DALVIK_OPCODES_EXTENDED_WIDTH[op_value][0](cm, buff)
   6330     except struct.error:
-> 6331         raise InvalidInstruction("Invalid Instruction for 0x%x:%s" % (op_value, repr(buff)))
   6332
   6333

InvalidInstruction: Invalid Instruction for 0x14ff:bytearray(b'\xff\x14ad')
```
Here is the hex value in the related dex and the dex version is 035.
![ang](https://user-images.githubusercontent.com/6297397/40608647-ac2533ec-629e-11e8-9fcd-7475a12c365f.jpg)
we can see `insns_size` is 7 and the instructions androguard parsed for `insns` is:

`D4 B3 F2 B5` -> `<androguard.core.bytecodes.dvm.Instruction22s object at 0x000001AC20619A58`
`15 A2 FF 14` ->`<androguard.core.bytecodes.dvm.Instruction21h object at 0x000001AC206199B0> `
`F6 A3` -> `<androguard.core.bytecodes.dvm.InstructionInvalid object at 0x000001AC20619A20>`. 
So the last instructions in `insns` is `FF 14 61 64`. So the format for this op is `Instruction41c`. So the whole instructions should be 8 bytes long instead of 4. That's why we get the `error: unpack requires a bytes object of length 4`.

**Comment by reox** [comment]
Okay so the opcode sequence is `D4 B3 F2 B5 15 A2 FF 14 F6 A3 FF 14 61 64`, this looks good.
The first opcide `D4` is correct, the second `15` too. But `F6` is actually unused. I'm not sure what the correct behaviour would be then... probably this bytecode would crash?
The format of `F6` is defined as `10x` so it is a pure opcode with no arguments. In this case `A3` would be the next opcode, which does not match as then `64` would be the last opcode but has no arguments.

It looks like the opcodes are injected to crash analysis tools.
Can you try decompilation with other tools? What does they give as result?

I think we should implement the unused instructions as well, but then this bytecode is also not parseable...

**Comment by reox** [comment]
btw these extended width opcodes seem to be never used again by android? They are not shown in the official documentation anymore.
probably we can remove them from androguard completly...
does someone has more information about them?

**Comment by reox** [comment]
It looks like i can not download the sample from koodous (server timeout). But I changed the opcodes to unused. Can you try the changes in #520? probably there is more to do than just fixing the opcode table...

**Comment by reox** [comment]
okay this is interesting: If jeb thinks that `F6A3FF14` is this iput-wide-quick, what is then `6164`?
Opcode 61 is `sget-wide` and has one 8 bit and one 16bit argument. But I can only see the first 8bit argument in the opcode...

Would be interesting to see, if there are more samples using unused opcodes.
As the official documentation says they are unused (Is there any official doc with the wide opcodes still?) I would consider a usage of them as "malicious"... But I'm not sure how this can be implemented... 

I also noticed now, that when the true 10x format would be used, the second byte must be 0. But in this case it is A3...

**Comment by reox** [comment]
I had an idea: When encountering an unknown opcode, we could create a pseudoopcode which consumes the rest of the opcodes / everything until the next valid opcode / ...

Or come up with a more solid approach...

**Comment by thecrackofdawn** [comment]
Just skipping the invalid opcode instead of the whole method sounds good to me.  For now I just [skip the whole method](https://github.com/thecrackofdawn/androguard/commit/18d74d8f242eac37eddeba31df6a28e0fcd1e25a). On the other hands, I think it may be a good idea to do what AOSP does when encounters invalid opcode. I will check how AOSP parse dex when I have time.

**Comment by reox** [comment]
So I found other samples which do crazy stuff.
I extracted one function where this is the bytecode:
```
29 EC FF B4 C0 CC 82 B3 8B 98 C7 82 8D 14 52 7A 4B EB AB 49 E1 39 D6 06 C5 5F 9B D8 CB 1E 59 7B
79 D9 D5 79 86 42 B5 06 F3 5D 63 DB E2 5E 70 7B 18 CB 87 79 AA 39 8D 06 CA 5D 62 DB 9E 5E 70 7B
65 EB F3 67 BC 1B 85 15 FB 01 09 CA B6 5E 01 6B 52 EB DA 79 A2 38 8D 04 A6 5D 62 DB 9E 5E 72 7B
65 E9 B5 49 B8 39 87 04 FB 5C 7D EB E7 5E 74 7B 73 EB 13 79 DF 29 AC 06 D3 5D 1F CB 8D 2D 01 5B
34 EB DF 79 DF 29 CC 06 D7 5D 09 CB C9 5E 01 6B 52 EB DB 79 A2 39 F9 26 EC 5D 17 CB A9 5E 58 23
06 CB DA 79 FA 39 82 06 D0 22 7D EB E4 5E 74 7B 41 50 E3 79 9A 39 8D 06 C5 5D 62 DB 9E 5E 70 7B
65 EB AA 59 F3 39 93 06 B3 5D 13 CB 8D 5F 63 7A 67 EB EE 69 B4 39 F9 16 ED 5D 17 CB A9 5E 1E 6B
54 EB DF 79 A2 38 BF A9 C9 5C 17 CB D4 4E 4B 7B 68 EB D7 78 FA 7B 95 06 BD 6D 06 CB B5 5C 58 DD
07 AB FB 79 BE 0B F9 16 EF 5D 17 CB 87 5E 65 7B 19 FB F3 79 AE 39 BE 06 AF A2 31 CB AE 5E 6A 7A
78 EB AA 69 95 39 96 06 DF 5C 63 EB B7 5E 60 7B 41 37 AB 49 A4 39 D7 07 88 1D 11 CB F1 1E 71 7B
3D AA D9 79 C0 19 9F 06 C3 5D 19 CB 8D ED 6F 7B 6F EB 80 39 AF 39 BF 07 F1 5D 1B CB B9 5F 6F 7B
41 02 AA 59 F3 39 93 06 FB ED 71 1C DE 5D B0 1F DF DE 8D CD B8 30
```

As you can see, it starts with a invalid `goto/16` opcode, as the high byte of the opcode is `0xEC` and not `0x00`. The goto sends the interpreter to -19201 which is pretty out of bounds....
So I guess this would read as invalid and break the code.
After that follows other opcodes which makes no sense, including unimplemented ones like `0xf3`...

So this would be the perfect usecase for a parser which would simply stop and not raise exceptions.

sample: DEX file sha256: 0fac1afe04694862eb3154cdf7c7c13b72c5966e5f640120c52c69a7aa0f7727

**Comment by reox** [comment]
@thecrackofdawn btw have you investigated in the AOSP?

I was reading the old comments, and I think now that using pseudoopcodes might be the wrong way. I also have changed the unused opcodes to throw an error, as there is basically undefined behaviour ahead.
So from my current point of view, it would make sense to raise the InvalidInstruction exceptions but catch them in the LSA class and simply stop there processing and log errors.

**Comment by reox** [comment]
@thecrackofdawn i checked in a version where the processing stops instead of raising an exception

**Comment by thecrackofdawn** [comment]
@reox Sorry, I haven't investigated how the AOSP deal with the invalid opcode. 
I'm not sure where to find the version you checked in.

**Comment by reox** [comment]
@thecrackofdawn it is work in progress: #681
