### ISSUE TITLE
androsign.py

### ISSUE THREAD

**Issue by Cydia5530** [androguard/androguard#521]
on my computer, the following code can not exec...
    print("Issuer:", get_certificate_name_string(x509_cert.issuer, short=True))
    print("Subject:", get_certificate_name_string(x509_cert.subject, short=True))
But previous code can exec normally
   print("Issuer:", x509_cert.issuer.human_friendly)
   print("Subject:", x509_cert.subject.human_friendly)

is there something wrong?

**Comment by reox** [comment]
do you get an error message?

**Comment by Cydia5530** [comment]
Environmient info:
    python                      3.6
    androguard              3.2.0
    asn1crypto               0.24.0

Traceback info:
  Traceback (most recent call last): 
     File "C:/Users/yidia/Desktop/TestApp/pytest/andro.py", line 68, in <module>
         main()
     File "C:/Users/yidia/Desktop/TestApp/pytest/andro.py", line 30, in main
         getSign()
     File "C:/Users/yidia/Desktop/TestApp/pytest/andro.py", line 45, in getSign
          print("Issuer:", get_certificate_name_string(x509_cert.issuer, short=True))
     File "E:\Anaconda1\envs\py36\lib\site-packages\androguard\util.py", line 49, in 
             get_certificate_name_string
           return ", ".join(["{}={}".format(_.get(attr,(attr,attr))[0 if short else 1], name[attr]) for attr in name])
      TypeError: 'Name' object is not iterable

I debugged step by step, think it seems like the function "get_certificate_name_string", there is no attr name issuer in all the attrs.
_ = {
        'business_category' : ("businessCategory", "businessCategory"),
        'serial_number' : ("serialNumber", "serialNumber"),
        'country_name' : ("C", "countryName"),
        'postal_code' : ("postalCode", "postalCode"),
        'state_or_province_name' : ("ST", "stateOrProvinceName"),
        'locality_name' : ("L", "localityName"),
        'street_address' : ("street", "streetAddress"),
        'organization_name' : ("O", "organizationName"),
        'organizational_unit_name' : ("OU", "organizationalUnitName"),
        'title' : ("title", "title"),
        'common_name' : ("CN", "commonName"),
        'initials' : ("initials", "initials"),
        'generation_qualifier' : ("generationQualifier", "generationQualifier"),
        'surname' : ("SN", "surname"),
        'given_name' : ("GN", "givenName"),
        'name' : ("name", "name"),
        'pseudonym' : ("pseudonym", "pseudonym"),
        'dn_qualifier' : ("dnQualifier", "dnQualifier"),
        'telephone_number' : ("telephoneNumber", "telephoneNumber"),
        'email_address' : ("E", "emailAddress"),
        'domain_component' : ("DC", "domainComponent"),
        'name_distinguisher' : ("nameDistinguisher", "nameDistinguisher"),
        'organization_identifier' : ("organizationIdentifier", "organizationIdentifier"),
    }

**Comment by reox** [comment]
Okay thanks for the feedback - I still can not reproduce this with samples I own. Can you share the sample that causes this bug? Or is it for every sample you use?

**Comment by Cydia5530** [comment]
oh，This is my test sample. And others apk cannot works well. 
https://github.com/Cydia5530/apkInfo/blob/master/test.apk
https://github.com/Cydia5530/apkInfo/blob/master/hello-world.apk

**Comment by reox** [comment]
Both samples work for me:
master:

```
$ python3 androsign.py --show --all ~/Downloads/test.apk
test.apk, package: 'com.hx.mianliu'
Is signed v1: True
Is signed v2: False
Found 1 unique certificates
Issuer: C=CN, ST=Kd, L=Rsw, O=Tencent, OU=Tencent, CN=hx
Subject: C=CN, ST=Kd, L=Rsw, O=Tencent, OU=Tencent, CN=hx
Serial Number: 0x736650e5
Hash Algorithm: sha256
Signature Algorithm: rsassa_pkcs1v15
Valid not before: 2017-09-14 16:58:21+00:00
Valid not after: 2839-01-28 16:58:21+00:00
md5 ed6f316ca52d6a5a7aa903cf3b2d549a
sha1 b82e33ade0d0002cd8544ea34bc4de1bddc9b045
sha256 2d0d96263dafc2bae08c3dc4cfa5ee4ec07c32b0ca8b955b52ee4df51702a01c
sha512 5e5d3e26e5116e203bf04f72bd1a7d806e95432d177d7586020e41aa5b6b504872336f4568e04b89d4ddd52f166de96e6640adab298024207729d02850b1af04

$ python3 androsign.py --show --all ~/Downloads/hello-world.apk 
hello-world.apk, package: 'de.rhab.helloworld'
Is signed v1: True
Is signed v2: True
Found 1 unique certificates
Issuer: C=DE, ST=Hessen, L=Frankfurt, O=RHAB, OU=KeyStore, CN=Robert Habermann
Subject: C=DE, ST=Hessen, L=Frankfurt, O=RHAB, OU=KeyStore, CN=Robert Habermann
Serial Number: 0x3d75a604
Hash Algorithm: sha256
Signature Algorithm: rsassa_pkcs1v15
Valid not before: 2016-12-29 13:16:54+00:00
Valid not after: 2041-12-23 13:16:54+00:00
md5 2487974b62a94eaa8254b95dd8ce8fc7
sha1 652f6129c87d0540bf986fc00efd9ab8a78784de
sha256 6e566427da36dd913639b1112f747b77408851b4857a1d63ebf91e02b06f2088
sha512 b1d5626db96375a52f21df846baf7d379e644f36e383505038106c50514d5ed5f71a568fed5065a807528a07ae80a98e35d54527f967290cfdad336dba9101b4
```

fresh virtualenv with androguard 3.2.0 release
```
$ androsign.py --show --all ~/Downloads/test.apk 
test.apk, package: 'com.hx.mianliu'
Is signed v1: True
Is signed v2: False
Found 1 unique certificates
Issuer: Common Name: hx, Organizational Unit: Tencent, Organization: Tencent, Locality: Rsw, State/Province: Kd, Country: CN
Subject: Common Name: hx, Organizational Unit: Tencent, Organization: Tencent, Locality: Rsw, State/Province: Kd, Country: CN
Serial Number: 0x736650e5
Hash Algorithm: sha256
Signature Algorithm: rsassa_pkcs1v15
Valid not before: 2017-09-14 16:58:21+00:00
Valid not after: 2839-01-28 16:58:21+00:00
md5 ed6f316ca52d6a5a7aa903cf3b2d549a
sha1 b82e33ade0d0002cd8544ea34bc4de1bddc9b045
sha256 2d0d96263dafc2bae08c3dc4cfa5ee4ec07c32b0ca8b955b52ee4df51702a01c
sha512 5e5d3e26e5116e203bf04f72bd1a7d806e95432d177d7586020e41aa5b6b504872336f4568e04b89d4ddd52f166de96e6640adab298024207729d02850b1af04

$ androsign.py --show --all ~/Downloads/hello-world.apk 
hello-world.apk, package: 'de.rhab.helloworld'
Is signed v1: True
Is signed v2: True
Found 1 unique certificates
Issuer: Common Name: Robert Habermann, Organizational Unit: KeyStore, Organization: RHAB, Locality: Frankfurt, State/Province: Hessen, Country: DE
Subject: Common Name: Robert Habermann, Organizational Unit: KeyStore, Organization: RHAB, Locality: Frankfurt, State/Province: Hessen, Country: DE
Serial Number: 0x3d75a604
Hash Algorithm: sha256
Signature Algorithm: rsassa_pkcs1v15
Valid not before: 2016-12-29 13:16:54+00:00
Valid not after: 2041-12-23 13:16:54+00:00
md5 2487974b62a94eaa8254b95dd8ce8fc7
sha1 652f6129c87d0540bf986fc00efd9ab8a78784de
sha256 6e566427da36dd913639b1112f747b77408851b4857a1d63ebf91e02b06f2088
sha512 b1d5626db96375a52f21df846baf7d379e644f36e383505038106c50514d5ed5f71a568fed5065a807528a07ae80a98e35d54527f967290cfdad336dba9101b4
```


What commandline options are you using?

**Comment by Cydia5530** [comment]
i used https://github.com/androguard/androguard/blob/master/androsign.py
when i modify the code in  this file 
      print("Issuer:", get_certificate_name_string(x509_cert.issuer, short=True))
to 
     print("Issuer:", get_certificate_name_string(x509_cert.issuer.native, short=True))

the result finally become a pretty formate ：
Issuer: C=CN, ST=Kd, L=Rsw, O=Tencent, OU=Tencent, CN=hx (this is a more commen form for cert 'issuer, i think )

When i debug the code , ‘’get_certificate_name_string“ need a dict para.  sorry, i didn’t read the code careful.
