### ISSUE TITLE
Create a new logo design

### ISSUE THREAD

**Issue by VhanIrving11** [androguard/androguard#523]
The project has already a logo design, but i am willing to add something new. can i submit my logo design ?

**Comment by loydjayme25** [comment]
hey @VhanIrving11 , if you think this will be + good the the project. feel free to do it, i am fine that you will also help improve the androguard.

**Comment by VhanIrving11** [comment]
thank you sir @loydjayme25

**Comment by reox** [comment]
If you like, maybe you can tackle these tasks:
* change logo in readthedocs
* change logo in gui
* create favicon and change in gui
* add logo/banner to pypi

**Comment by VhanIrving11** [comment]
does my design fits to the project ?

![proposals](https://user-images.githubusercontent.com/39739005/40872260-da37168c-667d-11e8-999c-78ce1cf5b6e4.png)
