### ISSUE TITLE
Implicit call tracing in xref creation

### ISSUE THREAD

**Issue by coffezhou** [androguard/androguard#532]
The current call graph maybe incomplete. 
Fro example, in the following code snippet, I think that the method onCreate() will invoke method procedure() which invokes methods download() and activate(). However, when I obtain the call graph, I 
find that onCreate() only invokes an initialize function AlertActivity$1;-><init>, which is generated by the compiler (I guess). 
The smali code show that the method procedure() is invoked by method run(), but there does not exist an edge between onCreate() and run(). So, is there necessary to add an edge between onCreate() and run(), such that there is a relationship like onCreate()->run()->procedure()->download()/activates()?

code snippet of [Dropdialer.apk](https://github.com/ashishb/android-malware/tree/master/BreakBottleneck/SamplesOfHIP2014TalkBreakBottleneck/Dropdialer.A) 

`public class AlertActivity extends Activity {

    protected void onCreate(Bundle savedInstanceState) {
        
        this.workThread = new Thread(new Runnable() {
            public void run() {
                AlertActivity.this.procedure();
                Log.d("Thread", "end thread");
                AlertActivity.this.handler.sendEmptyMessage(0);
            }
        });
    }

    public void procedure() {
        download("http://dl.dropbox.com/u/87265868/srv.txt", "srv.txt");
        activate(parse("srv.txt"));
        Log.d("procedure", "end");
    }

    public void download(String inurl, String name) {
       
    }

    public void activate(String activateCode) {
        
    }
}`

**smali code (simplified)**
`.class AlertActivity$1;

 direct methods
.method constructor <init>(AlertActivity;)V
    .locals 0

    .prologue
    .line 1
    iput-object p1, p0, AlertActivity$1;->this$0:AlertActivity;

    .line 133
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

 virtual methods
.method public run()V
    .locals 2

    .prologue
    .line 137
    iget-object v0, p0, AlertActivity$1;->this$0:AlertActivity;

    invoke-virtual {v0}, AlertActivity;->procedure()V

.end method
`

**Comment by reox** [comment]
It looks like the call between onCreate() and run() is never found as run() is never called explicitly and is also "hidden" inside the anoymous Runnable object.
Inside `onCreate` there is this bytecode:
```
      58 (0x00000118) new-instance                   v0, Ljava/lang/Thread;
      59 (0x0000011c) new-instance                   v1, Lcom/nnew/superMariowallpapers/AlertActivity$5;
      60 (0x00000120) invoke-direct                  v1, v3, Lcom/nnew/superMariowallpapers/AlertActivity$5;-><init>(Lcom/nnew/superMariowallpapers/AlertActivity;)V
      61 (0x00000126) invoke-direct                  v0, v1, Ljava/lang/Thread;-><init>(Ljava/lang/Runnable;)V
      62 (0x0000012c) iput-object                    v0, v3, Lcom/nnew/superMariowallpapers/AlertActivity;->workThread Ljava/lang/Thread;
```

So, the call to the constructor is recorded but not the run, as it is called implictly by the Thread.

Maybe we can add an implicit call tracer to `_create_xref`... But this will take some time.

**Comment by reox** [comment]
Btw are there other implicit calls? Would be nice to record them in such a way:

```
Classname, methodname, object type, called method
Ljava/lang/Thread; <init>, Ljava/lang/Runnable; run
...
```

**Comment by coffezhou** [comment]
Thanks for your reply and these nice works!
Actually, there are five implicit calls in methods onCreate() of class _AlertActivity_ of [Dropdialer.apk](https://github.com/ashishb/android-malware/tree/master/BreakBottleneck/SamplesOfHIP2014TalkBreakBottleneck/Dropdialer.A), they are:
`[Lcom/nnew/superMariowallpapers/AlertActivity; onCreate(),
 Landroid/view/View$OnClickListener; onClick]`
`[Lcom/nnew/superMariowallpapers/AlertActivity; onCreate(), 
Landroid/view/View$OnClickListener; onClick]`
`[Lcom/nnew/superMariowallpapers/AlertActivity; onCreate(), Landroid/content/DialogInterface$OnClickListener; onClick]`
`[Lcom/nnew/superMariowallpapers/AlertActivity; onCreate(), Landroid/os/Handler; handleMessage]`
`[Lcom/nnew/superMariowallpapers/AlertActivity; onCreate(), Ljava/lang/Runnable; run]`

These implicit calls are caused by creating a new object using keyword **new**. For instance, the implicit call between onCreate() and  run() is caused by the following code snippet.

```
this.workThread = new Thread(new Runnable() {
            public void run() {
                AlertActivity.this.procedure();
                Log.d("Thread", "end thread");
                AlertActivity.this.handler.sendEmptyMessage(0);
            }
        });
```
In this case, the compiler will generate an auxiliary class like _AlertActivity$5_. So, a solution is to add edges from onCreate() to all methods in auxiliary class  _AlertActivity$5_.

**Comment by reox** [comment]
> So, a solution is to add edges from onCreate() to all methods in auxiliary class AlertActivity$5.

Is it a good idea to use all methods? I think one can gather a list of all implicit calls and create the correct edge. Of course, you need to know all implicit calls beforehand, which might be quite hard.
But it should be possible to implement such a system.

But then there are again new problems: What about conditional implicit calls like callbacks?

**Comment by reox** [comment]
please leave this open, maybe we can implement this some day
