### ISSUE TITLE
Redirect androlyze output to file

### ISSUE THREAD

**Issue by scaruso** [androguard/androguard#533]
Hi,

I'm sorry to write here but I do not know where else to do it.

I run this command:
`In [16]: d.get_class('Lcom/prime31/AdMobPlugin;').source()`

and I obtain this:
`package com.prime31;
public class AdMobPlugin extends com.prime31.AdMobPluginBase implements com.google.ads.AdListener {
    private String _adUnitId;
    private com.google.ads.InterstitialAd _interstitial;
    private com.google.ads.AdView _adView;
    private java.util.Set _testDevices;
    public AdMobPlugin()
    {
        this._testDevices = new java.util.HashSet();
        return;
    }
    static synthetic com.google.ads.AdView access$0(com.prime31.AdMobPlugin p1)
    {
        return p1._adView;
    }
    static synthetic void access$1(com.prime31.AdMobPlugin p0, com.google.ads.AdView p1)
    {
        p0._adView = p1;
        return;
    }
    static synthetic java.util.Set access$2(com.prime31.AdMobPlugin p1)
    {
        return p1._testDevices;
    }
    static synthetic com.google.ads.InterstitialAd access$3(com.prime31.AdMobPlugin p1)
    {
        return p1._interstitial;
    }
    static synthetic void access$4(com.prime31.AdMobPlugin p0, com.google.ads.InterstitialAd p1)
    {
        p0._interstitial = p1;
        return;
    }
    public void createBanner(String p5, int p6, int p7)
    {
        if ((this._adUnitId != 0) || (p5 != 0)) {
            if ((p5 == 0) || ((p5 == "") || (p5.length() <= 5))) {
                v0 = this._adUnitId;
            } else {
                v0 = p5;
            }
            android.util.Log.i("Prime31", new StringBuilder("using adUnitId: ").append(v0).toString());
            this.getActivity().runOnUiThread(new com.prime31.AdMobPlugin$1(this, p6, v0, p7));
        } else {
            android.util.Log.i("Prime31", "You cannot request a banner without first calling init!");
        }
        return;
    }
    public void createBannerLegacy(int p2, int p3)
    {
        this.createBanner(0, p2, p3);
        return;
    }
    public void destroyBanner()
    {
        if (this._adView != 0) {
            this.getActivity().runOnUiThread(new com.prime31.AdMobPlugin$2(this));
        }
        return;
    }
    public void displayInterstital()
    {
        if (this._interstitial != 0) {
            this.getActivity().runOnUiThread(new com.prime31.AdMobPlugin$6(this));
        }
        return;
    }
    public float getAdViewHeight()
    {
        if (this._adView != 0) {
            v0 = ((float) this._adView.getHeight());
        } else {
            v0 = 0;
        }
        return v0;
    }
    public void hideBanner(boolean p3)
    {
        if (this._adView != 0) {
            this.getActivity().runOnUiThread(new com.prime31.AdMobPlugin$3(this, p3));
        }
        return;
    }
    public boolean isInterstitalReady()
    {
        if (this._interstitial != 0) {
            v0 = this._interstitial.isReady();
        } else {
            v0 = 0;
        }
        return v0;
    }
    public void onDismissScreen(com.google.ads.Ad p4)
    {
        this.UnitySendMessage("AdMobAndroidManager", "dismissingScreen", "");
        android.util.Log.d("Prime31", "adView: onDismissScreen");
        return;
    }
    public void onFailedToReceiveAd(com.google.ads.Ad p4, com.google.ads.AdRequest$ErrorCode p5)
    {
        this.UnitySendMessage("AdMobAndroidManager", "failedToReceiveAd", String.valueOf(p5));
        android.util.Log.d("Prime31", new StringBuilder("onFailedToReceiveAd. errorCode: ").append(String.valueOf(p5)).toString());
        return;
    }
    public void onLeaveApplication(com.google.ads.Ad p4)
    {
        this.UnitySendMessage("AdMobAndroidManager", "leavingApplication", "");
        android.util.Log.d("Prime31", "adView: onLeaveApplication");
        return;
    }
    public void onPresentScreen(com.google.ads.Ad p4)
    {
        this.UnitySendMessage("AdMobAndroidManager", "presentingScreen", "");
        android.util.Log.d("Prime31", "adView: presentingScreen");
        return;
    }
    public void onReceiveAd(com.google.ads.Ad p4)
    {
        this.UnitySendMessage("AdMobAndroidManager", "receivedAd", "");
        android.util.Log.d("Prime31", "adView: onReceiveAd");
        return;
    }
    public void refreshAd()
    {
        if (this._adView != 0) {
            this.getActivity().runOnUiThread(new com.prime31.AdMobPlugin$4(this));
        }
        return;
    }
    public void requestInterstital(String p3)
    {
        this.getActivity().runOnUiThread(new com.prime31.AdMobPlugin$5(this, p3));
        return;
    }
    public void setPublisherId(String p1)
    {
        this._adUnitId = p1;
        return;
    }
    public void setTestDevices(String[] p5)
    {
        android.util.Log.i("Prime31", new StringBuilder("setting: ").append(String.valueOf(p5.length)).append(" test devices").toString());
        v0 = 0;
        while (v0 < p5.length) {
            if (this._testDevices.contains(p5[v0]) == 0) {
                this._testDevices.add(p5[v0]);
            }
            v0++;
        }
        android.util.Log.i("Prime31", new StringBuilder("total test devices: ").append(this._testDevices.size()).toString());
        return;
    }
}`

There is a way to redirect the output (though there isn't a `Out[i]`) to a file?

**Comment by reox** [comment]
just use some python foo:
```
with open("output.file", "w") as fp:
    fp.write(d.get_class('Lcom/prime31/AdMobPlugin;').source())
```
