### ISSUE TITLE
How to retrieve smali code from APK

### ISSUE THREAD

**Issue by Skullflow** [androguard/androguard#536]
Is there a way to retrive smali code from an APK?

**Comment by reox** [comment]
See #341 
currently this is not possible, as the syntax is not SMALI code. It might be possible to convert between the formats though...

**Comment by Skullflow** [comment]
I need some input which i can work and be able to extract some features... maybe i can deal with bytecode.

I found this script to extract it:

```
a = apk.APK(file)
	d = dvm.DalvikVMFormat(a.get_dex())
	for current_class in d.get_classes():
		for method in current_class.get_methods():
			print method.get_name(), method.get_descriptor()
			byte_code = method.get_code()
			if byte_code != None:
				byte_code = byte_code.get_bc()
				idx = 0
				for i in byte_code.get_instructions():
					print "%x " % (idx),i.get_name(),i.get_output()
					idx += i.get_length()
```
Is this the only way to do that?

**Comment by reox** [comment]
yes this looks good. But you might want to iterate over all dex files of an APK.

With this approach it should be easy to write a smali converter. Take a look at androdd: https://github.com/androguard/androguard/blob/master/androdd.py#L124
and this method which is called there: https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/dvm.py#L8537

If you would add a method which writes out smali code for a class, I would definitely merge it ;)

**Comment by Skullflow** [comment]
I think it's better to have the bytecode instead of smali code for my project (Google saved my day!), so for now i will extract only the bytecode.

If I will need smali code, i will add the method!

Thanks! :)

**Comment by Skullflow** [comment]
What about bytecode obfuscation?

**Comment by reox** [comment]
what do you mean by that?
Do you mean wrong bytecode which crashes androguard like #519 or just code which is obfuscated to hide the real behaviour?
In the first case it would be required to fix androguard, in the latter case you need to come up with some deobfuscation technique

**Comment by reox** [comment]
btw: If you see any samples which show the behaviour like that in #519, please report them. I tested several thousand APKs and could not find a single one which had such bytecode and the one from the issue is not available on koodous...

**Comment by Skullflow** [comment]
So I need to extract the bytecode and do deobfuscation by myself? Is it not an androguard build-in feature?

**Comment by reox** [comment]
No, if you extract the bytecode using the method above, you get exactly the bytecode as in the DEX file.

**Comment by Skullflow** [comment]
Ok, got it.

Thanks!

**Comment by Skullflow** [comment]
I'm doing a malware analysis based on bytecode and for my purpose the amount of data for each apk are too big and i need a solution in order to filter bytecode.
Until now i filtered some frequent opcodes (e.s. return, new-instance, const) but i think this is not a good approach.

Is there a way to remove useless information from bytecode?

**Comment by reox** [comment]
I think that really depends on your definition of useless...

If you really want to drop certain opcodes, you can probably do that by changing the way instructions are read, for example here: https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/dvm.py#L6482
Or, without modifying the code, you can write a wrapper to the get_instructions method, which filters out the opcodes.

**Comment by Skullflow** [comment]
Well, I think it's very hard to understand which data have to be removed...
And I can't find anything on google for resolve this problem.

I just implemented a wrapper that filter out opcodes that contains the following: return, move, iget, iput and new-instance.

But i'm not sure if i'm removing useful features or not...

any advice?

**Comment by reox** [comment]
I think that really depends on your goal. I'm not aware of any papers or algorithms you could use (but i also never investigated in that direction).

You might want to use an AST and use some tree/graph magic in it - There is even some functionality for that in the decompiler but i never touched that. It would be interessting though if you can create an AST from a method directly with androguard.
If you find out, please let me know!
