### ISSUE TITLE
How to get the source code of a class

### ISSUE THREAD

**Issue by mspreitz** [androguard/androguard#539]
in older versions of androlyze it was possible to get the source code of a class by entering `d.get_class('Lcom/test/own/TestActivity;').source()` this seems to be no longer available.

Is there a new command that displays the source of a given class?

**Comment by reox** [comment]
Should be still possible IMHO.
do you get an error message?

**Comment by mspreitz** [comment]
In [6]: d.get_class('Lcom/test/own/TestActivity;').source()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/bin/androlyze.py in <module>()
----> 1 d.get_class('Lcom/test/own/TestActivity;').source()

AttributeError: 'list' object has no attribute 'get_class'

**Comment by mspreitz** [comment]
thanks a lot!
