### ISSUE TITLE
Error when using androcg.py in python3

### ISSUE THREAD

**Issue by r3j3c73d** [androguard/androguard#541]
Hi, I want to generate  Call Graph with graphml ext
I searched among issues and find out I should use androcg.py, if I'm wrong tell me please.
then I tried to use it like this
androcg.py --output tmp/StepByStepShoe.apk/ StepByStepShoe.apk
but I got this line:
Could not find a method to export files to apk/!
what is this mean? I tried it with 2 file 
thanks

- Androguard 3.2.0: master
- Python Version: 3.6
- Ubuntu 18.04

**Comment by reox** [comment]
can you share the APK and the full stacktracke? thanks!

**Comment by reox** [comment]
`--output` defines the output FILE not a folder! Please try to create the callgraph like this:
```
androcg.py --output StepByStepShoe.gml StepByStepShoe.apk
```

**Comment by r3j3c73d** [comment]
Yes you are right, i need to use --output and file name to get results, thank you very much
I think it's better if --output not used create default output for it.
thanks for this good project
