### ISSUE TITLE
Empty call graph when classname argument is used

### ISSUE THREAD

**Issue by gulizseray** [androguard/androguard#545]
When I used the "--classname" argument while creating call graphs using androcs.py, the resulting graph is always empty.

### System Information
- Androguard Version: 3.2.0
- Python Version: 3.7.0
- Operating System: Mac OSX

### Further Log Files and Output
Output always looks like this:
graph [
  directed 1
]

**Comment by reox** [comment]
thanks for the bug report! Can you share the APK and the exact cmdline options you are using?

**Comment by gulizseray** [comment]
[Venmo.apk.zip](https://github.com/androguard/androguard/files/2228152/Venmo.apk.zip)

**Comment by gulizseray** [comment]
Thanks for looking into this so quickly! I tried running with these (and some others, always got empty call graph):

androcg.py ~/Venmo.apk --classname TabCentralActivity
androcg.py ~/Venmo.apk --classname com.venmo.TabCentralActivity
androcg.py ~/Venmo.apk --classname com.venmo.controller.ActivationActivity

**Comment by gulizseray** [comment]
Any updates on this?

**Comment by reox** [comment]
Sorry for the late response. I see what the problem is: you need to give the classname filter as a regular expression:

```
androcg.py ~/Venmo.apk --classname '.*TabCentralActivity.*' 
```
should work!
