### ISSUE TITLE
ValueError reading app's name using get_app_name()

### ISSUE THREAD

**Issue by znakeeye** [androguard/androguard#547]
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do
a, d, dx = misc.AnalyzeAPK(apk, session=sess)
print(a.get_app_name())

### Describe what you expected
The name of the app should be printed.

### Describe what actually happened
File "C:\Python\Python37-32\lib\site-packages\androguard\core\bytecodes\apk.py", line 286, in get_app_name
    res_id = int(app_name[1:], 16)
ValueError: invalid literal for int() with base 16: '**android:0104006C'**

### System Information

- Androguard Version: 3.2.1
- Python Version: 3.7
- Operating System: Windows 10

### Further Log Files and Output

App was compiled with latest Android Studio 3.1 with the following relevant settings:
minSdkVersion 17
targetSdkVersion 27
multiDexEnabled true

**Comment by reox** [comment]
These are android specific resources and described in the system's resource file. Androguard is not aware of them: see #266

**Comment by znakeeye** [comment]
I'm afraid this is not the case here. The app name is a custom non-android string in original XML code:

```
<application
    android:name="android.support.multidex.MultiDexApplication"
    android:label="@string/app_name">
    <activity
        android:name=".MainActivity"
        android:screenOrientation="portrait"
        android:label="@string/app_name" >
    </activity>
```

I believe the only gotcha here is the use of `MultiDexApplication` as described [here](https://developer.android.com/studio/build/multidex). Still, the extracted manifest does show this "@android:" prefix for a bunch of labels.

**Comment by reox** [comment]
The App name is not affected by multidex. It is stored inside  Androidmanifest.xml and not in one of the dexes.
There is always only one manifest, regardless how many dexes are in the apk.
Multidex is just a way oft splitting large Codebasis up, as each der file has limits in how many methods, classes and strings it can store.

Have you compiled the application yourself? Can you share the apk as well as the source code?
I guess that the compiler optimizes the manifest and changes common names to ones from the system resources.

**Comment by znakeeye** [comment]
Unfortunately, this apk cannot be shared. However, recompiling the APK actually solved the problem! I analyzed the old APK and saw some weird stuff going on (possibly a bug at the time of compilation):

If I strip the "android" part from the resource ID, the app name is reported as "Android System" which is indeed found in the SDK:
```
<!-- Label for the Android system components when they are shown to the user. -->
<string name="android_system_label">Android System</string>
```
**More interestingly**, the embedded AndroidManifest.xml is **not my manifest**! The size is around 177 kB, and it contains garbage values and lots of generic Android stuff.
