### ISSUE TITLE
No decoder found for type: 'layout'!

### ISSUE THREAD

**Issue by znakeeye** [androguard/androguard#549]
Trying to read layout resources. Obviously, axml.py doesn't contain a `get_layout_resources` method. Hence the error when running androarsc.py (v3.2.1).

`androarsc.py -i test.apk -t layout`

Any chance this will be implemented soon?

**Comment by reox** [comment]
probably this would require some time... maybe you can work on it and create a PR? I would be happy to merge it :)

**Comment by znakeeye** [comment]
I suppose this might require some vendor-specific framework APKs to get 100% correct results?

**Comment by reox** [comment]
I'm not sure if there is vendor specific code in there... you can use the code from AOSP to get a hint about the used structures. There should be links to the relevant code segments in androguard's source already, if i'm not mistaken.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by reox** [comment]
this is a duplicate of #493
