### ISSUE TITLE
Analyzing thousands of apps at a time

### ISSUE THREAD

**Issue by gulizseray** [androguard/androguard#551]
Hi. I want to use Androguard to analyze many apps at a time. I saw you can create sessions with Androguard, but the docs specifically say you shouldn't use sessions to analyze too many apps at a time (I also couldn't get sessions to work but that's gonna be another question). I don't want Androguard to decompile all the apps again and again each time I run my code. I want the decompiled results to be saved on the disk to be reused when I create call graphs etc. How should I go about doing this? Thanks in advance.

**Comment by gulizseray** [comment]
What I want to do is basically save the immediate result from AnalyzeApk() so that I won't have to do that all the time, it seems very costly, especially if you want to do that for thousands of apps at a time. So the idea of sessions seems appropriate to me, but not only that I can't get it to work for a single app, the documentation clearly instructs not to do this for too many apps.

**Comment by reox** [comment]
Ah okay, so the concept is that you have a big, powerful machine and want to do the real analysis later?
The reason I added the warning about Sessions is the following: The session takes much more space than the APK alone. Thus, if you have harddisk space considerations --> do not use sessions.
If you have TB of space, then you are good to go.
But I would not use sessions after all but just pickle the APK and Analysis object separately, as the DalvikVMFormats are stored in the Analysis Object as well.

Here is a quick demo how this could work:

```
from pickle import dump
from androguard.misc import AnalyzeAPK
from hashlib import sha512
import sys

a, _, dx = AnalyzeAPK('examples/tests/a2dp.Vol_137.apk')

sha = sha512()

sha.update(a.get_raw())

with open("{}_apk.p".format(sha.hexdigest()), "wb") as fp:
    dump(a, fp)

with open("{}_analysis.p".format(sha.hexdigest()), "wb") as fp:
    # It looks like here is the recursion problem...
    sys.setrecursionlimit(50000)
    dump(dx, fp)
```

Now, for the sizes:
```
31M	24a62690a770891a8f43d71e8f7beb24821d46a75e017ef4f4e6a04624105466621c96305d8e86f9900042e3ef1d5806a5d9ac873bebdf798483790446bd275e_analysis.p
852K	24a62690a770891a8f43d71e8f7beb24821d46a75e017ef4f4e6a04624105466621c96305d8e86f9900042e3ef1d5806a5d9ac873bebdf798483790446bd275e_apk.p
808K	examples/tests/a2dp.Vol_137.apk
```

That means, a 1M APK will explode into 30 times that easily!

I could bring down the size significantly, by using lzma:

```
from pickle import dump
from androguard.misc import AnalyzeAPK
from hashlib import sha512
import sys
import lzma

a, _, dx = AnalyzeAPK('examples/tests/a2dp.Vol_137.apk')

sha = sha512()

sha.update(a.get_raw())

with lzma.open("{}_apk.p.lzma".format(sha.hexdigest()), "wb") as fp:
    dump(a, fp)

with lzma.open("{}_analysis.p.lzma".format(sha.hexdigest()), "wb") as fp:
    # It looks like here is the recursion problem...
    sys.setrecursionlimit(50000)
    dump(dx, fp)
```

```
4,5M	24a62690a770891a8f43d71e8f7beb24821d46a75e017ef4f4e6a04624105466621c96305d8e86f9900042e3ef1d5806a5d9ac873bebdf798483790446bd275e_analysis.p.lzma
748K	24a62690a770891a8f43d71e8f7beb24821d46a75e017ef4f4e6a04624105466621c96305d8e86f9900042e3ef1d5806a5d9ac873bebdf798483790446bd275e_apk.p.lzma
```

The sizes could be further reduced if the bytecode would not be stored... But this would take some major refactoring in the code.

**Comment by reox** [comment]
TODO: put this into to documentation, it might help someone in the future
