### ISSUE TITLE
find_fields() does not list static fields

### ISSUE THREAD

**Issue by znakeeye** [androguard/androguard#554]
Using androguard v3.2.1. Create a new app in Android Studio and modify _MainActivity.cs_ as shown:

```
public class MainActivity extends AppCompatActivity {
    public static final int Weirdness = 0x12345;

    /* ... */
}
```

Compile it (in debug mode) and analyze the produced APK!

```
a, d, dx = misc.AnalyzeAPK("test-app.apk")
for f in dx.find_fields(fieldname="Weirdness"):
    print(f)
```

The _Weirdness_ field will not be listed. Is this a bug or should I use another method to get hold of the static property?

**Comment by znakeeye** [comment]
Hmm... does this comment have anything to do with this?

> # TODO maybe we should add a step 3a here and check for all const fields. You can then xref for integers etc!

**Comment by znakeeye** [comment]
Ok, so this feature is not implemented yet. Any ideas on how to get it done? In my case, the instruction seems to be of type `Instruction31i`. An extra condition like `elif 0x12 <= op_value <= 0x19:` reveals an opcode of **0x14**. That's a start. Then what? The constant value is there, but I don't know what to do with it. Should I add a `self.consts` similar to `self.strings`?

Also, it would be nice to handle not just 0x14...

Please help.

**Comment by reox** [comment]
I make it an enhancement:
* Add a function to Analysis to get all fields, not only the used ones.
