### ISSUE TITLE
User experience

### ISSUE THREAD

**Issue by MartinThoma** [androguard/androguard#561]
You use a lot of different command line scripts. As a user, I wish you would use one. I recommend using `click` for that.

**Comment by reox** [comment]
the thing is, that the scripts are usually written for a specific job and used in a chain of other tools. If there would be only a single script, this would probably degrade into something like `androguard <subcommand><options> ...`

Do you think that this would improve the usability? I mean it does in certain cases, for example `virsh` also has subcommands. 

you are very welcome to send a pull request ;)

**Comment by reox** [comment]
I took a look at click and it seems to be quite advanced over the current argument parsers.
What it allows would be to have definitions for commonly used functions somewhere else and detached from the scripts and easily provide cmdline tools.

**Comment by reox** [comment]
I have a question regarding the usage of the click library. If there is a function for doing something with default arguments set:
```
def dosomething_main(x, y=2, z=None):
    pass
```

What would be the best way to create a cli interface for it? I see, that you created a wrapper function for it like this:

```
@click.command()
@click.option("-x")
@click.option("-y", default=2)
@click.option("-z")
def dosomething(x, y, z):
    dosomething_main(x, y, z)
```

But this effectively duplicates the default values, right? But I need to have the default values in `dosomething_main`, otherwise it is hard to reuse in a python module.
How would you deal with this in your opinion?

**Comment by MartinThoma** [comment]
Hm, ok, let's see:

* We have a function `dosomething_main(x, y=2, z=None)` which should definitely keep the default arguments
* We have a CLI for that function. Of course, it should have the same default arguments.

One way to do this is to externalize the defaults, e.g.:

```
defaults = {'y': 2, 'z': None}
@click.command()
@click.option("-x")
@click.option("-y", default=defaults['y'])
@click.option("-z", default=defaults['z'])
def dosomething(x, y, z):
    dosomething_main(x, y, z)

def dosomething_main(x, y=defaults['y'], z=defaults['z']):
    pass
```

Another option might be [introspection](https://stackoverflow.com/a/12627202/562769).

**Comment by reox** [comment]
Thanks for the information! Probably worth a feature request ;)

**Comment by reox** [comment]
Okay I send a feature request but it seems that calling the function which is decorated directly is disregarded. So it would always be better to write a extra cli function for function.

**Comment by reox** [comment]
Thanks again for implementing this, it is a really nice addition! I added now a function for androdis too (not merged yet though)
