### ISSUE TITLE
androdis.py

### ISSUE THREAD

**Issue by MartinThoma** [androguard/androguard#562]
### Describe what you did

```
$ androdis.py -i classes.dex
```

### Describe what happened

```
Traceback (most recent call last):
  File "/home/math/.local/bin/androdis.py", line 74, in <module>
    sys.argv[:] = arguments
NameError: name 'sys' is not defined
```

### System Information

- Androguard Version: androguard==3.2.
- Python Version: Python 3.5.2
- Ubuntu 16.04

**Comment by brazeel** [comment]
Yeah I encountered with the same problem, so did you got a workaround?

**Comment by reox** [comment]
import sys i guess...
