### ISSUE TITLE
ICC edges in CFG created by Androguard

### ISSUE THREAD

**Issue by gulizseray** [androguard/androguard#564]
Does Androguard create edges for ICC calls (i.e., startActivity etc) in the control flow graph?

**Comment by reox** [comment]
I think they are not regarded as an entry point right now.
By default these are the entry points: https://github.com/androguard/androguard/blob/master/androcg.py#L74

**Comment by gulizseray** [comment]
I'm a little confused with this reply since it's referring to the call graph code and not control flow graph. What I wanted to ask is this: if an app starts a component of another app, would this be reflected in the control flow graph? I know Amandroid does keep track of inter-component communication calls, but some other tools don't. I'm just not sure what Androguard does in this case.
