### ISSUE TITLE
Question about function parameters in Androguard callgraphs

### ISSUE THREAD

**Issue by gulizseray** [androguard/androguard#565]
Is there a way to get access to the parameters of a method in the callgraph created by Androguard?

For example, say I have the following node in my call graph:
Lcom/example/app/MainActivity;->startActivity(Landroid/content/Intent;)V

Is there a way to know what kind of an intent object (i.e., the class) was used in this call? If not, could I get this information from the control flow graph instead?

Thanks!

**Comment by reox** [comment]
That is not an easy task to do - at least statically it is hard to impossible. Using dynamic analysis, you could get the parameters - but this is out of the scope of androguard.

There are some specific cases, where the parameters are available from the bytecode.
What you would need to do is to run all code up to the call and analyse the flow of information. I think this is not done right now, but wasn't there a statemachine of some sort implemented somewhere? I do not quite remember...
