### ISSUE TITLE
Newbie Questions

### ISSUE THREAD

**Issue by learner291** [androguard/androguard#566]
I have started my PhD research on detecting android malware. I am learning about what is involved in conducting such research and I have come across your tool. I have following questions and I would appreciate if you could help/guide me:

1) How does Androguard detect/classify an apk as malware or benign after conducting static analysis? As far as I can tell Androguard does not use machine learning algorithms for this purpose.

2) Is following the correct/efficient method for extracting all classes used by an apk?

```
a = apk.APK(apk_name)
for dex in a.get_all_dex():
    d = dvm.DalvikVMFormat(dex)
    outcome = analysis.Analysis(d)
    self.classess_list.append(outcome.get_classess())
```

3) Could you recommend some practical books or other material which I can use to improve the practical aspects of my research so that I can run experiments? I can find theory via my literature review.

4) Could you also recommend the best possible way to use Androguard with the goal of conducting static analysis and classifying an apk as benign or malware? I have looked at Androguard examples, is there "how to use example sections" for someone who is just starting to learn?

I am sorry for asking basic questions.
Thanks

**Comment by learner291** [comment]
Thank you for taking time and replying to me.

I will use the approach that you mentioned with regards to question 2.

Regarding question 3 and 4, I have come across some books and papers but they are mainly theoretical. I am looking for some practical examples as my mind understand better when I look at code and try to understand how different pieces work together.

Are you aware of any step by step practical guides/examples for extracting features and loading them into machine learning tool?

Thank you.

**Comment by reox** [comment]
I'm by no means a machine learning expert, but feature extraction should IMO not depend on the tool you are using. So the first question should be: "How can we detect X", or "What features do we even have".
Then you start collecting them and _then_ you start worrying about how to get those features into the ML tool you are using. There is also a lot of research on feature selection and so on...
But usually you have some knowledge about, lets say malware. Here is an easy example:
You figure, that the samples in the malware class are always using SEND_SMS permission. Now you simply can extract that feature from the APK and give it to your tool.


Searching for "androguard" in academical search engines already yields a lot of stuff, have a look here:
https://scholar.google.at/scholar?cites=10662197497559346379&as_sdt=2005&sciodt=0,5

As a starting point, I would implement a tool which uses permissions only. There has been plenty of papers which use all kind of methods. Even I implemented a Random Forest and a Neural network approach using only the permissions. The results are not good but also not terrible bad either.
You can easily compare the results to existing studies and learn how to use the tools at the same time.
hth!

**Comment by reox** [comment]
btw: I think there are no actual step by step guides for malware detection.
But there is already a lot of documentation on how to use machine learning toolkits. So you should probably look at the examples of scikit-learn or tensorflow, or whatever floats your boat!

**Comment by learner291** [comment]
Thank you, I really appreciate your help, I will go through those papers.

Could you tell me how I can use Androguard to detect if an app is using the following codes:

Encryption/cryptic code
Reflection code
Native code
dynamic code
using database

Finally, can Androguard be used to perform static analysis on Native code?

**Comment by reox** [comment]
yes, you can do this if you know the APIs you want to track. Then the analysis module is suited to give you the usage of every call.
There was a system implemented in androguard where several APIs where already collected but as the android sdk expands, it was not reliable anymore.

Native code is currently not supported, there were some attempts to integrate radare2 and IDA into androguard... There are currently probably much better tools for native code out there. It would be really nice to have some wrapper code for androguard though.

**Comment by learner291** [comment]
I'll go through the documentation further in order to find the relevant code and let you know if I have any issues.

I have tried your code for getting all the classes, however, I am received following error:

```
   dx.add(d)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/analysis/analysis.py", line 939, in add
    for current_class in vm.get_classes():
AttributeError: 'bytes' object has no attribute 'get_classes'

Process finished with exit code 1
```

My code is as follows:


```
from androguard.core.bytecodes import apk
from androguard.core.analysis import analysis

apk_name = '/media/sf_Ubuntu_Shared_Folder/1&1 Online Storage.apk'
package = ''
myclasses = []

a = apk.APK(apk_name)
package = a.get_package()
dx = analysis.Analysis()
for d in a.get_all_dex():
    dx.add(d)
myclasses = dx.get_classes()
```

The error is on dx.add(d), can you help please?

**Comment by reox** [comment]
ah sorry, you need to get the bytes and put them into a DalvikVMFormat first:

```
from androguard.core.bytecodes import apk
from androguard.core.bytecodes.dvm import DalvikVMFormat
from androguard.core.analysis import analysis

apk_name = '/media/sf_Ubuntu_Shared_Folder/1&1 Online Storage.apk'
package = ''
myclasses = []

a = apk.APK(apk_name)
package = a.get_package()
dx = analysis.Analysis()
for d in a.get_all_dex():
    dx.add(DalvikVMFormat(d))
myclasses = dx.get_classes()
```

**Comment by learner291** [comment]
Thank you, it works!
