### ISSUE TITLE
New Logo Enhancement Proposal

### ISSUE THREAD

**Issue by debpedrano** [androguard/androguard#567]
Greetings Project Owner, 

I am a graphics designer who contributes on any Open Source projects. I saw your project that is really helpful in the community, I am interested in making a NEW LOGO because the current logo is not properly constructed and it would be an honor to enhance it.

I am asking your permission to do it.

Regards,

Deb

**Comment by reox** [comment]
can you explain what is wrong with the current logo or what you want to change?

for reference, here is the old one: 
![old](https://raw.githubusercontent.com/androguard/androguard/master/docs/androguard.png)
and the new one:
![new](https://raw.githubusercontent.com/androguard/androguard/master/assets/CI/logo-1.png)

now that I look at it more closely, I find these points:

* the colorschema is too much grey
* there is too much space between the shield and the circle around it
* I like the new ninja's mask
* But I like the old ninja's antennas more than the new ones
* The girdle is missing
* It looks like that the grey tones are not the same for the ninja's body and arms

**Comment by debpedrano** [comment]
@reox I am pointing on the new one, that's why I observe about the pointes you commented. 
too much space, and the mask is not properly made. 
I like the old, can I make some changes on the new logo?

**Comment by reox** [comment]
Unfortunately, the PNG is all we got...

**Comment by reox** [comment]
Sure, if you have the svg in the repo, it is easy to create all desired formats and sizes from it.

**Comment by debpedrano** [comment]
Great, ill be making it now :)

**Comment by debpedrano** [comment]
@reox is this one okay? 
![image](https://user-images.githubusercontent.com/40510200/47256058-3e54ac00-d4ac-11e8-8c9a-94cccb0dd2a8.png)

**Comment by debpedrano** [comment]
![image](https://user-images.githubusercontent.com/40510200/47256122-1580e680-d4ad-11e8-8bb2-033e3b461644.png)

**Comment by reox** [comment]
Why the darker green? The android color was OK IMO.
Also the eyes have now different colors as they are transparent? Why not leave them black?
The size looks better, but I think you could even make the circle smaller and darker to have it stand out more?

**Comment by debpedrano** [comment]
Okay, I will not that @reox.

**Comment by debpedrano** [comment]
![image](https://user-images.githubusercontent.com/40510200/47262747-2409e500-d523-11e8-8884-b20d0c95db20.png)

**Comment by reox** [comment]
looks good!
@androguard/external-contributors what do you think?

**Comment by debpedrano** [comment]
@reox I will send a Pull Request which includes the editable files

**Comment by debpedrano** [comment]
@reox , whats up?

**Comment by reox** [comment]
maybe someone from @androguard/external-contributors wants to say something?

**Comment by debpedrano** [comment]
I agree with you also @reox , when I try to look at the shield and it seems the outer part is not circle. But in fact, it is circle. Maybe it is because of the top most part of the shield, I have to change it for you.

**Comment by debpedrano** [comment]
How about this one @reox , I made the outer circle bigger and darker, in order for the main logo at the center to standout. what do you think?

![image](https://user-images.githubusercontent.com/40510200/47760548-bcf0eb00-dcef-11e8-8f89-50b890c7c955.png)

**Comment by reox** [comment]
@androguard/external-contributors any input from you?
