### ISSUE TITLE
How to use the androguard to extract the mapping informations between API and permissions?

### ISSUE THREAD

**Issue by zqkFrank** [androguard/androguard#571]
I see the the "androguard-master\androguard\core\api_specific_resources"  has the api_permission_mappings directory, Could I use the androguard to extract the mapping informations between API and permissions?  I dont' know how to use them, Could you give me some suggestions?

- Androguard Version: master
- Python Version: 3.5
- Operating System: Windows7

**Comment by reox** [comment]
try something like:
```
from androguard.core.api_specific_resources import load_permission_mappings

mapping = load_permission_mappings(24)  # 24 is the API level
```

mapping is now a dict with `{API: [permissions]}`

**Comment by ezamorab** [comment]
Hi, I have a question in relation to this, how could I get a mapping for Android 8 (API lvl 26)?

Thanks in advance.

**Comment by reox** [comment]
@ezamorab they are not available in axplorer yet...
