### ISSUE TITLE
resurect function Analysis.get_permissions

### ISSUE THREAD

**Issue by zqkFrank** [androguard/androguard#572]
I am learning about how to better use the androguard, I see that I can  extract the permissions used in the program by using the command "dx.get_permissions([ ])" in the androguard-2, but I don't see this function is the androguard-3.2.1. If I want to use this funtion, what show I do? I would appreciate if you could help me. Thanks!

**Comment by reox** [comment]
I just added a new function for that: #670 

would be nice if you can take a look!

I guess the API has changed but the results should be similar
