### ISSUE TITLE
difference between androguard 2 &3

### ISSUE THREAD

**Issue by p0prxx** [androguard/androguard#573]
the androguard 2 has get_strings_by_method() and toPathVariable() in tainted_variables, what's the equivalent representation in androguard 3.x? thanks

**Comment by reox** [comment]
probably you can get similar results using xrefs.

**Comment by subho007** [comment]
@reox `get_strings_by_method` and `toPathVariable` and related to taintAnalysis which is now replaced with Xrefs, which works better. I don't think you need to `resurrect-functions` this.

**Comment by reox** [comment]
okay good to know. I'll close this then!
