### ISSUE TITLE
Error decoding a valid APK

### ISSUE THREAD

**Issue by jdoestovsky** [androguard/androguard#575]
I'm trying to decode an APK (link: https://we.tl/t-vG5ww1Nrf2) using androguard, but see the following exception:

```
File "/home/xd/try.py" in parse_apk
  182.         return APK(apk_file, False)
File "/home/xd/.env/local/lib/python2.7/site-packages/androguard/core/bytecodes/apk.py" in __init__
  108.         self.zip = zipfile.ZipFile(io.BytesIO(self.__raw), mode="r")
File "/usr/lib/python2.7/zipfile.py" in __init__
  770.                 self._RealGetContents()
File "/usr/lib/python2.7/zipfile.py" in _RealGetContents
  857.             x._decodeExtra()
File "/usr/lib/python2.7/zipfile.py" in _decodeExtra
  388.             tp, ln = unpack('<HH', extra[:4])

Exception Type: error at /home/xd/try.py
Exception Value: unpack requires a string argument of length 4
```

This apk has been signed using signapk.jar as described here: http://www.londatiga.net/it/how-to-sign-apk-zip-files/

### System Information

- Androguard Version: 3.2.1
- Python Version: 2.7
- Operating System: macOS 10.13

**Comment by reox** [comment]
Might be a reoccurence of the old zipfile bug? I know there was a bug in old python versions like 2.5...
Can you try the same thing with python 3?

**Comment by jdoestovsky** [comment]
Thank you for the mention of the bug. I believe you are referring to is here: https://bugs.python.org/issue14315

I see this has since been fixed. Can confirm this indeed works on python 3.6 and the latest release on the 2.7 branch (as of this writing, i.e. 2.7.14)

Thank you for your prompt response, appreciate it!
