### ISSUE TITLE
Incomplete permission mappings

### ISSUE THREAD

**Issue by lucacapacci** [androguard/androguard#576]
API permission mappings (at https://github.com/androguard/androguard/tree/master/androguard/core/api_specific_resources/api_permission_mappings) are incomplete. 
Example: there are  no mappings for permission "android.permission.CAMERA". However, old versions of androguard (before switching from python files to json files) had mappings for permission "android.permission.CAMERA".
I would suggest to perform a merge between the old permission mappings and the new ones, since I believe both the old ones and the new ones may be incomplete.

**Comment by reox** [comment]
The mappings are generated from axplorer, and there is already a issue for this in their issue tracker: https://github.com/reddr/axplorer/issues/3
