### ISSUE TITLE
AttributeError: module 'androguard.core.analysis.analysis' has no attribute 'newVMAnalysis'

### ISSUE THREAD

**Issue by yaorc911** [androguard/androguard#577]
- Androguard Version: 3.2.1
- Python Version: 3.6

Hi,
    I want to get the API called in apk file, but this method hint has failed. Is there any other method?

**Comment by reox** [comment]
Can you give us an example how you got this error or at least the full stacktrace? Thank you!

**Comment by reox** [comment]
`newVMAnalysis` is veeeery old... It was used in Androguard 2. You need to use `Analysis` now. Have you copied this code from some old project?

**Comment by yaorc911** [comment]
Yes, I'm referring to an old project based on Python2, Thank you for your help.
