### ISSUE TITLE
Bug: TypeError: argument of type 'NoneType' is not iterable in core/bytecodes/apk.py

### ISSUE THREAD

**Issue by JonathanSalwan** [androguard/androguard#58]
Hey,

With some APK, I got this crash:

<pre>
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 205, in __init__
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 295, in get_files_types
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 308, in _patch_magic
TypeError: argument of type 'NoneType' is not iterable
</pre>

When I call:

<pre>
apk = APK(apkFile)
</pre>

The bug occurs here at line 308 in the core/bytecodes/apk.py file:

<pre>
 307     def _patch_magic(self, buffer, orig):
 308         if ("Zip" in orig) or ("DBase" in orig):
</pre>

I tried to return None if "orig" is None and it seems to be working but I'm not sure about the side effect.

<pre>
 307     def _patch_magic(self, buffer, orig):
 308         if orig is None:
 309             return orig
 310         if ("Zip" in orig) or ("DBase" in orig):
</pre>

Cheers,

**Comment by subho007** [comment]
It would be really helpful if you can share your dex or apk file.

**Comment by reox** [comment]
@JonathanSalwan is this one still an issue? If it is, would it be possible to share the APK file?

**Comment by JonathanSalwan** [comment]
@reox, "`Jan 20, 2015`", sorry man, i don't have this APK anymore and i don't know if it's still an issue or not.

**Comment by reox** [comment]
thanks for checking, if you encounter it again, feel free to reopen!
