### ISSUE TITLE
How to get the CFG of the whole APK just from the smali file

### ISSUE THREAD

**Issue by xiaomoqi123** [androguard/androguard#580]
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do

- is this error specific to a single file?
- if possible give a minimal working example where the error happens

### System Information

- Androguard Version: master
- Python Version: 2.7/3.5/...
- Operating System

### Further Log Files and Output

- please report logs, tracebacks and other useful information
- if possible report the files you tried to analyze!

**Comment by reox** [comment]
androguard does not work on smali files. compile a dex out of it, so you can use it in androguard.
