### ISSUE TITLE
AnalyzeDex/ODex documentation discrepancies

### ISSUE THREAD

**Issue by ehrenb** [androguard/androguard#581]
In release 3.2.1 the [AnalyzeDex ](https://github.com/androguard/androguard/blob/master/androguard/misc.py#L81)[documentation](https://androguard.readthedocs.io/en/latest/api/androguard.html?highlight=analyzedex#androguard.misc.AnalyzeDex) states the function returns two objects (DalvikVMFormat and Analysis), but actually it returns a (sha256 string, DalvikVMFormat, and Analysis) since it is calling down the addDex function in [session.py](https://github.com/androguard/androguard/blob/v.3.2.1/androguard/session.py)

The same discrepancy occurs with the [AnalyzeODex ](https://github.com/androguard/androguard/blob/master/androguard/misc.py#L102)and addDEY.

**Comment by reox** [comment]
Yes thats true. Thanks for reporting!
There were a lot of changes on many functions, which are, unfortunately, not documented correctly.
