### ISSUE TITLE
UnicodeEncodeError: Unencoded UTF-8 unicode in ARSC._analyze

### ISSUE THREAD

**Issue by jochasinga** [androguard/androguard#582]
The bug is here : https://github.com/androguard/androguard/blob/a18256203d7af751c8862b04b15b15c23225b54f/androguard/core/bytecodes/axml.py#L1017

`language` and `region` are `<unicode>` type but are being used as string. This raised the following error:

```shell

UnicodeEncodeError: 'ascii' codec can't encode character u'\xa4' in position 0: ordinal not in range(128)

```
`u'\xa4'` being some unicode region name.

- Androguard Version: master
- Python Version: 2.7.10
- Operating System: Mac OS

**Comment by reox** [comment]
I also saw your PR! Thanks for that! Have you tested this with python3.x as well? Can you upload the AXML file here or even write a short testcase? I remember that I tried to fix this but had troubles propagating the changes all the way through all the functions...

**Comment by jochasinga** [comment]
@reox I haven't tested with 3.x but I can do that. I can add a testcase for this as well. However, I think this fix should be pretty isolated enough to not effect other functions since it's only used to format a string that gets assigned to a `locale` variable.

Are we're looking for a more "universal" fix?

**Comment by reox** [comment]
that would be very appreciated, thanks!

> Are we're looking for a more "universal" fix? Then we better off looking into ARSCResTableConfig.

yes and no. I read through the whole ARSC parser once and i think there is much which needs to be rewritten anyways. Then, the universal fix would be to decide which parts are actually strings and which are bytes. Unfortunately, python2 was very sloppy with bytes/strings conversions, thus there are many problems now, that androguard runs on py3.
So please, do not chase the rabbit too long. If the fix works in both py3 and py2 its fine for now!

**Comment by jochasinga** [comment]
Actually if these lines

https://github.com/androguard/androguard/blob/a18256203d7af751c8862b04b15b15c23225b54f/androguard/core/bytecodes/axml.py#L1012-L1017

were replaced by

```python

locale = a_res_type.config.get_language_and_region()

```

It achieved the same without the error. Can you take a look?

**Comment by reox** [comment]
yes, that one looks better. would you like to change that in your PR?

**Comment by reox** [comment]
It looks like the fix did not work and made the resource parser unusable...
