### ISSUE TITLE
Does Androguard track variable values during the creation of a CFG?

### ISSUE THREAD

**Issue by projectbtle** [androguard/androguard#586]
Hello,

I'm trying to automatically obtain the input values to specific functions within APKs (for a large number of APKs). The inputs to the functions may be different for different APKs in how they are produced. That is, some may define and use them immediately, which is easy to trace. Others may use values passed as arguments and apply muliple formatting functions before they are used.  

I was wondering whether Androguard could be used for this purpose. During CFG creation, does Androguard happen to track variable values?

**Comment by reox** [comment]
No, this is currently not done.
I'm not sure, but it could be possible to do something though.

Related: #564

**Comment by kneep** [comment]
Hi @reox ,

I just got the exact same question. I think it is very cool if we can have this feature.

In many of my test cases, I need check whether a method is called with a certain argument value. There are cases calls would become problematic if they are called with certain arguments. When the argument is a `String`, I currently also check where the particular string value is referenced. So if a method calls both the method and the string value that I'm interested, it is very likely a hit and more manual audit is needed. But if the argument interested is a numeric, this workaround does not work.

I also noticed that [androwarn](https://github.com/maaaaz/androwarn) seemed to have some implementation. I quickly skimmed his code and was not sure if that really worked. The logic seems not correct and surely it's also a simplified version. Not sure.

I know implementing full variable tracing is quite tricky. That's what [FlowDroid](https://github.com/secure-software-engineering/FlowDroid) does. But it would be great if we have a poor man's implementation in androguard. I think we only need to trace variables to the boundary of the calling method. That would cover most cases.

**Comment by reox** [comment]
Maybe have a look here: https://github.com/androguard/androguard/issues/593

I found out that the AST has this information. Maybe you could come up with some parsing for that?

**Comment by projectbtle** [comment]
Sorry, I didn't realise I hadn't replied. Better late than never? (even 2 years late...)

I don't remember the specifics now, but I did try to use the AST and found that it didn't have the information I wanted. But of course, this was with a much older version of Androguard, so this may no longer be valid/relevant.
