### ISSUE TITLE
AXML parser does not recognises namespaces

### ISSUE THREAD

**Issue by dobaniashish** [androguard/androguard#588]
### Everything returns as null
All the methods returns null except for package

### Code
```
a = APK(args.apk)
print('get_package')
print(a.get_package())
print('get_app_name')
print(a.get_app_name())
print('get_androidversion_code')
print(a.get_androidversion_code())
print('get_androidversion_name')
print(a.get_androidversion_name())
print('get_min_sdk_version')
print(a.get_min_sdk_version())
print('get_target_sdk_version')
print(a.get_target_sdk_version())
print('get_permissions')
print(a.get_permissions())
```

### Response
```
get_package
com.android.chrome
get_app_name

get_androidversion_code
None
get_androidversion_name
None
get_min_sdk_version
None
get_target_sdk_version
None
get_permissions
[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
None, None, None]
```

### System Information
- Androguard Version: 3.2.1
- Python Version: 3.6
- Operating System: CentOS 7/Windows 10

### FIle
APK: Google Chrome v70.0.3538.110
Version Code: 353811002
URL: https://apkpure.com/google-chrome-fast-secure/com.android.chrome
URL: https://play.google.com/store/apps/details?id=com.android.chrome

**Comment by reox** [comment]
This is odd. It looks like that the XML does not have the android namespace.

For example:
```
In [8]: a.xml['AndroidManifest.xml'].findall('.//service')[0].attrib
Out[8]: {'name': 'org.chromium.chrome.browser.upgrade.UpgradeIntentService', 'exported': 'false'}
```

therefore the `get_elements` does not work...
```
In [10]: list(a.get_elements("service", "name"))
Out[10]: []

In [11]: list(a.get_elements("service", "name", with_namespace=False))
Out[11]: 
['org.chromium.chrome.browser.upgrade.UpgradeIntentService',
 'org.chromium.chrome.browser.browseractions.BrowserActionsService',
 'org.chromium.chrome.browser.photo_picker.DecoderService',
 ...
```

Not sure what the issue is here, but it looks like that the AXML parser does not works here.
With aapt, i can see the namespaces:
```
E: manifest (line=2)
  A: http://schemas.android.com/apk/res/android:versionCode(0x0101021b)=(type 0x10)0x1516ba3a
  A: http://schemas.android.com/apk/res/android:versionName(0x0101021c)="70.0.3538.110" (Raw: "70.0.3538.110")
  A: package="com.android.chrome" (Raw: "com.android.chrome")
  A: platformBuildVersionCode=(type 0x10)0x1c
  A: platformBuildVersionName=(type 0x10)0x9
  E: uses-sdk (line=3)
    A: http://schemas.android.com/apk/res/android:minSdkVersion(0x0101020c)=(type 0x10)0x18
    A: http://schemas.android.com/apk/res/android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
```

**Comment by reox** [comment]
I looked a little bit into this: There is no START_NAMESPACE chunk in the manifest file but the namespace URI is set on the attribute.
I'm not sure if the format has changed somehow, but assuming this is a valid APK by google itself, they probably changed it...

**Comment by reox** [comment]
I started to rewrite the AXMLPrinter by using ETree directly. ETree can handle namespaces very well, when they are directly given.

It would be nice to test this somehow...
@eighthave one possibility would be to use f-droid, as there are all the compiled and raw AndroidManifest.xml files available. The test would be to take both files, and check if the resulting XML is the same (= if the canonical form of both XMLs is the same). Would this be easy to do? For example, is there an easy to use source where both files are in the same place?

**Comment by reox** [comment]
@androguard/external-contributors maybe some of you have a clue for me: There is something I do not understand with the AXML format: you can define namespace/prefix mappings but each tag or attribute uses only the URI parameter to define the namespace uri.
Does this mean, that the namespace mappings are just there to provide this meta information, which is never used? Is this correct?

**Comment by reox** [comment]
I also implemented now the namespace mapping, so in the printed XML there is no `ns01` but `android` or whatever the prefix is known in the file.

**Comment by eighthave** [comment]
Someone was building Chromium for Android, and that also had similar bizarre namespace issues.  I ended up switching the logic to always use the canonical URL for the namespace rather than the _xmlns_ name declared in the XML, and that seems to work more reliably, but then with a hack with no namespace for Chromium-based apps.

* https://gitlab.com/fdroid/fdroidserver/commit/84dfd6b06af1799d776a72af13d5c32642bda84e
* https://gitlab.com/fdroid/fdroidserver/issues/515
* https://gitlab.com/fdroid/fdroidserver/merge_requests/536

**Comment by eighthave** [comment]
You should get a copy of the f-droid.org mirror, that includes APKs and source tarballs for each one.  I think this mirror has public _rsync_ access: https://ftp.fau.de/  Otherwise, send me an email, and I'll give you direct access to the f-droid.org mirror server.

**Comment by eighthave** [comment]
Here are other public mirrors: https://fdroid.gitlab.io/mirror-monitor/

**Comment by reox** [comment]
> Someone was building Chromium for Android, and that also had similar bizarre namespace issues

So I think the issue there is, that they do not provide the namespace mapping anymore - because this is only cosmetic. The new AXML parser should be aware of this and insert the correct namespace, regardless of what the mapping says.


> You should get a copy of the f-droid.org mirror, that includes APKs and source tarballs for each one. I think this mirror has public _rsync_ access: https://ftp.fau.de/ Otherwise, send me an email, and I'll give you direct access to the f-droid.org mirror server.

ah yeah, the rsyncing is working already - I just did not pulled the source tarballs...
I will try that! Thanks for the hint ;)
It should be possible then to compare the files!

**Comment by eighthave** [comment]
did you find any mention of the namespace being cosmetic anywhere?

**Comment by reox** [comment]
> 
> did you find any mention of the namespace being cosmetic anywhere?

No, the problem is that there is no documentation other than the sourcecode :/
But aapt just prints out the namespace mappings and it looks like it does some assumptions for the chrome files. There, even though no prefix mappings are given anywhere, the namespaces will print `android:`.
My assumption is, that you should take the namespace uri from the tag/attribute and use that one. 
See here: http://androidxref.com/9.0.0_r3/xref/frameworks/base/tools/aapt/XMLNode.cpp#build_namespace
If the Vector of namespace mappings is empty, it will simply take the string of the namespace uri.

**Comment by reox** [comment]
So I fiddled togeher a script to compare the manifests, and here are the first problems...
In the source files, numerical values are given as strings. But these are compiled into the integer values:
```
INFO:manifestcheck:Comparing: /mnt/tmp/fdroid/repo/com.elsdoerfer.android.autostarts_24_src.tar.gz vs /mnt/tmp/fdroid/repo/com.elsdoerfer.android.autostarts_24.apk
INFO:manifestcheck:Attributes do not match: {http://schemas.android.com/apk/res/android}installLocation='auto', {http://schemas.android.com/apk/res/android}installLocation='0'
WARNING:manifestcheck:File /mnt/tmp/fdroid/repo/com.elsdoerfer.android.autostarts_24.apk does not compare!
INFO:manifestcheck:Comparing: /mnt/tmp/fdroid/repo/com.ichi2.anki_25_src.tar.gz vs /mnt/tmp/fdroid/repo/com.ichi2.anki_25.apk
INFO:manifestcheck:Attributes do not match: {http://schemas.android.com/apk/res/android}installLocation='auto', {http://schemas.android.com/apk/res/android}installLocation='0'
WARNING:manifestcheck:File /mnt/tmp/fdroid/repo/com.ichi2.anki_25.apk does not compare!
INFO:manifestcheck:Comparing: /mnt/tmp/fdroid/repo/com.morphoss.acal_57_src.tar.gz vs /mnt/tmp/fdroid/repo/com.morphoss.acal_57.apk
INFO:manifestcheck:Attributes do not match: {http://schemas.android.com/apk/res/android}launchMode='standard', {http://schemas.android.com/apk/res/android}launchMode='0'
INFO:manifestcheck:children 5 do not match: activity
INFO:manifestcheck:children 25 do not match: application
WARNING:manifestcheck:File /mnt/tmp/fdroid/repo/com.morphoss.acal_57.apk does not compare!
INFO:manifestcheck:Comparing: /mnt/tmp/fdroid/repo/com.colinmcdonough.android.torch_2_src.tar.gz vs /mnt/tmp/fdroid/repo/com.colinmcdonough.android.torch_2.apk
INFO:manifestcheck:Attributes do not match: {http://schemas.android.com/apk/res/android}screenOrientation='portrait', {http://schemas.android.com/apk/res/android}screenOrientation='1'
INFO:manifestcheck:children 1 do not match: activity
INFO:manifestcheck:children 1 do not match: application
WARNING:manifestcheck:File /mnt/tmp/fdroid/repo/com.colinmcdonough.android.torch_2.apk does not compare!
INFO:manifestcheck:Comparing: /mnt/tmp/fdroid/repo/com.ghostsq.commander_163_src.tar.gz vs /mnt/tmp/fdroid/repo/com.ghostsq.commander_163.apk
INFO:manifestcheck:Attributes do not match: {http://schemas.android.com/apk/res/android}installLocation='auto', {http://schemas.android.com/apk/res/android}installLocation='0'
WARNING:manifestcheck:File /mnt/tmp/fdroid/repo/com.ghostsq.commander_163.apk does not compare!
INFO:manifestcheck:Comparing: /mnt/tmp/fdroid/repo/budo.budoist_30_src.tar.gz vs /mnt/tmp/fdroid/repo/budo.budoist_30.apk
INFO:manifestcheck:Comparing: /mnt/tmp/fdroid/repo/org.woltage.irssiconnectbot_393_src.tar.gz vs /mnt/tmp/fdroid/repo/org.woltage.irssiconnectbot_393.apk
INFO:manifestcheck:Attributes do not match: {http://schemas.android.com/apk/res/android}installLocation='auto', {http://schemas.android.com/apk/res/android}installLocation='0'
WARNING:manifestcheck:File /mnt/tmp/fdroid/repo/org.woltage.irssiconnectbot_393.apk does not compare!
INFO:manifestcheck:Comparing: /mnt/tmp/fdroid/repo/apps.droidnotify_29_src.tar.gz vs /mnt/tmp/fdroid/repo/apps.droidnotify_29.apk
INFO:manifestcheck:Attributes do not match: {http://schemas.android.com/apk/res/android}installLocation='internalOnly', {http://schemas.android.com/apk/res/android}installLocation='1'
WARNING:manifestcheck:File /mnt/tmp/fdroid/repo/apps.droidnotify_29.apk does not compare!
INFO:manifestcheck:Comparing: /mnt/tmp/fdroid/repo/no.rkkc.bysykkel_25_src.tar.gz vs /mnt/tmp/fdroid/repo/no.rkkc.bysykkel_25.apk
INFO:manifestcheck:children length differs, 7 != 6
INFO:manifestcheck:children 4 do not match: application
WARNING:manifestcheck:File /mnt/tmp/fdroid/repo/no.rkkc.bysykkel_25.apk does not compare!
INFO:manifestcheck:Comparing: /mnt/tmp/fdroid/repo/com.byagowi.persiancalendar_38_src.tar.gz vs /mnt/tmp/fdroid/repo/com.byagowi.persiancalendar_38.apk
INFO:manifestcheck:Attributes do not match: {http://schemas.android.com/apk/res/android}configChanges='keyboardHidden|orientation|screenSize', {http://schemas.android.com/apk/res/android}configChanges='0x000004A0'
INFO:manifestcheck:children 6 do not match: activity
INFO:manifestcheck:children 3 do not match: application
```

Thus, the manifests usually do not compare correctly. Which means one would either do not compare attribute values or do some magic in androguard to resolve all these values...
