### ISSUE TITLE
Is Android Namespace aware?

### ISSUE THREAD

**Issue by reox** [androguard/androguard#595]
Some Manifest files seem to have a broken attribute name. See for example this file: https://github.com/androguard/androguard/blob/8de05b03af2b363b436cfa7646ab1bbfd4ddb13a/examples/axml/AndroidManifest_NamespaceInAttributeName.xml

they wrote the namespace string into the attribute and have the URI == -1:

```
Name 'android:versionName' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:minSdkVersion' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:targetSdkVersion' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:name' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:name' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:name' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:name' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
[...]
```

I thought this would not be correctly read by Android, but it does. On a Android 8 phone, all listed permissions are granted to the application on installation.
How does this work? Does the Android parser not check the attribute names?
In this case, we would need to check if the name is a compound of ns prefix and attribute name, then split it and check if there is a correct namespace mapping for this prefix.

Anyone has details how the Manifest Parsing works on android?

**Comment by kneep** [comment]
Can you elaborate what you think is wrong with the example manifest? I just don't get it. Isn't the 'android:' required?

**Comment by reox** [comment]
The resource chunk based XML / AXML format (or however it is called) distinguishes between the namespace URI, namespace prefix and attribute/element name.
In the case of the string `android:foobar`, `foobar` is the name and `android` is the namespace prefix. Thus, there must be some `xmlns:android='some_uri'` defined in order to have a functional XML.

In the AXML format an element or attribute chunk contains the following information: the namespace URI and the name. To get the prefix, there is a special chunk which maps the namespace uri to a prefix. So this is the `xmlns: ...` attribute.
That means, the attribute/element name's namespace is solely constructed by the URI and the mapping between namespace URI and prefix is just needed to generate a plain XML file out of it.
lxml handles this very elegent IMO, by not relying on the mapping at all but simply specifying the URI. A correct mapping can then provided later or can be autogenerated. The default for lxml is, to specify namespace prefixes with `ns00`, `ns01`, ...

Okay, so far for the mapping issue.
Now for these broken files: The problem here is, that they specify a prefix inside the name. In XML a colon is forbidden inside a name, thus `android:foobar` is not a valid name but a prefix + a name.
In these files, the namespace URI is 0xFFFFFFFF, thus unset. That means they say, the attribute/element name is `android:foobar` and there is no namespace.
Now it gets even more weird: Take a look at the output of aapt dump xmltree:
```
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=2)
    A: android:versionCode(0x0101021b)=(type 0x10)0x1
    A: :(0x0101021c)="1.0" (Raw: "1.0")
    A: package="jyiaivi.ohduxbbylb" (Raw: "jyiaivi.ohduxbbylb")
    E: uses-sdk (line=6)
      A: :(0x0101020c)=(type 0x10)0x8
      A: :(0x01010270)=(type 0x10)0xa
    E: uses-permission (line=9)
      A: :(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw: "android.permission.WRITE_EXTERNAL_STORAGE")
    E: uses-permission (line=10)
      A: :(0x01010003)="android.permission.WRITE_SECURE_SETTINGS" (Raw: "android.permission.WRITE_SECURE_SETTINGS")
    E: uses-permission (line=11)
      A: :(0x01010003)="android.permission.READ_PHONE_STATE" (Raw: "android.permission.READ_PHONE_STATE")
    E: uses-permission (line=12)
      A: :(0x01010003)="android.permission.CHANGE_WIFI_MULTICAST_STATE" (Raw: "android.permission.CHANGE_WIFI_MULTICAST_STATE")
    E: uses-permission (line=13)
[...]
```

Here, the attribute names are simply missing! 
as a comparison, this is what androguard decodes:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" versionName="1.0" package="jyiaivi.ohduxbbylb">
  <uses-sdk minSdkVersion="8" targetSdkVersion="10"/>
  <uses-permission name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission name="android.permission.WRITE_SECURE_SETTINGS"/>
  <uses-permission name="android.permission.READ_PHONE_STATE"/>
  <uses-permission name="android.permission.CHANGE_WIFI_MULTICAST_STATE"/>
[...]
```

So aapt has a problem with these attribute names but if you install this application on an android device, it will list all the permissions! Thus, there is a very significant difference between aapt and android. Somehow Android does not check if the name is valid or "fixes" this issue by linking the prefix inside the name to the namespace.

Obviously `android:foobar` is not correct but the question is should the name be `foobar` and no prefix or should we fix the namespace mapping and make `android` a prefix - but what is the correct URI then? Should we look it up in the mapping, but what if there is no mapping (like in the newer manifest files for example by google chrome)?
And why does the android system let such files be installed and grants the permissions?

**Comment by subho007** [comment]
This is true @reox and that is why I keep a check if namespace is required or not. Check my this commit: https://github.com/appknox/pyaxmlparser/pull/34/commits/f6130dd70a8dea368fc79ae4c39e1a4c1736df31 for the core.py file

This is not so elegant, but if you have something else in mind, let me know.

**Comment by reox** [comment]
@subho007 so android basically does not care about the namespace?
Does anyone can hint me to the code in AOSP where the AndroidManifest.xml is parsed?

**Comment by reox** [comment]
@subho007 I noticed today that the new functions will always use the namespace now - which is probably fine. But do you know if there are any attributes which do not use a namespace? I.e. which used `get_elements(..., with_namespace=False)`?

**Comment by reox** [comment]
@subho007 ah, nevermind.... you can still use tag.get() if you require the exact match!

**Comment by eighthave** [comment]
Here's a test case, a valid APK from Google Play:
[com.car2go_129215.apk.zip](https://github.com/androguard/androguard/files/3096080/com.car2go_129215.apk.zip)
