### ISSUE TITLE
How to check if a certain interface is implemented in an apk?

### ISSUE THREAD

**Issue by kneep** [androguard/androguard#604]
I would like to check if the X509TrustManager interface in Android is implemented in an apk. If yes, will do more check for the code. Is there a way to do this? I checked the code but have no clues :(.

**Comment by kneep** [comment]
The ‘interface’ here doesn’t mean method. It means the Java concept interface which can be subclassed. X509TrustManager is such a interface. I would like to check if it there is any class in an apk implementing this interface. This is the first step.

**Comment by reox** [comment]
So you want to find all classes which do this:
```
class Foobar implements X509TrustManager {
 ...
}
```
?
Or do you want any usage of an X509TrustManager like:

```
X509TrustManager foo = someFunctionWhichReturnsATrustManager();
```

You can try this one: https://androguard.readthedocs.io/en/latest/api/androguard.core.analysis.html#androguard.core.analysis.analysis.Analysis.find_classes

```
dx.find_classes("Ljavax/net/ssl/X509TrustManager;")
```

**Comment by kneep** [comment]
The first is what I want. Will this code return all the subclasses of this interface?

**Comment by reox** [comment]
this should work for you:
```
from androguard.misc import AnalyzeDex

h, d, dx = AnalyzeDex('x509.dex')

for c in dx.get_classes():
    if c.is_external():
        continue

    if 'Ljavax/net/ssl/X509TrustManager;' in c.orig_class.interfaces:
        print(c.orig_class.get_name())
```
The dex file (it is zipped)
[x509.zip](https://github.com/androguard/androguard/files/2763772/x509.zip)

**Comment by kneep** [comment]
Thanks. That works. Actually I did skim the `ClassDefItem` class to see what I can use but overlooked the `get_interfaces` method :(. 

I have two more questions:
1. For the latter case you mentioned above, is the answer just to call ClassAnalysis.xref_from() to check who really initiates an instance of X509TrustManager?
2. How to check if a method throws a certain class of exception? For example, the `checkClientTrusted` of `X509TrustManager` must throw `IllegalArgumentException` or `CertificateException` in at least one of its code branches.

**Comment by reox** [comment]
ad 1): If the class is referenced somewhere, it should end up as an external class in the Analysis object.
Thus, you should be able to search for it like `dx.find_classes('Ljavax/net/ssl/X509TrustManager;')`.

ad 2): this is really tricky right now. It _should_ be implemented somewhere in the basic blocks but I need to figure out how this works.
There is also `MethodAnalysis` and `MethodClassAnalysis` which confuses me (and probably every one else too) which I belive should be merged some day (see #412 )
But inside `MethodAnalysis` should be the logic to detect exception handling using `BasicBlock`.

**Comment by reox** [comment]
Few minutes later: The exception part of MethodAnalysis is actually only try-catch handler.

**Comment by kneep** [comment]
Does the following code look good to you?
```py
                        # First there must be at least one 'throw' instruction.
                        instructions = encoded_method.get_instructions()
                        throw_found = False
                        result[class_name][method_name] = 'false'

                        for instruction in instructions:
                            inst_name = instruction.get_name()
                            # There should be at least one throw
                            if inst_name == 'throw':
                                throw_found = True
                                break
                        if not throw_found:
                            continue
                        # Secondly check if any Exception class is in xref_to
                        method_analysis = class_analysis.get_method_analysis(
                            encoded_method)
                        xrefs = method_analysis.get_xref_to()
                        for xref in xrefs:
                            if xref[1].get_class_name() == 'Ljava/security/cert/CertificateException;' and xref[1].get_name() == '<init>':
                                break
```

**Comment by kneep** [comment]
Hi @reox , just another question. Assuming two external classes A and B, is it possible for androguard to know if B is a subclass(either direct or indirect) of A?

**Comment by kneep** [comment]
> I think this would work.
> 
> One problem could be, if the thrown exception is not a direct instance of CertificateException. In this case you would need to check the class if it is a subclass. But I'm not sure how common this would be...

I think the signature of the interface assures its implementation only throw `CertificateException` or its subclasses. So I simply removed the class name check.

A corner case that could break this code is that A implements `X509TrustManager` and B subclasses A. In this case, B does not have `Ljavax/net/ssl/X509TrustManager` in its `vm_class.get_interfaces()`. So far I don't find a simple way to identify B as an `X509TrustManager`.

**Comment by reox** [comment]
yes this is true. You would need to check each class for the parent class, up to the point where the parent class is java.lang.Object.
But there is a problem if you encounter ever an external class: there the interfaces and inheritance is not known for a static decompiler...
