### ISSUE TITLE
androgui is actually external

### ISSUE THREAD

**Issue by reox** [androguard/androguard#636]
I found out, that the androgui is actually partially external: https://github.com/mtivadar/qiew

See the commit of ee4e54a1ec145f1be5ac181738aea348517f1747

That these source codes are actually copied is not mentioned anywhere. Is this a problem? qiew is released as GPLv2
@eighthave Do you know how to deal with this licensing? From what I see, we are violating GPLv2 here...

**Comment by reox** [comment]
Reading this: https://dwheeler.com/essays/floss-license-slide.html
Thus, using GPLv2 code is impossible for us.

Therefore we need either to have qiew use another licence or remove this code from androguard, right?

**Comment by eighthave** [comment]
It is fine to include any kind of collection of source code with mixed
up licenses.  Any potential conflicts come with the binaries.  Any
binary packages that include the GPLv2 and Apache-2.0 code will have the
GPLv2 license.  Like that diagram shows, Apache-2.0 is compatible with
the GPLv2.

If someone wants an Apache-2.0-licensed binary package, they will have
to leave out the GPLv2 licensed code.

FYI, there is also LGPL-3 code in there already, see:
https://salsa.debian.org/python-team/modules/androguard/blob/master/debian/copyright

Also, are you sure that commit in androguard included code from Qiew?
Perhaps it just included constants.  Constants are facts, and facts or
collections of facts are not copyrightable.

**Comment by reox** [comment]
> It is fine to include any kind of collection of source code with mixed up licenses. Any potential conflicts come with the binaries.

So as this is python, we are fine as usually bytecode is never packaged but always the .py files - which are sourcecode?

>  Any binary packages that include the GPLv2 and Apache-2.0 code will have the GPLv2 license. Like that diagram shows, Apache-2.0 is compatible with the GPLv2.

ah okay, I thought this diagram reads like "if there is a connection, you can combine code, and the target of the arrow is the new licence". As there is no connection between Apache 2.0 and GPLv2 you can not mix?

>  Also, are you sure that commit in androguard included code from Qiew?

yes, `Banners.py BinViewMode.py DataModel.py DisasmViewMode.py HexViewMode.py TextDecorators.py TextSelection.py ViewMode.py cemu.py search.ui annotation.ui` are directly copied (and modifed) from qiew. `binwindow.py` in androguard is partially `qiew.py`.

> FYI, there is also LGPL-3 code in there already, see:

It looks like that androguard was originally licenced as (L)GPLv3, which was changed in 6cf11e1b3d0a0adf91ea1ce94b49bddd56c8a4cf and c04c3714fed2e57db56aa6162090ed4e43608565
Maybe these files are actually leftovers from this change?

**Comment by eighthave** [comment]
I guess there is a conflict between Apache-2.0 and GPLv2-only.
https://www.apache.org/licenses/GPL-compatibility.html

But if it is GPLv2-or-later, then the binary combination would become
GPLv3-or-later licensed.  Debian actually compiles bytecode .pyc on
installation.

Sounds like the project should be labeled as GPL-3-or-later since that's
the most likely license that is compatible with all the code that is
included.  That change is fine by me.  But as long as all the bits are
labeled with their copyright and license, it is OK have the
mixed-license source code in one repo.

**Comment by reox** [comment]
qiew is unfortunately GPLv2 without or later...

so yeah, we need to label the code correctly.

**Comment by eighthave** [comment]
I only found "GPLv2" listed in the Qiew code, and the LICENSE file and the link to the license both point to the standard GPLv2 which is GPLv2-or-later.  I found no specific declaration of GPLv2-only.  GPLv2-or-later is the default also.  So I documented the licenses like this:
https://salsa.debian.org/python-team/modules/androguard/commit/9b63d95279c1b392d6db344df22f3788a6c2e347

**Comment by reox** [comment]
okay, did not knew that this is the default!

But not all files in gui are from qiew. Some are from the "old" gui.
