### ISSUE TITLE
replace native encoding with little-endian

### ISSUE THREAD

**Issue by reox** [androguard/androguard#644]
Most parsers in androguard use native encoding setting in struct.unpack, which is not un-correct, as most architectures are little-endian.
But for correctness, they should be changed to little-endian, in order to circumvent problems.

There is also an endian marker in the DEX file which is afaik not checked.

**Comment by Neakxs** [comment]
Endian tag seems to be checked in `HeaderItem` :

https://github.com/androguard/androguard/blob/984c0d981be2950cf0451e484f7b0d4d53bc4911/androguard/core/bytecodes/dvm.py#L501-L503

Maybe we can add support of big-endian DEX files when refactoring `struct.unpack` usage

**Comment by reox** [comment]
I never ever saw any DEX file using Big Endian.  I would be very surprised if AOSP is even capable of parsing such files.
Thus, I would not bother with big endian at all.
