### ISSUE TITLE
Strings do not have an offset where they are referenced?

### ISSUE THREAD

**Issue by kneep** [androguard/androguard#657]
I just don't find such a thing. I think it is quite useful as that of a class or method. Can we add that?

**Comment by reox** [comment]
yep that sounds good. Xrefs are a little bit unstructured right now...

**Comment by kneep** [comment]
Yes. I noticed some new sections were added recently.

**Comment by reox** [comment]
In the current master, there is now a switch to get the offset of the string usage: https://androguard.readthedocs.io/en/latest/api/androguard.core.analysis.html#androguard.core.analysis.analysis.StringAnalysis.get_xref_from
