### ISSUE TITLE
how to get a function's annotation?

### ISSUE THREAD

**Issue by gygl09** [androguard/androguard#66]
in Java, there are some annotations, like @ override @ javascriptinterface. is it possible to get these annotations using androguard?

**Comment by subho007** [comment]
You should know @javascriptinterface is a wrapper method. You should do a taint search of method "addJavascriptInterface"

**Comment by gygl09** [comment]
ClassDefItem.get_annotations_off()

another useful doc is https://source.android.com/devices/tech/dalvik/dex-format.html
