### ISSUE TITLE
Does anyone know the principle of Androrisk risk assessment? Ask for your help

### ISSUE THREAD

**Issue by 15601099033** [androguard/androguard#665]
Does anyone know the principle of Androrisk risk assessment?

**Comment by reox** [comment]
I havn't heard that name in years...

Androrisk used to gather some red flags and calculate some score.
But all of that would highly depend on the flags beeing updated regulary (i.e. each new API release) and the score would depend on how "risky" someone would decide an action was.
Thus it was removed.

But you can still access the code via git and take a look.

Do you have any specific question about androrisk?

**Comment by 15601099033** [comment]
Do you know how to calculate the fuzzy risk value of this software? Is the method of fuzzy comprehensive evaluation used? How to assign value? If you want to change, what will change more correctly. Thank you for your explanation. I don't know anything.

**Comment by reox** [comment]
That really depends on what you want to do...

I would try to find some research papers covering the topic and adjust this to your needs.
