### ISSUE TITLE
When I run androlyze.py, I receive an error

### ISSUE THREAD

**Issue by ClickListener** [androguard/androguard#668]
### Describe what you wanted to do

I use `pip3 install androguard` commend install the androguard, and successfully. But when I run `androlyze.py`,  I receive an error
```
zhangxudeMacBook-Pro:bin zhangxu$ python3 androlyze.py 
Traceback (most recent call last):
  File "androlyze.py", line 47, in <module>
    androlyze_main(args.debug, args.ddebug, args.no_session, args.apk)
TypeError: androlyze_main() takes 2 positional arguments but 4 were given
```

### System Information

- Androguard Version: 3.3.5
- Python Version:3.7
- Operating System :macos 10.14.3

what should I do for this error?

**Comment by ClickListener** [comment]
I have got the solution. I run `androguard analyze` command， and I find the `<function androguard.cli.main.androlyze_main(session, filename)>`，`androlyze_main()` method just have two argument,but the `androlyze.py` file use `androlyze_main(args.debug, args.ddebug, args.no_session, args.apk)` .  but I don't kown where is the `androlyze_main()` declared.  so can you fixed this issue?

**Comment by reox** [comment]
But does `androguard analyze` works? I guess the problem are some new features of the analyze command, which I have forgotten to backport to the legacy tool `androlyze`.
If you can, use `androguard analyze` as the standalone tools will probably be removed someday.

**Comment by ClickListener** [comment]
@reox It works. By the way, Do you know how to auto search which Activity in APK using which permission?

**Comment by reox** [comment]
ok, I'll try to fix the standalone tools then.

For the permissions: there is currently no automated way, but this might help you: https://github.com/androguard/androguard/issues/222

**Comment by ClickListener** [comment]
@reox Thank you for your fast feedback. And I have found `androguard/core/bytecodes/` carefully, but I can't find `api_permissions.py` any more.   Did your last reply mean : For now, we just can get all permission which APK set in androidmanifest.xml file, but could not get extract the used permissions. 
Can you confirm to me if I'm right? 
By the way, is there a method replace `show_Permissions(dx)`?

**Comment by reox** [comment]
Ahh I see, there was some refactoring, thus this file was moved...

I just created two new methods in the Analysis class to deal with this issue: `get_permssions` and `get_permission_usage`: #670 

It would be nice if you could test them a little bit and tell me what you think!

**Comment by ClickListener** [comment]
@reox OK, I have seen the last commit. Can I update androguard by pip3? Or just test it by download origin code of branch-master, and use command `python3 setup.py install` to install?

**Comment by reox** [comment]
you can use pip to clone from git like this: 
```
pip install git+https://github.com/androguard/androguard.git
```
See https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

**Comment by ClickListener** [comment]
@reox OK, I will it and test it! If I find something, I will feedback at the fast time. Thank you very much!

**Comment by ClickListener** [comment]
@reox It works!  And would you like consider this: Could you provider an API that can output all usage of permissions in androidmanifest.xml. It will very convenient of user.

**Comment by reox** [comment]
Yes, i think that would be useful, but for best flexibility it needs some other changes as well...

For now you could do something like:
```
for perm in a.get_aosp_permissions():
    dx.get_permission_usage(perm, a.get_effective_target_sdk_version())
```

**Comment by ClickListener** [comment]
@reox OK！Thank you very much!

**Comment by ClickListener** [comment]
@reox Ask one more question. Do you have plan of updating the `aosp_permissions` and `api_permission_mappings`?

**Comment by reox** [comment]
yes this is always the plan... But as we depend on other tools to produce this, we are always lacking support for the newest API levels.

**Comment by SamiraSadat** [comment]
Hi..:(
i have gotten the error too, what happens! and what should we do? is there any way to introduce our apk grammatically? i need it soon, it's force for me, i want to introduce some apk and extract API sequence from dex file? is it possible with androguard or not!?

this is the error:

Traceback (most recent call last):
  File "androlyze.py", line 47, in <module>
    androlyze_main(args.debug, args.ddebug, args.no_session, args.apk)
TypeError: androlyze_main() takes 2 positional arguments but 4 were given

**Comment by reox** [comment]
@SamiraSadat please use `androguard analyze` instead of `androlyze.py`!

**Comment by SamiraSadat** [comment]
Thanks. And one more question:
How can I run androguard analyze in python?
I import the androguard module but when I want to run the above code, I got a error.
Ii seems it works just in cmd.
If you guide me how to run it in python . I will be so thankful::)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by SamiraSadat** [comment]
> @SamiraSadat please use `androguard analyze` instead of `androlyze.py`!
> 
> Or use the master branch, where `androlyze` is fixed.

androguard analyze doesn't run in python environment. I got the result in cmd, but not python. how to use in python environment?

**Comment by reox** [comment]
@SamiraSadat I dont understand the question. What do you mean with it does not run?
Have you installed androguard already?

**Comment by SamiraSadat** [comment]
> @SamiraSadat I dont understand the question. What do you mean with it does not run?
> Have you installed androguard already?

Yes, i did. and also import androguard using this:
>>> import androguard.
let me clear my scenario.
 I have about 5 APK in a directory. Want to write a code in which disassemble apk to get DEXs. 
Then, from dex file extracts sequence of API method calls.
To Do this, i change '.apk' to '.zip' (extension), later unzip them to extract dex files. beacuse they had the same name i renamed the dex files with the application's name. This is the code:
>>> import os
In [2]: os.chdir('H:\CICAndMalDataset\Sample')
In [3]: from zipfile import ZipFile
In [4]: for f in os.listdir():
   ...:     file_name, file_extension = os.path.splitext(f)
   ...:     with ZipFile (f, 'r') as zipobj:
   ...:         zipobj.extract('classes.dex')
   ...:         os.rename('classes.dex', file_name+'.dex')
 
and this the dex file i printed below:
>>> for d in os.listdir():
            print(d)

com.challengerx.dex
com.chase.sig.android.dex
com.ChatFriendforKiK.dex
com.chatgum.chat.rooms.dex
com.chatous.chatous.dex
____________________________________________________________________________________________

Now, i'm interested to extract classes, methods, and API calls using "androguard". At the end, i want to have a suence of API method calls. to Do this, i write a loop in you see below:
for d in os.listdir():
    classes = d.get_classes()
    for c in classes:
        methods = c.get_methods()
        for m in methods:
    ...:     for _, call, _ in m.get_xref_to():
    ...:         print(call.name)

i don't know which sub module must be added in order the python recognize that items in the directory is a dex file. how to do it...?
and the problem is that the order of the algorithm is N**4 and awful. 
As a expert , what do you suggest me?

thank you in advance.

**Comment by reox** [comment]
You might want to take a look at https://androguard.readthedocs.io/en/latest/intro/bulk.html#using-androauto
