### ISSUE TITLE
Clarification of Supported File Formats for Callgraphs

### ISSUE THREAD

**Issue by bushidocodes** [androguard/androguard#672]
Firstly, thank you for all your work on this project! It's very useful!

I'm trying to use androguard to generate a callgraph, and the documentation for using androguard as a CLI tool mentions that the extension of the output file determines the format that is use, but it does not say which extensions are supported. 

Can you please clarify the file formats that are supported and the associated file extensions that the tool looks for?

Thanks!

Current state of docs is below:

```
Usage: androguard cg [OPTIONS] [APK]

  Create a call graph and export it into a graph format.

  Example:

      $ androguard cg APK

Options:
  -o, --output TEXT           Filename of the output file, the extension is
                              used to decide which format to use (default
                              callgraph.gml)  [default: callgraph.gml]
```

**Comment by reox** [comment]
all formats which are understood by networkx: https://networkx.github.io/documentation/stable/reference/readwrite/index.html

currently gml, gexf, gpickle, graphml, yaml and net are supported.

And you are right, this is missing in the documentation!

**Comment by bushidocodes** [comment]
To confirm, that corresponds to the following file extensions, right?
*.adjlist
*.edgelist
*.gexf
*.gml
*.gpickle
*.graphml
*.json
*.yaml
*.net

The NetworkX lib lists a bunch of different types of data that serialized into JSON, so it's not clear what one would be requesting if I used that file extension.

**Comment by reox** [comment]
See
https://github.com/androguard/androguard/blob/master/androguard/cli/main.py#L111-L117

To implement json, you would need to choose a writer method of networkx and implement it there...
