### ISSUE TITLE
AttributeError: 'EncodedMethod' object has no attribute 'get_xref_to'

### ISSUE THREAD

**Issue by SamiraSadat** [androguard/androguard#680]
i wanr to extract api method calls from apps.
this is my code:
### for a in os.listdir():
    app = apk.APK(a)
    dex = dvm.DalvikVMFormat(app)
    for meth in dex.get_methods():
          for _, call, _ in meth.get_xref_to():
                print("  calling -> {} -- {}".format(call.class_name, call.name))
but i got an error: 
AttributeError: 'EncodedMethod' object has no attribute 'get_xref_to'
 how to fix it

**Comment by reox** [comment]
you need to run the xrefs on `MethodClassAnalysis`: https://androguard.readthedocs.io/en/latest/intro/xrefs.html

**Comment by SamiraSadat** [comment]
> you need to run the xrefs on `MethodClassAnalysis`: https://androguard.readthedocs.io/en/latest/intro/xrefs.html

would you please show me how to add this part to my code...? i got confused.

**Comment by reox** [comment]
So instead of
```
app = apk.APK(a)
dex = dvm.DalvikVMFormat(app)
for meth in dex.get_methods():
      for _, call, _ in meth.get_xref_to():
            print("  calling -> {} -- {}".format(call.class_name, call.name))
```

you simply do:
```
from androguard.misc import AnalyzeAPK
app, list_of_dex, dx = AnalyzeAPK(a)
for meth in dx.get_methods():
      for _, call, _ in meth.get_xref_to():
            print("  calling -> {} -- {}".format(call.class_name, call.name))
```

Note, that `AnalyzeAPK` returns a `list(DalvikVMFormat)`, as there might be multiple DEX files in the APK. But `Analysis` bundles them together.

**Comment by SamiraSadat** [comment]
> So instead of
> 
> ```
> app = apk.APK(a)
> dex = dvm.DalvikVMFormat(app)
> for meth in dex.get_methods():
>       for _, call, _ in meth.get_xref_to():
>             print("  calling -> {} -- {}".format(call.class_name, call.name))
> ```
> 
> you simply do:
> 
> ```
> from androguard.misc import AnalyzeAPK
> app, list_of_dex, dx = AnalyzeAPK(a)
> for meth in dx.get_methods():
>       for _, call, _ in meth.get_xref_to():
>             print("  calling -> {} -- {}".format(call.class_name, call.name))
> ```
> 
> Note, that `AnalyzeAPK` returns a `list(DalvikVMFormat)`, as there might be multiple DEX files in the APK. But `Analysis` bundles them together.

TnQ. and is it possible to write the output in a txt file...?

**Comment by reox** [comment]
Sure, whatever you like. Just take a look at the python documentation: https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

**Comment by SamiraSadat** [comment]
> Sure, whatever you like. Just take a look at the python documentation: https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

Thanks. i did it, but there is an other issue. for 5 apk file it tooks about 78 seconds and i have about 2500 sample. that will be run in almost 12 hours. it's too slowwwwwwww:(
isn't any other way to run fast?

**Comment by reox** [comment]
Depending what you want to extract, androguard is slow. There are some optimizations in the PR queue, but they do not help in all cases.

You can try to run it in multiple cores too. Usually one run per CPU is fine.
