### ISSUE TITLE
Examples for DEX 038 and 039

### ISSUE THREAD

**Issue by reox** [androguard/androguard#682]
I really can't find any apps using Dalvik 038 or 039 format. Even 036 and 037 are very rare.

@androguard/external-contributors Does anyone can provide some examples?

Out of curiosity: there are rumors about older version than 035. I mean official versions from the pre Android 1.0 era not malware try to do crazy stuff. Anyone has such samples by chance?

**Comment by reox** [comment]
btw open source apps would be appreciated in order to write better testcases.

**Comment by Neakxs** [comment]
I've found the library https://github.com/square/okhttp which is Dalvik 038 when compiled with _dx_

**Comment by reox** [comment]
@Neakxs thanks for the hint! I'll try that!

@eighthave I also scanning fdroid right now - our favorite datamining set :D - looks like there are also a few samples having 037 and 038. No 039 so far... I'll keep you posted!

**Comment by reox** [comment]
@eighthave thats reallt interesting: out of 22k files, only 4 have a different dex version than 035... the new versions are really not that common,

**Comment by eighthave** [comment]
I know little about the updated DEX formats.  Perhaps they've only added
extensions since 035, so most apps don't need them.

**Comment by reox** [comment]
@eighthave yes, the new stuff is only required if you use new java features. AFAIK it is used when using lambda expressions or other dynamic stuff... But it is also quite hard to find an example which will compile with the new opcodes. I have one example where dx would use them but d8 does not.

I found out that setting the minimal API level for dx or d8 has an effect on the DEX version. Thus, only apps with very high minimal API levels will actually compile to a new DEX version, hence the rare versions.

**Comment by eighthave** [comment]
Ah right, yeah, minSdkVersion will for sure enforce the DEX version,
since new DEX updates would not be shipped to older Android versions.

**Comment by FloatingGuy** [comment]
@reox  i use  androguard (3.3.5) to static analysis  android system app. The Android 9 (Pie) release has introduced a new type of Dex file, the Compact Dex (Cdex). 
i use  the "compact_dex_converter" tool   to convert a Cdex file back to standard Dex, the dex version is dex.039.  
[classes.zip.tar.gz](https://github.com/androguard/androguard/files/3723432/classes.zip.tar.gz)

**Comment by reox** [comment]
@FloatingGuy thanks for the APK!

What I would also really need is an APK which contains the `invoke-polymorphic` and `invoke-polymorphic/range` opcodes...

**Comment by zzzzfeng** [comment]
@reox here is a apk with dex.039
[com.miui.securitycore.zip](https://github.com/androguard/androguard/files/3823696/com.miui.securitycore.zip)

**Comment by neomafo88** [comment]
VirusTotal Livehunt rule is another resource to conduct a survey about DEX file Dalvik versions
