### ISSUE TITLE
Thoughts on bytecode output in disassembler

### ISSUE THREAD

**Issue by reox** [androguard/androguard#683]
The output format of the bytecode is not very consistent and also in some cases misleading.
For example, there are some fields which are parsed as float, although they are not really float (not in any case at least) or offsets are given in hex but are usually not denoted as such.

I propose that we rework the bytecode output.

Current ideas:

* offsets should always be given in decimal notation with explicit sign (i.e. +23, -42).
* Other idea: offsets are written in hexadecimal with explicit sign and suffixed `h` (i.e. +17h, -2ah)
* The unit for offsets is bytes or 16bit units or instructions? In the bytecode it is 16bit units... therefore I would use them to allow easier tracing of stuff. The couting offset should correspond to this unit
* constant values are always given in the format denoted in the dalvik documentation - that means there is no interpretation at this stage what kind of format the constant could be
* registers are written as `vX` (just like they are right now)
* parameters are written as `pX` (just like they are right now)

@androguard/external-contributors what are your thoughts here? Do you have links to existsing notations which work great? Maybe be more like smali?

**Comment by reox** [comment]
fixed the float stuff - the values should make now more sense,.

**Comment by subho007** [comment]
What is your progress with this?
