### ISSUE TITLE
Is there a way to get opcodes from the dex files?

### ISSUE THREAD

**Issue by zqkFrank** [androguard/androguard#685]
I want to acquire the get opcodes from the dex files, is there a  way to get?  Thanks!

**Comment by reox** [comment]
what exactly are "get opcodes"? Do you mean the sget-\*, iget-\* and aget-\* opcodes?

anyways, you can iterate over all methods and then over the opcodes:

```
a,d,dx = AnalyzeAPK('some_apk')
for m_a in dx.get_methods():
    m = m_a.get_method()
    if m_a.is_external():
        # External methods do not have opcodes
        continue
    idx = 0
    for ins in m.get_instructions():
        # You can access the instruction here and do stuff with it... 
        print('{:08x}  {:04x}  {:24s} {}'.format(idx, ins.get_op_value(), ins.get_name(), ins.get_output()))
        idx += ins.get_length()
```                        

For more information on the instructions see https://androguard.readthedocs.io/en/latest/api/androguard.core.bytecodes.html?highlight=Instruction#androguard.core.bytecodes.dvm.Instruction

**Comment by zqkFrank** [comment]
Very thanks for your help! It helps a lot. Excuse me, if I want to extract the features of API calls, what should I do? Thanks!

**Comment by reox** [comment]
What exactly do you mean? All external methods can be somehow regarded as API.
Therefore just search for external methods:
```
a,d,dx = AnalyzeAPK('apkfile')
for x in dx.get_external_classes():
    for m in x.get_methods():      
        print(m.get_xref_from())
```

**Comment by zqkFrank** [comment]
When I  want to obtain opcodes I executed the codes you provided above.  However I don't know the purpose of the function  of  ins.get_output().  And the document says that  "Return an additional output of the instruction",  I'm not sure the means of  "Return an additional output of the instruction" and the means of this function? Could you explain it in detail? thanks!

**Comment by reox** [comment]
https://source.android.com/devices/tech/dalvik/dalvik-bytecode

take a look at _Human-syntax and mnemonics_

For example: `invoke-virtual {vC, vD, vE, vF, vG}, meth@BBBB`

`invoke-virtual` is the opcode mnemonic, availabe via `get_name()`
`{vC, vD, vE, vF, vG}, meth@BBBB` are the arguments or the output, available via `get_output`.
