### ISSUE TITLE
No pyqt5 found exiting!!!!

### ISSUE THREAD

**Issue by SivertPL** [androguard/androguard#687]
What the fuck is this shit?
I've installed pyperclip and pyqt5 using
pip3 install pyperclip pyqt5
esktop/kroot2$ androguard gui
No PyQT5 found! Exiting...

using latest kubuntu

**Comment by reox** [comment]
How did you install androguard? Which version of androguard are you using?

please check if this works:
```
$ python
Python 3.7.2rc1 (default, Dec 12 2018, 06:25:49) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
```
