### ISSUE TITLE
Some call graphs are empty, some with no links and some has relationship.

### ISSUE THREAD

**Issue by SamiraSadat** [androguard/androguard#692]
Hi..)
First of all, thank you for responding the past issues.
Then, I used your codes (written in issues 464) to draw call graph. I tried for some classes and surprised why some of the graphs are empty, some with several nodes but no links between them, and some with nodes and links between them,

How do you describe it...?

**Comment by reox** [comment]
> How do you describe it...?

please provide a sample, the command you are using and maybe upload the callgraphs here!

**Comment by SamiraSadat** [comment]
This is the command:

```
def DRAW_CALL_GRAPH(ap):
    file = open('H:\ReverseEngineering\Sample\Call_Graph\Landroid_view_accessibility_AccessibilityRecord.txt', 'w')
    app, list_of_dex, dx = AnalyzeAPK(ap)
    CFG = nx.DiGraph()
    for m in dx.find_methods(classname="Landroid/view/accessibility/AccessibilityRecord;"):
        orig_method = m.get_method()
        file.write("Found Method --> {}".format(orig_method) + '\n')
        if isinstance(orig_method, ExternalMethod):
            is_this_external = True
        else:
            is_this_external = False
        CFG.add_node(orig_method, external=is_this_external)
        for other_class, callee, offset in m.get_xref_to():
            if isinstance(callee, ExternalMethod):
                is_external = True
            else:
                is_external = False
            if callee not in CFG.node:
                CFG.add_node(callee, external=is_external)
            if not CFG.has_edge(orig_method, callee):
                CFG.add_edge(orig_method, callee)
    nx.draw_networkx(CFG)
    plt.draw()
    plt.show()
            
for f in os.listdir():
    DRAW_CALL_GRAPH(f)

**Comment by SamiraSadat** [comment]
And these are the plots:

![Landroid_support_v4_accessibilityservice_AccessibilityServiceInfoCompat](https://user-images.githubusercontent.com/45191491/57755675-b57eb580-7706-11e9-98ab-77dc11bd69ba.png)
![Landroid_view_accessibility_AccessibilityDelegateCompat](https://user-images.githubusercontent.com/45191491/57755676-b6174c00-7706-11e9-9847-0346378ffbda.png)
![Ljava_lang_StringBuilder](https://user-images.githubusercontent.com/45191491/57755678-b6174c00-7706-11e9-81c2-898a6aea2f5d.png)

**Comment by reox** [comment]
Okay, If I understood you correctly, you would like to generate a call graph for all methods from the class `Landroid/view/accessibility/AccessibilityRecord;`?

I had some APK here, but what I see is, that all methods in this class are external, thus there is no `xref_to`.

You can test to dump the code of the method to check if it is really empty.

**Comment by SamiraSadat** [comment]
Yes, Righ:) I want to draw a call graph for all methods of a specific class.
But how can we edit the code in order to separate the external and internal method with two different colors just like your documentation...?
![screenshot_182951](https://user-images.githubusercontent.com/45191491/57763637-08606900-7717-11e9-947c-6868d01440c2.png)

**Comment by reox** [comment]
The coloring is done via gephi. I just wrote the information into the nodes.

The problem is, if you specify an external class as the start, you must use `get_xref_from` instead of `get_xref_to`. The best would be to use both methods, to get all xrefs.

For example, you can get the same result by using `androgaurd cg`:
```
> androguard cg -o accessibility.gml --classname "Landroid/view/accessibility/AccessibilityRecord;" D:\tmp\base.apk
```

In this case, there are also no connections between the nodes.
I think I'll add a feature to collect the `xref_to` as well, in order to start with external methods.

**Comment by SamiraSadat** [comment]
You know, your '.py files' doesn't work in my system and I'm not interested to fix it.

**Comment by reox** [comment]
what are "my .py files"? You mean the androguard command?

**Comment by SamiraSadat** [comment]
Yes and also files such as 'androlyze.py' and other some.
You see the below. 
![Capture](https://user-images.githubusercontent.com/45191491/57767611-0ac6c100-771f-11e9-8ccd-00350449c722.PNG)

**Comment by reox** [comment]
is `APK` a file? I guess this is a folder? The command just works with a single file.

**Comment by reox** [comment]
I added some changes in #697 in order to print all xrefs. I also changed to a MultiDiGraph, so you can get some information about how often some xref is used.

**Comment by SamiraSadat** [comment]
I mean .apk
