### ISSUE TITLE
Remove MUTF8String decoding during Analysis

### ISSUE THREAD

**Issue by Neakxs** [androguard/androguard#694]
After running an analysis, I found out that this module decode MUTF8String objects during loading :

```
              Name               | TotTime  |  Calls   | Source

_create_basic_block              | 5.971508 |    77741 | analysis.py:353   
decode                           | 2.734008 |   233223 | mutf8.py:1     
<method 'match' of '_sre.SRE_Pat | 1.934750 |  9321734 |
get_name                         | 1.391285 |  9295715 | dvm.py:4058  
__init__                         | 1.163591 |   330950 | analysis.py:46    
get_instructions                 | 0.978675 |  1221727 | dvm.py:6403  
push                             | 0.881970 |  1143986 | analysis.py:177   
get_basic_block                  | 0.849655 |   241833 | analysis.py:240   
__init__                         | 0.786382 |   278862 | dvm.py:4594  
<method 'format' of 'str' object | 0.699736 |   641916 |
get_instruction                  | 0.639783 |  1141095 | dvm.py:6364  
get_instructions                 | 0.573447 |  3754860 | dvm.py:6532  
<built-in method builtins.chr>   | 0.488775 |  8922411 |
__init__                         | 0.350184 |     7497 | dvm.py:5176  
set_childs                       | 0.340317 |   254228 | analysis.py:158   
get_ins_off                      | 0.337355 |     3795 | dvm.py:6602  
__format__                       | 0.330624 |   797396 | mutf8.py:198   
<built-in method _struct.unpack> | 0.265196 |  2238376 |
string                           | 0.251999 |   797396 | mutf8.py:132   
__str__                          | 0.247739 |   155482 | dvm.py:2969  
```

I think it's possible to remove it and maybe improve the loading time.

**Comment by reox** [comment]
I found out that the change to MUTF8String breaks a lot of my existing scripts, for example as I iterate over all classname using `dx.classes.keys()`. Before, this would return a keyset of `str` in the form of `Lsdfsdf;`.
Now it returns the `MUTF8String`, thus I need to call `.string` on each of them to get the same result.

I get now the following error:
`TypeError: expected string or bytes-like object`

Do you know an easy way of providing backwards compatabilty? Is it possible to get the decoded string by default? I saw that you set all the `__xxx__` methods but maybe there is some other magic in python to make this work?

**Comment by reox** [comment]
Also, maybe change the `__repr__` to return `.string` instead. That would certainly help for printing the strings and will look the same.

**Comment by Neakxs** [comment]
> I found out that the change to MUTF8String breaks a lot of my existing scripts, for example as I iterate over all classname using `dx.classes.keys()`. Before, this would return a keyset of `str` in the form of `Lsdfsdf;`.
> Now it returns the `MUTF8String`, thus I need to call `.string` on each of them to get the same result.
> 
> I get now the following error:
> `TypeError: expected string or bytes-like object`

Can I have some examples in order to find a solution ?
As a quick solution, I would say to use `[i.string for i in dx.classes.keys()]`

> Do you know an easy way of providing backwards compatabilty? Is it possible to get the decoded string by default? I saw that you set all the `__xxx__` methods but maybe there is some other magic in python to make this work?

That was the point of setting special methods (`__eq__` allows comparison between `MUTF8String` and `str`). I don't see how to provide backwards compatibility without decoding strings yet


> Also, maybe change the `__repr__` to return `.string` instead. That would certainly help for printing the strings and will look the same.

We'll need to call `__str__` then since the `str` returned by `MUTF8String.string` is a unicode string

**Comment by reox** [comment]
It is usually when I use regexes on the thing:

```
from androguard.core import mutf8
import re
x = mutf8.MUTF8String(b'\x66\x31')
re.match(r'f\d+', x)  # fails with TypeError: expected string or bytes-like object
re.match(r'f\d+', x.string)  # works
```

**Comment by Neakxs** [comment]
Ok, I'll try something in #695.

It will probably involve `bytes` inheritance, thus regexes will work as is but it will require to use a bytes pattern

**Comment by reox** [comment]
mhh would it be possible to have it work with string instead? I must admit, these are the areas of python where I have not much knowledge :grinning:

**Comment by Neakxs** [comment]
Since I haven't found a way of using `re` with classes, it would involve that strings are decoded at creation and remove MUTF8String time improvements during parsing

However, it's possible to remove the `.string` property and use the `str()` function on any `MUTF8String` object

**Comment by reox** [comment]
mhh okay I guess using .string or str is the best we could do. Or add some wrapper method which provides a list of all classnames (as this is usually the requirement)

**Comment by reox** [comment]
I did some test, so it looks like you can either have one of the two:
```
import re


class Bar(str):
    def __init__(self, content):
        self.content = content

    def __str__(self):
        return self.content

    def __repr__(self):
        return self.content


print(re.match('hello.*', Bar('hello world')))


class Foo(bytes):
    def __init__(self, content):
        self.content = content

    def __str__(self):
        return self.content

    def __repr__(self):
        return self.content

print(re.match(b'hello.*', Foo(b'hello world')))
```

The dream would be to have one object which behaves like bytes or string depending on the context... But I guess that is just illusionary...

**Comment by Neakxs** [comment]
> The dream would be to have one object which behaves like bytes or string depending on the context... But I guess that is just illusionary...

I don't see how we could do that ...

**Comment by Neakxs** [comment]
@reox, I made some changes in #695 
`MUTF8String` is now a subclass of `bytes`
