### ISSUE TITLE
Can Androguard extract a context- or flow-sensitive call graph?

### ISSUE THREAD

**Issue by Ken-HUST** [androguard/androguard#698]
The call graph extracted by Androguard seems as a context- and flow- insensitive call graph which may be an inaccurate call graph. Therefor, can Androguard  extract a more accurate call graph? Thanks a lot!

**Comment by reox** [comment]
yes, you can extract CFG per method as well: https://androguard.readthedocs.io/en/latest/tools/androdd.html

In master you can also dump with the offsets of each call in the callgraph. Maybe that helps as well.

**Comment by Ken-HUST** [comment]
> yes, you can extract CFG per method as well: https://androguard.readthedocs.io/en/latest/tools/androdd.html
> 
> In master you can also dump with the offsets of each call in the callgraph. Maybe that helps as well.

I have tried FlowDroid to extract an app's call graph, which can ensure contexts and flows are preserved. Although the call graph is a more precise call graph, the efficiency is too low because FlowDroid is a static taint-based system. Therefor, what I want is to obtain a similar precise call graph as extracted by FlowDroid. When I tried Androguard to extract function call graph, I have found that the efficiency is really perfect. However, the call graph extracted by Androguard may not be as precise as by FlowDroid. So, can i obtain a  call graph by Androguard as precise as  by FlowDroid? Thanks a lot!

**Comment by reox** [comment]
I have not worked with flowdroid, can you quickly give some example what you want to achieve?

**Comment by Ken-HUST** [comment]
> I have not worked with flowdroid, can you quickly give some example what you want to achieve?

I have tried FlowDroid only for some days, so I am sorry I can't give you some examples. The job i'm doing is to implement the method by MaMaDroid (a paper publised in NDSS2017: Mamadroid: Detecting android malware by building markov chains of behavioral models).  The source code of MaMaDroid is public, and the extraction of call graph is based on Soot and FlowDroid. When I tried it, I have found the efficiency is too low. Then I tried Androguard to construct the call graph instead of by FlowDroid and then extracted the feature vector in MaMaDroid. Given feature vectors, we can perform classification by training and testing. However, the feature vector extracted from call graph by Androguard is not as good as by FlowDroid. So i'm confused that the call graph extracted by Androguard may not be as precise as by FlowDroid.

**Comment by reox** [comment]
> MaMaDroid 

ah yes, I have seen the paper.
So you want the same call graph as with Soot and FlowDroid but with androguard?

In the paper, there is fig 4 - this can be done already with androguard I guess... as this is the normal callgraph.
So what you want is fig 5, i guess?
In this case you would need to use the `BasicBlocks` provided in the analysis package and squish this information into the call graph. Right now I have no good idea how this could be done though.

**Comment by Ken-HUST** [comment]
> > MaMaDroid
> 
> ah yes, I have seen the paper.
> So you want the same call graph as with Soot and FlowDroid but with androguard?
> 
> In the paper, there is fig 4 - this can be done already with androguard I guess... as this is the normal callgraph.
> So what you want is fig 5, i guess?
> In this case you would need to use the `BasicBlocks` provided in the analysis package and squish this information into the call graph. Right now I have no good idea how this could be done though.

I'm sorry for my late reply. Yes, what i want is the same call graph as with Soot and FlowDroid but with androguard. Thanks for your constructive suggestions, i will conduct deep analysis to use the BasicBlocks information.

**Comment by reox** [comment]
If you like, just create a PR if you want to have it in androguard!

**Comment by Yumlembam** [comment]
@Ken-HUST can you provide the link of source code of mamdroid.

**Comment by Ken-HUST** [comment]
> @Ken-HUST can you provide the link of source code of mamdroid.

https://bitbucket.org/gianluca_students/mamadroid_code/src/master/
