### ISSUE TITLE
Reverse call graph option

### ISSUE THREAD

**Issue by gianlucascoccia** [androguard/androguard#701]
I am using Androguard to generate callgraphs. 
However I don't understand the results.
I would expect that each node would represent a method and edges represent calls among method.

Instead, what I get is the following:
<img width="948" alt="Schermata 2019-05-27 alle 12 26 10" src="https://user-images.githubusercontent.com/3214514/58414089-a7bc1f00-807a-11e9-9414-bd71f229152a.png">

Why there is an  arrow in node labels? what is the call graph format?

**Comment by reox** [comment]
>  I would expect that each node would represent a method and edges represent calls among method.

that is correct, and indeed what you get!

> Why there is an arrow in node labels?

you mean the `->`? That is just a separator between the class name and the method name.
The format for the method is:
`ClassType->methodName(Arguments)Returntype`

**Comment by gianlucascoccia** [comment]
Thanks for the clarification. 
So in the picture I used as an example method getInstalledPackagesRefacotr, belonging to class com.sdbox.plugin.NoOne, calls all the other methods.

Is there a way to get all the methods that are calling getInstalledPackagesRefacotr instead? I guess that is technically called a reverse call graph.

**Comment by reox** [comment]
I think it should be possible to implement this natively.
as a workaround you could create the full call graph and filter all edges in the graph viewer you are using.

**Comment by reox** [comment]
wait a minute ;) This is actually implemented already in master!
I have changed the code in the way that xref_from are also used.

Can you check with the current master if it will work for you?

**Comment by gianlucascoccia** [comment]
I tried with the latest version and indeed it shows some incoming edges. However, (at least in the limited tries I did) it stops at the first level of incoming edges while I would like to build the whole stack of calls that lead to the method invocation.

Guess that I need to implement that in my own script, right? Generating the whole call graph seems to take quite some time.

**Comment by reox** [comment]
Ah I see. So that would mean to implement some depth search too.
You could implement this as an option to the `get_call_graph` function. If you like just send a PR!

**Comment by SamiraSadat** [comment]
Hi,
Would you please copy the code you used for your call graph, here...?

**Comment by gianlucascoccia** [comment]
I did not write any code, I've used the command line `cg` command with the `--methodname` option.

**Comment by SamiraSadat** [comment]
This is the first time I’m using androguard command such as cg.
When I use androguard cg with app’s path and method name it turns me some class names including this method like the pic copied for you.

androguard cg H:\ReverseEngineering\Sample\APK\com.camata_apps.copalibertadores.apk --methodname isFullScreen()Z

[cid:image003.png@01D5164B.5E335B80]

but how do I get the plot…?


________________________________

**Comment by gianlucascoccia** [comment]
Can't see the pic, anyway it will save the plot into a callgraph.gml  file in the same folder (unless you change the name with the `-o` parameter). You can visualize this plot with a program that supports .gml files ([Gephi](https://gephi.org) works for me).

I'm not sure you are providing the methodname parameter correctly, I think you shouldn't include parenthesis and return type ( in other words try `isFullScreen` instead of `isFullScreen()Z`)

**Comment by SamiraSadat** [comment]
How can I see the options of androguard cg such as –methodname?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by SamiraSadat** [comment]
Ok, I tried it with other one: get string
And founded method listed in the screen. But I still couldn’t find the plot, you mean it must be in the APK folder…?
See the attached file.:)

________________________________

**Comment by reox** [comment]
@SamiraSadat you can use --help to get an overview about the command and you can consult the online help: https://androguard.readthedocs.io/en/latest/tools/androcg.html

**Comment by SamiraSadat** [comment]
I use 
`androguard cg H:\ReverseEngineering\Sample\APK\com.camata_apps.copalibertadores.apk --methodname getId`
to generate call graph for getId method. The Gephi reports that there are 75 Nodes and 71 Edges, but doesn't show the plot. what's the problem with it...? 

![Uploading Capture2.PNG…]()
![Uploading Capture3.PNG…]()

**Comment by reox** [comment]
I'm no pro in gephi but it looks like that you are missing the Graph window.
Try to click on Window -> Graph to activate it...
