### ISSUE TITLE
I need some apps with multi dex

### ISSUE THREAD

**Issue by SamiraSadat** [androguard/androguard#705]
Hi again:)
would you please introduce me some popular apps with multi dex which has 2,3,4,5 dex files...?

**Comment by reox** [comment]
instagram and youtube have each four classes.dex

**Comment by SamiraSadat** [comment]
and a program with 2 or 3 files....?

**Comment by reox** [comment]
This one here has two classes: https://github.com/androguard/androguard/blob/master/examples/tests/multidex/multidex.apk

The AOSP browser has 3...

but I also saw APKs with >20 classes.dex and I can not give you an individual example for each ;)
If you want examples for each, just download some APK collections and scan over them.

**Comment by SamiraSadat** [comment]
No need, it's enough. TnQ:)

**Comment by SamiraSadat** [comment]
I need a real app with 2-dex files include method calls and manifest.xml :(

**Comment by reox** [comment]
You can generate them on your own... Just grab some random app from f-droid in source code, and compile to multidex. Then you can create any number of dex files you like.
