### ISSUE TITLE
I can't use any of androguard command in cmd

### ISSUE THREAD

**Issue by SamiraSadat** [androguard/androguard#706]
Please ..... Please....
Tell me How to fix it. I'm tired of this error. I can't run any of androguard command in cmd. This is the error:

> Traceback (most recent call last):
>   File "c:\users\fotuh\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\fotuh\anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Fotuh\Anaconda3\Scripts\androguard.exe\__main__.py", line 9, in <module>
>   File "c:\users\fotuh\anaconda3\lib\site-packages\click\core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\fotuh\anaconda3\lib\site-packages\click\core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "c:\users\fotuh\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\fotuh\anaconda3\lib\site-packages\click\core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\fotuh\anaconda3\lib\site-packages\click\core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\fotuh\anaconda3\lib\site-packages\androguard\cli\entry_points.py", line 476, in analyze
>     androlyze_main(session, apk)
>   File "c:\users\fotuh\anaconda3\lib\site-packages\androguard\cli\main.py", line 359, in androlyze_main
>     filetype = androconf.is_android(filename)
>   File "c:\users\fotuh\anaconda3\lib\site-packages\androguard\core\androconf.py", line 210, in is_android
>     with open(filename, "rb") as fd:
> PermissionError: [Errno 13] Permission denied: 'H:\\ReverseEngineering\\Sample\\APK'

**Comment by reox** [comment]
As I already mentioned in another thread: do not give a folder as argument but a single file!

**Comment by reox** [comment]
I pushed some changes to master, which will create a better error message if you not pass a file to the script.

**Comment by SamiraSadat** [comment]
Thank you. it's a silly but common mistake:)
