### ISSUE TITLE
yara -x rule clarity required

### ISSUE THREAD

**Issue by dexter0810** [androguard/androguard#709]
yara -x androguard=d8adb784d08a951ebacf2491442cf90d21c20192085e44d1cd22e2b6bdd4ef5f-report.json rule.yar sample.apk

In this rule we test the rules written in the yar file with the json report generated and sample.apk contains random content? So, basically the json and yar file are the ones of importance? 

Please correct me if I'm wrong. 

Any help is much appreciated.

**Comment by reox** [comment]
The androguard yara extension is developed by koodous.
I can unfortunstely not help you here...

**Comment by reox** [comment]
Please raise an issue here: https://github.com/Koodous/androguard-yara
