### ISSUE TITLE
Run-Time and File-Size of extracting method calls from multi-dex applications such as instagram

### ISSUE THREAD

**Issue by SamiraSadat** [androguard/androguard#710]
First of all, I would like to thank you for answering my previous questions:)
and then, I would ask you to read this issue carefully because your answer is too important for me. I target the instagram app which has 3 DEX files.
I have written two different codes for extracting method call from dex file, as you may have seen it before. Code No.1, uses _apk, dvm_ sub-module and code No.2 uses _analysis_ sub-module. I decide to print the output of the codes in a _txt file_, as you see in both codes. I also test the codes in both 'w', 'a' mode which stands for write to file, append to file.

Code No.1 :

```
import os
import time
from androguard.core.bytecodes import apk,dvm
from androguard.core.analysis import analysis


os.chdir('H:\ReverseEngineering\Sample\APK')

def PRINT_METHOD_CALLS(m):
    file = open('H:\ReverseEngineering\Sample\MethodCalls_instagram2.txt','a' )
    app = apk.APK(m)
    app_dex = dvm.DalvikVMFormat(app.get_dex())
    app_x = analysis.Analysis(app_dex)
    app_x.create_xref()
    classes = app_dex.get_classes()
    for class_ in classes:
        cx = app_x.get_class_analysis(class_.get_name())
        for method in cx.get_methods():
            file.write("inside Method {} ".format(method.name) + ':' + '\n')
            for _, call, _ in method.get_xref_to():
               file.write("    calling -> {} -- {}".format(call.class_name, call.name) + '\n')
    file.close()

begin = time.time() 
 
for app in os.listdir():
    PRINT_METHOD_CALLS(app)

end = time.time()

print(end-begin)
```

    

Code No.2 :

```
from androguard.misc import AnalyzeAPK
import os
import time

os.chdir('H:\ReverseEngineering\Sample\APK')

def EXTRACT_METHOD_CALLS(a):
    app, list_of_dex, dx = AnalyzeAPK(a)
    for method in dx.get_methods():
        file.write("inside Method {} ".format(method.name) + ':' + '\n')
        for _, call, _ in method.get_xref_to():
            file.write("    calling -> {} -- {}".format(call.class_name, call.name) + '\n')


begin = time.time() 
 
for apk in os.listdir():
    file_name , file_extension = os.path.splitext(apk)
    file = open(file_name + '.txt', 'w')
    EXTRACT_METHOD_CALLS(apk)
    file.close()


end = time.time()

print(end-begin)
```

The results I want to talk about with you, are the **run-time** and **txt file's size**.
on my computer, they are like below:

  | Run time |   | File Size |  
-- | -- | -- | -- | --
  | "w" | "a" | "w" | "a"
Code No.1 | 197 sec | 217 sec | 11.8 MB | 11.8 MB
Code No.2 | 571 sec | 503 sec | 31.7 MB | 31.7 MB

First of all, I thought because this is a multi-dex application, File Size must be different in "w", "a" mode, as a clear explanation, I thought in write mode codes will overwrite the Method call's of second dex file on first and also overwrite the third on the second. and in the append mode, it will just add them and nothing will overwrite. I really wonder when I see the content and the size of files in both "w" and "a" are equal. what's your idea, what really happens...?

Second, why does Run-Time increase in append mode...?

Third, the difference in content(last part) and increase in size, show that  Code No.2 deals with multi-dex file better. but I want to sure that whole the method calls in all dex file have written in txt file or Not...? please guide me about this. 

Sorry, it was a bit long:)

**Comment by reox** [comment]
The first code is wrong for multi dex files.
You are just adding the first dex and running analysis on it.
This is also the reason why the first code is much faster, as you are not taking into account all the DEX files.

A note: Use a session and reset it after each call of AnalyzeAPK - otherwise you will have all analyzed files in memory (see last code example here: https://androguard.readthedocs.io/en/latest/intro/sessions.html)

**Comment by SamiraSadat** [comment]
Good point, So the code No.2 must be like below:

> from androguard.misc import AnalyzeAPK, get_default_session

> def EXTRACT_METHOD_CALLS(a):

>_# get a default session_
>     sess = get_default_session()

> _# Use the session_
>     app, list_of_dex, dx = AnalyzeAPK(a , session = sess)

>  _# Extract Method Calls_
>     for method in dx.get_methods():
>         file.write("inside Method {} ".format(method.name) + ':' + '\n')
>         for _, call, _ in method.get_xref_to():
>             file.write("    calling -> {} -- {}".format(call.class_name, call.name) + '\n')

>  _#reset the session_
>     sess.reset()

Right....?

**Comment by SamiraSadat** [comment]
Would you please answer me...!
_[as a master]_ I need your approve if code No.2 is compatible with multi-dex files.

**Comment by reox** [comment]
that looks good
