### ISSUE TITLE
I want to get classes except android apis

### ISSUE THREAD

**Issue by ksg97031** [androguard/androguard#713]
I want to bypass the android API classes. (ex android.arch, android.support ..etc)
Follow you're [comment](https://github.com/androguard/androguard/pull/711#issuecomment-498157188) and I used is_android_api but As a result, I can't get the result what i want.

I think `self.is_external()` returns always false
```python
 937         if not self.is_external(): # <<
 938             # API must be external
 939             return False
```
### System Information

- Androguard Version: master
- Python Version: 3.7
- Operating macOS

### Further Log Files and Output
```python
... run my script
Landroid/support/v4/content/ModernAsyncTask$1;
Landroid/support/v4/content/ModernAsyncTask$3;
Landroid/support/v4/content/ModernAsyncTask$4;
Landroid/support/v4/content/ModernAsyncTask$AsyncTaskResult;
Landroid/support/v4/content/ModernAsyncTask$InternalHandler;
Landroid/support/v4/content/ModernAsyncTask$Status;
Landroid/support/v4/content/ModernAsyncTask$WorkerRunnable;
Landroid/support/v4/content/ModernAsyncTask;
...
```

Thank you for your support.

**Comment by reox** [comment]
I would not count the support library as an API. In my opinion the API are just the classes defined here: https://developer.android.com/reference/packages.html
Per definition they must be external, as the code is not inside the APK but in the Android system.

You probably want to filter the support classes as well, this can be achieved using `find_classes` and a regex on the classname.

**Comment by ksg97031** [comment]
@reox you're right, it's my mistake.
  
Thank you for your help.
