### ISSUE TITLE
strings and fields reference methods that aren't found in dx.get_methods()

### ISSUE THREAD

**Issue by cheavyio** [androguard/androguard#714]
Strings and Fields have xrefs from methods that aren't in dx.get_methods().  This is happening with every APK I've tried.

This should demonstrate the issue - 

```
methods = set(dx.get_methods())
for s in dx.get_strings():
    for x in s.get_xref_from():
        if x[1] not in methods:
            print("unable to find {}".format(x[1]))
```

**Comment by reox** [comment]
the second argument is of type `EncodedMethod` not `MethodClassAnalysis`... I guess that is a little bit confusing

**Comment by cheavyio** [comment]
Sorry, I used the wrong example.  This should demonstrate it -

for s in dx.get_strings():
    for c, method in s.get_xref_from():
        ma = dx.get_method_analysis(method)
        if not ma:
            print("failed to find method {}".format(method))
        else:
            print("found method {}".format(method))

It is the same for Field xrefs also.

**Comment by reox** [comment]
you are right! I'll look into this.

**Comment by reox** [comment]
This is probably related to #407 
There is MethodAnalysis and MethodClassAnalysis. The latter objects are created on the fly when a method xref is created using the AddMXrefFrom/AddMXrefTo function on ClassAnalysis.
The first ones are created when calling add() on the Analysis.

I would like to merge both together... At the same time I can look into this issue in more detail.
It looks like the MethodClassAnalysis is not created for some reason, even though there is an EncodedMethod for it.
