### ISSUE TITLE
ARSCParser doesn't properly decode strings encoded in mutf-8

### ISSUE THREAD

**Issue by pandaxtc** [androguard/androguard#723]
Some valid APKs with resources.arsc files that have strings encoded in mutf-8 don't decode properly. The `_decode_bytes` method logs '`invalid decoded string length'` for any strings that contain characters encoded as surrogates, since python improperly decodes these when just using `decode('utf-8', 'replace')`. 

This only occurs in blocks marked as utf-8, so this can be fixed afaict by decoding utf-8 strings using the surrogatepass option, then re-encoding in utf-16-le with surrogatepass again, and using the number of bytes to get the string length instead of `len()`.

- Androguard Version: master
- Python Version: 3.6.5
- Debian

**Comment by reox** [comment]
Is the error in the ARSC parser or in the DEX parser?
the Android XML files IMO do not use MUTF-8 but regular UTF8. Only DEX uses MUTF8.
Can you poste a full traceback as well as the file where this happens?
