### ISSUE TITLE
questions: Is there any way to save the source code of a class to a text file? I was trying to do but the output is distorted. I can store class name, Method Name, but I cannot store the source code.

### ISSUE THREAD

**Issue by SanondaDattaGupta** [androguard/androguard#724]
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do

- is this error specific to a single file?
- if possible give a minimal working example where the error happens

### System Information

- Androguard Version: master
- Python Version: 3.4/3.5/...
- Operating System

### Further Log Files and Output

- please report logs, tracebacks and other useful information
- if possible report the files you tried to analyze!

**Comment by reox** [comment]
For the record: instead of using `.source()`, use `.get_source()` on the `EncodedMethod`. it does not syntax highlight the source code, hence is safe for saving into a file.
