### ISSUE TITLE
No atttribute 'MagicError'

### ISSUE THREAD

**Issue by ajpagente** [androguard/androguard#726]
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do

A call to a.get_files_types() crashes when the magic library throws an exception. 
The issue is the exception handler uses **magic.MagicError** which does not exist:

```
try:  
    ftype = magic.from_buffer(buffer[:1024])
except magic.MagicError as e:
    log.exception("Error getting the magic type: %s", e)
    return default
```

### Describe what you expected
The file should be marked Unknown if the magic library is not able to identify it.

### Describe what actually happened
get_files_types() crashes and the developer will not know which file caused the issue.

### System Information

- Androguard Version: 3.4.0
- python-magic:     0.4.15
- python-magic-bin: 0.4.14
- Python Version: 3.7.2
- Operating System: Windows 7 Enterprise SP1

### Further Log Files and Output

Traceback (most recent call last):
  File "tests\test_apk.py", line 23, in testFilesTypes
    files_types = a.get_files_types()
  File "C:\[redacted]\androguard\androguard\core\bytec
odes\apk.py", line 696, in get_files_types
    self._files[i] = self._get_file_magic_name(buffer)
  File "C:\[redacted]\androguard\androguard\core\bytec
odes\apk.py", line 666, in _get_file_magic_name
    except magic.MagicError as e:
AttributeError: module 'magic' has no attribute 'MagicError'

**Comment by reox** [comment]
you have the wrong magic library installed, althouth `python-magic` seems to be the correct one.
Can you check in a virtualenv?

```
virtualenv venv
venv\Scripts\activate.bat
pip install androguard[magic]
```
If it works, then you probably have some other magic lib installed.
One problem with all the magic stuff is, that the libraries all call their module `magic`...

**Comment by ajpagente** [comment]
I list the steps I followed:

After I run pip install androguard[magic] in a virtual env, I confirm that I have python-magic 0.4.15 installed. But I get:

> No Magic library was found on your system. 

So I run pip install python-magic-bin which installs version python-magic-bin 0.4.14
After this I get:

> AttributeError: module 'magic' has no attribute 'MagicError'

Looking at magic.py source code. It defines a class:
```python
class MagicException(Exception):
    def __init__(self, message):
        super(MagicException, self).__init__(message)
        self.message = message
```
Do I have the wrong package?

**Comment by reox** [comment]
> Do I have the wrong package?
No, it looks like python-magic-bin or python-magic are fine. I think MagicError is the wrong type and MagicException should be used - I checked the code of python-magic and this exception is raised there. I'll fix this!

**Comment by reox** [comment]
can you please check if the PR solved the issue? Thanks!

**Comment by ajpagente** [comment]
Yes, the issue is fixed. When an exception is thrown the file type indicates **Unknown**.
Thank you for your help.
