### ISSUE TITLE
get instruction from xref_to

### ISSUE THREAD

**Issue by mehrant95** [androguard/androguard#727]
Is there any way to get `instruction` object from output of `xref_to`? For example, when there is an external method call, i want to know if it is an `invoke-super` instruction or an `invoke-virtual`. Is there any way?

**Comment by reox** [comment]
the xrefs return an `EncodedMethod` object, you can get the instructions via https://androguard.readthedocs.io/en/latest/api/androguard.core.bytecodes.html#androguard.core.bytecodes.dvm.DCode.get_instructions

**Comment by mehrant95** [comment]
Calling `get_xref_to()` on a `MethodClassAnalysis` returns a `set` of `tuple`s: (`ClassAnalysis`, `EncodedMethod` or `ExternalMethod`, `int`). In cases when the second item is an `ExternalMethod`, how can i retrieve the according instruction?

**Comment by reox** [comment]
Like so:
```
mca = list(dx.find_methods('Lcom/demo/videos/MainActivity;', 'onCreate'))[0]  # Just grab the MethodClassAnalysis object

import androguard
for _, m, off in mca.get_xref_to():
   if isinstance(m, androguard.core.analysis.analysis.ExternalMethod):
        print("External", m.full_name, " -> ins", mca.get_method().get_instruction(None, off=off))
```

should print something like:
```
External Landroid/app/Activity; onCreate (Landroid/os/Bundle;)V  -> ins invoke-super v1, v2, Landroid/app/Activity;->onCreate(Landroid/os/Bundle;)V
External Lcom/demo/videos/MainActivity; getComponentName ()Landroid/content/ComponentName;  -> ins invoke-virtual v1, Lcom/demo/videos/MainActivity;->getComponentName()Landroid/content/ComponentName;
```
