### ISSUE TITLE
Negative resource id in result

### ISSUE THREAD

**Issue by XuYunnan** [androguard/androguard#73]
My source code is like:

``` python
from androguard.misc import *
a, d, dx = AnalyzeAPK(APKFile)
a.show()
```

But output of `a.show()` contains negative resource id:

```
    res/raw/bdgethtmltag.js Unknown -9ea23b
    res/raw/bdtiebarcss.js Unknown 33810998
    res/raw/bdtiebarjs.js Unknown -156d68f3
```

How can I convert these to correct res id?

**Comment by reox** [comment]
those are not the Resource IDs but the CRC32 of the file and a negative value is possible, if the crc32 is interpreted as signed int.
As now zlib.crc32 is used, the result should be an unsigned int: https://docs.python.org/3/library/zlib.html#zlib.crc32
