### ISSUE TITLE
Past certificates in v3

### ISSUE THREAD

**Issue by lsvinicius** [androguard/androguard#732]
I saw the Android API 28 have a method called **getSigningCertificateHistory** which retrieves all past certificates, even if apk is signed with v3 only.

I have tried to obtain past certificates using Androguard but it only returns the newest one for v3.

Is it possible to retrieve past certificates with a v3 only APK ?

**Comment by reox** [comment]
I'm not completly informed about the new signing mechansim, but I would guess this method works by checking the certificate cache on the device rather than certificates stored in the APK?
Or how does this work?

**Comment by lsvinicius** [comment]
I'm currently studying this, I found there is an XML file being read in the device, but have not checked it out how it is being generated, however, if the information is there, it should come from the own APK, otherwise, how would it be populated ?

**Comment by reox** [comment]
I had no deep look into v3 but as far as i understood the only new mechanism is a function to replace your current sigining certificate with a new one. I guess that is the only new information and the old certificates are just stored on the android device for whatever reason.
It comes probably from packages.xml.

**Comment by lsvinicius** [comment]
But I'm able to install a v3 only APK with rotation and **getSigningCertificateHistory** is returning the previous certificates.
And yes, information is in packages.xml.

**Comment by reox** [comment]
If you could find out where the information is stored in the apk, i can have a look if it can easily implemeted!

**Comment by lsvinicius** [comment]
Gonna keep searching, thanks.

**Comment by reox** [comment]
If you find anything, please post it here :) I'm interested in details as well!

**Comment by lsvinicius** [comment]
Good news, I have found it. At first I was searching in the API's code, but it turns out **apksigner** also have the code to retrieve past certificates (though it is being used only to guarantee the last certificate in the proof of rotation (por) scheme is the same used to sign the apk) .

In method **parseSigner** from _https://android.googlesource.com/platform/tools/apksig/+/master/src/main/java/com/android/apksig/internal/apk/v3/V3SigningCertificateLineage.java_ there is a parsing additional attributes block. It calls method **SigningCertificateLineage.readFromV3AttributeValue** which calls the method doing the heavy stuff **readSigningCertificateLineage** and it is in
_https://android.googlesource.com/platform/tools/apksig/+/master/src/main/java/com/android/apksig/internal/apk/v3/V3SigningCertificateLineage.java_

The code in API is similar, not sure if it is doing something different because I did not test it.

**Comment by lsvinicius** [comment]
Hi @reox, do you think it would be possible to implement this feature in androguard ?

**Comment by reox** [comment]
I can probably not implement this myself right now, but if you (or someone else) want to tackle that problem, I would happily merge it :)

**Comment by lsvinicius** [comment]
Good to know, I will tackle it. 

Thanks
