### ISSUE TITLE
Requested API level 29 is larger than maximum we have, returning API level 28 instead.

### ISSUE THREAD

**Issue by mayankmetha** [androguard/androguard#735]
Add support for Android API Level 29.

**Comment by reox** [comment]
yeah this depends on axplorer...

@U039b you generated the permission mappings for the other API levels. Can you maybe generate them for the newer ones as well?

**Comment by Bubu** [comment]
The warning is pretty confusing for our usecase. We started using androguards apk parsing and `get_targetSDK()` function for figuring out the targersdk version of an apk.

The it shows
> Requested API level 30 is larger than maximum we have, returning API level 28 instead

But it returns 30 (which is good). I don't think the warning is relevant at all for us but I'm hesitant to silence all androguard warnings.

**Comment by reox** [comment]
If i remember correctly, this warning comes from the permission loader, which does not have the json file of api 30 (or 29) - hence the warning.
The version extracted from the AndroidManifest should in any case be correct. The warning message should probably be more descriptive (i.e. Requested API level for permission mapping file not found in androguard, the maximum we have is X. Permission mappings might not be correct for your sample)
