### ISSUE TITLE
remove formatted_operands from instructions

### ISSUE THREAD

**Issue by reox** [androguard/androguard#740]
I see the point of having formatted_operands, i.e. if the operand is somehow interpreted.
But in my opinion this makes only things worse... My plan would be to drop it completely.
@androguard/external-contributors what do you think? Are there any reason why we should keep it?

**Comment by eighthave** [comment]
I haven't encountered the term _formatted_operands_ anywhere, where might we be hitting it?

**Comment by reox** [comment]
See the Instruction classes in https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/dvm.py like https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/dvm.py#L4721

But the problem with them is, that they are sometimes wrong - hence they need a lot of fixing anyways.
And what I see from other disassemblers, they do not interpret the result in any way. Thats why I would remove them.

**Comment by eighthave** [comment]
ok, that's out of my realm of us, so I have no opinion.

**Comment by reox** [comment]
Or does anyone use more disassemblers than I do? Usually formatted_operands is only used in the cases where the value with is inside the bytecode is somehow transformed. I.e. there are opcodes storing the value BBBB but it is extended to 32/64bit and gets BBBB0000 or BBBB000000000000.
I think at the disassembly level we do not really care about the actual value BBBB but want the value which is used in the processing of the bytecodes, right? (At least I would be more interested in the actual used value than the value from the bytecode)

**Comment by reox** [comment]
done
