### ISSUE TITLE
How to extract module, operation, method, artifacts using androgurad?

### ISSUE THREAD

**Issue by SamiraSadat** [androguard/androguard#743]
Hi.
I have written this code to extract API calls using androguard:

```
from androguard.misc import AnalyzeAPK, get_default_session
import os 
os.chdir('H:\Sample\APK')
#---------------------------------------------------------------------------------------
def EXTRACT_API_CALLS(a):
    sess = get_default_session()
    app, list_of_dex, dx = AnalyzeAPK(a , session = sess)
    # Write Method Calls to a .txt file.......///
    for method in dx.get_methods():
        for _, call, _ in method.get_xref_to():
            file.write(call.class_name + call.name + '\n')
    sess.reset()
#------------------------------------------------------------------------------------------
for apk in os.listdir():
    file_name , file_extension = os.path.splitext(apk)
    file = open(file_name + '.txt', 'w')
    EXTRACT_API_CALLS(apk)
    file.close()
```
The output is like this:
**inside Method loadClassBinaryName :
    calling -> Ldalvik/system/DexFile; -- loadClassBinaryName**

How Can i change the code to get this kind of output?
![image](https://user-images.githubusercontent.com/45191491/66456219-e080f180-ea79-11e9-9b90-8ac7316bf32d.png)

**Comment by reox** [comment]
I have never seen this kind of notation but you should be able to split up the class name and get the rest from descriptor of the method...

**Comment by SamiraSadat** [comment]
Actually I saw it in the paper discussing malware detection systems. Thanks
