### ISSUE TITLE
Question about data flow implementation

### ISSUE THREAD

**Issue by krnick** [androguard/androguard#746]
Hello,

I have seen that kind of issue many times in the past few years. Just wondering the data flow of parameter tracking has done or not yet.

Example like:

String x = "hello"
someobject.function(x);
other_object.function(x);

Could we check the x is the same value or the same memory address in somehow?

or we could just use what you mentioned from #593 for now?

Thank You.

**Comment by krnick** [comment]
@reox thank you for your prompt reply, I will do some 
research about that, maybe I could contribute it once I figure out. 😄

**Comment by reox** [comment]
I revisited the problem today, and it looks like what I wrote in #593 is still valid: you can use the AST to get this information, but it is quite hidden and there is IMO no way right now to check stuff inside the AST quickly.
So probably you would use the AST, put it into some kind of graph library, check for the MethodInvocation and then read the parameters.
It is possible that the parameters are nested, like in this example:
```
    void stringBuild(String x){
        String y = "hello";

        String z = y + x + y;

        System.out.println(z);
    }
```

gives this AST:
```
{'body': ['BlockStatement',
          None,
          [['ExpressionStatement',
            ['MethodInvocation',
             [['FieldAccess',
               [['TypeName', (java/lang/System, 0)]],
               (java/lang/System, out, Ljava/io/PrintStream;)],
              ['MethodInvocation',
               [['MethodInvocation',
                 [['MethodInvocation',
                   [['MethodInvocation',
                     [['ClassInstanceCreation',
                       (java/lang/StringBuilder, <init>, ()V),
                       [],
                       ['TypeName', (java/lang/StringBuilder, 0)]],
                      ['Literal', 'hello', ('java/lang/String', 0)]],
                     (java/lang/StringBuilder,
                      append,
                      (Ljava/lang/String;)Ljava/lang/StringBuilder;),
                     append,
                     True],
                    ['Local', 'p3']],
                   (java/lang/StringBuilder,
                    append,
                    (Ljava/lang/String;)Ljava/lang/StringBuilder;),
                   append,
                   True],
                  ['Literal', 'hello', ('java/lang/String', 0)]],
                 (java/lang/StringBuilder,
                  append,
                  (Ljava/lang/String;)Ljava/lang/StringBuilder;),
                 append,
                 True]],
               (java/lang/StringBuilder, toString, ()Ljava/lang/String;),
               toString,
               True]],
             (java/io/PrintStream, println, (Ljava/lang/String;)V),
             println,
             True]],
           ['ReturnStatement', None]]],
 'comments': [],
 'flags': [],
 'params': [[['TypeName', (java/lang/String, 0)], ['Local', 'p3']]],
 'ret': ['TypeName', ('.void', 0)],
 'triple': (Foobar, stringBuild, (Ljava/lang/String;)V)}
```

As you can see, the whole string creation is part of the MethodInvocation, but you had to somehow normalize the expression to get something like `Literal('hello') + Local(p3) + Literal('hello')`

**Comment by krnick** [comment]
@reox  thank you for your reply

I will try this method. Besides, I would like to know if the Android smali code after decompiled is in sequential. If so, maybe we could tracking variables from the .ag file.

maybe it would be faster than AST?

**Comment by reox** [comment]
yes the "smali" (i mean it is not really smali...) code is in the sequence of opcodes - but not in the sequence of calls! The only thing that is certain is, that the beginning of the method is at the top. But if there are conditions and jumps, the order my vary.

Idk if it would be faster than using the AST. I would guess that there are probably better tools for parsing ASTs than for parsing plain text.
In my opinion: if you can display the data as graphs, use them.

**Comment by krnick** [comment]
Got it, thanks 😄
