### ISSUE TITLE
get the bytecode based on class_name and method name

### ISSUE THREAD

**Issue by krnick** [androguard/androguard#755]
Hi @reox 

I have read the [Parsing Instructions and Bytecode](https://androguard.readthedocs.io/en/latest/intro/instructions.html) but I found that there is no way to search for a specific class_name and method_name to get a bytecode. Could it possible to use ``get_name()``, ``get_output()`` to get output like the .ag file.

Assume I have the example as below:

```
class_name ="Lcom/google/progress/AndroidClientService;"
method_name = "sendMessage"

m  = dx.get_method(class_name, method_name)
```

and then just

```
for idx, ins in m.get_instructions_idx():
    print(idx, ins.get_op_value(), ins.get_name(), ins.get_output())
```

Sorry, maybe there is already such a function but I don't know, if it does, I would like to contribute to the documentation.

Thank you!

**Comment by reox** [comment]
classname and methodname is not enough to uniquely identify a method in java! you need the descriptor as well - hence the reason`get_method` has three parameters.
But you can use `find_methods`:

```
for m in dx.find_methods(class_name, method_name):
    print(m.full_name)
    for idx, ins in m.get_method().get_instructions_idx():
        print(idx, ins.get_op_value(), ins.get_name(), ins.get_output())
```

**Comment by krnick** [comment]
Thanks! this is what I looking for, it is useful !!

I think this is a good example for users who want to read the bytecode of the specific function. Maybe we could add it to the documentation?

---

If you want to get the bytecode from given specific class_name and method_name, you can follow the example as shown below

```
for m in dx.find_methods("Ltests/androguard/TestActivity;","foo"):
    print(m.full_name)
    for idx, ins in m.get_method().get_instructions_idx():
        print(idx, ins.get_op_value(), ins.get_name(), ins.get_output())
```
and the output will look like:

```
Ltests/androguard/TestActivity; foo (I I)I
0 1 move v0, v4
2 52 if-lt v3, v0, +005h
6 57 if-nez v3, +00eh
10 15 return v0
12 216 add-int/lit8 v4, v0, 1
16 147 div-int v3, v0, v3
20 1 move v0, v4
22 40 goto -ah
24 13 move-exception v1
26 19 const/16 v3, 10
```

**Comment by krnick** [comment]
#759
