### ISSUE TITLE
Jadx decompiler fails to return the source code

### ISSUE THREAD

**Issue by adamjanovsky** [androguard/androguard#763]
### Describe what you wanted to do

When analyzing some apks, I figured that jadx is giving more suitable source-code. Thus, I wanted to use Androguard with the jadx decompiler and access the source code of classes. Sadly, it always remains empty. I followed the documentation at https://androguard.readthedocs.io/en/latest/intro/use_jadx.html. Fails on all apks. Minimal working example:

```
    a = APK('examples/android/TestsAndroguard/bin/TestActivity.apk')
    d = DalvikVMFormat(a)
    dx = Analysis(d)
    decompiler = DecompilerJADX(d, dx, jadx='/path/to/my/jadx')
    d.set_decompiler(decompiler)
    #d.set_vmanalysis(dx)

    for cls in d.get_classes():
        print(cls.source())
```

### Describe what you expected

I expected the source code to be returned/printed. upon calling `cls.source()`

### Describe what actually happened

`None` is being returned/printed.

### System Information

- Androguard Version: 3.3.5
- Python Version: 3.6
- MacOS
- Tried with old jadx 1.10 and with the newest

### Further Log Files and Output

During the decompilation, the following appears on the stdout

```
... (more lines before)
Found a class called sources/android/support/v4/content/ModernAsyncTask, which is not found by androguard!
Found a class called sources/android/support/v4/content/ContextCompat, which is not found by androguard!
Found a class called sources/android/support/v4/content/ContextCompatHoneycomb, which is not found by androguard!
Found a class called sources/android/support/v4/content/IntentCompatHoneycomb, which is not found by androguard!
... (more lines after)
Found a class called android/support/v4/view/VelocityTrackerCompat$BaseVelocityTrackerVersionImpl which is not decompiled by jadx
Found a class called android/support/v4/view/VelocityTrackerCompat$HoneycombVelocityTrackerVersionImpl which is not decompiled by jadx
... (more lines after)
```

Is my code composed correctly? Am I trying to emuleate behaviour that is not meant to be supported?

**Comment by adamjanovsky** [comment]
Oh, silly me, I rushed a bit. The cause is that the paths of Androguard and Jadx don't match by a single `sources/` directory. I'll try to fix that and create PR, hopefully I manage -- never saw that code...

**Comment by 1eafy** [comment]
I try to use your method is not available, I use Windows OS, I choose to use regular expression to find the path.
```
        for root, dirs, files in os.walk(tmpfolder):
            for f in files:
                if not f.endswith(".java"):
                    log.warning("found a file in jadx folder which is not a java file: {}".format(f))
                    continue
                # as the path begins always with `self.res` (hopefully), we remove that length
                # also, all files should end with .java
                # path = os.path.join(root, f)[len("sources/") + 1:-5]
                path = os.path.join(root, f)
                path = path.replace(os.sep, "/")
                path = findall(".*/sources/(.*)\.java", path)
                path = path[0] if len(path) > 0 else ""

                # Special care for files without package
                # All files that have no package set, will get the
                # package `defpackage` automatically
                if path.startswith("defpackage"):
                    path = path[len("defpackage/"):]
````

**Comment by mastercaution** [comment]
Androguard still does not find the source files decompiled by JADX, because they are placed under `tmpfolder/sources` like @adamjanovsky already pointed out.

@adamjanovsky @1eafy and #869 already attempted to fix this issue, but it didn't find its way into the main version yet. Those attempts adjust the location where Androguard searches for the source files. Another approach would be to adjust the JADX call, so it places the sources to the expected location `tmpfolder` directly. This can be achieved, by changing the `-d` flag to `-ds` in [decompiler.py#L652](https://github.com/androguard/androguard/blob/4e0bed55f93726f57967089699c227c2cdaac8ff/androguard/decompiler/decompiler.py#L652)

```py
cmd = [jadx, "-ds", tmpfolder, "--escape-unicode", "--no-res", tf.name]
```

**Comment by lxy417** [comment]
I used this Merged，it don‘t show this error，but i also can't get method’s source code
[https://github.com/androguard/androguard/pull/899](url)
`Found a class called sources/android/support/v4/content/ModernAsyncTask, which is not found by androguard!`
