### ISSUE TITLE
Fixed androguard sign bug

### ISSUE THREAD

**Issue by baotang2118** [androguard/androguard#764]
### Describe what you wanted to do

When I run a command in cmd like this `androguard sign --all --show example.apk`, I found this bug in `\androguard\cli\main.py` line 482, in this error, the getting PublicKeyInfo function in asn1crypto isn't available any more and they move to use a newer library named oscrypto to get the public key. I try both of installing ways from pip and from source. It still has a bug there.

### System Information

- Androguard Version: master
- Python Version: 3.7.5
- Operating System: Windows 10

### Further Log Files and Output

```
Found 1 unique public keys associated with the certs
PublicKey Algorithm: dsa
Bit Size: 1024
Error in com.whatsapp-1.apk
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\androguard\cli\main.py", line 482, in androsign_main
    print("Fingerprint:", binascii.hexlify(x509_public_key.fingerprint))
  File "c:\program files\python37\lib\site-packages\asn1crypto\keys.py", line 1245, in fingerprint
    'asn1crypto.keys.PublicKeyInfo().fingerprint has been removed, '
asn1crypto._errors.APIException: asn1crypto.keys.PublicKeyInfo().fingerprint has been removed, please use oscrypto.asymmetric.PublicKey().fingerprint instead
```

### Describe what you expected

I have just already fixed it by changing some code in `main.py`. Can I commit change to this repository ?

### Describe what actually happened

Add `from oscrypto import asymmetric` in `androsign_main()`
Change `x509_public_key = keys.PublicKeyInfo.load(public_key)` to `x509_public_key = asymmetric.load_public_key(public_key)`
Change `print("Hash Algorithm:", x509_public_key.hash_algo)` to `print("Hash Algorithm:", asymmetric.dump_public_key(x509_public_key))`
It works well now.

```
Found 1 unique public keys associated with the certs
PublicKey Algorithm: dsa
Bit Size: 1024
Fingerprint: b'551bbe22c35026d1d9b3b91305056ee24ed19bb26970d6408e80d0113101da9f'
Hash Algorithm: b'-----BEGIN PUBLIC KEY-----\nMIIBuDCCASwGByqGSM44BAEwggEfAoGBAP1/U4EddRIpUt9KnC7s5Of2EbdSPO9E\nAMMeP4C2USZpRV1AIlH7WT2NWPq/xfW6MPbLm1Vs14E7gB00b/JmYLdrmVClpJ+f\n6AR7ECLCT7up1/63xhv4O1fnxqimFQ8E+4P208UewwI1VBNaFpEy9nXzrith1yrv\n8iIDGZ3RSAHHAhUAl2BQjxUjC8yykrmCouuEC/BYHPUCgYEA9+GghdabPd7LvKtc\nNrhXuXmUr7v6OuqC+VdMCz0HgmdRWVeOutRZT+ZxBxCBgLRJFnEj6EwoFhO3zwky\njMim4TwWeotUfI0o4KOuHiuzpnWRbqN/C/ohNWLx+2J6ASQ7zKTxvqhRkImog9/h\nWuWfBpKLZl6Ae1UlZAFMO/7PSSoDgYUAAoGBANEZi0uBaHvPJG1BqKcl8KmJpRvO\nMm6EyCjh9VZki9cdpIcFTW3nD/9LSUMraGKqSPwqkxYbLBWi/15nFnLftXbp0Sqv\n9zabmpnQT7KdK7uypQPuQbH/N4hwZPQf4oBWCQY1AKjlRzSSgtFZgc21igi+3lHd\nfphnKVs9+0X/xrJZ\n-----END PUBLIC KEY-----\n'
```

**Comment by robsouth84** [comment]
Same issue here, solution worked but had to load oscrypto with pip after making updates.

**Describe what you wanted to do:**
view signing cert info with 
`$ androsign --all --show EasterEgg.apk`

**System Information**
installed by downloading master zip from github, unzipping, and running sudo python3 setup.py install

**$ androguard --version**
androguard, version 3.3.5
**$ uname -a**
Linux lubuntu-VirtualBox 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**$ python3 --version**
Python 3.6.9
**$ python --version**
Python 2.7.17


**Describe what actually happened**
```
$ androsign --all --show EasterEgg.apk
EasterEgg.apk, package: 'com.android.egg'
Is signed v1: True
Is signed v2: True
Is signed v3: False
Found 1 unique certificates
Issuer: C=US, ST=California, L=Mountain View, O=Android, OU=Android, CN=Android, E=android@android.com
Subject: C=US, ST=California, L=Mountain View, O=Android, OU=Android, CN=Android, E=android@android.com
Serial Number: 0xb3998086d056cffa
```
[...]
```
Found 1 unique public keys associated with the certs
PublicKey Algorithm: rsa
Bit Size: 2048
Error in EasterEgg.apk
Traceback (most recent call last):
  File "/home/lubuntu/.local/lib/python3.6/site-packages/androguard/cli/main.py", line 485, in androsign_main
    print("Fingerprint:", binascii.hexlify(x509_public_key.fingerprint))
  File "/home/lubuntu/.local/lib/python3.6/site-packages/asn1crypto/keys.py", line 1245, in fingerprint
    'asn1crypto.keys.PublicKeyInfo().fingerprint has been removed, '
asn1crypto._errors.APIException: asn1crypto.keys.PublicKeyInfo().fingerprint has been removed, please use oscrypto.asymmetric.PublicKey().fingerprint instead
```

Fix:
1) switch crypto lib in main.py as defined by [baotang2118](https://github.com/baotang2118) [here](https://github.com/androguard/androguard/issues/764#issue-529751533) 
2) install new dependency (oscrypto)
`$ pip3 install oscrypto`

**Comment by elig0n** [comment]
here's a diff file for 3.3.5

patch  `../lib/python3.6/site-packages/androguard/cli/main.py` with:
```
423d422
<     from oscrypto import asymmetric
483c482
<                     x509_public_key = asymmetric.load_public_key(public_key)
---
>                     x509_public_key = keys.PublicKeyInfo.load(public_key)
488c487
<                         print("Hash Algorithm:", asymmetric.dump_public_key(x509_public_key))
---
>                         print("Hash Algorithm:", x509_public_key.hash_algo)                                          
```
