### ISSUE TITLE
How to find references to EXTERNAL static fields?

### ISSUE THREAD

**Issue by FlowerCode** [androguard/androguard#765]
For example, a reference to content uri:
`sget-object v3, Landroid/provider/CalendarContract$Calendars;->CONTENT_URI:Landroid/net/Uri;`

It does't show up in `MethodAnalysis`'s `get_xref_to`, or `ClassData`'s `get_static_fields`

I maunally inspected `MethodAnalysis` and it doesn't seems to be in any field.

**Comment by beyzacevik** [comment]
Is there any progress on this subject?
