### ISSUE TITLE
Bad magic number for central directory

### ISSUE THREAD

**Issue by liorko87** [androguard/androguard#766]
### Describe what you wanted to do

I'm trying to create call graphs of a dataset of APKs I have.  
When I'm trying to use the androguard utility I got few errors:

1. `ValueError: negative seek value -4730916`
2. `zipfile.BadZipfile: Bad magic number for central directory`

- is this error specific to a single file? No it's happened on multiple files
- if possible give a minimal working example where the error happens:

In order to create the call graphs I'm using this command:
`androguard cg <apk_name>`

### Describe what you expected

A valid call graph

### Describe what actually happened

Exception as I stated above

### System Information

- Androguard Version: master
- Python Version: 3.6
- Operating System: Ubuntu 18.04

**Comment by reox** [comment]
The apk is probably broken. Is it installable on android?

**Comment by liorko87** [comment]
I didn't test it on real android device.
