### ISSUE TITLE
Why would it delete files under output directory???????

### ISSUE THREAD

**Issue by gistdoit** [androguard/androguard#768]
It just made lose 10 days of work!! Anyway i can recover it?

**Comment by elanimus** [comment]
It would have wiped lots of files if i ran it on destop or downloads. Wow.. great job guys

**Comment by reox** [comment]
sorry to hear that!
The option says right now:
```
If the output folder already exsist, it will be overwritten!
```

maybe this is not clear enough... probably should change the message
