### ISSUE TITLE
Suggestion: turn off color output

### ISSUE THREAD

**Issue by elig0n** [androguard/androguard#770]
`arsc` and `axml` commands show colored output
since I run it on windows cmd.exe the color codes appear raw and scramble the output,
but even without it it would be useful (piping, seeing a clean output etc...)
I suggest to implement an option to turn colors off

**Comment by reox** [comment]
IMO this should be automagic if the output is piped... Maybe it is broken on windows.

as a workaround, you can also use the --output option.
