### ISSUE TITLE
how to excact exceptions thrown behind the method

### ISSUE THREAD

**Issue by yeshen4328** [androguard/androguard#772]
![image](https://user-images.githubusercontent.com/12472005/71070837-85285980-21b6-11ea-9503-e61c1c60eed6.png)
how do I excract exceptions shown in the picture.
I found out that exceptions thrown by try-catch in the body of the method can be extracted by using `'DvMethod(dx.get_method(med)).exceptions'`. But It doesn't work in the previous situation.

**Comment by reox** [comment]
I'm not sure if this information can be retrieved from the DEX file statically. Please refer to the DEX file documentation if the exception class name is stored. If it is somewhere, you can probably retrieve it via androguard.
