### ISSUE TITLE
Frosting support ?

### ISSUE THREAD

**Issue by Te-k** [androguard/androguard#773]
At the end of 2017, Google started to add a [Google Play store signature](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html) to APKs uploaded on the play store. It seems to be called "frosting" internally, and it was reversed and implemented in [apkverifier](https://github.com/avast/apkverifier) (see [here too](https://stackoverflow.com/a/51857027)).

Is it currently parsed by androguard ? If no, is there any plan to add this feature ?

**Comment by reox** [comment]
No it is not in androguard right now. There was a similar question here: #732 

Right now, I can not implement anything for androguard. But if you (or anyone else) wants to tackle the problem, please go for it! PRs are highly welcome!

**Comment by Te-k** [comment]
Any reason for closing all the issues?
