### ISSUE TITLE
Which call graph algorithm does androguard use?

### ISSUE THREAD

**Issue by linghuiluo** [androguard/androguard#784]
Hi, thank you for building this great tool. I wonder which call graph algorithm does androguard use to create the call graph? 

– Class Hierarchy analysis (CHA) 
– Rapid Type analysis (RTA) 
– Variable Type Analysis (VTA) 
– Andersen 
– Steensguard 

is the call graph context-sensitive?

**Comment by linghuiluo** [comment]
@adesnos  can you answer my questions? Thanks

**Comment by trstcod** [comment]
I guess RTA because most of the static tools use this as it is not that complicated.

**Comment by AnonymousAnalyst** [comment]
> I guess RTA because most of the static tools use this as it is not that complicated.

sounds reasonable. However, it will be great if the author can confirm this.

**Comment by linghuiluo** [comment]
> I guess RTA because most of the static tools use this as it is not that complicated.

sounds reasonable. However, it will be great if the author can confirm this.
