### ISSUE TITLE
Permissions actually used are missing

### ISSUE THREAD

**Issue by beyzacevik** [androguard/androguard#787]
My main goal is to create a mapping between API-calls and permissions used in a third party library/APK. But first, I want to extract the permissions actually used from an APK or dex file of third party libraries. I've read the documentation. I used this code below. The APK is a simple one, it only requests READ_CONTACTS and actually uses this permission. (APK is attached.)
 
from androguard.core.analysis import analysis
from androguard.misc import AnalyzeAPK
```
a,b,dx = AnalyzeAPK('/Users/beyzacevik/Downloads/app-read-contacts.apk')

print(a.get_permissions())
print(a.get_details_permissions())

```
a.get_permissions() extracts permissions declared in manifest file. However, permission from manifest file might not be actually used. Because of this, I examined the dx using the code piece below. Result did not include READ_CONTACTS permission. Why might it be the case?  APK is compiled in API level 29. Can it be the reason? 
-----
And also for creating mappings between API calls and used permission, I use the code below to extract API calls made from a method. I think that if I map these API calls with the ones in Axplorer. I can conclude up what I need. However, I am not sure if it would be reliable even if the API level is correct. 

```
for clas in dx.get_classes():
    for method in clas.get_methods():
            for api_call in method.get_xref_to(): 
                    print('api_call: ', api_call)
```

**Comment by krnick** [comment]
If you need to use the API of reading contact, you need to declare it in AndroidManifest.xml, on the other hand, if you only have the permission declaration, It does not necessarily use the API call.
