### ISSUE TITLE
Deprecation warning due to invalid escape sequences in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [androguard/androguard#796]
### Describe what you wanted to do

```
find . -iname '*py' | grep -Ev 'setup|rdf4|tool' | xargs -P4 -I{} python3.8 -Wall -m py_compile {} 
./androguard/core/bytecodes/apk.py:1027: DeprecationWarning: invalid escape sequence \>
  """
```

Depreaction warning due to invalid escape sequences in Python 3.7 . https://github.com/asottile/pyupgrade/ can be used to resolve the warnings.

**Comment by krnick** [comment]
@tirkarthi Thank you for reminding！
