### ISSUE TITLE
How to rename a field, a method or a class?

### ISSUE THREAD

**Issue by cryptax** [androguard/androguard#839]
A typical task of reverse engineering consists in renaming methods to give them a more meaningful name.
How can we do that with Androguard? I have tried `set_name` on `androguard.core.bytecodes.dvm.EncodedField` objects, but that does not work.

```
In [94]: f.get_field()
Out[94]: <androguard.core.bytecodes.dvm.EncodedField at 0x7f1c774cedf0>

In [95]: f.get_field().set_name('blah')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.9/site-packages/androguard/cli/main.py in <module>
----> 1 f.get_field().set_name('blah')

/usr/local/lib/python3.9/site-packages/androguard/core/bytecodes/dvm.py in set_name(self, value)
   2861 
   2862     def set_name(self, value):
-> 2863         self.CM.set_hook_field_name(self, value)
   2864         self.reload()
   2865 

/usr/local/lib/python3.9/site-packages/androguard/core/bytecodes/dvm.py in set_hook_field_name(self, encoded_field, value)
   7506 
   7507             try:
-> 7508                 delattr(class_def.F, name)
   7509             except AttributeError:
   7510                 python_export = False

TypeError: attribute name must be string, not 'MUTF8String'
```

**Comment by adesnos** [comment]
I'm rewriting all the code in rust (with a python binding), so I will close all these issues.

**Comment by krnick** [comment]
Hello @adesnos !! , glad to see you come back, I am very happy to help with the Python binding part. If there is anything I could help with, please let me know :) 

thank you!

**Comment by adesnos** [comment]
thx !

Yes sure I will start to commit in the next days :)

I will leave the repo like that right now, but everything will be changed to start from a clean base, and well after 10 years it will not be the same !

**Comment by cryptax** [comment]
@adesnos  ok... but is this a bug, or is renaming meant to be done some other way?

**Comment by krnick** [comment]
> thx !
> 
> Yes sure I will start to commit in the next days :)
> 
> I will leave the repo like that right now, but everything will be changed to start from a clean base, and well after 10 years it will not be the same !

Great, please let me know once you start the new repo! I am also working on android analysis and develop [quark-engine](https://github.com/quark-engine/quark-engine) for Android malware analysis, which heavily based on androguard 😄

**Comment by adesnos** [comment]
@cryptax clearly I don't know and I don't want to check lol It is too old and all this code will be refactor soon
