### ISSUE TITLE
Query api call

### ISSUE THREAD

**Issue by Markstrk** [androguard/androguard#842]
I want to use this framework to analyze whether a method in the apk is called. I can achieve this by "dx.get_tainted_packages().search_methods()" before. But now these methods have been removed, can you tell me an alternative method. Thanks very much!

**Comment by subho007** [comment]
you can use `xref` to do the same. Have a look at https://github.com/androguard/androguard/blob/master/tests/test_analysis.py#L129 to understand how to use them

**Comment by reox** [comment]
dont forget that there is also a manual: https://androguard.readthedocs.io/en/latest/intro/xrefs.html
