### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by Ayrx** [androguard/androguard#844]
There have been 292 commits to `master` since the 3.3.5 release. Could we get a new version published to PyPI to make installation easier?

**Comment by krnick** [comment]
Hi @Ayrx , I can help with this part, but currently, there is no major maintainer for Androguard. As the original author @adesnos of Androguard mentioned, he wants to write a new Androguard with Rust in #839.

I can update the current version 3.4.0a1 on [PyPi](https://pypi.org/project/androguard/#history) to the official release version 3.4.0. What do you think, @reox

**Comment by reox** [comment]
IMO the current master needs testing, as there were many major changes. Furthermore, as far as I remember there are still many todos left. However I lost track of that and all the issues are closed now.
Personally, I would still leave it as a pre-release, so it is obvious that there might be errors ahead. 

Btw, if you really want to use the latest master, you can also give pip a git url:
```
$ python3 -m pip install git+https://github.com/androguard/androguard
````
There is actually no need to use the pypi version - if you really want to.

**Comment by Ayrx** [comment]
I'll close this since it appears that there isn't interest in publishing a new release.

FWIW, I think it would be a good idea to have a "final" Python-only release before a major rewrite happens. :)

**Comment by chenrui333** [comment]
There is some issue with `3.4.0a1`, ie it missed requirements.txt in the pypi tarball file. Can we publish a new one? What's more is it is still marked as pre-release for the last three years, I think it would be good to publish a new one. Let me know if that makes sense. Thanks!!

relates to:
- https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1314
- https://github.com/Homebrew/homebrew-core/pull/123807

**Comment by eighthave** [comment]
I can take on the work of making a new release if someone can publish it to pypi.org (I don't have access)

**Comment by reox** [comment]
I have not looked at this project since 2019 😅 So I'm also not sure what the current state is and how androguard is supposed to be installed right now, as it does not provide a setup.py?

Nevertheless, I can add others to pypi if required. Do you @adesnos and @totoag have a pypi account, as you are probably right now the lead devs?

**Comment by chenrui333** [comment]
Just a note, this is still an issue for https://github.com/Homebrew/homebrew-core/pull/125224

**Comment by totoag** [comment]
@reox yes I'm here ! Can you give me the admin right on the pypi project please ? (totoag is my account). Thx !

**Comment by krnick** [comment]
glad you're back! just sent you the admin invitation @totoag

**Comment by totoag** [comment]
Just accepted it ! thx !!

**Comment by erev0s** [comment]
I am really glad to announce that version 4.0.0 will be released soon based on the current [pyproject.toml](https://github.com/androguard/androguard/blob/master/pyproject.toml) file.
