### ISSUE TITLE
Unable to create CFG using decompile command

### ISSUE THREAD

**Issue by AkshatSood** [androguard/androguard#847]
I am using Androguard to create CFGs for a project. When I try to create the Call Graph, I am successfully able to produce GML files with the Call Graph. But I am facing issues while creating a Control Flow Graph. 

I am using the default command provided in the documentation, which is as follows 

`androguard decompile -o "./output" -f png -i "application01.apk"`

When I run the command, I get the following error towards the end of the execution of the process: 

`AssertionError: "dot" with args ['-Tpng', 'C:\\AppData\\Local\\Temp\\tmpxjrnke5e'] returned code: 1`

Ideally, I would want the CFG in a format that I can read and process, i.e., either a JSON or GML file. 

- Androguard Version: 3.3.5
- Python Version: 3.7.3
- Operating System: Windows 10

**Comment by AkshatSood** [comment]
The only solution I was able to find for this was to use the apkviewer file provided in Androguard v1.9, which produces a graphml file for the CFG.

**Comment by NarcherAlter** [comment]
> 我能找到的唯一解决方案是使用 Androguard v1.9 中提供的 apkviewer 文件，它为 CFG 生成一个 graphml 文件。

May I ask in what way did you solve it? I do not know how to use code to solve this problem.
