### ISSUE TITLE
When will Android API 29/30 be supported

### ISSUE THREAD

**Issue by lxzh** [androguard/androguard#852]
When will Android API 29/30 be supported [MobSF/issues#1637](https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1637)

```
Requested API level 30 is larger than maximum we have, returning API level 28 instead
```

**Comment by martink87** [comment]
So never?

**Comment by hackeraf** [comment]
Why was this closed? We know that 30 is larger than the maximum you have. We are asking when 30 will be supported.

**Comment by vctrferreira** [comment]
Hello?
