### ISSUE TITLE
Maintaining Legacy Codebase

### ISSUE THREAD

**Issue by subho007** [androguard/androguard#859]
Hey @adesnos I wanted to see if it is okay if one of us can maintain this repo, or if I can have a fork which I can maintain it, so that if there are any bugs/issues in this legacy repo, atleast we can address that.

pip installation updates are not required, since lot of untested modules and codes are currently present in this repo. But now, it is becoming a problem for me to keep a track of all the newer issues which are coming, along with PRs being submitted in this repo and keeping a sync locally in my repo.

Let me know what works the best. If you think I should keep an unofficial fork, is it ok to put in a note in the README.md in this repo? or I can volunteer to keep a check on this repo itself?

**Comment by totoag** [comment]
Sorry for the delay, back on it to simplify many things, remove dependencies etc

So feel free to submit code !
