### ISSUE TITLE
How to generate call graph for thousands of APKs at a time

### ISSUE THREAD

**Issue by stu-sky** [androguard/androguard#860]
Hi,

i want to extract call graphs of thousands of APks at a time.Now i know that i can use androguard cg  create a call graph from the docs.But for many APKs,does it mean I will repeat this command a thousand times?

So is there a more convenient way?I am an inexperienced rookie.I would be grateful for any good ideas or advice  of the problem

**Comment by totoag** [comment]
Will be put that in the doc

**Comment by erev0s** [comment]
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.
