### ISSUE TITLE
Control Flow Graph generation does not work

### ISSUE THREAD

**Issue by JoyMitra** [androguard/androguard#872]
Androguard's cg tool depends on the networkx module. However, the current version of networkx, i.e., 2.5.1 breaks the tool. I was able to make it work with networkx 2.3. With the recent version, an attribute error occurs on almost all the apks I tested. A fix needs to be made to make it compatible with the current version of networkx.

**Comment by erev0s** [comment]
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.
