### ISSUE TITLE
Resource Type: 0x0000

### ISSUE THREAD

**Issue by 6dlz** [androguard/androguard#888]
AXML file has an unusual resource type! Malware likes to to such stuff to anti androguard! But we try to parse it anyways. Resource Type: 0x0000

**Comment by totoag** [comment]
Any file to checkout ?

**Comment by bsstudent23** [comment]
this file  - https://www.virustotal.com/gui/file/a720d84205ac28d15c3681d62d767cdc636486e15ab6ddf775ccd46cc8801435

**Comment by erev0s** [comment]
Given that the issue is old and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.
