### ISSUE TITLE
Why session Load failed?

### ISSUE THREAD

**Issue by GeniusPudding** [androguard/androguard#890]
![image](https://user-images.githubusercontent.com/55935566/171807325-46255e9b-ea8b-43e3-9858-ab32ed034b37.png)

I'm trying the session load,save in androguard.
I read the doc and just copy and paste the session part with few modifications.
However I got 
![image](https://user-images.githubusercontent.com/55935566/171807546-48639311-ca55-4552-956d-731b44cb1cdc.png)

It is sure that in input apk file and the ag file is exists and not empty file. But maybe something else wrong...

**Comment by erev0s** [comment]
Currently the session is not working as expected due to different reasons.
The load functionality has been removed and the entire "session approach" needs to be implemented from scratch, while setting clear expectations.
