### ISSUE TITLE
AttributeError: 'EncodedMethod' object has no attribute 'is_external'

### ISSUE THREAD

**Issue by Fengjiayin1983** [androguard/androguard#910]
_, _, dx = AnalyzeAPK(a.apk)
dcg = dx.get_call_graph()
 for node in dcg.nodes()
       if node.is_external():
               print(node)

AttributeError: 'EncodedMethod' object has no attribute 'is_external'
As per the 3.4 version, there is no is_external() method there.

how to fix it?
I would appreciate it if you could reply to me!

**Comment by erev0s** [comment]
Closing this as the issue is old and the source has substantially changed.
Please feel free to open a new issue if this persists.
