### ISSUE TITLE
setup.py file missing

### ISSUE THREAD

**Issue by saksham95sj** [androguard/androguard#911]
I found multiple tools that uses androguard and requires setup.py file to install and use those tools. But setup.py file is missing from this repo.
Please let me know the alternative way as I am new to this.

**Comment by eybisi** [comment]
+1 where is setup.py ? It's stated in documentation https://androguard.readthedocs.io/en/latest/intro/installation.html

**Comment by sanzoghenzo** [comment]
It has been deleted with many other files in the cleanup commit 56faaa7135966014850b3d19ce5221c3f2712eac

Not sure if this was an oversight or intended.

**Comment by erev0s** [comment]
a new setup.py is in place now
