### ISSUE TITLE
How to install the master version of the androguard?

### ISSUE THREAD

**Issue by VidyaKamath** [androguard/androguard#918]
Can someone help me with the steps to install the androguard with the master code?
I do not find `setup.py` and I am not aware of other methods to install.

**Comment by VidyaKamath** [comment]
Hi @totoag, 
I found that the setup.py was deleted in this commit https://github.com/androguard/androguard/commit/56faaa7135966014850b3d19ce5221c3f2712eac

Can you please help me with the steps to install the master version of the code as a package in a local environment?

**Comment by mrexodia** [comment]
I recreated a working version of `setup.py`: https://github.com/mrexodia/androguard/tree/fix-dex

To use it in `requirements.txt`:

```
git+https://github.com/mrexodia/androguard@b24ff41bbcdf01b55d9e10f2748004193c2a9707#egg=androguard
```

**Comment by erev0s** [comment]
Please try again now that the setup.py and pyproject.toml files are there. You can also try to install from PyPI.
