### ISSUE TITLE
cannot output java source: AttributeError: 'NoneType' object has no attribute 'display_all'

### ISSUE THREAD

**Issue by XingYuanWei** [androguard/androguard#920]
i used androguard in python. as following show code
class_list = dex.get_classes()

''' python
import os
from androguard.misc import AnalyzeAPK
from androguard.core.bytecodes.apk import APK
from androguard.core.bytecodes.dvm import DalvikVMFormat
from androguard.core.analysis.analysis import Analysis
from androguard.decompiler.decompiler import DecompilerJADX
test_apk_path = 'dataset/demo/0a6c1e045e34438bd3bbf08e664e6c19'

apk = APK(test_apk_path)
dex = DalvikVMFormat(apk)
analysis = Analysis(dex)
class_list = dex.get_classes()
class_1 = class_list[1]
print(class_1.source())

#
but it cannot output java source, then report an error
 print(class_1.source())
  File "D:\anaconda\envs\malware\lib\site-packages\androguard\core\bytecodes\dvm.py", line 3652, in source
    self.CM.decompiler_ob.display_all(self)
AttributeError: 'NoneType' object has no attribute 'display_all'

**Comment by erev0s** [comment]
Given that the issue refers to a rather old version of the project and the project is substantially different nowadays, I will be closing this.
Please feel free to reopen it in case it still stands.
