### ISSUE TITLE
i want to know one class(eg gson) belong to which packages(eg com.google) , what can i do?

### ISSUE THREAD

**Issue by IMZGforever** [androguard/androguard#921]
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do

- is this error specific to a single file?
- if possible give a minimal working example where the error happens

### System Information

- Androguard Version: master
- Python Version: 3.4/3.5/...
- Operating System

### Further Log Files and Output

- please report logs, tracebacks and other useful information
- if possible report the files you tried to analyze!

**Comment by erev0s** [comment]
lacking information
