### ISSUE TITLE
Add support for Android 12 and later

### ISSUE THREAD

**Issue by schr-0dinger** [androguard/androguard#932]
Kindly add support for newer versions of Android

**Comment by chgans** [comment]
Does anyone know which tool is used to generate the permissions located here: https://github.com/androguard/androguard/tree/master/androguard/core/api_specific_resources/aosp_permissions

I work on AOSP on a regular basis, i can add Android 12, 12L and 13, i just need to know where is the script that generates these json files.

**Comment by themoep** [comment]
Hi! I used https://github.com/U039b/aosp_permissions_extraction to [generate it for API 29](https://github.com/androguard/androguard/pull/810)

**Comment by chgans** [comment]
Thanks for sharing.

> generated using https://github.com/U039b/aosp_permissions_extraction and adjusted naming convention to camel case for permissionLevel and permissionGroup

What is this camel case story? Does the output of the script need to be processed?

**Comment by BJTUpupil** [comment]
> Thanks for sharing.
> 
> > generated using https://github.com/U039b/aosp_permissions_extraction and adjusted naming convention to camel case for permissionLevel and permissionGroup
> 
> What is this camel case story? Does the output of the script need to be processed?

Does it can abstract  API 30 ~ API 33 from Android 12 and Android 13? Google has integrated android AOSP files into the framework, I don't know if I can use this tool on Android 12 and 13.

**Comment by chgans** [comment]
I ran that tool on AOSP 13, didn't noticed any issue, just trying to find out what this camel case story is.

**Comment by themoep** [comment]
androguard expects the id to be "permissionGroup" and "protectionLevel" but the generated json contains it as "permission_group" and "protection_level". I chose to post-process the json so they are all consistent in androguard instead copying them as is and adding some logic to handle both ids.

see https://github.com/androguard/androguard/blob/master/androguard/core/apk/__init__.py#L357

**Comment by erev0s** [comment]
It should be fixed by https://github.com/androguard/androguard/commit/8c5300743a484420c2782e9124bab2fce3bfaed9
