### ISSUE TITLE
About APK Call Graph

### ISSUE THREAD

**Issue by Rook1eHan** [androguard/androguard#933]
when i use the command
`androguard cg sample_apk.apk`
to create a call graph from an apk, it gives a .gml file
and i notice that some method's name is masked with letter a/b/c in the .gml file
such as <analysis.MethodAnalysis Lt;->a(Ljava/lang/String; I)Z [access_flags=private static] @ 0x1c7c4>
there are 't' and 'a' in the node
i wonder how to get rid of such things
or what can i do to prevent this situation?

**Comment by Drovis** [comment]
Are you using the pypi version?

**Comment by Rook1eHan** [comment]
yes exactly---- Replied Message ***@***.***>Date05/12/2023 16:19 ***@***.***> ***@***.***>***@***.***>SubjectRe: [androguard/androguard] About APK Call Graph (Issue #933)
Are you using the pypi version?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/androguard/androguard/issues/933#issuecomment-1545363973",
"url": "https://github.com/androguard/androguard/issues/933#issuecomment-1545363973",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Rook1eHan** [comment]
> Are you using the pypi version?

yes
so what version should i use ?
thanks

**Comment by erev0s** [comment]
@Rook1eHan the apk was most probably obfuscated and it resulted to this. This is often the case with obfuscated apks
