### ISSUE TITLE
Problem with androguard cg in pip package because of networkx library changed 

### ISSUE THREAD

**Issue by Drovis** [androguard/androguard#934]
Some methods and attributes of networkx have changed so it is necessary to specify in your requierments that the version of networkx has to be 1.11 and not >=1.11

**Comment by k0da101** [comment]
any solution for this issue?
`androguard` needs `>=1.11`  it works with the default installation  `networkx=3.2.1`
at the same time `cg` needs `networkx=1.11`

**Comment by erev0s** [comment]
there is no solution to this at the moment besides setting the networkx to 1.11.
cg has been removed from the latest available version and there is an open discussion https://github.com/androguard/androguard/discussions/968 as to whether it should be reimplemented
