### ISSUE TITLE
Installing androguard version 3.4.0a1 in Linux

### ISSUE THREAD

**Issue by mervecigdem** [androguard/androguard#942]
Hello,

I have a question about installing androguard version 3.4.0a1 in Linux.

Previously I have downloaded it into my Windows computer and I used it without any problem. By the way thank you for this library, it helped me a lot.

Now I want to install androguard into a remote Linux server, I can access the Linux server via putty, so I can use only command line. I can only install androguard 3.3.5 there but I couldn't install 3.4.0a1.

Firstly, I tired:
pip3.9 install -U androguard[magic,GUI]
But it said current version 3.3.5 is already satisfied, so it didn't download 3.4.0a1.

Secondly, I tried:
pip3.9 install -e git+https://github.com/androguard/androguard.git#egg=androguard
I received an error: "ERROR: androguard from git+https://github.com/androguard/androguard.git#egg=androguard does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found."

Then, I tried:
git clone --recursive https://github.com/androguard/androguard.git
cd androguard/
pip3.9 install .
I received an error: "ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found."

So I couldn't download the new version in remote Linux server. I would appreciate it if you can suggest other download methods. Thank you so much.

**Comment by erev0s** [comment]
Please try now. This should be fixed
