### ISSUE TITLE
Repacking/changing files in an APK

### ISSUE THREAD

**Issue by HGStyle** [androguard/androguard#946]
Is it possible to repack an unpacked APK, or to change files into them ? If yes, how ? Thanks in advance.

**Comment by erev0s** [comment]
I believe this falls a bit outside of the scope of androguard. Technically you could do it, utilizing some of the methods available but I dont think you are looking for something like this.

Maybe apktool where you can unpack - edit - repack the apk is closer to what you seek.
I will be closing this and feel free to reopen it if there is something more
