### ISSUE TITLE
What command replacing `cg` now? (master branch version)

### ISSUE THREAD

**Issue by ityoung** [androguard/androguard#959]
Hi, I'm trying to generate call graph of an APK, 
there were some errors when using pip version(3.3.5), so I trying using the latest code at master branch,
and the `cg` command was illeagle then.

How to generate call graph now? @totoag @hallucino @erev0s 

many thx !

**Comment by erev0s** [comment]
@ityoung as far as i can see the option to create a call graph (`androcg_main`) has been removed for quite some time already. Not sure what are the reasons behind this decision.

**Comment by erev0s** [comment]
https://github.com/androguard/androguard/discussions/968
