### ISSUE TITLE
HOME and other documentation wiki pages

### ISSUE THREAD

**Issue by tthtlc** [androguard/androguard#96]
i noticed that the wiki home page is not updated to point back to github.

can i volunteer to make that update?   and after i am done i will submit a pull request.   just to make sure nobody else is doing likewise.

thanks.

**Comment by adesnos** [comment]
You can do it. Thx !

**Comment by subho007** [comment]
@tthtlc I had opened a PR way before, but I still haven't had the time to complete it still. You can check the checklist of the PR #21
