### ISSUE TITLE
androguard cg uses an old version of networkx 

### ISSUE THREAD

**Issue by maryam-tanha** [androguard/androguard#964]
Hello,

When I run ""androguard cg  " with an apk as input, I get the following error:

**_AttributeError: 'DiGraph' object has no attribute 'node'. Did you mean: '_node'?_**

I did search online and found out it is related to using an older version of networkx. Could you please provide some guidance how to solve this issue?

**Comment by erev0s** [comment]
Hi @maryam-tanha this will not be solved as the `cg` command has been deprecated for a long time already.
The last version you can find it available is the 3.3.5 from 2019.

If you would like to try to solve it on your own you can fetch the source from back then and in the requirements point the networkx to use a compatible version.
