### ISSUE TITLE
incomplete get_operands

### ISSUE THREAD

**Issue by lucacapacci** [androguard/androguard#97]
Hi, is it normal that `instruction.get_operands()` doesn't give me the same registers as `instruction.get_output()`?

 Example to better explain:

If i execute `print instruction.get_output()` I get:

```
v0 ... v7, Landroid/database/sqlite/SQLiteDatabase;->query(Ljava/lang/String; [Ljava/lang/String; Ljava/lang/String; [Ljava/lang/String; Ljava/lang/String; Ljava/lang/String; Ljava/lang/String;)Landroid/database/Cursor; 
```

If I execute `print instruction.get_operands()` I get:

```
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (256, 420, 'Landroid/database/sqlite/SQLiteDatabase;->query(Ljava/lang/String; [Ljava/lang/String; Ljava/lang/String; [Ljava/lang/String; Ljava/lang/String; Ljava/lang/String; Ljava/lang/String;)Landroid/database/Cursor;')]
```

The result of `get_output()` ranges from v0 to v7, while the result of `get_operands()` ranges from (0, 0) to (0, 6). Maybe I'm wrong, but I expected `get_operands()` to range from (0, 0) to (0, 7).

The instruction type in this example is `<class 'androguard.core.bytecodes.dvm.Instruction3rc'>`

Thanks

**Comment by reox** [comment]
I think I see the problem here:
in get_operands it should be  range(self.CCCC, self.NNNN + 1), as NNNN is also a valid register
