### ISSUE TITLE
ModuleNotFoundError: No module named 'androguard.core.bytecodes'

### ISSUE THREAD

**Issue by supremehj** [androguard/androguard#978]
![image](https://github.com/androguard/androguard/assets/149232077/a08ee3ed-c67a-4bd0-933e-3f24ffb697f9)
In androguard version 3.5 it supports androguard.core.bytecodes, but when I updated to andoguard version 4, I get the following error.
ModuleNotFoundError: No module named 'androguard.core.bytecodes'

### System Information
- HP Elitebook
- Androguard Version: 4.0.1
- Python Version: 3.9.7
- Operating System: Window 10
- IDE= Jupiternotebook

**Comment by erev0s** [comment]
There are structural changes in the code, thats why.
Please use:
```
from androguard.core.apk import APK

**Comment by supremehj** [comment]
> There are structural changes in the code, thats why. Please use:
> 
> ```
> from androguard.core.apk import APK
> ```

![image](https://github.com/androguard/androguard/assets/149232077/0f03e8e7-176c-409b-9da8-31313f9e5d16)
Sir I creates an infinite loop.

**Comment by erev0s** [comment]
try to also set the logger output to error so it wont be as verbose:

```
from androguard.util import set_log

set_log("ERROR")

**Comment by supremehj** [comment]
> try to also set the logger output to error so it wont be as verbose:
> 
> ```
> from androguard.util import set_log
> 
> set_log("ERROR")
> ```

it takes same processing time, but it doesn't show me the permissions which are extracted from apk.

**Comment by erev0s** [comment]
@erev0s it should take the same processing time as before.
I cant replicate the issue on my side using a test apk.
Try with another APK and if it works, then feel free to share the first APK so I can check it out.
