### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by yrlve** [androguard/androguard#987]
I just want to ask a question. I am importing the module 'APK' from 'androguard.core.bytecode' in my Python project using version 3.12. However, it seems that the module is not found. I have installed 'androguard' in my virtual environment, but I don't know how to fix this issue.

![WhatsApp Image 2024-01-03 at 12 35 43](https://github.com/androguard/androguard/assets/154949713/7e8c80cb-af1b-45c8-bbde-7bf84fcf7027)

- Androguard Version: 4.0.2
- Python Version: 3.12
- Windows

**Comment by erev0s** [comment]
hi @yrlve the structure of the project has changed, though the documentation not yet!
please use:
~~~~
from androguard.core.apk import APK
~~~~
