### ISSUE TITLE
(Incorrect) relative path in androguard/core/androconf.py

### ISSUE THREAD

**Issue by teprrr** [androguard/androguard#99]
Hi,

The path to permission files is hardcoded, and when running scripts from the root directory looks for them from a wrong place. Basically this small patch fixes it for me, but isn't obviously a great fix. Just adding it here before I forget about it.

diff --git a/androguard/core/androconf.py b/androguard/core/androconf.py
index 842661d..43eb722 100644
--- a/androguard/core/androconf.py
+++ b/androguard/core/androconf.py
@@ -102,7 +102,7 @@ CONF = {
     "LAZY_ANALYSIS": False,
     "MAGIC_PATH_FILE": None,
     
-    "PATH_TO_API_SPECIFIC_RESOURCE_MODULES" : "../androguard/core/api_specific_resources",
+    "PATH_TO_API_SPECIFIC_RESOURCE_MODULES" : "androguard/core/api_specific_resources",
     "DEFAULT_API" : 19,
 }

**Comment by subho007** [comment]
This commit should fix it https://github.com/xysec/androguard/commit/51c781499a515ce73f80ad02e0a9c60119ad6bdb

@teprrr @adesnos @Lircyn

**Comment by dweinstein** [comment]
@subho007 how about a PR for them to approve the fix. I can confirm that the referenced patch fixes it the problem. /cc @adesnos

**Comment by dweinstein** [comment]
I opened a PR, hopefully @adesnos can merge so we can fix master...

**Comment by giantpune** [comment]
+1 for @dweinstein 's PR.

**Comment by zyrikby** [comment]
Thank you guys for the correction. I use AndroGuard as a library in my projects, so my version worked fine for me. I did not know that it does not work for AndroGuard scripts.

**Comment by dweinstein** [comment]
@teprrr can you close this issue if things are good now for you?

**Comment by teprrr** [comment]
Thanks guys, seems to work fine!

**Comment by dweinstein** [comment]
sweet!

**Comment by subho007** [comment]
@dweinstein thanks for the PR I couldn't open a PR that's why I was referencing the commit. My git repo is a mess right now, will make it proper later :+1:

**Comment by dweinstein** [comment]
@subho007 all I did was create a branch off androguard master and cherry-pick your commit then open a PR for it. :-)
