### ISSUE TITLE
 androguard.core.api_specific_resources: Requested API level 34 is larger than maximum we have, returning API level 28 instead.

### ISSUE THREAD

**Issue by onephones** [androguard/androguard#991]
Please remove this template if you only have a question or do not want to create a new issue.

### Describe what you wanted to do

- is this error specific to a single file?
- if possible give a minimal working example where the error happens

### System Information

- Androguard Version: master
- Python Version: 3.4/3.5/...
- Operating System

### Further Log Files and Output

- please report logs, tracebacks and other useful information
- if possible report the files you tried to analyze!
 androguard.core.api_specific_resources: Requested API level 34 is larger than maximum we have, returning API level 28 instead.

**Comment by erev0s** [comment]
Please make sure you are using the latest version
