### ISSUE TITLE
question about call graph

### ISSUE THREAD

**Issue by ztjlime** [androguard/androguard#992]
I am using the Windows version ，when i run the test code of [4dcdd81](https://github.com/androguard/androguard/commit/4dcdd8123059827cc61e9a9ad6bada39559c6dd5)，it does not work，and shows：no attribute ‘get_call_graph.’
How could i create a call graph on windows with 4.0.2 version?

**Comment by erev0s** [comment]
4.0.2 does not have the call graph yet. Please make sure to follow the instruction here: https://github.com/androguard/androguard/wiki#getting-a-version-with-all-the-latest-commits to get the latest updates installed

new version will be released somewhere in the near future
