### ISSUE TITLE
Get only imported, used class and modules not all names under the packages 

### ISSUE THREAD

**Issue by maxacademind1** [androguard/androguard#999]
### Describe what you wanted to do
 I am trying get only used class and methods from apks. i mean if there is an import like "com.google.android.gms.ads.banner" in mainactivity do not also return "com.google.android.gms.ads.native". 

### Describe what you expected
if i import "com.google.firebase.FirebaseAuth", it must return only used modules not all package.

### Describe what actually happened
it analyzes all class under the package and brings all instances like "com.google.android.gms.ads.banner.a1" ,"com.google.android.gms.ads.banner.a1.xyz","com.google.android.gms.ads.banner.a1.xyz.tqqw"  .....
### System Information

- Androguard Version: 4.0.2
- Python Version: 3.11
- win10

### Code Block
```
from androguard.core import apk
from androguard.core.dex import DEX
        a = apk.APK(app_package_name+'.apk')
        all_dex = a.get_all_dex()
        package_classes = set()
        rule_set = list(filter(None,re.split('\n|\r|\t',rules)))
        for dex in all_dex:
            d = DEX(dex)
            for cls in d.get_classes():
                package = cls.get_name() 
                package = package[1:].replace("/", ".").rstrip(";").lower()
                if package.startswith("com.") or package.startswith("org.") or package.startswith("admost.") or package.startswith("mtg."):
                    package_classes.add(package)
        for a in rule_set:
            for b in package_classes:
                 if a in b:
                     result.add(a)
        print(result)


I will be appreciated if you tell my missing points.

**Comment by maxacademind1** [comment]
@erev0s

**Comment by erev0s** [comment]
not sure I understand fully what you are trying to do but maybe what you are looking for is the [ClassAnalysis](https://github.com/androguard/androguard/blob/master/androguard/core/analysis/analysis.py#L972).

The following is an example of getting a specific class:
~~~~
a, d, dx = AnalyzeAPK(apkPath)
class_name = 'Lcom/my/class;'
example_class_analysis = dx.get_class_analysis(class_name)
~~~~

**Comment by maxacademind1** [comment]
> not sure I understand fully what you are trying to do but maybe what you are looking for is the [ClassAnalysis](https://github.com/androguard/androguard/blob/master/androguard/core/analysis/analysis.py#L972).
> 
> The following is an example of getting a specific class:
> 
> ```
> a, d, dx = AnalyzeAPK(apkPath)
> class_name = 'Lcom/my/class;'
> example_class_analysis = dx.get_class_analysis(class_name)
> ```

Thanks for the response. Sorry for the explanations. I think I can explain better through the demo. For example, the first photo below is the packages I implemented in the demo application. The 2nd photo shows the first lines of my application. As you can see, I only used "FirebaseAuth" and I didn't use any of the other modules of the packages in the first photo. I wonder if there is a way to get only imported metho's that I used in the application? Can I analyze an apk in this way? If so, where am I making a mistake?

1)
![Capture11](https://github.com/androguard/androguard/assets/136687446/5d429d63-ee36-4b7f-9cc2-298af869162b)


2)
![Capture222](https://github.com/androguard/androguard/assets/136687446/8e3dc23c-2dec-48d3-a077-116e068854ff)

**Comment by erev0s** [comment]
it seems that what you are looking for are the cross-references to other classes that are used within a class:
~~~~
a, d, dx = AnalyzeAPK(fpath)
class_name = 'Lcom/my/class;'
example_class = dx.get_class_analysis(class_name)
for f in example_class.xrefto:
    print(f.name)
~~~~

Maybe it would be a good idea to also try out the `androguard analyze` where you can experiment easily and figure out what you need.
